# CASE 2: Inference Reproducibility with Independent  #

Because the number of classification folds across the 100 runs is too large, we only provide the Jupyter notebook for one fold here, namely the first fold of the reshuffling process. This notebook reproduces the zero setting for the Meta-learner model. To reproduce the other results, simply follow the same workflow and continue running the remaining folds.

## classification

### PanPep

##### majority

In [ ]:
import sys

SCRIPT_DIR = "../inference/PanPep_Weight_Inference"
TEST_DATA = "../data/fig4/reshuffling_majority_0.csv"
NEGATIVE_DATA = "../data/Control_dataset.txt"  #Blank file
!{sys.executable} {SCRIPT_DIR}/inference_majority.py \
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "{SCRIPT_DIR}/Requirements" \
    --support_dir "../data/support/majority" \
    --peptide_encoding "{SCRIPT_DIR}/peptide_b.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_b.npz" \
    --result_dir "CASE2_majority"

Using 1 GPUs: [0]
Using model configuration: default

Processing peptide: LLAGIGTVPI on device: cuda:0
Positive TCRs: 324, Negative TCRs: 9552
Total batches: 1
Loading support data from: ../data/support/majority
Loading support data for peptide: LLAGIGTVPI
Query data size: 9876

Processing batch 1/1 for peptide LLAGIGTVPI - 2026-03-16 23:29:01
Finetuning model...
batch processing time: 13.41s, Progress: 100.0%
Successfully wrote 9876 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_majority/LLAGIGTVPI.parquet

Peptide LLAGIGTVPI processing time: 13.46s

Processing peptide: TTDPSFLGRY on device: cuda:0
Positive TCRs: 166, Negative TCRs: 9552
Total batches: 1
Loading support data from: ../data/support/majority
Loading support data for peptide: TTDPSFLGRY
Query data size: 9718

Processing batch 1/1 for peptide TTDPSFLGRY - 2026-03-16 23:29:14
Finetuning model...
batch processing time: 12.91s, Progress: 100.0%
Successfully wrote 9718 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_majority/TTDPSFLGRY.parquet

Peptide TTDPSFLGRY processing time: 12.96s

Processing peptide: ATDALMTGF on device: cuda:0
Positive TCRs: 52, Negative TCRs: 9552
Total batches: 1
Loading support data from: ../data/support/majority
Loading support data for peptide: ATDALMTGF
Query data size: 9604

Processing batch 1/1 for peptide ATDALMTGF - 2026-03-16 23:29:27
Finetuning model...
batch processing time: 9.99s, Progress: 100.0%
Successfully wrote 9604 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_majority/ATDALMTGF.parquet

Peptide ATDALMTGF processing time: 10.04s

Processing peptide: LTDEMIAQY on device: cuda:0
Positive TCRs: 52, Negative TCRs: 9552
Total batches: 1
Loading support data from: ../data/support/majority
Loading support data for peptide: LTDEMIAQY
Query data size: 9604

Processing batch 1/1 for peptide LTDEMIAQY - 2026-03-16 23:29:38
Finetuning model...
batch processing time: 9.78s, Progress: 100.0%
Successfully wrote 9604 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_majority/LTDEMIAQY.parquet

Peptide LTDEMIAQY processing time: 9.83s

Total execution time: 47.59s (0.01 hours)

In [14]:
import os
import pandas as pd

PARQUET_DIR = "../inference/PanPep_Weight_Inference/CASE2_majority"
CSV_PATH = "../data/fig4/reshuffling_majority_0.csv"

OUTPUT_DIR = "./result"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "CASE2_majority_scored.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

csv_df = pd.read_csv(CSV_PATH)

if "label" in csv_df.columns:
    csv_df = csv_df.rename(columns={"label": "Label"})

peptides = csv_df["peptide"].unique()

results = []
for pep in peptides:
    parquet_path = os.path.join(PARQUET_DIR, f"{pep}.parquet")
    if not os.path.exists(parquet_path):
        print(f"[SKIP] No parquet for {pep}")
        continue

    parquet_df = pd.read_parquet(parquet_path)[["CDR3", "Score"]].rename(
        columns={"CDR3": "binding_TCR"}
    )

    pep_rows = csv_df[csv_df["peptide"] == pep].copy()
    merged = pep_rows.merge(parquet_df, on="binding_TCR", how="left")
    results.append(merged)

    print(f"[OK] {pep}: {len(merged)} rows, {merged['Score'].notna().sum()} scored")

if results:
    final_df = pd.concat(results, ignore_index=True)
    final_df.to_csv(OUTPUT_PATH, index=False)

    print(f"\nSaved to {OUTPUT_PATH}")
    print(f"Total rows: {len(final_df)}, scored: {final_df['Score'].notna().sum()}")
else:
    print("No results to save.")

[OK] ATDALMTGF: 52 rows, 52 scored
[OK] LLAGIGTVPI: 324 rows, 324 scored
[OK] LTDEMIAQY: 52 rows, 52 scored
[OK] TTDPSFLGRY: 166 rows, 166 scored

Saved to ./result/CASE2_majority_scored.csv
Total rows: 594, scored: 594

In [16]:
!{sys.executable} ../metric_calculation/AUC.py \
                    --root_dir ./result \
                    --output_file ./CASE2_majority_auc.csv

Finding CSV files...
Found 1 CSV files
Processed 1/1 files (100.0%)
Failed: 1

In [17]:
import pandas as pd

df = pd.read_csv("./CASE2_majority_auc.csv")
df

,folder_path,file_name,roc_auc,pr_auc,status
0,./result,CASE2_majority_scored.csv,0.544899,0.565792,success
1,./result,[FOLDER_SUMMARY],0.544899,0.565792,success (averaged over 1 files)

##### few-shot

In [ ]:
import sys

SCRIPT_DIR = "../inference/PanPep_Weight_Inference"
TEST_DATA = "../data/fig4/reshuffling_few_0.csv"
NEGATIVE_DATA = "../data/Control_dataset.txt"

!{sys.executable} {SCRIPT_DIR}/inference_few_shot.py \
    --mode single \
    --model default\
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "{SCRIPT_DIR}/Requirements" \
    --support_dir "../data/support/few" \
    --peptide_encoding "{SCRIPT_DIR}/peptide_b.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_b.npz" \
    --result_dir "CASE2_few"

Using 1 GPUs: [0]
Using model configuration: default
Inference mode: single
support_dir enabled: will load k-shot data from ../data/support/few

Processing peptide: NTNSSPDDQIGYY on device: cuda:0
Positive TCRs: 10, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9562

Processing batch 1/1 for peptide NTNSSPDDQIGYY - 2026-03-16 23:32:41
Finetuning model...
batch processing time: 1.09s, Progress: 100.0%
Successfully wrote 9562 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/NTNSSPDDQIGYY.parquet

Total time for peptide NTNSSPDDQIGYY: 1.14s

Processing peptide: RLLPLLALLAL on device: cuda:0
Positive TCRs: 26, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9578

Processing batch 1/1 for peptide RLLPLLALLAL - 2026-03-16 23:32:42
Finetuning model...
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9578 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/RLLPLLALLAL.parquet

Total time for peptide RLLPLLALLAL: 0.66s

Processing peptide: ALASCMGLIY on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9560

Processing batch 1/1 for peptide ALASCMGLIY - 2026-03-16 23:32:43
Finetuning model...
batch processing time: 0.61s, Progress: 100.0%
Successfully wrote 9560 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/ALASCMGLIY.parquet

Total time for peptide ALASCMGLIY: 0.65s

Processing peptide: FLGKIWPSYK on device: cuda:0
Positive TCRs: 16, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9568

Processing batch 1/1 for peptide FLGKIWPSYK - 2026-03-16 23:32:43
Finetuning model...
batch processing time: 0.61s, Progress: 100.0%
Successfully wrote 9568 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLGKIWPSYK.parquet

Total time for peptide FLGKIWPSYK: 0.65s

Processing peptide: FYAFSYYYDL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9558

Processing batch 1/1 for peptide FYAFSYYYDL - 2026-03-16 23:32:44
Finetuning model...
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FYAFSYYYDL.parquet

Total time for peptide FYAFSYYYDL: 0.67s

Processing peptide: HLCGSHLVEA on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9558

Processing batch 1/1 for peptide HLCGSHLVEA - 2026-03-16 23:32:45
Finetuning model...
batch processing time: 0.64s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/HLCGSHLVEA.parquet

Total time for peptide HLCGSHLVEA: 0.68s

Processing peptide: ILDTAGKEEY on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9558

Processing batch 1/1 for peptide ILDTAGKEEY - 2026-03-16 23:32:45
Finetuning model...
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/ILDTAGKEEY.parquet

Total time for peptide ILDTAGKEEY: 0.67s

Processing peptide: KLVAMGINAV on device: cuda:0
Positive TCRs: 30, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9582

Processing batch 1/1 for peptide KLVAMGINAV - 2026-03-16 23:32:46
Finetuning model...
batch processing time: 2.29s, Progress: 100.0%
Successfully wrote 9582 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/KLVAMGINAV.parquet

Total time for peptide KLVAMGINAV: 2.33s

Processing peptide: LALWGPDPAA on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9560

Processing batch 1/1 for peptide LALWGPDPAA - 2026-03-16 23:32:48
Finetuning model...
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9560 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/LALWGPDPAA.parquet

Total time for peptide LALWGPDPAA: 0.66s

Processing peptide: LTSLTILQLY on device: cuda:0
Positive TCRs: 66, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9618

Processing batch 1/1 for peptide LTSLTILQLY - 2026-03-16 23:32:49
Finetuning model...
batch processing time: 0.67s, Progress: 100.0%
Successfully wrote 9618 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/LTSLTILQLY.parquet

Total time for peptide LTSLTILQLY: 0.71s

Processing peptide: LVSDGGPNLY on device: cuda:0
Positive TCRs: 42, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9594

Processing batch 1/1 for peptide LVSDGGPNLY - 2026-03-16 23:32:50
Finetuning model...
batch processing time: 0.73s, Progress: 100.0%
Successfully wrote 9594 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/LVSDGGPNLY.parquet

Total time for peptide LVSDGGPNLY: 0.77s

Processing peptide: QQDKHYDLSY on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9560

Processing batch 1/1 for peptide QQDKHYDLSY - 2026-03-16 23:32:50
Finetuning model...
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9560 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/QQDKHYDLSY.parquet

Total time for peptide QQDKHYDLSY: 0.66s

Processing peptide: RGPGRAFVTI on device: cuda:0
Positive TCRs: 122, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9674

Processing batch 1/1 for peptide RGPGRAFVTI - 2026-03-16 23:32:51
Finetuning model...
batch processing time: 0.64s, Progress: 100.0%
Successfully wrote 9674 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/RGPGRAFVTI.parquet

Total time for peptide RGPGRAFVTI: 0.69s

Processing peptide: RLITGRLQSL on device: cuda:0
Positive TCRs: 12, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9564

Processing batch 1/1 for peptide RLITGRLQSL - 2026-03-16 23:32:52
Finetuning model...
batch processing time: 0.73s, Progress: 100.0%
Successfully wrote 9564 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/RLITGRLQSL.parquet

Total time for peptide RLITGRLQSL: 0.77s

Processing peptide: SLFNTVATLY on device: cuda:0
Positive TCRs: 72, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9624

Processing batch 1/1 for peptide SLFNTVATLY - 2026-03-16 23:32:52
Finetuning model...
batch processing time: 0.74s, Progress: 100.0%
Successfully wrote 9624 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/SLFNTVATLY.parquet

Total time for peptide SLFNTVATLY: 0.78s

Processing peptide: VSATAGTTVY on device: cuda:0
Positive TCRs: 14, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9566

Processing batch 1/1 for peptide VSATAGTTVY - 2026-03-16 23:32:53
Finetuning model...
batch processing time: 0.64s, Progress: 100.0%
Successfully wrote 9566 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/VSATAGTTVY.parquet

Total time for peptide VSATAGTTVY: 0.68s

Processing peptide: YLLPRRGPRL on device: cuda:0
Positive TCRs: 14, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9566

Processing batch 1/1 for peptide YLLPRRGPRL - 2026-03-16 23:32:54
Finetuning model...
batch processing time: 0.74s, Progress: 100.0%
Successfully wrote 9566 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/YLLPRRGPRL.parquet

Total time for peptide YLLPRRGPRL: 0.78s

Processing peptide: AIFYLITPV on device: cuda:0
Positive TCRs: 18, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9570

Processing batch 1/1 for peptide AIFYLITPV - 2026-03-16 23:32:55
Finetuning model...
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9570 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/AIFYLITPV.parquet

Total time for peptide AIFYLITPV: 0.67s

Processing peptide: AIIRILQQL on device: cuda:0
Positive TCRs: 12, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9564

Processing batch 1/1 for peptide AIIRILQQL - 2026-03-16 23:32:55
Finetuning model...
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9564 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/AIIRILQQL.parquet

Total time for peptide AIIRILQQL: 0.66s

Processing peptide: ALDIEIATY on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9560

Processing batch 1/1 for peptide ALDIEIATY - 2026-03-16 23:32:56
Finetuning model...
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9560 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/ALDIEIATY.parquet

Total time for peptide ALDIEIATY: 0.67s

Processing peptide: ALSKGVHFV on device: cuda:0
Positive TCRs: 70, Negative TCRs: 9551
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9621

Processing batch 1/1 for peptide ALSKGVHFV - 2026-03-16 23:32:57
Finetuning model...
batch processing time: 0.65s, Progress: 100.0%
Successfully wrote 9621 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/ALSKGVHFV.parquet

Total time for peptide ALSKGVHFV: 0.68s

Processing peptide: ALWEIQQVV on device: cuda:0
Positive TCRs: 68, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9620

Processing batch 1/1 for peptide ALWEIQQVV - 2026-03-16 23:32:57
Finetuning model...
batch processing time: 0.64s, Progress: 100.0%
Successfully wrote 9620 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/ALWEIQQVV.parquet

Total time for peptide ALWEIQQVV: 0.68s

Processing peptide: ALWMRLLPL on device: cuda:0
Positive TCRs: 28, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9580

Processing batch 1/1 for peptide ALWMRLLPL - 2026-03-16 23:32:58
Finetuning model...
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9580 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/ALWMRLLPL.parquet

Total time for peptide ALWMRLLPL: 0.67s

Processing peptide: AMFWSVPTV on device: cuda:0
Positive TCRs: 156, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9708

Processing batch 1/1 for peptide AMFWSVPTV - 2026-03-16 23:32:59
Finetuning model...
batch processing time: 0.69s, Progress: 100.0%
Successfully wrote 9708 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/AMFWSVPTV.parquet

Total time for peptide AMFWSVPTV: 0.73s

Processing peptide: CLAVHECFV on device: cuda:0
Positive TCRs: 16, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9568

Processing batch 1/1 for peptide CLAVHECFV - 2026-03-16 23:33:00
Finetuning model...
batch processing time: 0.64s, Progress: 100.0%
Successfully wrote 9568 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/CLAVHECFV.parquet

Total time for peptide CLAVHECFV: 0.68s

Processing peptide: CLNEYHLFL on device: cuda:0
Positive TCRs: 16, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9568

Processing batch 1/1 for peptide CLNEYHLFL - 2026-03-16 23:33:00
Finetuning model...
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9568 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/CLNEYHLFL.parquet

Total time for peptide CLNEYHLFL: 0.66s

Processing peptide: DTDFVNEFY on device: cuda:0
Positive TCRs: 12, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9564

Processing batch 1/1 for peptide DTDFVNEFY - 2026-03-16 23:33:01
Finetuning model...
batch processing time: 0.61s, Progress: 100.0%
Successfully wrote 9564 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/DTDFVNEFY.parquet

Total time for peptide DTDFVNEFY: 0.65s

Processing peptide: ELAGIGLTV on device: cuda:0
Positive TCRs: 16, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9568

Processing batch 1/1 for peptide ELAGIGLTV - 2026-03-16 23:33:02
Finetuning model...
batch processing time: 0.65s, Progress: 100.0%
Successfully wrote 9568 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/ELAGIGLTV.parquet

Total time for peptide ELAGIGLTV: 0.70s

Processing peptide: ELTSMKYFV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9558

Processing batch 1/1 for peptide ELTSMKYFV - 2026-03-16 23:33:02
Finetuning model...
batch processing time: 0.71s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/ELTSMKYFV.parquet

Total time for peptide ELTSMKYFV: 0.76s

Processing peptide: FIAGLIAIV on device: cuda:0
Positive TCRs: 10, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9562

Processing batch 1/1 for peptide FIAGLIAIV - 2026-03-16 23:33:03
Finetuning model...
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9562 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FIAGLIAIV.parquet

Total time for peptide FIAGLIAIV: 0.66s

Processing peptide: FLAHIQWMV on device: cuda:0
Positive TCRs: 14, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9566

Processing batch 1/1 for peptide FLAHIQWMV - 2026-03-16 23:33:04
Finetuning model...
batch processing time: 0.61s, Progress: 100.0%
Successfully wrote 9566 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLAHIQWMV.parquet

Total time for peptide FLAHIQWMV: 0.66s

Processing peptide: FLALCADSI on device: cuda:0
Positive TCRs: 10, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9562

Processing batch 1/1 for peptide FLALCADSI - 2026-03-16 23:33:04
Finetuning model...
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9562 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLALCADSI.parquet

Total time for peptide FLALCADSI: 0.67s

Processing peptide: FLCWHTNCY on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9558

Processing batch 1/1 for peptide FLCWHTNCY - 2026-03-16 23:33:05
Finetuning model...
batch processing time: 0.72s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLCWHTNCY.parquet

Total time for peptide FLCWHTNCY: 0.76s

Processing peptide: FLHVTYVPA on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9558

Processing batch 1/1 for peptide FLHVTYVPA - 2026-03-16 23:33:06
Finetuning model...
batch processing time: 0.72s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLHVTYVPA.parquet

Total time for peptide FLHVTYVPA: 0.76s

Processing peptide: FLLNKEMYL on device: cuda:0
Positive TCRs: 14, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9566

Processing batch 1/1 for peptide FLLNKEMYL - 2026-03-16 23:33:06
Finetuning model...
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9566 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLLNKEMYL.parquet

Total time for peptide FLLNKEMYL: 0.66s

Processing peptide: FLNGSCGSV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9558

Processing batch 1/1 for peptide FLNGSCGSV - 2026-03-16 23:33:07
Finetuning model...
batch processing time: 0.64s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLNGSCGSV.parquet

Total time for peptide FLNGSCGSV: 0.68s

Processing peptide: FLNRFTTTL on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9560

Processing batch 1/1 for peptide FLNRFTTTL - 2026-03-16 23:33:08
Finetuning model...
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9560 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLNRFTTTL.parquet

Total time for peptide FLNRFTTTL: 0.66s

Processing peptide: FLPGVYSVI on device: cuda:0
Positive TCRs: 12, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9564

Processing batch 1/1 for peptide FLPGVYSVI - 2026-03-16 23:33:08
Finetuning model...
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9564 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLPGVYSVI.parquet

Total time for peptide FLPGVYSVI: 0.67s

Processing peptide: FLPRVFSAV on device: cuda:0
Positive TCRs: 12, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9564

Processing batch 1/1 for peptide FLPRVFSAV - 2026-03-16 23:33:09
Finetuning model...
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9564 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLPRVFSAV.parquet

Total time for peptide FLPRVFSAV: 0.67s

Processing peptide: FLTENLLLY on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9560

Processing batch 1/1 for peptide FLTENLLLY - 2026-03-16 23:33:10
Finetuning model...
batch processing time: 0.65s, Progress: 100.0%
Successfully wrote 9560 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLTENLLLY.parquet

Total time for peptide FLTENLLLY: 0.68s

Processing peptide: FLVLLPLVS on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9558

Processing batch 1/1 for peptide FLVLLPLVS - 2026-03-16 23:33:10
Finetuning model...
batch processing time: 0.75s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLVLLPLVS.parquet

Total time for peptide FLVLLPLVS: 0.80s

Processing peptide: FLWSVFWLI on device: cuda:0
Positive TCRs: 40, Negative TCRs: 9552
Total batches: 1
Loading k-shot data from: ../data/support/few
Query data size: 9592

Processing batch 1/1 for peptide FLWSVFWLI - 2026-03-16 23:33:11
Finetuning model...
batch processing time: 0.68s, Progress: 100.0%
Successfully wrote 9592 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_few/FLWSVFWLI.parquet

Total time for peptide FLWSVFWLI: 0.73s


In [22]:
import os
import pandas as pd

PARQUET_DIR = "../inference/PanPep_Weight_Inference/CASE2_few"
CSV_PATH = "../data/fig4/reshuffling_few_0.csv"

OUTPUT_DIR = "./result"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "CASE2_few_scored.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

csv_df = pd.read_csv(CSV_PATH)

if "label" in csv_df.columns:
    csv_df = csv_df.rename(columns={"label": "Label"})

peptides = csv_df["peptide"].unique()

results = []
for pep in peptides:
    parquet_path = os.path.join(PARQUET_DIR, f"{pep}.parquet")
    if not os.path.exists(parquet_path):
        print(f"[SKIP] No parquet for {pep}")
        continue

    parquet_df = pd.read_parquet(parquet_path)[["CDR3", "Score"]].rename(
        columns={"CDR3": "binding_TCR"}
    )

    pep_rows = csv_df[csv_df["peptide"] == pep].copy()
    merged = pep_rows.merge(parquet_df, on="binding_TCR", how="left")
    results.append(merged)

    print(f"[OK] {pep}: {len(merged)} rows, {merged['Score'].notna().sum()} scored")

if results:
    final_df = pd.concat(results, ignore_index=True)
    final_df.to_csv(OUTPUT_PATH, index=False)

    print(f"\nSaved to {OUTPUT_PATH}")
    print(f"Total rows: {len(final_df)}, scored: {final_df['Score'].notna().sum()}")
else:
    print("No results to save.")

[OK] AIFYLITPV: 18 rows, 18 scored
[OK] AIIRILQQL: 12 rows, 12 scored
[OK] ALASCMGLIY: 8 rows, 8 scored
[OK] ALDIEIATY: 8 rows, 8 scored
[OK] ALSKGVHFV: 70 rows, 70 scored
[OK] ALWEIQQVV: 68 rows, 68 scored
[OK] ALWMRLLPL: 28 rows, 28 scored
[OK] AMFWSVPTV: 156 rows, 156 scored
[OK] CLAVHECFV: 16 rows, 16 scored
[OK] CLNEYHLFL: 16 rows, 16 scored
[OK] DTDFVNEFY: 12 rows, 12 scored
[OK] ELAGIGLTV: 16 rows, 16 scored
[OK] ELTSMKYFV: 6 rows, 6 scored
[OK] FIAGLIAIV: 10 rows, 10 scored
[OK] FLAHIQWMV: 14 rows, 14 scored
[OK] FLALCADSI: 10 rows, 10 scored
[OK] FLCWHTNCY: 6 rows, 6 scored
[OK] FLGKIWPSYK: 16 rows, 16 scored
[OK] FLHVTYVPA: 6 rows, 6 scored
[OK] FLLNKEMYL: 14 rows, 14 scored
[OK] FLNGSCGSV: 6 rows, 6 scored
[OK] FLNRFTTTL: 8 rows, 8 scored
[OK] FLPGVYSVI: 12 rows, 12 scored
[OK] FLPRVFSAV: 12 rows, 12 scored
[OK] FLTENLLLY: 8 rows, 8 scored
[OK] FLVLLPLVS: 6 rows, 6 scored
[OK] FLWSVFWLI: 40 rows, 40 scored
[OK] FTSDYYQLY: 76 rows, 76 scored
[OK] FTVLCLTPV: 18 rows, 18 scored
[OK] FVCDNIKFA: 6 rows, 6 scored
[OK] FYAFSYYYDL: 6 rows, 6 scored
[OK] GIIYIIYKL: 56 rows, 56 scored
[OK] GSHLVEALY: 24 rows, 24 scored
[OK] GTDLEGNFY: 6 rows, 6 scored
[OK] HLCGSHLVEA: 6 rows, 6 scored
[OK] HLMSFPQSA: 6 rows, 6 scored
[OK] HPVTKYIM: 124 rows, 124 scored
[OK] HSNLNDATY: 98 rows, 98 scored
[OK] IILVAVPHV: 20 rows, 20 scored
[OK] ILDTAGKEEY: 6 rows, 6 scored
[OK] ILGFVFTLT: 10 rows, 10 scored
[OK] ILSAHVATA: 10 rows, 10 scored
[OK] IMLCCMTSC: 12 rows, 12 scored
[OK] IQATVMIIV: 34 rows, 34 scored
[OK] KITEHSWNA: 6 rows, 6 scored
[OK] KLDGFMGRI: 6 rows, 6 scored
[OK] KLFIRQEEV: 6 rows, 6 scored
[OK] KLKDCVMYA: 12 rows, 12 scored
[OK] KLNEEIAII: 10 rows, 10 scored
[OK] KLQFTSLEI: 12 rows, 12 scored
[OK] KLQVFLIVL: 20 rows, 20 scored
[OK] KLSYGIATV: 10 rows, 10 scored
[OK] KLVAMGINAV: 30 rows, 30 scored
[OK] KLWAQCVQL: 46 rows, 46 scored
[OK] KMYAFTLES: 32 rows, 32 scored
[OK] KQIYKTPPI: 8 rows, 8 scored
[OK] KSVNITFEL: 34 rows, 34 scored
[OK] KVYPIILRL: 20 rows, 20 scored
[OK] LACFVLAAV: 8 rows, 8 scored
[OK] LALWGPDPAA: 8 rows, 8 scored
[OK] LAVDGVLSV: 8 rows, 8 scored
[OK] LLDDFVEII: 10 rows, 10 scored
[OK] LLLDRLNQL: 32 rows, 32 scored
[OK] LLLEWLAMA: 20 rows, 20 scored
[OK] LLNKHIDAY: 10 rows, 10 scored
[OK] LLPPLLEHL: 12 rows, 12 scored
[OK] LLSILCIWV: 16 rows, 16 scored
[OK] LLYDANYFL: 76 rows, 76 scored
[OK] LMCQPILLL: 8 rows, 8 scored
[OK] LMIERFVSL: 8 rows, 8 scored
[OK] LMNVLTLVY: 6 rows, 6 scored
[OK] LNIDLLWSV: 10 rows, 10 scored
[OK] LPDDFMGCV: 8 rows, 8 scored
[OK] LSFKELLVY: 6 rows, 6 scored
[OK] LTSLTILQLY: 66 rows, 66 scored
[OK] LVGPTPVNI: 34 rows, 34 scored
[OK] LVSDGGPNLY: 42 rows, 42 scored
[OK] LWLLWPVTL: 8 rows, 8 scored
[OK] MLAKALRKV: 6 rows, 6 scored
[OK] MLDMYSVML: 6 rows, 6 scored
[OK] MMILSDDAV: 6 rows, 6 scored
[OK] MQVESDDYI: 6 rows, 6 scored
[OK] MVWESGCTV: 10 rows, 10 scored
[OK] NILDAIAEI: 8 rows, 8 scored
[OK] NLFLFLFAV: 12 rows, 12 scored
[OK] NLIDSYFVV: 6 rows, 6 scored
[OK] NSSTCMMCY: 14 rows, 14 scored
[OK] NTNSSPDDQIGYY: 10 rows, 10 scored
[OK] NVFAFPFTI: 10 rows, 10 scored
[OK] NYMPYFFTL: 14 rows, 14 scored
[OK] PTDNYITTY: 40 rows, 40 scored
[OK] PTEKGANEY: 8 rows, 8 scored
[OK] PTHEEHLFY: 6 rows, 6 scored
[OK] QAKWRLQTL: 24 rows, 24 scored
[OK] QLARQQVHV: 6 rows, 6 scored
[OK] QQDKHYDLSY: 8 rows, 8 scored
[OK] RGPGRAFVTI: 122 rows, 122 scored
[OK] RIMTWLDMV: 12 rows, 12 scored
[OK] RLGPVQNEV: 14 rows, 14 scored
[OK] RLITGRLQSL: 12 rows, 12 scored
[OK] RLLPLLALLAL: 26 rows, 26 scored
[OK] RLPGVLPRA: 86 rows, 86 scored
[OK] RQLLFVVEV: 14 rows, 14 scored
[OK] RTATKAYNV: 42 rows, 42 scored
[OK] RTATKQYNV: 176 rows, 176 scored
[OK] RYSIFFDYM: 12 rows, 12 scored
[OK] SLFNTVATLY: 72 rows, 72 scored
[OK] SLISGMWLL: 16 rows, 16 scored
[OK] SLLMPILTL: 6 rows, 6 scored
[OK] SLLRSLENV: 22 rows, 22 scored
[OK] SMMILSDDA: 6 rows, 6 scored
[OK] SMWALVISV: 6 rows, 6 scored
[OK] STNVGSNTY: 44 rows, 44 scored
[OK] SVLYYQNNV: 12 rows, 12 scored
[OK] SWMESEFRV: 6 rows, 6 scored
[OK] TALALLLLD: 6 rows, 6 scored
[OK] TDLGQNLLY: 20 rows, 20 scored
[OK] TLKNTVCTV: 6 rows, 6 scored
[OK] TLLANVTAV: 26 rows, 26 scored
[OK] TLMNVITLV: 8 rows, 8 scored
[OK] TLMNVLTLV: 20 rows, 20 scored
[OK] TMADLVYAL: 6 rows, 6 scored
[OK] TSAMQTMLF: 10 rows, 10 scored
[OK] TSQWLTNIF: 18 rows, 18 scored
[OK] TTIQTIVEV: 8 rows, 8 scored
[OK] TVAYFNMVY: 6 rows, 6 scored
[OK] VFLVLLPLV: 14 rows, 14 scored
[OK] VIVMLTPLV: 12 rows, 12 scored
[OK] VIYQYMDDL: 8 rows, 8 scored
[OK] VLAWLYAAV: 6 rows, 6 scored
[OK] VMNILLQYV: 36 rows, 36 scored
[OK] VMVELVAEL: 28 rows, 28 scored
[OK] VSATAGTTVY: 14 rows, 14 scored
[OK] VTDAAHLLI: 60 rows, 60 scored
[OK] VYFLQSINF: 52 rows, 52 scored
[OK] VYIGDPAQL: 14 rows, 14 scored
[OK] WLLWPVTLA: 28 rows, 28 scored
[OK] YADVFHLYL: 20 rows, 20 scored
[OK] YILKYSVFL: 36 rows, 36 scored
[OK] YLFDESGEF: 8 rows, 8 scored
[OK] YLGGMSYYC: 8 rows, 8 scored
[OK] YLLLRVLNI: 10 rows, 10 scored
[OK] YLLPGWKL: 40 rows, 40 scored
[OK] YLLPRRGPRL: 14 rows, 14 scored
[OK] YLYALVYFL: 16 rows, 16 scored
[OK] YMPYFFTLL: 12 rows, 12 scored
[OK] YTMADLVYA: 14 rows, 14 scored
[OK] YVDNSSLTI: 14 rows, 14 scored
[OK] YVVDDPCPI: 6 rows, 6 scored
[OK] YVWKSYVHV: 12 rows, 12 scored

Saved to ./result/CASE2_few_scored.csv
Total rows: 3290, scored: 3290

In [25]:
!{sys.executable} ../metric_calculation/AUC.py \
                    --root_dir ./result \
                    --output_file ./CASE2_few_auc.csv

Finding CSV files...
Found 1 CSV files
Processed 1/1 files (100.0%)
Failed: 1

In [26]:
import pandas as pd

df = pd.read_csv("./CASE2_few_auc.csv")
df

,folder_path,file_name,roc_auc,pr_auc,status
0,./result,CASE2_few_scored.csv,0.52439,0.51448,success
1,./result,[FOLDER_SUMMARY],0.52439,0.51448,success (averaged over 1 files)

#### zero-shot

In [ ]:
import sys

SCRIPT_DIR = "../inference/PanPep_Weight_Inference"
TEST_DATA = "../data/fig4/reshuffling_zero_0.csv"
NEGATIVE_DATA = "../data/Control_dataset.txt"

!{sys.executable} {SCRIPT_DIR}/inference_zero_shot.py \
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "{SCRIPT_DIR}/Requirements" \
    --result_dir "CASE2_zero"\
    --peptide_encoding "{SCRIPT_DIR}/peptide_b.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_b.npz" \
    --model default

Using 1 GPUs: [0]
Using model configuration: default

Processing peptide: ALWMRLLPLL on device: cuda:0

Processing batch 1/1 for peptide ALWMRLLPLL - 2026-03-16 23:36:22
batch processing time: 1.04s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/ALWMRLLPLL.parquet

Peptide ALWMRLLPLL processing time: 1.07s

Processing peptide: CTDDNALAYY on device: cuda:0

Processing batch 1/1 for peptide CTDDNALAYY - 2026-03-16 23:36:23
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/CTDDNALAYY.parquet

Peptide CTDDNALAYY processing time: 0.65s

Processing peptide: EIFDRYGEEV on device: cuda:0

Processing batch 1/1 for peptide EIFDRYGEEV - 2026-03-16 23:36:24
batch processing time: 0.61s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/EIFDRYGEEV.parquet

Peptide EIFDRYGEEV processing time: 0.64s

Processing peptide: FIASNGVKLV on device: cuda:0

Processing batch 1/1 for peptide FIASNGVKLV - 2026-03-16 23:36:25
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FIASNGVKLV.parquet

Peptide FIASNGVKLV processing time: 0.65s

Processing peptide: FLLSLFSLWL on device: cuda:0

Processing batch 1/1 for peptide FLLSLFSLWL - 2026-03-16 23:36:25
batch processing time: 0.70s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FLLSLFSLWL.parquet

Peptide FLLSLFSLWL processing time: 0.73s

Processing peptide: RMMEYGTTMV on device: cuda:0

Processing batch 1/1 for peptide RMMEYGTTMV - 2026-03-16 23:36:26
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/RMMEYGTTMV.parquet

Peptide RMMEYGTTMV processing time: 0.66s

Processing peptide: TLATHGLAAV on device: cuda:0

Processing batch 1/1 for peptide TLATHGLAAV - 2026-03-16 23:36:27
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/TLATHGLAAV.parquet

Peptide TLATHGLAAV processing time: 0.65s

Processing peptide: VMNILLQYVV on device: cuda:0

Processing batch 1/1 for peptide VMNILLQYVV - 2026-03-16 23:36:27
batch processing time: 0.65s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/VMNILLQYVV.parquet

Peptide VMNILLQYVV processing time: 0.68s

Processing peptide: VVVGAGGVGK on device: cuda:0

Processing batch 1/1 for peptide VVVGAGGVGK - 2026-03-16 23:36:28
batch processing time: 0.89s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/VVVGAGGVGK.parquet

Peptide VVVGAGGVGK processing time: 0.91s

Processing peptide: VVVGAVGVGK on device: cuda:0

Processing batch 1/1 for peptide VVVGAVGVGK - 2026-03-16 23:36:29
batch processing time: 0.61s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/VVVGAVGVGK.parquet

Peptide VVVGAVGVGK processing time: 0.64s

Processing peptide: AALPILFQV on device: cuda:0

Processing batch 1/1 for peptide AALPILFQV - 2026-03-16 23:36:30
batch processing time: 0.61s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/AALPILFQV.parquet

Peptide AALPILFQV processing time: 0.64s

Processing peptide: AFLLFLVLI on device: cuda:0

Processing batch 1/1 for peptide AFLLFLVLI - 2026-03-16 23:36:30
batch processing time: 0.73s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/AFLLFLVLI.parquet

Peptide AFLLFLVLI processing time: 0.76s

Processing peptide: ALASCMGLI on device: cuda:0

Processing batch 1/1 for peptide ALASCMGLI - 2026-03-16 23:36:31
batch processing time: 0.69s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/ALASCMGLI.parquet

Peptide ALASCMGLI processing time: 0.72s

Processing peptide: ALLPGLPAA on device: cuda:0

Processing batch 1/1 for peptide ALLPGLPAA - 2026-03-16 23:36:32
batch processing time: 0.72s, Progress: 100.0%
Successfully wrote 9560 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/ALLPGLPAA.parquet

Peptide ALLPGLPAA processing time: 0.75s

Processing peptide: ALNLGETFV on device: cuda:0

Processing batch 1/1 for peptide ALNLGETFV - 2026-03-16 23:36:33
batch processing time: 0.76s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/ALNLGETFV.parquet

Peptide ALNLGETFV processing time: 0.78s

Processing peptide: ALNNIINNA on device: cuda:0

Processing batch 1/1 for peptide ALNNIINNA - 2026-03-16 23:36:33
batch processing time: 0.84s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/ALNNIINNA.parquet

Peptide ALNNIINNA processing time: 0.87s

Processing peptide: ALPETTADI on device: cuda:0

Processing batch 1/1 for peptide ALPETTADI - 2026-03-16 23:36:34
batch processing time: 0.69s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/ALPETTADI.parquet

Peptide ALPETTADI processing time: 0.72s

Processing peptide: ALYYPSARI on device: cuda:0

Processing batch 1/1 for peptide ALYYPSARI - 2026-03-16 23:36:35
batch processing time: 0.78s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/ALYYPSARI.parquet

Peptide ALYYPSARI processing time: 0.81s

Processing peptide: AMDEFIERY on device: cuda:0

Processing batch 1/1 for peptide AMDEFIERY - 2026-03-16 23:36:36
batch processing time: 0.69s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/AMDEFIERY.parquet

Peptide AMDEFIERY processing time: 0.72s

Processing peptide: AMQTMLFTM on device: cuda:0

Processing batch 1/1 for peptide AMQTMLFTM - 2026-03-16 23:36:36
batch processing time: 0.66s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/AMQTMLFTM.parquet

Peptide AMQTMLFTM processing time: 0.69s

Processing peptide: ATSRMLSYY on device: cuda:0

Processing batch 1/1 for peptide ATSRMLSYY - 2026-03-16 23:36:37
batch processing time: 0.66s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/ATSRMLSYY.parquet

Peptide ATSRMLSYY processing time: 0.69s

Processing peptide: ATSRTLSYY on device: cuda:0

Processing batch 1/1 for peptide ATSRTLSYY - 2026-03-16 23:36:38
batch processing time: 0.68s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/ATSRTLSYY.parquet

Peptide ATSRTLSYY processing time: 0.71s

Processing peptide: AVLDMCASL on device: cuda:0

Processing batch 1/1 for peptide AVLDMCASL - 2026-03-16 23:36:39
batch processing time: 0.74s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/AVLDMCASL.parquet

Peptide AVLDMCASL processing time: 0.79s

Processing peptide: CLAYYFMRF on device: cuda:0

Processing batch 1/1 for peptide CLAYYFMRF - 2026-03-16 23:36:39
batch processing time: 0.95s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/CLAYYFMRF.parquet

Peptide CLAYYFMRF processing time: 0.98s

Processing peptide: CLEASFNYL on device: cuda:0

Processing batch 1/1 for peptide CLEASFNYL - 2026-03-16 23:36:40
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/CLEASFNYL.parquet

Peptide CLEASFNYL processing time: 0.66s

Processing peptide: CLGSLIYST on device: cuda:0

Processing batch 1/1 for peptide CLGSLIYST - 2026-03-16 23:36:41
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/CLGSLIYST.parquet

Peptide CLGSLIYST processing time: 0.66s

Processing peptide: CTDDNALAY on device: cuda:0

Processing batch 1/1 for peptide CTDDNALAY - 2026-03-16 23:36:42
batch processing time: 0.73s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/CTDDNALAY.parquet

Peptide CTDDNALAY processing time: 0.79s

Processing peptide: DKDPQFKDN on device: cuda:0

Processing batch 1/1 for peptide DKDPQFKDN - 2026-03-16 23:36:42
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/DKDPQFKDN.parquet

Peptide DKDPQFKDN processing time: 0.65s

Processing peptide: DLTSFLLSL on device: cuda:0

Processing batch 1/1 for peptide DLTSFLLSL - 2026-03-16 23:36:43
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/DLTSFLLSL.parquet

Peptide DLTSFLLSL processing time: 0.65s

Processing peptide: DNVILLNKH on device: cuda:0

Processing batch 1/1 for peptide DNVILLNKH - 2026-03-16 23:36:44
batch processing time: 0.64s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/DNVILLNKH.parquet

Peptide DNVILLNKH processing time: 0.67s

Processing peptide: DRLNQLESK on device: cuda:0

Processing batch 1/1 for peptide DRLNQLESK - 2026-03-16 23:36:44
batch processing time: 0.73s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/DRLNQLESK.parquet

Peptide DRLNQLESK processing time: 0.75s

Processing peptide: DYKHYTPSF on device: cuda:0

Processing batch 1/1 for peptide DYKHYTPSF - 2026-03-16 23:36:45
batch processing time: 0.65s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/DYKHYTPSF.parquet

Peptide DYKHYTPSF processing time: 0.67s

Processing peptide: DYTEISFML on device: cuda:0

Processing batch 1/1 for peptide DYTEISFML - 2026-03-16 23:36:46
batch processing time: 0.66s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/DYTEISFML.parquet

Peptide DYTEISFML processing time: 0.69s

Processing peptide: ETALALLLL on device: cuda:0

Processing batch 1/1 for peptide ETALALLLL - 2026-03-16 23:36:46
batch processing time: 2.19s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/ETALALLLL.parquet

Peptide ETALALLLL processing time: 2.22s

Processing peptide: EWFLAYILF on device: cuda:0

Processing batch 1/1 for peptide EWFLAYILF - 2026-03-16 23:36:49
batch processing time: 0.64s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/EWFLAYILF.parquet

Peptide EWFLAYILF processing time: 0.66s

Processing peptide: FAMQMAYRF on device: cuda:0

Processing batch 1/1 for peptide FAMQMAYRF - 2026-03-16 23:36:49
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9560 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FAMQMAYRF.parquet

Peptide FAMQMAYRF processing time: 0.65s

Processing peptide: FFSYFAVHF on device: cuda:0

Processing batch 1/1 for peptide FFSYFAVHF - 2026-03-16 23:36:50
batch processing time: 0.91s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FFSYFAVHF.parquet

Peptide FFSYFAVHF processing time: 0.94s

Processing peptide: FGDDTVIEV on device: cuda:0

Processing batch 1/1 for peptide FGDDTVIEV - 2026-03-16 23:36:51
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FGDDTVIEV.parquet

Peptide FGDDTVIEV processing time: 0.66s

Processing peptide: FIDIKRGVY on device: cuda:0

Processing batch 1/1 for peptide FIDIKRGVY - 2026-03-16 23:36:52
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FIDIKRGVY.parquet

Peptide FIDIKRGVY processing time: 0.66s

Processing peptide: FIDTKRGVY on device: cuda:0

Processing batch 1/1 for peptide FIDTKRGVY - 2026-03-16 23:36:52
batch processing time: 0.80s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FIDTKRGVY.parquet

Peptide FIDTKRGVY processing time: 0.83s

Processing peptide: FISTCACEI on device: cuda:0

Processing batch 1/1 for peptide FISTCACEI - 2026-03-16 23:36:53
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FISTCACEI.parquet

Peptide FISTCACEI processing time: 0.66s

Processing peptide: FKDNVILLN on device: cuda:0

Processing batch 1/1 for peptide FKDNVILLN - 2026-03-16 23:36:54
batch processing time: 0.69s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FKDNVILLN.parquet

Peptide FKDNVILLN processing time: 0.72s

Processing peptide: FKDQVILLN on device: cuda:0

Processing batch 1/1 for peptide FKDQVILLN - 2026-03-16 23:36:54
batch processing time: 0.66s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FKDQVILLN.parquet

Peptide FKDQVILLN processing time: 0.69s

Processing peptide: FLAFVVFLL on device: cuda:0

Processing batch 1/1 for peptide FLAFVVFLL - 2026-03-16 23:36:55
batch processing time: 0.71s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FLAFVVFLL.parquet

Peptide FLAFVVFLL processing time: 0.74s

Processing peptide: FLDGSCGSV on device: cuda:0

Processing batch 1/1 for peptide FLDGSCGSV - 2026-03-16 23:36:56
batch processing time: 0.80s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FLDGSCGSV.parquet

Peptide FLDGSCGSV processing time: 0.83s

Processing peptide: FLEGETLPT on device: cuda:0

Processing batch 1/1 for peptide FLEGETLPT - 2026-03-16 23:36:57
batch processing time: 0.61s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FLEGETLPT.parquet

Peptide FLEGETLPT processing time: 0.64s

Processing peptide: FLEYHDVRV on device: cuda:0

Processing batch 1/1 for peptide FLEYHDVRV - 2026-03-16 23:36:57
batch processing time: 0.72s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FLEYHDVRV.parquet

Peptide FLEYHDVRV processing time: 0.75s

Processing peptide: FLFAVGFYL on device: cuda:0

Processing batch 1/1 for peptide FLFAVGFYL - 2026-03-16 23:36:58
batch processing time: 0.75s, Progress: 100.0%
Successfully wrote 9560 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FLFAVGFYL.parquet

Peptide FLFAVGFYL processing time: 0.78s

Processing peptide: FLIGCNYLG on device: cuda:0

Processing batch 1/1 for peptide FLIGCNYLG - 2026-03-16 23:36:59
batch processing time: 0.59s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FLIGCNYLG.parquet

Peptide FLIGCNYLG processing time: 0.62s

Processing peptide: FLKKDAPYI on device: cuda:0

Processing batch 1/1 for peptide FLKKDAPYI - 2026-03-16 23:36:59
batch processing time: 0.73s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FLKKDAPYI.parquet

Peptide FLKKDAPYI processing time: 0.76s

Processing peptide: FLLPSLATV on device: cuda:0

Processing batch 1/1 for peptide FLLPSLATV - 2026-03-16 23:37:00
batch processing time: 0.76s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FLLPSLATV.parquet

Peptide FLLPSLATV processing time: 0.79s

Processing peptide: FLPFFSDVT on device: cuda:0

Processing batch 1/1 for peptide FLPFFSDVT - 2026-03-16 23:37:01
batch processing time: 0.58s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FLPFFSDVT.parquet

Peptide FLPFFSDVT processing time: 0.61s

Processing peptide: FLPFFSNVT on device: cuda:0

Processing batch 1/1 for peptide FLPFFSNVT - 2026-03-16 23:37:02
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FLPFFSNVT.parquet

Peptide FLPFFSNVT processing time: 0.64s

Processing peptide: FLYENAFLP on device: cuda:0

Processing batch 1/1 for peptide FLYENAFLP - 2026-03-16 23:37:02
batch processing time: 0.79s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FLYENAFLP.parquet

Peptide FLYENAFLP processing time: 0.82s

Processing peptide: FMCVEYCPI on device: cuda:0

Processing batch 1/1 for peptide FMCVEYCPI - 2026-03-16 23:37:03
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FMCVEYCPI.parquet

Peptide FMCVEYCPI processing time: 0.64s

Processing peptide: FMSEAKCWT on device: cuda:0

Processing batch 1/1 for peptide FMSEAKCWT - 2026-03-16 23:37:04
batch processing time: 0.68s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FMSEAKCWT.parquet

Peptide FMSEAKCWT processing time: 0.71s

Processing peptide: FSAVGDICY on device: cuda:0

Processing batch 1/1 for peptide FSAVGDICY - 2026-03-16 23:37:04
batch processing time: 0.65s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FSAVGDICY.parquet

Peptide FSAVGDICY processing time: 0.67s

Processing peptide: FSVVGNICY on device: cuda:0

Processing batch 1/1 for peptide FSVVGNICY - 2026-03-16 23:37:05
batch processing time: 0.81s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FSVVGNICY.parquet

Peptide FSVVGNICY processing time: 0.84s

Processing peptide: FTISVTTEI on device: cuda:0

Processing batch 1/1 for peptide FTISVTTEI - 2026-03-16 23:37:06
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9554 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FTISVTTEI.parquet

Peptide FTISVTTEI processing time: 0.65s

Processing peptide: FTPLVPFWI on device: cuda:0

Processing batch 1/1 for peptide FTPLVPFWI - 2026-03-16 23:37:07
batch processing time: 0.61s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_zero/FTPLVPFWI.parquet

Peptide FTPLVPFWI processing time: 0.64s

Processing peptide: FVFLVLLPL on device: cuda:0

Processing batch 1/1 for peptide FVFLVLLPL - 2026-03-16 23:37:07
batch processing time: 0.64s, Progress: 100.0%

In [29]:
import os
import pandas as pd

PARQUET_DIR = "../inference/PanPep_Weight_Inference/CASE2_zero"
CSV_PATH = "../data/fig4/reshuffling_zero_0.csv"

OUTPUT_DIR = "./result"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "CASE1_zero_scored.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

csv_df = pd.read_csv(CSV_PATH)

if "label" in csv_df.columns:
    csv_df = csv_df.rename(columns={"label": "Label"})

peptides = csv_df["peptide"].unique()

results = []
for pep in peptides:
    parquet_path = os.path.join(PARQUET_DIR, f"{pep}.parquet")
    if not os.path.exists(parquet_path):
        print(f"[SKIP] No parquet for {pep}")
        continue

    parquet_df = pd.read_parquet(parquet_path)[["CDR3", "Score"]].rename(
        columns={"CDR3": "binding_TCR"}
    )

    pep_rows = csv_df[csv_df["peptide"] == pep].copy()
    merged = pep_rows.merge(parquet_df, on="binding_TCR", how="left")
    results.append(merged)

    print(f"[OK] {pep}: {len(merged)} rows, {merged['Score'].notna().sum()} scored")

if results:
    final_df = pd.concat(results, ignore_index=True)
    final_df.to_csv(OUTPUT_PATH, index=False)

    print(f"\nSaved to {OUTPUT_PATH}")
    print(f"Total rows: {len(final_df)}, scored: {final_df['Score'].notna().sum()}")
else:
    print("No results to save.")

[OK] AALPILFQV: 2 rows, 2 scored
[OK] AFLLFLVLI: 2 rows, 2 scored
[OK] ALASCMGLI: 2 rows, 2 scored
[OK] ALLPGLPAA: 8 rows, 8 scored
[OK] ALNLGETFV: 4 rows, 4 scored
[OK] ALNNIINNA: 4 rows, 4 scored
[OK] ALPETTADI: 4 rows, 4 scored
[OK] ALWMRLLPLL: 2 rows, 2 scored
[OK] ALYYPSARI: 4 rows, 4 scored
[OK] AMDEFIERY: 4 rows, 4 scored
[OK] AMQTMLFTM: 6 rows, 6 scored
[OK] ATSRMLSYY: 2 rows, 2 scored
[OK] ATSRTLSYY: 6 rows, 6 scored
[OK] AVLDMCASL: 2 rows, 2 scored
[OK] CLAYYFMRF: 6 rows, 6 scored
[OK] CLEASFNYL: 6 rows, 6 scored
[OK] CLGSLIYST: 2 rows, 2 scored
[OK] CTDDNALAYY: 6 rows, 6 scored
[OK] CTDDNALAY: 2 rows, 2 scored
[OK] DKDPQFKDN: 2 rows, 2 scored
[OK] DLTSFLLSL: 2 rows, 2 scored
[OK] DNVILLNKH: 6 rows, 6 scored
[OK] DRLNQLESK: 2 rows, 2 scored
[OK] DYKHYTPSF: 2 rows, 2 scored
[OK] DYTEISFML: 2 rows, 2 scored
[OK] EIFDRYGEEV: 4 rows, 4 scored
[OK] ETALALLLL: 2 rows, 2 scored
[OK] EWFLAYILF: 2 rows, 2 scored
[OK] FAMQMAYRF: 8 rows, 8 scored
[OK] FFSYFAVHF: 2 rows, 2 scored
[OK] FGDDTVIEV: 2 rows, 2 scored
[OK] FIASNGVKLV: 2 rows, 2 scored
[OK] FIDIKRGVY: 2 rows, 2 scored
[OK] FIDTKRGVY: 2 rows, 2 scored
[OK] FISTCACEI: 4 rows, 4 scored
[OK] FKDNVILLN: 6 rows, 6 scored
[OK] FKDQVILLN: 2 rows, 2 scored
[OK] FLAFVVFLL: 6 rows, 6 scored
[OK] FLDGSCGSV: 6 rows, 6 scored
[OK] FLEGETLPT: 2 rows, 2 scored
[OK] FLEYHDVRV: 4 rows, 4 scored
[OK] FLFAVGFYL: 8 rows, 8 scored
[OK] FLIGCNYLG: 4 rows, 4 scored
[OK] FLKKDAPYI: 2 rows, 2 scored
[OK] FLLPSLATV: 6 rows, 6 scored
[OK] FLLSLFSLWL: 4 rows, 4 scored
[OK] FLPFFSDVT: 6 rows, 6 scored
[OK] FLPFFSNVT: 4 rows, 4 scored
[OK] FLYENAFLP: 2 rows, 2 scored
[OK] FMCVEYCPI: 6 rows, 6 scored
[OK] FMSEAKCWT: 2 rows, 2 scored
[OK] FSAVGDICY: 2 rows, 2 scored
[OK] FSVVGNICY: 4 rows, 4 scored
[OK] FTISVTTEI: 2 rows, 2 scored
[OK] FTPLVPFWI: 4 rows, 4 scored
[OK] FVFLVLLPL: 2 rows, 2 scored
[OK] FVLAAVYRI: 6 rows, 6 scored
[OK] FVMMSAPPA: 4 rows, 4 scored
[OK] FVTVYSHLL: 4 rows, 4 scored
[OK] FWITIAYII: 2 rows, 2 scored
[OK] GAIKLDDKD: 2 rows, 2 scored
[OK] GDAALALLL: 4 rows, 4 scored
[OK] GGETALALL: 6 rows, 6 scored
[OK] GLFKDCSKV: 8 rows, 8 scored
[OK] GLIAIVMVT: 6 rows, 6 scored
[OK] GLMWLSYFV: 6 rows, 6 scored
[OK] GLTVLPPLL: 4 rows, 4 scored
[OK] GLVEVEKGV: 6 rows, 6 scored
[OK] GSEHSLAEY: 2 rows, 2 scored
[OK] GVFCGVDAV: 2 rows, 2 scored
[OK] GVYALIAGA: 8 rows, 8 scored
[OK] GVYDYLVST: 8 rows, 8 scored
[OK] HLRMAGHSL: 2 rows, 2 scored
[OK] HSYFTSDYY: 2 rows, 2 scored
[OK] HTDLMAAYV: 6 rows, 6 scored
[OK] HYPYRLWHY: 4 rows, 4 scored
[OK] IFNGECPNF: 2 rows, 2 scored
[OK] IIFWFSLEL: 2 rows, 2 scored
[OK] IIWFLLLSV: 2 rows, 2 scored
[OK] IKLDDKDPQ: 4 rows, 4 scored
[OK] ILLLDQALV: 6 rows, 6 scored
[OK] ILLWQPIPV: 2 rows, 2 scored
[OK] ILMHCQTTL: 8 rows, 8 scored
[OK] ISDEFSSNV: 2 rows, 2 scored
[OK] ITNFKSVLY: 2 rows, 2 scored
[OK] ITSGWTFGA: 2 rows, 2 scored
[OK] IVNSVLLFL: 2 rows, 2 scored
[OK] KDPQFKDNV: 2 rows, 2 scored
[OK] KIILFLALI: 4 rows, 4 scored
[OK] KIYSKHTPI: 2 rows, 2 scored
[OK] KLDDKDPNF: 2 rows, 2 scored
[OK] KLLKSIAAT: 2 rows, 2 scored
[OK] KLNIKLLGV: 8 rows, 8 scored
[OK] KLPDDFMGC: 6 rows, 6 scored
[OK] KLVNKFLAL: 4 rows, 4 scored
[OK] KMFDAYVNT: 2 rows, 2 scored
[OK] KQLPFFYYS: 8 rows, 8 scored
[OK] KQLSSNFGA: 6 rows, 6 scored
[OK] KQWLVWLLL: 2 rows, 2 scored
[OK] LDDKDPNFK: 4 rows, 4 scored
[OK] LDRLNQLES: 2 rows, 2 scored
[OK] LIDFYLCFL: 8 rows, 8 scored
[OK] LIIMRTFKV: 8 rows, 8 scored
[OK] LITGRLQSL: 6 rows, 6 scored
[OK] LLEWLAMAV: 6 rows, 6 scored
[OK] LLFLMSFTV: 2 rows, 2 scored
[OK] LLFLVLIML: 8 rows, 8 scored
[OK] LLIRWQHFL: 2 rows, 2 scored
[OK] LLLDDFVEI: 2 rows, 2 scored
[OK] LLLTILTSL: 2 rows, 2 scored
[OK] LLSVCLGSL: 4 rows, 4 scored
[OK] LLVDLAEEL: 2 rows, 2 scored
[OK] LLWPVTLAC: 2 rows, 2 scored
[OK] LMGHFAWWT: 4 rows, 4 scored
[OK] LMWLIINLV: 2 rows, 2 scored
[OK] LNKHIDAYK: 2 rows, 2 scored
[OK] LPDDFTGCV: 6 rows, 6 scored
[OK] LQAENVTGL: 2 rows, 2 scored
[OK] LQAGNATEV: 2 rows, 2 scored
[OK] LTALRLCAY: 8 rows, 8 scored
[OK] LTGHMLDMY: 2 rows, 2 scored
[OK] LTNDNTSRY: 8 rows, 8 scored
[OK] LTSFLLSLF: 2 rows, 2 scored
[OK] LTYHGAIKL: 6 rows, 6 scored
[OK] LVFLFVAAI: 2 rows, 2 scored
[OK] LYALVYFLH: 2 rows, 2 scored
[OK] LYDANYFLC: 2 rows, 2 scored
[OK] MCDVRQLLF: 2 rows, 2 scored
[OK] MFDAYVNTF: 2 rows, 2 scored
[OK] MFLARGIVF: 4 rows, 4 scored
[OK] MLFTMLRKL: 4 rows, 4 scored
[OK] MQLFFSYFA: 2 rows, 2 scored
[OK] MSDVKCTSV: 4 rows, 4 scored
[OK] MVTNNTFTL: 6 rows, 6 scored
[OK] NFSKLINII: 2 rows, 2 scored
[OK] NLDAVPTGY: 2 rows, 2 scored
[OK] NLDESLIDL: 2 rows, 2 scored
[OK] NLDYIINLI: 2 rows, 2 scored
[OK] NLSDRVVFV: 4 rows, 4 scored
[OK] NSAIGKIQY: 4 rows, 4 scored
[OK] NTFSSTFNV: 6 rows, 6 scored
[OK] NTLQCIMLV: 2 rows, 2 scored
[OK] NTLTLAVPY: 2 rows, 2 scored
[OK] NVILLNKHI: 4 rows, 4 scored
[OK] NVLTLVYKV: 4 rows, 4 scored
[OK] PTDSYITTY: 8 rows, 8 scored
[OK] PYMFLSEWI: 4 rows, 4 scored
[OK] QLCTQHQPY: 2 rows, 2 scored
[OK] QLEMELTPV: 4 rows, 4 scored
[OK] QPYRVVVLS: 2 rows, 2 scored
[OK] QWNLVIGFL: 4 rows, 4 scored
[OK] RFLYIIKLI: 2 rows, 2 scored
[OK] RINATLETK: 2 rows, 2 scored
[OK] RLFARTRSM: 2 rows, 2 scored
[OK] RLLYPDYQI: 8 rows, 8 scored
[OK] RLNQLESKM: 6 rows, 6 scored
[OK] RLNQLESKV: 8 rows, 8 scored
[OK] RLSFKELLV: 2 rows, 2 scored
[OK] RLVDPQIQL: 4 rows, 4 scored
[OK] RLYLDAYNM: 2 rows, 2 scored
[OK] RMMEYGTTMV: 4 rows, 4 scored
[OK] RMWDFDIFL: 6 rows, 6 scored
[OK] RSDTRYVLM: 2 rows, 2 scored
[OK] RTIKGTYHW: 2 rows, 2 scored
[OK] RTIKVFTTV: 8 rows, 8 scored
[OK] RVVVLSFEL: 4 rows, 4 scored
[OK] RYLALYNKY: 2 rows, 2 scored
[OK] SISVLISAL: 4 rows, 4 scored
[OK] SLENVAFNV: 4 rows, 4 scored
[OK] SLINTLNDL: 6 rows, 6 scored
[OK] SLIYSTAAL: 6 rows, 6 scored
[OK] SLLSVLLSM: 6 rows, 6 scored
[OK] SLLVLVQST: 2 rows, 2 scored
[OK] SLPFGWLIV: 2 rows, 2 scored
[OK] SMQNCVLKL: 8 rows, 8 scored
[OK] SQLGGLHLL: 4 rows, 4 scored
[OK] SSSKLWAQY: 2 rows, 2 scored
[OK] SSSTCMMCY: 2 rows, 2 scored
[OK] STDVTIATY: 8 rows, 8 scored
[OK] STECSNLLL: 2 rows, 2 scored
[OK] STSAFVETV: 4 rows, 4 scored
[OK] SYLDLPWYL: 8 rows, 8 scored
[OK] TDDNALSYY: 4 rows, 4 scored
[OK] TFTYASALW: 2 rows, 2 scored
[OK] TILTSLLVL: 6 rows, 6 scored
[OK] TLATHGLAAV: 2 rows, 2 scored
[OK] TSDPTTFHL: 2 rows, 2 scored
[OK] TSNEVAVLY: 2 rows, 2 scored
[OK] TTEELPDEF: 2 rows, 2 scored
[OK] TTLNDFNLV: 2 rows, 2 scored
[OK] TVYSHLLLV: 2 rows, 2 scored
[OK] TWLTYTGAI: 2 rows, 2 scored
[OK] TYHGAIKLD: 2 rows, 2 scored
[OK] VAFNTLLFL: 4 rows, 4 scored
[OK] VFLVLWPLV: 6 rows, 6 scored
[OK] VLLAPLLSA: 2 rows, 2 scored
[OK] VLLSMQGAV: 2 rows, 2 scored
[OK] VLNDILSRL: 6 rows, 6 scored
[OK] VLQVRDVLV: 2 rows, 2 scored
[OK] VLSFELLHA: 2 rows, 2 scored
[OK] VLVCVLVAL: 2 rows, 2 scored
[OK] VLYENQKLI: 2 rows, 2 scored
[OK] VMCGGSLYV: 2 rows, 2 scored
[OK] VMDEFIERY: 2 rows, 2 scored
[OK] VMHANYIFW: 6 rows, 6 scored
[OK] VMNILLQYVV: 4 rows, 4 scored
[OK] VSDGTHWFV: 2 rows, 2 scored
[OK] VVVGAGGVGK: 2 rows, 2 scored
[OK] VVVGAVGVGK: 2 rows, 2 scored
[OK] VYAWNRKRI: 4 rows, 4 scored
[OK] WLIVGVALL: 2 rows, 2 scored
[OK] WLMWLIINL: 2 rows, 2 scored
[OK] WLTYTGAIK: 2 rows, 2 scored
[OK] WSMATYYLF: 2 rows, 2 scored
[OK] WVLALFDEV: 6 rows, 6 scored
[OK] YANRNRFLY: 8 rows, 8 scored
[OK] YASAVVLLI: 2 rows, 2 scored
[OK] YFLQSINFV: 2 rows, 2 scored
[OK] YFTSDYYQL: 2 rows, 2 scored
[OK] YHGAIKLDD: 4 rows, 4 scored
[OK] YLAVFDKNL: 2 rows, 2 scored
[OK] YLDSTDVTI: 4 rows, 4 scored
[OK] YLEGSVRVV: 8 rows, 8 scored
[OK] YQDVNCTEV: 8 rows, 8 scored
[OK] YTDFSSEII: 2 rows, 2 scored
[OK] YTNSFTRGV: 8 rows, 8 scored
[OK] YTVELGTEV: 2 rows, 2 scored
[OK] YVDDSSLTI: 8 rows, 8 scored
[OK] YVFHLYLQY: 2 rows, 2 scored
[OK] YYKKDNSYF: 2 rows, 2 scored

Saved to ./result/CASE1_zero_scored.csv
Total rows: 858, scored: 858

In [31]:
!{sys.executable} ../metric_calculation/AUC.py \
                    --root_dir ./result \
                    --output_file ./CASE2_zero_auc.csv

Finding CSV files...
Found 1 CSV files
Processed 1/1 files (100.0%)
Failed: 1

In [32]:
import pandas as pd

df = pd.read_csv("./CASE2_zero_auc.csv")
df

,folder_path,file_name,roc_auc,pr_auc,status
0,./result,CASE1_zero_scored.csv,0.48267,0.489076,success
1,./result,[FOLDER_SUMMARY],0.48267,0.489076,success (averaged over 1 files)

#### Meta-learner

In [ ]:
import sys

SCRIPT_DIR = "../inference/PanPep_Weight_Inference"
TEST_DATA = "../data/fig4/reshuffling_zero_0.csv"
NEGATIVE_DATA = "../data/Control_dataset.txt"

!{sys.executable} {SCRIPT_DIR}/inference_meta_learner.py \
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "{SCRIPT_DIR}/Requirements" \
    --result_dir "CASE2_meta"\
    --peptide_encoding "{SCRIPT_DIR}/peptide_b.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_b.npz"

Using 1 GPUs: [0]
GPU 0 will process 230 peptides with approximately 858 TCRs

Processing peptide: ALLPGLPAA on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide ALLPGLPAA - 2026-03-16 23:45:29
batch processing time: 0.87s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/ALLPGLPAA.parquet

Total time for peptide ALLPGLPAA: 0.98s

Processing peptide: FAMQMAYRF on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide FAMQMAYRF - 2026-03-16 23:45:30
batch processing time: 0.57s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/FAMQMAYRF.parquet

Total time for peptide FAMQMAYRF: 0.66s

Processing peptide: FLFAVGFYL on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide FLFAVGFYL - 2026-03-16 23:45:31
batch processing time: 0.57s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/FLFAVGFYL.parquet

Total time for peptide FLFAVGFYL: 0.67s

Processing peptide: GLFKDCSKV on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide GLFKDCSKV - 2026-03-16 23:45:31
batch processing time: 0.57s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/GLFKDCSKV.parquet

Total time for peptide GLFKDCSKV: 0.65s

Processing peptide: GVYALIAGA on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide GVYALIAGA - 2026-03-16 23:45:32
batch processing time: 0.61s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/GVYALIAGA.parquet

Total time for peptide GVYALIAGA: 0.70s

Processing peptide: GVYDYLVST on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide GVYDYLVST - 2026-03-16 23:45:33
batch processing time: 0.55s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/GVYDYLVST.parquet

Total time for peptide GVYDYLVST: 0.65s

Processing peptide: ILMHCQTTL on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide ILMHCQTTL - 2026-03-16 23:45:34
batch processing time: 0.66s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/ILMHCQTTL.parquet

Total time for peptide ILMHCQTTL: 0.75s

Processing peptide: KLNIKLLGV on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide KLNIKLLGV - 2026-03-16 23:45:35
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/KLNIKLLGV.parquet

Total time for peptide KLNIKLLGV: 0.74s

Processing peptide: KQLPFFYYS on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide KQLPFFYYS - 2026-03-16 23:45:35
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/KQLPFFYYS.parquet

Total time for peptide KQLPFFYYS: 0.75s

Processing peptide: LIDFYLCFL on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide LIDFYLCFL - 2026-03-16 23:45:36
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/LIDFYLCFL.parquet

Total time for peptide LIDFYLCFL: 0.75s

Processing peptide: LIIMRTFKV on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide LIIMRTFKV - 2026-03-16 23:45:37
batch processing time: 0.63s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/LIIMRTFKV.parquet

Total time for peptide LIIMRTFKV: 0.72s

Processing peptide: LLFLVLIML on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide LLFLVLIML - 2026-03-16 23:45:38
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/LLFLVLIML.parquet

Total time for peptide LLFLVLIML: 0.73s

Processing peptide: LTALRLCAY on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide LTALRLCAY - 2026-03-16 23:45:39
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/LTALRLCAY.parquet

Total time for peptide LTALRLCAY: 0.76s

Processing peptide: LTNDNTSRY on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide LTNDNTSRY - 2026-03-16 23:45:39
batch processing time: 0.69s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/LTNDNTSRY.parquet

Total time for peptide LTNDNTSRY: 0.79s

Processing peptide: PTDSYITTY on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide PTDSYITTY - 2026-03-16 23:45:40
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/PTDSYITTY.parquet

Total time for peptide PTDSYITTY: 0.73s

Processing peptide: RLLYPDYQI on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide RLLYPDYQI - 2026-03-16 23:45:41
batch processing time: 0.56s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/RLLYPDYQI.parquet

Total time for peptide RLLYPDYQI: 0.65s

Processing peptide: RLNQLESKV on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide RLNQLESKV - 2026-03-16 23:45:42
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/RLNQLESKV.parquet

Total time for peptide RLNQLESKV: 0.74s

Processing peptide: RTIKVFTTV on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide RTIKVFTTV - 2026-03-16 23:45:43
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/RTIKVFTTV.parquet

Total time for peptide RTIKVFTTV: 0.74s

Processing peptide: SMQNCVLKL on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide SMQNCVLKL - 2026-03-16 23:45:43
batch processing time: 0.73s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/SMQNCVLKL.parquet

Total time for peptide SMQNCVLKL: 0.83s

Processing peptide: STDVTIATY on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide STDVTIATY - 2026-03-16 23:45:44
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/STDVTIATY.parquet

Total time for peptide STDVTIATY: 0.74s

Processing peptide: SYLDLPWYL on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide SYLDLPWYL - 2026-03-16 23:45:45
batch processing time: 0.63s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/SYLDLPWYL.parquet

Total time for peptide SYLDLPWYL: 0.73s

Processing peptide: YANRNRFLY on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide YANRNRFLY - 2026-03-16 23:45:46
batch processing time: 0.70s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/YANRNRFLY.parquet

Total time for peptide YANRNRFLY: 0.79s

Processing peptide: YLEGSVRVV on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide YLEGSVRVV - 2026-03-16 23:45:47
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/YLEGSVRVV.parquet

Total time for peptide YLEGSVRVV: 0.73s

Processing peptide: YQDVNCTEV on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide YQDVNCTEV - 2026-03-16 23:45:48
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/YQDVNCTEV.parquet

Total time for peptide YQDVNCTEV: 0.74s

Processing peptide: YTNSFTRGV on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide YTNSFTRGV - 2026-03-16 23:45:49
batch processing time: 0.63s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/YTNSFTRGV.parquet

Total time for peptide YTNSFTRGV: 0.72s

Processing peptide: YVDDSSLTI on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide YVDDSSLTI - 2026-03-16 23:45:49
batch processing time: 0.56s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/YVDDSSLTI.parquet

Total time for peptide YVDDSSLTI: 0.64s

Processing peptide: AMQTMLFTM on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide AMQTMLFTM - 2026-03-16 23:45:50
batch processing time: 0.58s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/AMQTMLFTM.parquet

Total time for peptide AMQTMLFTM: 0.67s

Processing peptide: ATSRTLSYY on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide ATSRTLSYY - 2026-03-16 23:45:51
batch processing time: 0.75s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/ATSRTLSYY.parquet

Total time for peptide ATSRTLSYY: 0.85s

Processing peptide: CLAYYFMRF on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide CLAYYFMRF - 2026-03-16 23:45:52
batch processing time: 0.69s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/CLAYYFMRF.parquet

Total time for peptide CLAYYFMRF: 0.80s

Processing peptide: CLEASFNYL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide CLEASFNYL - 2026-03-16 23:45:53
batch processing time: 0.63s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/CLEASFNYL.parquet

Total time for peptide CLEASFNYL: 0.72s

Processing peptide: CTDDNALAYY on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide CTDDNALAYY - 2026-03-16 23:45:53
batch processing time: 0.55s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/CTDDNALAYY.parquet

Total time for peptide CTDDNALAYY: 0.64s

Processing peptide: DNVILLNKH on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide DNVILLNKH - 2026-03-16 23:45:54
batch processing time: 0.57s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/DNVILLNKH.parquet

Total time for peptide DNVILLNKH: 0.66s

Processing peptide: FKDNVILLN on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide FKDNVILLN - 2026-03-16 23:45:55
batch processing time: 2.34s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/FKDNVILLN.parquet

Total time for peptide FKDNVILLN: 2.44s

Processing peptide: FLAFVVFLL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide FLAFVVFLL - 2026-03-16 23:45:57
batch processing time: 0.66s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/FLAFVVFLL.parquet

Total time for peptide FLAFVVFLL: 0.75s

Processing peptide: FLDGSCGSV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide FLDGSCGSV - 2026-03-16 23:45:58
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/FLDGSCGSV.parquet

Total time for peptide FLDGSCGSV: 0.74s

Processing peptide: FLLPSLATV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide FLLPSLATV - 2026-03-16 23:45:59
batch processing time: 0.62s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/FLLPSLATV.parquet

Total time for peptide FLLPSLATV: 0.71s

Processing peptide: FLPFFSDVT on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide FLPFFSDVT - 2026-03-16 23:46:00
batch processing time: 0.74s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/FLPFFSDVT.parquet

Total time for peptide FLPFFSDVT: 0.82s

Processing peptide: FMCVEYCPI on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide FMCVEYCPI - 2026-03-16 23:46:01
batch processing time: 0.67s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/FMCVEYCPI.parquet

Total time for peptide FMCVEYCPI: 0.76s

Processing peptide: FVLAAVYRI on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide FVLAAVYRI - 2026-03-16 23:46:02
batch processing time: 0.59s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/FVLAAVYRI.parquet

Total time for peptide FVLAAVYRI: 0.68s

Processing peptide: GGETALALL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide GGETALALL - 2026-03-16 23:46:02
batch processing time: 0.56s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/GGETALALL.parquet

Total time for peptide GGETALALL: 0.66s

Processing peptide: GLIAIVMVT on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide GLIAIVMVT - 2026-03-16 23:46:03
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/GLIAIVMVT.parquet

Total time for peptide GLIAIVMVT: 0.73s

Processing peptide: GLMWLSYFV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide GLMWLSYFV - 2026-03-16 23:46:04
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/GLMWLSYFV.parquet

Total time for peptide GLMWLSYFV: 0.74s

Processing peptide: GLVEVEKGV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide GLVEVEKGV - 2026-03-16 23:46:05
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/GLVEVEKGV.parquet

Total time for peptide GLVEVEKGV: 0.74s

Processing peptide: HTDLMAAYV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide HTDLMAAYV - 2026-03-16 23:46:05
batch processing time: 0.66s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/HTDLMAAYV.parquet

Total time for peptide HTDLMAAYV: 0.75s

Processing peptide: ILLLDQALV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide ILLLDQALV - 2026-03-16 23:46:06
batch processing time: 0.56s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/ILLLDQALV.parquet

Total time for peptide ILLLDQALV: 0.64s

Processing peptide: KLPDDFMGC on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide KLPDDFMGC - 2026-03-16 23:46:07
batch processing time: 0.57s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/KLPDDFMGC.parquet

Total time for peptide KLPDDFMGC: 0.66s

Processing peptide: KQLSSNFGA on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide KQLSSNFGA - 2026-03-16 23:46:08
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/KQLSSNFGA.parquet

Total time for peptide KQLSSNFGA: 0.73s

Processing peptide: LITGRLQSL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide LITGRLQSL - 2026-03-16 23:46:09
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/LITGRLQSL.parquet

Total time for peptide LITGRLQSL: 0.72s

Processing peptide: LLEWLAMAV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide LLEWLAMAV - 2026-03-16 23:46:09
batch processing time: 0.63s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/LLEWLAMAV.parquet

Total time for peptide LLEWLAMAV: 0.72s

Processing peptide: LPDDFTGCV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide LPDDFTGCV - 2026-03-16 23:46:10
batch processing time: 0.62s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_meta/LPDDFTGCV.parquet


In [40]:
import os
import pandas as pd

PARQUET_DIR = "../inference/PanPep_Weight_Inference/CASE2_meta"
CSV_PATH = "../data/fig4/reshuffling_zero_0.csv"

OUTPUT_DIR = "./result"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "CASE2_meta_scored.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

csv_df = pd.read_csv(CSV_PATH)

if "label" in csv_df.columns:
    csv_df = csv_df.rename(columns={"label": "Label"})

peptides = csv_df["peptide"].unique()

results = []
for pep in peptides:
    parquet_path = os.path.join(PARQUET_DIR, f"{pep}.parquet")
    if not os.path.exists(parquet_path):
        print(f"[SKIP] No parquet for {pep}")
        continue

    parquet_df = pd.read_parquet(parquet_path)[["CDR3", "Score"]].rename(
        columns={"CDR3": "binding_TCR"}
    )

    pep_rows = csv_df[csv_df["peptide"] == pep].copy()
    merged = pep_rows.merge(parquet_df, on="binding_TCR", how="left")
    results.append(merged)

    print(f"[OK] {pep}: {len(merged)} rows, {merged['Score'].notna().sum()} scored")

if results:
    final_df = pd.concat(results, ignore_index=True)
    final_df.to_csv(OUTPUT_PATH, index=False)

    print(f"\nSaved to {OUTPUT_PATH}")
    print(f"Total rows: {len(final_df)}, scored: {final_df['Score'].notna().sum()}")
else:
    print("No results to save.")

[OK] AALPILFQV: 2 rows, 2 scored
[OK] AFLLFLVLI: 2 rows, 2 scored
[OK] ALASCMGLI: 2 rows, 2 scored
[OK] ALLPGLPAA: 8 rows, 8 scored
[OK] ALNLGETFV: 4 rows, 4 scored
[OK] ALNNIINNA: 4 rows, 4 scored
[OK] ALPETTADI: 4 rows, 4 scored
[OK] ALWMRLLPLL: 2 rows, 2 scored
[OK] ALYYPSARI: 4 rows, 4 scored
[OK] AMDEFIERY: 4 rows, 4 scored
[OK] AMQTMLFTM: 6 rows, 6 scored
[OK] ATSRMLSYY: 2 rows, 2 scored
[OK] ATSRTLSYY: 6 rows, 6 scored
[OK] AVLDMCASL: 2 rows, 2 scored
[OK] CLAYYFMRF: 6 rows, 6 scored
[OK] CLEASFNYL: 6 rows, 6 scored
[OK] CLGSLIYST: 2 rows, 2 scored
[OK] CTDDNALAYY: 6 rows, 6 scored
[OK] CTDDNALAY: 2 rows, 2 scored
[OK] DKDPQFKDN: 2 rows, 2 scored
[OK] DLTSFLLSL: 2 rows, 2 scored
[OK] DNVILLNKH: 6 rows, 6 scored
[OK] DRLNQLESK: 2 rows, 2 scored
[OK] DYKHYTPSF: 2 rows, 2 scored
[OK] DYTEISFML: 2 rows, 2 scored
[OK] EIFDRYGEEV: 4 rows, 4 scored
[OK] ETALALLLL: 2 rows, 2 scored
[OK] EWFLAYILF: 2 rows, 2 scored
[OK] FAMQMAYRF: 8 rows, 8 scored
[OK] FFSYFAVHF: 2 rows, 2 scored
[OK] FGDDTVIEV: 2 rows, 2 scored
[OK] FIASNGVKLV: 2 rows, 2 scored
[OK] FIDIKRGVY: 2 rows, 2 scored
[OK] FIDTKRGVY: 2 rows, 2 scored
[OK] FISTCACEI: 4 rows, 4 scored
[OK] FKDNVILLN: 6 rows, 6 scored
[OK] FKDQVILLN: 2 rows, 2 scored
[OK] FLAFVVFLL: 6 rows, 6 scored
[OK] FLDGSCGSV: 6 rows, 6 scored
[OK] FLEGETLPT: 2 rows, 2 scored
[OK] FLEYHDVRV: 4 rows, 4 scored
[OK] FLFAVGFYL: 8 rows, 8 scored
[OK] FLIGCNYLG: 4 rows, 4 scored
[OK] FLKKDAPYI: 2 rows, 2 scored
[OK] FLLPSLATV: 6 rows, 6 scored
[OK] FLLSLFSLWL: 4 rows, 4 scored
[OK] FLPFFSDVT: 6 rows, 6 scored
[OK] FLPFFSNVT: 4 rows, 4 scored
[OK] FLYENAFLP: 2 rows, 2 scored
[OK] FMCVEYCPI: 6 rows, 6 scored
[OK] FMSEAKCWT: 2 rows, 2 scored
[OK] FSAVGDICY: 2 rows, 2 scored
[OK] FSVVGNICY: 4 rows, 4 scored
[OK] FTISVTTEI: 2 rows, 2 scored
[OK] FTPLVPFWI: 4 rows, 4 scored
[OK] FVFLVLLPL: 2 rows, 2 scored
[OK] FVLAAVYRI: 6 rows, 6 scored
[OK] FVMMSAPPA: 4 rows, 4 scored
[OK] FVTVYSHLL: 4 rows, 4 scored
[OK] FWITIAYII: 2 rows, 2 scored
[OK] GAIKLDDKD: 2 rows, 2 scored
[OK] GDAALALLL: 4 rows, 4 scored
[OK] GGETALALL: 6 rows, 6 scored
[OK] GLFKDCSKV: 8 rows, 8 scored
[OK] GLIAIVMVT: 6 rows, 6 scored
[OK] GLMWLSYFV: 6 rows, 6 scored
[OK] GLTVLPPLL: 4 rows, 4 scored
[OK] GLVEVEKGV: 6 rows, 6 scored
[OK] GSEHSLAEY: 2 rows, 2 scored
[OK] GVFCGVDAV: 2 rows, 2 scored
[OK] GVYALIAGA: 8 rows, 8 scored
[OK] GVYDYLVST: 8 rows, 8 scored
[OK] HLRMAGHSL: 2 rows, 2 scored
[OK] HSYFTSDYY: 2 rows, 2 scored
[OK] HTDLMAAYV: 6 rows, 6 scored
[OK] HYPYRLWHY: 4 rows, 4 scored
[OK] IFNGECPNF: 2 rows, 2 scored
[OK] IIFWFSLEL: 2 rows, 2 scored
[OK] IIWFLLLSV: 2 rows, 2 scored
[OK] IKLDDKDPQ: 4 rows, 4 scored
[OK] ILLLDQALV: 6 rows, 6 scored
[OK] ILLWQPIPV: 2 rows, 2 scored
[OK] ILMHCQTTL: 8 rows, 8 scored
[OK] ISDEFSSNV: 2 rows, 2 scored
[OK] ITNFKSVLY: 2 rows, 2 scored
[OK] ITSGWTFGA: 2 rows, 2 scored
[OK] IVNSVLLFL: 2 rows, 2 scored
[OK] KDPQFKDNV: 2 rows, 2 scored
[OK] KIILFLALI: 4 rows, 4 scored
[OK] KIYSKHTPI: 2 rows, 2 scored
[OK] KLDDKDPNF: 2 rows, 2 scored
[OK] KLLKSIAAT: 2 rows, 2 scored
[OK] KLNIKLLGV: 8 rows, 8 scored
[OK] KLPDDFMGC: 6 rows, 6 scored
[OK] KLVNKFLAL: 4 rows, 4 scored
[OK] KMFDAYVNT: 2 rows, 2 scored
[OK] KQLPFFYYS: 8 rows, 8 scored
[OK] KQLSSNFGA: 6 rows, 6 scored
[OK] KQWLVWLLL: 2 rows, 2 scored
[OK] LDDKDPNFK: 4 rows, 4 scored
[OK] LDRLNQLES: 2 rows, 2 scored
[OK] LIDFYLCFL: 8 rows, 8 scored
[OK] LIIMRTFKV: 8 rows, 8 scored
[OK] LITGRLQSL: 6 rows, 6 scored
[OK] LLEWLAMAV: 6 rows, 6 scored
[OK] LLFLMSFTV: 2 rows, 2 scored
[OK] LLFLVLIML: 8 rows, 8 scored
[OK] LLIRWQHFL: 2 rows, 2 scored
[OK] LLLDDFVEI: 2 rows, 2 scored
[OK] LLLTILTSL: 2 rows, 2 scored
[OK] LLSVCLGSL: 4 rows, 4 scored
[OK] LLVDLAEEL: 2 rows, 2 scored
[OK] LLWPVTLAC: 2 rows, 2 scored
[OK] LMGHFAWWT: 4 rows, 4 scored
[OK] LMWLIINLV: 2 rows, 2 scored
[OK] LNKHIDAYK: 2 rows, 2 scored
[OK] LPDDFTGCV: 6 rows, 6 scored
[OK] LQAENVTGL: 2 rows, 2 scored
[OK] LQAGNATEV: 2 rows, 2 scored
[OK] LTALRLCAY: 8 rows, 8 scored
[OK] LTGHMLDMY: 2 rows, 2 scored
[OK] LTNDNTSRY: 8 rows, 8 scored
[OK] LTSFLLSLF: 2 rows, 2 scored
[OK] LTYHGAIKL: 6 rows, 6 scored
[OK] LVFLFVAAI: 2 rows, 2 scored
[OK] LYALVYFLH: 2 rows, 2 scored
[OK] LYDANYFLC: 2 rows, 2 scored
[OK] MCDVRQLLF: 2 rows, 2 scored
[OK] MFDAYVNTF: 2 rows, 2 scored
[OK] MFLARGIVF: 4 rows, 4 scored
[OK] MLFTMLRKL: 4 rows, 4 scored
[OK] MQLFFSYFA: 2 rows, 2 scored
[OK] MSDVKCTSV: 4 rows, 4 scored
[OK] MVTNNTFTL: 6 rows, 6 scored
[OK] NFSKLINII: 2 rows, 2 scored
[OK] NLDAVPTGY: 2 rows, 2 scored
[OK] NLDESLIDL: 2 rows, 2 scored
[OK] NLDYIINLI: 2 rows, 2 scored
[OK] NLSDRVVFV: 4 rows, 4 scored
[OK] NSAIGKIQY: 4 rows, 4 scored
[OK] NTFSSTFNV: 6 rows, 6 scored
[OK] NTLQCIMLV: 2 rows, 2 scored
[OK] NTLTLAVPY: 2 rows, 2 scored
[OK] NVILLNKHI: 4 rows, 4 scored
[OK] NVLTLVYKV: 4 rows, 4 scored
[OK] PTDSYITTY: 8 rows, 8 scored
[OK] PYMFLSEWI: 4 rows, 4 scored
[OK] QLCTQHQPY: 2 rows, 2 scored
[OK] QLEMELTPV: 4 rows, 4 scored
[OK] QPYRVVVLS: 2 rows, 2 scored
[OK] QWNLVIGFL: 4 rows, 4 scored
[OK] RFLYIIKLI: 2 rows, 2 scored
[OK] RINATLETK: 2 rows, 2 scored
[OK] RLFARTRSM: 2 rows, 2 scored
[OK] RLLYPDYQI: 8 rows, 8 scored
[OK] RLNQLESKM: 6 rows, 6 scored
[OK] RLNQLESKV: 8 rows, 8 scored
[OK] RLSFKELLV: 2 rows, 2 scored
[OK] RLVDPQIQL: 4 rows, 4 scored
[OK] RLYLDAYNM: 2 rows, 2 scored
[OK] RMMEYGTTMV: 4 rows, 4 scored
[OK] RMWDFDIFL: 6 rows, 6 scored
[OK] RSDTRYVLM: 2 rows, 2 scored
[OK] RTIKGTYHW: 2 rows, 2 scored
[OK] RTIKVFTTV: 8 rows, 8 scored
[OK] RVVVLSFEL: 4 rows, 4 scored
[OK] RYLALYNKY: 2 rows, 2 scored
[OK] SISVLISAL: 4 rows, 4 scored
[OK] SLENVAFNV: 4 rows, 4 scored
[OK] SLINTLNDL: 6 rows, 6 scored
[OK] SLIYSTAAL: 6 rows, 6 scored
[OK] SLLSVLLSM: 6 rows, 6 scored
[OK] SLLVLVQST: 2 rows, 2 scored
[OK] SLPFGWLIV: 2 rows, 2 scored
[OK] SMQNCVLKL: 8 rows, 8 scored
[OK] SQLGGLHLL: 4 rows, 4 scored
[OK] SSSKLWAQY: 2 rows, 2 scored
[OK] SSSTCMMCY: 2 rows, 2 scored
[OK] STDVTIATY: 8 rows, 8 scored
[OK] STECSNLLL: 2 rows, 2 scored
[OK] STSAFVETV: 4 rows, 4 scored
[OK] SYLDLPWYL: 8 rows, 8 scored
[OK] TDDNALSYY: 4 rows, 4 scored
[OK] TFTYASALW: 2 rows, 2 scored
[OK] TILTSLLVL: 6 rows, 6 scored
[OK] TLATHGLAAV: 2 rows, 2 scored
[OK] TSDPTTFHL: 2 rows, 2 scored
[OK] TSNEVAVLY: 2 rows, 2 scored
[OK] TTEELPDEF: 2 rows, 2 scored
[OK] TTLNDFNLV: 2 rows, 2 scored
[OK] TVYSHLLLV: 2 rows, 2 scored
[OK] TWLTYTGAI: 2 rows, 2 scored
[OK] TYHGAIKLD: 2 rows, 2 scored
[OK] VAFNTLLFL: 4 rows, 4 scored
[OK] VFLVLWPLV: 6 rows, 6 scored
[OK] VLLAPLLSA: 2 rows, 2 scored
[OK] VLLSMQGAV: 2 rows, 2 scored
[OK] VLNDILSRL: 6 rows, 6 scored
[OK] VLQVRDVLV: 2 rows, 2 scored
[OK] VLSFELLHA: 2 rows, 2 scored
[OK] VLVCVLVAL: 2 rows, 2 scored
[OK] VLYENQKLI: 2 rows, 2 scored
[OK] VMCGGSLYV: 2 rows, 2 scored
[OK] VMDEFIERY: 2 rows, 2 scored
[OK] VMHANYIFW: 6 rows, 6 scored
[OK] VMNILLQYVV: 4 rows, 4 scored
[OK] VSDGTHWFV: 2 rows, 2 scored
[OK] VVVGAGGVGK: 2 rows, 2 scored
[OK] VVVGAVGVGK: 2 rows, 2 scored
[OK] VYAWNRKRI: 4 rows, 4 scored
[OK] WLIVGVALL: 2 rows, 2 scored
[OK] WLMWLIINL: 2 rows, 2 scored
[OK] WLTYTGAIK: 2 rows, 2 scored
[OK] WSMATYYLF: 2 rows, 2 scored
[OK] WVLALFDEV: 6 rows, 6 scored
[OK] YANRNRFLY: 8 rows, 8 scored
[OK] YASAVVLLI: 2 rows, 2 scored
[OK] YFLQSINFV: 2 rows, 2 scored
[OK] YFTSDYYQL: 2 rows, 2 scored
[OK] YHGAIKLDD: 4 rows, 4 scored
[OK] YLAVFDKNL: 2 rows, 2 scored
[OK] YLDSTDVTI: 4 rows, 4 scored
[OK] YLEGSVRVV: 8 rows, 8 scored
[OK] YQDVNCTEV: 8 rows, 8 scored
[OK] YTDFSSEII: 2 rows, 2 scored
[OK] YTNSFTRGV: 8 rows, 8 scored
[OK] YTVELGTEV: 2 rows, 2 scored
[OK] YVDDSSLTI: 8 rows, 8 scored
[OK] YVFHLYLQY: 2 rows, 2 scored
[OK] YYKKDNSYF: 2 rows, 2 scored

Saved to ./result/CASE2_meta_scored.csv
Total rows: 858, scored: 858

In [41]:
!{sys.executable} ../metric_calculation/AUC.py \
                    --root_dir ./result \
                    --output_file ./CASE2_meta_auc.csv

Finding CSV files...
Found 1 CSV files
Processed 1/1 files (100.0%)
Failed: 1

In [42]:
import pandas as pd

df = pd.read_csv("./CASE2_meta_auc.csv")
df

,folder_path,file_name,roc_auc,pr_auc,status
0,./result,CASE2_meta_scored.csv,0.486413,0.485271,success
1,./result,[FOLDER_SUMMARY],0.486413,0.485271,success (averaged over 1 files)

### Other method

If you would like to reproduce other methods, you can use their web servers. For DLpTCR, you can use http://jianglab.org.cn/DLpTCR/ and select pTCRβ. For ERGO-II, you can use http://tcr2.cs.biu.ac.il/home and choose VDJdb mode.

## rank

For demonstration purposes, since running on the full background pool would be too time-consuming, we constructed a subset pool by randomly sampling 0.1% of the background library and used it for reproduction and result presentation. If you would like to reproduce the full original results, you can simply replace the subset background pool with the complete background library and rerun the same pipeline. In other words, the current setup is only for demonstration efficiency, while the full results can be recovered by using the original background pool.

In [ ]:
import sys

SCRIPT_DIR = "../inference/PanPep_Weight_Inference"
TEST_DATA = "../data/majority-fig3.csv"
NEGATIVE_DATA = "../data/Combined_library_sample_0.1pct.txt"

!{sys.executable} {SCRIPT_DIR}/inference_majority.py \
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "{SCRIPT_DIR}/Requirements" \
    --support_dir "../data/support/majority" \
    --peptide_encoding "{SCRIPT_DIR}/peptide_b.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_b.npz" \
    --result_dir "CASE2_majority_rank"

Using 1 GPUs: [0]
Using model configuration: default

Processing peptide: LLAGIGTVPI on device: cuda:0
Positive TCRs: 806, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../data/support/majority
Loading support data for peptide: LLAGIGTVPI
Query data size: 57265

Processing batch 1/6 for peptide LLAGIGTVPI - 2026-03-16 23:54:25
Finetuning model...
batch processing time: 15.23s, Progress: 16.7%

Processing batch 2/6 for peptide LLAGIGTVPI - 2026-03-16 23:54:40
Using finetuned model for inference...
batch processing time: 0.74s, Progress: 33.3%

Processing batch 3/6 for peptide LLAGIGTVPI - 2026-03-16 23:54:41
Using finetuned model for inference...
batch processing time: 0.71s, Progress: 50.0%

Processing batch 4/6 for peptide LLAGIGTVPI - 2026-03-16 23:54:41
Using finetuned model for inference...
batch processing time: 0.74s, Progress: 66.7%

Processing batch 5/6 for peptide LLAGIGTVPI - 2026-03-16 23:54:42
Using finetuned model for inference...
batch processing time: 0.67s, Progress: 83.3%

Processing batch 6/6 for peptide LLAGIGTVPI - 2026-03-16 23:54:43
Using finetuned model for inference...
batch processing time: 0.49s, Progress: 100.0%
Successfully wrote 57265 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_majority_rank/LLAGIGTVPI.parquet

Peptide LLAGIGTVPI processing time: 18.76s

Processing peptide: TTDPSFLGRY on device: cuda:0
Positive TCRs: 415, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../data/support/majority
Loading support data for peptide: TTDPSFLGRY
Query data size: 57186

Processing batch 1/6 for peptide TTDPSFLGRY - 2026-03-16 23:54:43
Finetuning model...
batch processing time: 11.52s, Progress: 16.7%

Processing batch 2/6 for peptide TTDPSFLGRY - 2026-03-16 23:54:55
Using finetuned model for inference...
batch processing time: 0.67s, Progress: 33.3%

Processing batch 3/6 for peptide TTDPSFLGRY - 2026-03-16 23:54:56
Using finetuned model for inference...
batch processing time: 0.68s, Progress: 50.0%

Processing batch 4/6 for peptide TTDPSFLGRY - 2026-03-16 23:54:56
Using finetuned model for inference...
batch processing time: 0.70s, Progress: 66.7%

Processing batch 5/6 for peptide TTDPSFLGRY - 2026-03-16 23:54:57
Using finetuned model for inference...
batch processing time: 0.61s, Progress: 83.3%

Processing batch 6/6 for peptide TTDPSFLGRY - 2026-03-16 23:54:58
Using finetuned model for inference...
batch processing time: 0.46s, Progress: 100.0%
Successfully wrote 57186 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_majority_rank/TTDPSFLGRY.parquet

Peptide TTDPSFLGRY processing time: 14.77s

Processing peptide: ATDALMTGF on device: cuda:0
Positive TCRs: 127, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../data/support/majority
Loading support data for peptide: ATDALMTGF
Query data size: 57129

Processing batch 1/6 for peptide ATDALMTGF - 2026-03-16 23:54:58
Finetuning model...
batch processing time: 12.23s, Progress: 16.7%

Processing batch 2/6 for peptide ATDALMTGF - 2026-03-16 23:55:11
Using finetuned model for inference...
batch processing time: 0.67s, Progress: 33.3%

Processing batch 3/6 for peptide ATDALMTGF - 2026-03-16 23:55:11
Using finetuned model for inference...
batch processing time: 0.64s, Progress: 50.0%

Processing batch 4/6 for peptide ATDALMTGF - 2026-03-16 23:55:12
Using finetuned model for inference...
batch processing time: 0.62s, Progress: 66.7%

Processing batch 5/6 for peptide ATDALMTGF - 2026-03-16 23:55:12
Using finetuned model for inference...
batch processing time: 0.58s, Progress: 83.3%

Processing batch 6/6 for peptide ATDALMTGF - 2026-03-16 23:55:13
Using finetuned model for inference...
batch processing time: 0.44s, Progress: 100.0%
Successfully wrote 57129 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_majority_rank/ATDALMTGF.parquet

Peptide ATDALMTGF processing time: 15.31s

Processing peptide: LTDEMIAQY on device: cuda:0
Positive TCRs: 127, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../data/support/majority
Loading support data for peptide: LTDEMIAQY
Query data size: 57129

Processing batch 1/6 for peptide LTDEMIAQY - 2026-03-16 23:55:14
Finetuning model...
batch processing time: 10.50s, Progress: 16.7%

Processing batch 2/6 for peptide LTDEMIAQY - 2026-03-16 23:55:24
Using finetuned model for inference...
batch processing time: 0.65s, Progress: 33.3%

Processing batch 3/6 for peptide LTDEMIAQY - 2026-03-16 23:55:25
Using finetuned model for inference...
batch processing time: 0.65s, Progress: 50.0%

Processing batch 4/6 for peptide LTDEMIAQY - 2026-03-16 23:55:26
Using finetuned model for inference...
batch processing time: 0.62s, Progress: 66.7%

Processing batch 5/6 for peptide LTDEMIAQY - 2026-03-16 23:55:26
Using finetuned model for inference...
batch processing time: 0.60s, Progress: 83.3%

Processing batch 6/6 for peptide LTDEMIAQY - 2026-03-16 23:55:27
Using finetuned model for inference...
batch processing time: 0.42s, Progress: 100.0%
Successfully wrote 57129 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE2_majority_rank/LTDEMIAQY.parquet

Peptide LTDEMIAQY processing time: 13.56s

Total execution time: 63.69s (0.02 hours)

In [45]:
!{sys.executable} ../metric_calculation/sort.py \
                    --input_dir ../inference/PanPep_Weight_Inference/CASE2_majority_rank \
                    --output_dir ./CASE2_majority_sort

Found 4 files to process:
  CSV files: 0
  Parquet files: 4

Completed processing 4 files

In [ ]:
!{sys.executable} ../metric_calculation/bedroc.py \
                    -i ./CASE2_majority_sort/CASE2_majority_rank \
                    -o ./CASE2_majority_bedroc

2026-03-16 23:57:13,353 - INFO - Input directory: /mnt/d/PanPep_Reusability/jupter/inference/PanPep_Weight_Inference/CASE2_majority_rank
2026-03-16 23:57:13,354 - INFO - Output directory: ./CASE2_majority_bedroc
2026-03-16 23:57:13,354 - INFO - Number of processes: 8
Total: 4 files, To process: 4 files
Processing files:   0%|                                   | 0/4 [00:00<?, ?it/s]
File: TTDPSFLGRY_sorted.parquet

File: LLAGIGTVPI_sorted.parquet

File: LTDEMIAQY_sorted.parquet

File: ATDALMTGF_sorted.parquet
Processing files: 100%|███████████████████████████| 4/4 [00:00<00:00, 29.71it/s]
2026-03-16 23:57:13,579 - INFO - Successfully processed 4 files.
2026-03-16 23:57:13,579 - INFO - Detailed results stored in: ./CASE2_majority_bedroc/
2026-03-16 23:57:13,579 - INFO - Starting summary calculation...
2026-03-16 23:57:13,582 - INFO - Reading 4 result files...
Reading detailed results: 100%|██████████████████| 4/4 [00:00<00:00, 152.00it/s]
2026-03-16 23:57:13,628 - INFO - Summary saved to: ./CASE2_majority_bedroc/summary_by_directory.csv
2026-03-16 23:57:13,628 - INFO - Total files processed: 4
2026-03-16 23:57:13,628 - INFO - Total unique directories: 1
2026-03-16 23:57:13,628 - INFO - Global mean BEDROC score: 0.2224
Top 10 directories by BEDROC score:
                                                                             Directory  BEDROC_Mean  BEDROC_Std  File_Count
/mnt/d/PanPep_Reusability/jupter/inference/PanPep_Weight_Inference/CASE2_majority_rank     0.222439    0.108694           4
2026-03-16 23:57:13,630 - INFO - Starting per-directory merge of detailed results...
2026-03-16 23:57:13,646 - WARNING - No directories found for merging.

In [48]:
import os
import glob
import pandas as pd

detailed_dir = "./CASE2_majority_bedroc"

# Print all CSV files in the detailed results directory
csv_files = sorted(glob.glob(os.path.join(detailed_dir, "*.csv")))

print(f"Found {len(csv_files)} CSV file(s) in: {detailed_dir}\n")

for file_path in csv_files:
    print("=" * 100)
    print(f"File: {file_path}")
    print("=" * 100)
    df = pd.read_csv(file_path)
    print(df)
    print("\n")

Found 5 CSV file(s) in: ./CASE2_majority_bedroc

====================================================================================================
File: ./CASE2_majority_bedroc/summary_by_directory.csv
====================================================================================================
                                           Directory  BEDROC_Mean  BEDROC_Std  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...     0.222439    0.108694

   File_Count
0           4


====================================================================================================
File: ./CASE2_majority_bedroc/temp_ATDALMTGF_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                   Filename  BEDROC_Score  Alpha
0  ATDALMTGF_sorted.parquet      0.375515     20


====================================================================================================
File: ./CASE2_majority_bedroc/temp_LLAGIGTVPI_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                    Filename  BEDROC_Score  Alpha
0  LLAGIGTVPI_sorted.parquet      0.157253     20


====================================================================================================
File: ./CASE2_majority_bedroc/temp_LTDEMIAQY_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                   Filename  BEDROC_Score  Alpha
0  LTDEMIAQY_sorted.parquet      0.134341     20


====================================================================================================
File: ./CASE2_majority_bedroc/temp_TTDPSFLGRY_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                    Filename  BEDROC_Score  Alpha
0  TTDPSFLGRY_sorted.parquet      0.222647     20

In [ ]:
!{sys.executable} "../metric_calculation/success_rate&hit_rate.py" \
    --root_dir "./CASE2_majority_sort/CASE2_majority_rank" \
    --output "CASE2_majority_sort" \
    --output_dir "./CASE2_majority_success"

2026-03-16 23:58:23,173 - INFO - Multiprocessing start method set to 'spawn'.
2026-03-16 23:58:23,252 - INFO - Configuration: ProcessingConfig(root_dir='/mnt/d/PanPep_Reusability/jupter/inference/PanPep_Weight_Inference/CASE2_majority_rank', top_k_ratio=1, batch_size=150, num_gpus=1, output_file='CASE2_majority_sort', output_dir='./CASE2_majority_success', gpu_id=None)
2026-03-16 23:58:23,253 - INFO - Detected 1 GPU(s)
Processing directories:   0%|                             | 0/1 [00:00<?, ?it/s]2026-03-16 23:58:25,154 - INFO - Process 1177481 using device: cuda:0
Processing directories: 100%|█████████████████████| 1/1 [00:02<00:00,  2.25s/it]
2026-03-16 23:58:25,529 - INFO - Combining 1 DataFrames...
2026-03-16 23:58:25,856 - INFO - Final results saved to CASE2_majority_success/CASE2_majority_sort.csv and CASE2_majority_success/CASE2_majority_sort.parquet

In [ ]:
!{sys.executable} "../metric_calculation/get_success_AUC.py" \
    --input "./CASE2_majority_success/CASE2_majority_sort.parquet" \
    --output "CASE2_majority_success_AUC"

Found 1 directories.
1. '/mnt/d/PanPep_Reusability/jupter/inference/PanPep_Weight_Inference/CASE2_majority_rank'
['/mnt/d/PanPep_Reusability/jupter/inference/PanPep_Weight_Inference/CASE2_majority_rank'] n=57265  Top_K range=(1, 57265)  y range=(0, 1)
/mnt/d/PanPep_Reusability/jupter/../metric_calculation/get_success_AUC.py:190: DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.
  area = float(np.trapz(ys, xs_norm))
  AUC@0.0100%: area=0
  AUC@0.1000%: area=6.11276e-06
  AUC@1.0000%: area=0.000438797
  AUC@5.0000%: area=0.00811599
  AUC@10.0000%: area=0.0244644
  AUC@20.0000%: area=0.0663292
  AUC@100.0000%: area=0.69559

Saved results to: CASE2_majority_success_AUC