# CASE 4: Training Reproducibility with TCRα Extension #

Since the number of models generated across the 10 folds is quite large, we provide only the Jupyter notebook for a single fold here, specifically the first fold in the reshuffling process. This notebook reproduces the zero setting of the Meta-learner model. The remaining results can be reproduced by following the same workflow for the other folds.

## classification

### PanPep

##### majority

In [7]:
import sys

SCRIPT_DIR = "../inference/PanPep_Weight_Inference"
TEST_DATA = "../data/independent_dataset(alpha)/tcra_majority.csv"
NEGATIVE_DATA = "../data/independent_dataset(alpha)/Control dataset_tcra.txt" #This is also equivalent to running the rank.
!{sys.executable} {SCRIPT_DIR}/inference_majority.py \
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "../data/fold1-alpha" \
    --support_dir "../data/majority-alpha" \
    --peptide_encoding "{SCRIPT_DIR}/peptide_ab.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_ab.npz" \
    --result_dir "CASE4_majority_rank"

Using 1 GPUs: [0]
Using model configuration: default

Processing peptide: LLAGIGTVPI on device: cuda:0
Positive TCRs: 361, Negative TCRs: 37098
Total batches: 4
Loading support data from: ../data/majority-alpha
Loading support data for peptide: LLAGIGTVPI
Query data size: 36883

Processing batch 1/4 for peptide LLAGIGTVPI - 2026-03-17 15:55:08
Finetuning model...
batch processing time: 13.68s, Progress: 25.0%

Processing batch 2/4 for peptide LLAGIGTVPI - 2026-03-17 15:55:22
Using finetuned model for inference...
batch processing time: 0.53s, Progress: 50.0%

Processing batch 3/4 for peptide LLAGIGTVPI - 2026-03-17 15:55:22
Using finetuned model for inference...
batch processing time: 0.50s, Progress: 75.0%

Processing batch 4/4 for peptide LLAGIGTVPI - 2026-03-17 15:55:23
Using finetuned model for inference...
batch processing time: 0.35s, Progress: 100.0%
Successfully wrote 36883 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_majority_rank/LLAGIGTVPI.parquet

Peptide LLAGIGTVPI processing time: 15.22s

Processing peptide: TTDPSFLGRY on device: cuda:0
Positive TCRs: 368, Negative TCRs: 37091
Total batches: 4
Loading support data from: ../data/majority-alpha
Loading support data for peptide: TTDPSFLGRY
Query data size: 36871

Processing batch 1/4 for peptide TTDPSFLGRY - 2026-03-17 15:55:23
Finetuning model...
batch processing time: 11.00s, Progress: 25.0%

Processing batch 2/4 for peptide TTDPSFLGRY - 2026-03-17 15:55:34
Using finetuned model for inference...
batch processing time: 0.50s, Progress: 50.0%

Processing batch 3/4 for peptide TTDPSFLGRY - 2026-03-17 15:55:35
Using finetuned model for inference...
batch processing time: 0.55s, Progress: 75.0%

Processing batch 4/4 for peptide TTDPSFLGRY - 2026-03-17 15:55:36
Using finetuned model for inference...
batch processing time: 0.46s, Progress: 100.0%
Successfully wrote 36871 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_majority_rank/TTDPSFLGRY.parquet

Peptide TTDPSFLGRY processing time: 12.66s

Processing peptide: ATDALMTGF on device: cuda:0
Positive TCRs: 106, Negative TCRs: 37353
Total batches: 4
Loading support data from: ../data/majority-alpha
Loading support data for peptide: ATDALMTGF
Query data size: 37291

Processing batch 1/4 for peptide ATDALMTGF - 2026-03-17 15:55:36
Finetuning model...
batch processing time: 10.44s, Progress: 25.0%

Processing batch 2/4 for peptide ATDALMTGF - 2026-03-17 15:55:47
Using finetuned model for inference...
batch processing time: 0.47s, Progress: 50.0%

Processing batch 3/4 for peptide ATDALMTGF - 2026-03-17 15:55:47
Using finetuned model for inference...
batch processing time: 0.51s, Progress: 75.0%

Processing batch 4/4 for peptide ATDALMTGF - 2026-03-17 15:55:48
Using finetuned model for inference...
batch processing time: 0.35s, Progress: 100.0%
Successfully wrote 37291 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_majority_rank/ATDALMTGF.parquet

Peptide ATDALMTGF processing time: 11.93s

Processing peptide: FLCMKALLL on device: cuda:0
Positive TCRs: 134, Negative TCRs: 37325
Total batches: 4
Loading support data from: ../data/majority-alpha
Loading support data for peptide: FLCMKALLL
Query data size: 37245

Processing batch 1/4 for peptide FLCMKALLL - 2026-03-17 15:55:51
Finetuning model...
batch processing time: 10.54s, Progress: 25.0%

Processing batch 2/4 for peptide FLCMKALLL - 2026-03-17 15:56:01
Using finetuned model for inference...
batch processing time: 0.48s, Progress: 50.0%

Processing batch 3/4 for peptide FLCMKALLL - 2026-03-17 15:56:02
Using finetuned model for inference...
batch processing time: 0.51s, Progress: 75.0%

Processing batch 4/4 for peptide FLCMKALLL - 2026-03-17 15:56:02
Using finetuned model for inference...
batch processing time: 0.37s, Progress: 100.0%
Successfully wrote 37245 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_majority_rank/FLCMKALLL.parquet

Peptide FLCMKALLL processing time: 12.04s

Processing peptide: KTFPPTEPK on device: cuda:0
Positive TCRs: 122, Negative TCRs: 37337
Total batches: 4
Loading support data from: ../data/majority-alpha
Loading support data for peptide: KTFPPTEPK
Query data size: 37265

Processing batch 1/4 for peptide KTFPPTEPK - 2026-03-17 15:56:03
Finetuning model...
batch processing time: 10.34s, Progress: 25.0%

Processing batch 2/4 for peptide KTFPPTEPK - 2026-03-17 15:56:13
Using finetuned model for inference...
batch processing time: 0.49s, Progress: 50.0%

Processing batch 3/4 for peptide KTFPPTEPK - 2026-03-17 15:56:14
Using finetuned model for inference...
batch processing time: 0.49s, Progress: 75.0%

Processing batch 4/4 for peptide KTFPPTEPK - 2026-03-17 15:56:14
Using finetuned model for inference...
batch processing time: 0.34s, Progress: 100.0%
Successfully wrote 37265 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_majority_rank/KTFPPTEPK.parquet

Peptide KTFPPTEPK processing time: 11.80s

Processing peptide: LTDEMIAQY on device: cuda:0
Positive TCRs: 120, Negative TCRs: 37339
Total batches: 4
Loading support data from: ../data/majority-alpha
Loading support data for peptide: LTDEMIAQY
Query data size: 37267

Processing batch 1/4 for peptide LTDEMIAQY - 2026-03-17 15:56:15
Finetuning model...
batch processing time: 12.89s, Progress: 25.0%

Processing batch 2/4 for peptide LTDEMIAQY - 2026-03-17 15:56:28
Using finetuned model for inference...
batch processing time: 0.44s, Progress: 50.0%

Processing batch 3/4 for peptide LTDEMIAQY - 2026-03-17 15:56:28
Using finetuned model for inference...
batch processing time: 0.41s, Progress: 75.0%

Processing batch 4/4 for peptide LTDEMIAQY - 2026-03-17 15:56:28
Using finetuned model for inference...
batch processing time: 0.29s, Progress: 100.0%
Successfully wrote 37267 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_majority_rank/LTDEMIAQY.parquet

Peptide LTDEMIAQY processing time: 14.18s

Processing peptide: QYIKWPWYI on device: cuda:0
Positive TCRs: 128, Negative TCRs: 37331
Total batches: 4
Loading support data from: ../data/majority-alpha
Loading support data for peptide: QYIKWPWYI
Query data size: 37255

Processing batch 1/4 for peptide QYIKWPWYI - 2026-03-17 15:56:29
Finetuning model...
batch processing time: 10.13s, Progress: 25.0%

Processing batch 2/4 for peptide QYIKWPWYI - 2026-03-17 15:56:39
Using finetuned model for inference...
batch processing time: 0.48s, Progress: 50.0%

Processing batch 3/4 for peptide QYIKWPWYI - 2026-03-17 15:56:40
Using finetuned model for inference...
batch processing time: 0.47s, Progress: 75.0%

Processing batch 4/4 for peptide QYIKWPWYI - 2026-03-17 15:56:40
Using finetuned model for inference...
batch processing time: 0.32s, Progress: 100.0%
Successfully wrote 37255 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_majority_rank/QYIKWPWYI.parquet

Peptide QYIKWPWYI processing time: 11.51s

Processing peptide: SPRWYFYYL on device: cuda:0
Positive TCRs: 362, Negative TCRs: 37097
Total batches: 4
Loading support data from: ../data/majority-alpha
Loading support data for peptide: SPRWYFYYL
Query data size: 36881

Processing batch 1/4 for peptide SPRWYFYYL - 2026-03-17 15:56:41
Finetuning model...
batch processing time: 11.58s, Progress: 25.0%

Processing batch 2/4 for peptide SPRWYFYYL - 2026-03-17 15:56:52
Using finetuned model for inference...
batch processing time: 0.53s, Progress: 50.0%

Processing batch 3/4 for peptide SPRWYFYYL - 2026-03-17 15:56:53
Using finetuned model for inference...
batch processing time: 0.52s, Progress: 75.0%

Processing batch 4/4 for peptide SPRWYFYYL - 2026-03-17 15:56:53
Using finetuned model for inference...
batch processing time: 0.33s, Progress: 100.0%
Successfully wrote 36881 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_majority_rank/SPRWYFYYL.parquet

Peptide SPRWYFYYL processing time: 13.09s

Processing peptide: VMATRRNVL on device: cuda:0
Positive TCRs: 241, Negative TCRs: 37218
Total batches: 4
Loading support data from: ../data/majority-alpha
Loading support data for peptide: VMATRRNVL
Query data size: 37075

Processing batch 1/4 for peptide VMATRRNVL - 2026-03-17 15:56:54
Finetuning model...
batch processing time: 13.26s, Progress: 25.0%

Processing batch 2/4 for peptide VMATRRNVL - 2026-03-17 15:57:07
Using finetuned model for inference...
batch processing time: 0.47s, Progress: 50.0%

Processing batch 3/4 for peptide VMATRRNVL - 2026-03-17 15:57:07
Using finetuned model for inference...
batch processing time: 0.48s, Progress: 75.0%

Processing batch 4/4 for peptide VMATRRNVL - 2026-03-17 15:57:08
Using finetuned model for inference...
batch processing time: 0.35s, Progress: 100.0%
Successfully wrote 37075 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_majority_rank/VMATRRNVL.parquet

Peptide VMATRRNVL processing time: 14.66s

Processing peptide: VMTTVLATL on device: cuda:0
Positive TCRs: 101, Negative TCRs: 37358
Total batches: 4
Loading support data from: ../data/majority-alpha
Loading support data for peptide: VMTTVLATL
Query data size: 37299

Processing batch 1/4 for peptide VMTTVLATL - 2026-03-17 15:57:08
Finetuning model...
batch processing time: 10.01s, Progress: 25.0%

Processing batch 2/4 for peptide VMTTVLATL - 2026-03-17 15:57:18
Using finetuned model for inference...
batch processing time: 0.45s, Progress: 50.0%

Processing batch 3/4 for peptide VMTTVLATL - 2026-03-17 15:57:19
Using finetuned model for inference...
batch processing time: 0.42s, Progress: 75.0%

Processing batch 4/4 for peptide VMTTVLATL - 2026-03-17 15:57:19
Using finetuned model for inference...
batch processing time: 0.30s, Progress: 100.0%
Successfully wrote 37299 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_majority_rank/VMTTVLATL.parquet

Peptide VMTTVLATL processing time: 11.30s

Processing peptide: YLQPRTFLL on device: cuda:0
Positive TCRs: 642, Negative TCRs: 36817
Total batches: 4
Loading support data from: ../data/majority-alpha
Loading support data for peptide: YLQPRTFLL
Query data size: 36433

Processing batch 1/4 for peptide YLQPRTFLL - 2026-03-17 15:57:20
Finetuning model...
batch processing time: 12.44s, Progress: 25.0%

Processing batch 2/4 for peptide YLQPRTFLL - 2026-03-17 15:57:32
Using finetuned model for inference...
batch processing time: 2.84s, Progress: 50.0%

Processing batch 3/4 for peptide YLQPRTFLL - 2026-03-17 15:57:35
Using finetuned model for inference...
batch processing time: 0.47s, Progress: 75.0%

Processing batch 4/4 for peptide YLQPRTFLL - 2026-03-17 15:57:36
Using finetuned model for inference...
batch processing time: 0.32s, Progress: 100.0%
Successfully wrote 36433 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_majority_rank/YLQPRTFLL.parquet

Peptide YLQPRTFLL processing time: 16.18s

Total execution time: 149.26s (0.04 hours)

In [8]:
import os
import pandas as pd

PARQUET_DIR = "../inference/PanPep_Weight_Inference/CASE4_majority_rank"
CSV_PATH = "../data/fig5/reshuffling_majority_0.csv"


OUTPUT_DIR = "./result"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "CASE4_majority_scored.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

csv_df = pd.read_csv(CSV_PATH)

if "label" in csv_df.columns:
    csv_df = csv_df.rename(columns={"label": "Label"})

peptides = csv_df["peptide"].unique()

results = []
for pep in peptides:
    parquet_path = os.path.join(PARQUET_DIR, f"{pep}.parquet")
    if not os.path.exists(parquet_path):
        print(f"[SKIP] No parquet for {pep}")
        continue

    parquet_df = pd.read_parquet(parquet_path)[["CDR3", "Score"]].rename(
        columns={"CDR3": "binding_TCR"}
    )

    pep_rows = csv_df[csv_df["peptide"] == pep].copy()
    merged = pep_rows.merge(parquet_df, on="binding_TCR", how="left")
    results.append(merged)

    print(f"[OK] {pep}: {len(merged)} rows, {merged['Score'].notna().sum()} scored")

if results:
    final_df = pd.concat(results, ignore_index=True)
    final_df.to_csv(OUTPUT_PATH, index=False)

    print(f"\nSaved to {OUTPUT_PATH}")
    print(f"Total rows: {len(final_df)}, scored: {final_df['Score'].notna().sum()}")
else:
    print("No results to save.")

[OK] ATDALMTGF: 44 rows, 44 scored
[OK] FLCMKALLL: 54 rows, 54 scored
[OK] KTFPPTEPK: 50 rows, 50 scored
[OK] LLAGIGTVPI: 146 rows, 146 scored
[OK] LTDEMIAQY: 48 rows, 48 scored
[OK] QYIKWPWYI: 52 rows, 52 scored
[OK] SPRWYFYYL: 146 rows, 146 scored
[OK] TTDPSFLGRY: 148 rows, 148 scored
[OK] VMATRRNVL: 98 rows, 98 scored
[OK] VMTTVLATL: 42 rows, 42 scored
[OK] YLQPRTFLL: 258 rows, 258 scored

Saved to ./result/CASE4_majority_scored.csv
Total rows: 1086, scored: 1086

In [9]:
!{sys.executable} ../metric_calculation/AUC.py \
                    --root_dir ./result \
                    --output_file ./CASE4_majority_auc.csv

Finding CSV files...
Found 1 CSV files
Processed 1/1 files (100.0%)
Failed: 1

In [10]:
import pandas as pd

df = pd.read_csv("./CASE4_majority_auc.csv")
df

,folder_path,file_name,roc_auc,pr_auc,status
0,./result,CASE4_majority_scored.csv,0.618303,0.647834,success
1,./result,[FOLDER_SUMMARY],0.618303,0.647834,success (averaged over 1 files)

##### few-shot

In [13]:
import sys

SCRIPT_DIR = "../inference/PanPep_Weight_Inference"
TEST_DATA = "../data/independent_dataset(alpha)/tcra_few.csv"
NEGATIVE_DATA = "../data/independent_dataset(alpha)/Control dataset_tcra.txt" #This is also equivalent to running the rank.
!{sys.executable} {SCRIPT_DIR}/inference_majority.py \
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "../data/fold1-alpha" \
    --support_dir "../data/few-alpha" \
    --peptide_encoding "{SCRIPT_DIR}/peptide_ab.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_ab.npz" \
    --result_dir "CASE4_few_rank"

Using 1 GPUs: [0]
Using model configuration: default

Processing peptide: PSDKHIEQYLKKIQNSLSTEWSP on device: cuda:0
Skipping peptide PSDKHIEQYLKKIQNSLSTEWSP - result file already exists

Processing peptide: GQVELGGGNAVEVCKGS on device: cuda:0
Skipping peptide GQVELGGGNAVEVCKGS - result file already exists

Processing peptide: GPEGAQGPRGEPGTP on device: cuda:0
Skipping peptide GPEGAQGPRGEPGTP - result file already exists

Processing peptide: GQVELGGGNAVEVCK on device: cuda:0
Skipping peptide GQVELGGGNAVEVCK - result file already exists

Processing peptide: HIKEYLNKIQNSLST on device: cuda:0
Skipping peptide HIKEYLNKIQNSLST - result file already exists

Processing peptide: HWFVTQRNFYEPQII on device: cuda:0
Skipping peptide HWFVTQRNFYEPQII - result file already exists

Processing peptide: IHSLLDEGKQSLTKL on device: cuda:0
Skipping peptide IHSLLDEGKQSLTKL - result file already exists

Processing peptide: NCTFEYVSQPFLMDL on device: cuda:0
Skipping peptide NCTFEYVSQPFLMDL - result file already exists

Processing peptide: NFSQILPDPSKPSKR on device: cuda:0
Skipping peptide NFSQILPDPSKPSKR - result file already exists

Processing peptide: NNSYECDIPIGAGIC on device: cuda:0
Skipping peptide NNSYECDIPIGAGIC - result file already exists

Processing peptide: PGVLLKEFTVSGNIL on device: cuda:0
Skipping peptide PGVLLKEFTVSGNIL - result file already exists

Processing peptide: PNANPNVDPNANPNV on device: cuda:0
Skipping peptide PNANPNVDPNANPNV - result file already exists

Processing peptide: PSDKHIKEYLNKIQN on device: cuda:0
Skipping peptide PSDKHIKEYLNKIQN - result file already exists

Processing peptide: RISNCVADYSVLYNS on device: cuda:0
Skipping peptide RISNCVADYSVLYNS - result file already exists

Processing peptide: SLFFSAQPFEITAST on device: cuda:0
Skipping peptide SLFFSAQPFEITAST - result file already exists

Processing peptide: STRQALRPRADGPVG on device: cuda:0
Skipping peptide STRQALRPRADGPVG - result file already exists

Processing peptide: TNFKYNYSVIEGGPI on device: cuda:0
Skipping peptide TNFKYNYSVIEGGPI - result file already exists

Processing peptide: VGGNYNYLYRLFRKS on device: cuda:0
Skipping peptide VGGNYNYLYRLFRKS - result file already exists

Processing peptide: YLNKIQNSLSTEWSP on device: cuda:0
Skipping peptide YLNKIQNSLSTEWSP - result file already exists

Processing peptide: ILKISNKYHTKGDH on device: cuda:0
Skipping peptide ILKISNKYHTKGDH - result file already exists

Processing peptide: TFEYVSQPFLMDLE on device: cuda:0
Skipping peptide TFEYVSQPFLMDLE - result file already exists

Processing peptide: APRGPHGGAASGL on device: cuda:0
Skipping peptide APRGPHGGAASGL - result file already exists

Processing peptide: DPPALASTNAEVT on device: cuda:0
Skipping peptide DPPALASTNAEVT - result file already exists

Processing peptide: LLEFYLAMPFATP on device: cuda:0
Skipping peptide LLEFYLAMPFATP - result file already exists

Processing peptide: NFIRMVISNPAAT on device: cuda:0
Skipping peptide NFIRMVISNPAAT - result file already exists

Processing peptide: NTNSSPDDQIGYY on device: cuda:0
Skipping peptide NTNSSPDDQIGYY - result file already exists

Processing peptide: PQQPFPQPEQPFP on device: cuda:0
Skipping peptide PQQPFPQPEQPFP - result file already exists

Processing peptide: RFYKTLRAEQASQ on device: cuda:0
Skipping peptide RFYKTLRAEQASQ - result file already exists

Processing peptide: DATYQRTRALVR on device: cuda:0
Skipping peptide DATYQRTRALVR - result file already exists

Processing peptide: PQPELPYPQPQL on device: cuda:0
Skipping peptide PQPELPYPQPQL - result file already exists

Processing peptide: QLQPFPQPELPY on device: cuda:0
Skipping peptide QLQPFPQPELPY - result file already exists

Processing peptide: HPNGYKSLSTL on device: cuda:0
Skipping peptide HPNGYKSLSTL - result file already exists

Processing peptide: PQPELPYPQPE on device: cuda:0
Skipping peptide PQPELPYPQPE - result file already exists

Processing peptide: RVAGDSGFAAY on device: cuda:0
Skipping peptide RVAGDSGFAAY - result file already exists

Processing peptide: ALAGIGILTV on device: cuda:0
Skipping peptide ALAGIGILTV - result file already exists

Processing peptide: ALWMRLLPLL on device: cuda:0
Skipping peptide ALWMRLLPLL - result file already exists

Processing peptide: FYAFSCYYDL on device: cuda:0
Skipping peptide FYAFSCYYDL - result file already exists

Processing peptide: FYAFSYYYDL on device: cuda:0
Skipping peptide FYAFSYYYDL - result file already exists

Processing peptide: KLFEFLVYGV on device: cuda:0
Skipping peptide KLFEFLVYGV - result file already exists

Processing peptide: KLVAMGINAV on device: cuda:0
Skipping peptide KLVAMGINAV - result file already exists

Processing peptide: LLFNILGGWV on device: cuda:0
Skipping peptide LLFNILGGWV - result file already exists

Processing peptide: LTSLTILQLY on device: cuda:0
Skipping peptide LTSLTILQLY - result file already exists

Processing peptide: LVSDGGPNLY on device: cuda:0
Skipping peptide LVSDGGPNLY - result file already exists

Processing peptide: MAALPRLIAF on device: cuda:0
Skipping peptide MAALPRLIAF - result file already exists

Processing peptide: MEVTPSGTWL on device: cuda:0
Skipping peptide MEVTPSGTWL - result file already exists

Processing peptide: QELIRQGTDY on device: cuda:0
Skipping peptide QELIRQGTDY - result file already exists

Processing peptide: RGPGRAFVTI on device: cuda:0
Skipping peptide RGPGRAFVTI - result file already exists

Processing peptide: RLITGRLQSL on device: cuda:0
Skipping peptide RLITGRLQSL - result file already exists

Processing peptide: RQFGPDWIVA on device: cuda:0
Skipping peptide RQFGPDWIVA - result file already exists

Processing peptide: VITAFTEGLK on device: cuda:0
Skipping peptide VITAFTEGLK - result file already exists

Processing peptide: VSATAGTTVY on device: cuda:0
Skipping peptide VSATAGTTVY - result file already exists

Processing peptide: AAFKRSCLK on device: cuda:0
Skipping peptide AAFKRSCLK - result file already exists

Processing peptide: AEVQIDRLI on device: cuda:0
Skipping peptide AEVQIDRLI - result file already exists

Processing peptide: AIFYLITPV on device: cuda:0
Skipping peptide AIFYLITPV - result file already exists

Processing peptide: AIIRILQQL on device: cuda:0
Skipping peptide AIIRILQQL - result file already exists

Processing peptide: ALDIEIATY on device: cuda:0
Skipping peptide ALDIEIATY - result file already exists

Processing peptide: ALKCKGFHV on device: cuda:0
Skipping peptide ALKCKGFHV - result file already exists

Processing peptide: ALSKGVHFV on device: cuda:0
Skipping peptide ALSKGVHFV - result file already exists

Processing peptide: ALWEIQQVV on device: cuda:0
Skipping peptide ALWEIQQVV - result file already exists

Processing peptide: ALWMRLLPL on device: cuda:0
Skipping peptide ALWMRLLPL - result file already exists

Processing peptide: CLAVHECFV on device: cuda:0
Skipping peptide CLAVHECFV - result file already exists

Processing peptide: DTDFVNEFY on device: cuda:0
Skipping peptide DTDFVNEFY - result file already exists

Processing peptide: EEIEITTHF on device: cuda:0
Skipping peptide EEIEITTHF - result file already exists

Processing peptide: ELAEYLYNI on device: cuda:0
Skipping peptide ELAEYLYNI - result file already exists

Processing peptide: ELRSRYWAI on device: cuda:0
Skipping peptide ELRSRYWAI - result file already exists

Processing peptide: FLAHIQWMV on device: cuda:0
Skipping peptide FLAHIQWMV - result file already exists

Processing peptide: FLALCADSI on device: cuda:0
Skipping peptide FLALCADSI - result file already exists

Processing peptide: FLHVTYVPA on device: cuda:0
Skipping peptide FLHVTYVPA - result file already exists

Processing peptide: FLLNKEMYL on device: cuda:0
Skipping peptide FLLNKEMYL - result file already exists

Processing peptide: FLNRFTTTL on device: cuda:0
Skipping peptide FLNRFTTTL - result file already exists

Processing peptide: FLPGVYSVI on device: cuda:0
Skipping peptide FLPGVYSVI - result file already exists

Processing peptide: FLPRVFSAV on device: cuda:0
Skipping peptide FLPRVFSAV - result file already exists

Processing peptide: FLWSVFWLI on device: cuda:0
Skipping peptide FLWSVFWLI - result file already exists

Processing peptide: FQQDKHYDL on device: cuda:0
Skipping peptide FQQDKHYDL - result file already exists

Processing peptide: FTSDYYQLY on device: cuda:0
Skipping peptide FTSDYYQLY - result file already exists

Processing peptide: FTVLCLTPV on device: cuda:0
Skipping peptide FTVLCLTPV - result file already exists

Processing peptide: GIIYIIYKL on device: cuda:0
Skipping peptide GIIYIIYKL - result file already exists

Processing peptide: GPRLGVRAT on device: cuda:0
Skipping peptide GPRLGVRAT - result file already exists

Processing peptide: GSHLVEALY on device: cuda:0
Skipping peptide GSHLVEALY - result file already exists

Processing peptide: HSNLNDATY on device: cuda:0
Skipping peptide HSNLNDATY - result file already exists

Processing peptide: ILGFVFTLT on device: cuda:0
Skipping peptide ILGFVFTLT - result file already exists

Processing peptide: ILKGKFQTA on device: cuda:0
Skipping peptide ILKGKFQTA - result file already exists

Processing peptide: ILSAHVATA on device: cuda:0
Skipping peptide ILSAHVATA - result file already exists

Processing peptide: IMLCCMTSC on device: cuda:0
Skipping peptide IMLCCMTSC - result file already exists

Processing peptide: IMNDMPIYM on device: cuda:0
Skipping peptide IMNDMPIYM - result file already exists

Processing peptide: IQATVMIIV on device: cuda:0
Skipping peptide IQATVMIIV - result file already exists

Processing peptide: KLFIRQEEV on device: cuda:0
Skipping peptide KLFIRQEEV - result file already exists

Processing peptide: KLKDCVMYA on device: cuda:0
Skipping peptide KLKDCVMYA - result file already exists

Processing peptide: KLNEEIAII on device: cuda:0
Skipping peptide KLNEEIAII - result file already exists

Processing peptide: KLQVFLIVL on device: cuda:0
Positive TCRs: 5, Negative TCRs: 37454
Total batches: 4
Loading support data from: ../data/few-alpha
Loading support data for peptide: KLQVFLIVL
Query data size: 37455

Processing batch 1/4 for peptide KLQVFLIVL - 2026-03-17 16:46:03
Finetuning model...
batch processing time: 10.47s, Progress: 25.0%

Processing batch 2/4 for peptide KLQVFLIVL - 2026-03-17 16:46:13
Using finetuned model for inference...
batch processing time: 0.42s, Progress: 50.0%

Processing batch 3/4 for peptide KLQVFLIVL - 2026-03-17 16:46:13
Using finetuned model for inference...
batch processing time: 0.43s, Progress: 75.0%

Processing batch 4/4 for peptide KLQVFLIVL - 2026-03-17 16:46:14
Using finetuned model for inference...
batch processing time: 0.30s, Progress: 100.0%
Successfully wrote 37455 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_few_rank/KLQVFLIVL.parquet

Peptide KLQVFLIVL processing time: 11.77s

Processing peptide: KLWAQCVQL on device: cuda:0
Positive TCRs: 21, Negative TCRs: 37438
Total batches: 4
Loading support data from: ../data/few-alpha
Loading support data for peptide: KLWAQCVQL
Query data size: 37455

Processing batch 1/4 for peptide KLWAQCVQL - 2026-03-17 16:46:14
Finetuning model...
batch processing time: 12.46s, Progress: 25.0%

Processing batch 2/4 for peptide KLWAQCVQL - 2026-03-17 16:46:27
Using finetuned model for inference...
batch processing time: 0.43s, Progress: 50.0%

Processing batch 3/4 for peptide KLWAQCVQL - 2026-03-17 16:46:27
Using finetuned model for inference...
batch processing time: 0.42s, Progress: 75.0%

Processing batch 4/4 for peptide KLWAQCVQL - 2026-03-17 16:46:28
Using finetuned model for inference...
batch processing time: 0.33s, Progress: 100.0%
Successfully wrote 37455 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_few_rank/KLWAQCVQL.parquet

Peptide KLWAQCVQL processing time: 13.76s

Processing peptide: KMYAFTLES on device: cuda:0
Positive TCRs: 7, Negative TCRs: 37452
Total batches: 4
Loading support data from: ../data/few-alpha
Loading support data for peptide: KMYAFTLES
Query data size: 37455

Processing batch 1/4 for peptide KMYAFTLES - 2026-03-17 16:46:28
Finetuning model...
batch processing time: 10.06s, Progress: 25.0%

Processing batch 2/4 for peptide KMYAFTLES - 2026-03-17 16:46:38
Using finetuned model for inference...
batch processing time: 0.48s, Progress: 50.0%

Processing batch 3/4 for peptide KMYAFTLES - 2026-03-17 16:46:39
Using finetuned model for inference...
batch processing time: 0.45s, Progress: 75.0%

Processing batch 4/4 for peptide KMYAFTLES - 2026-03-17 16:46:39
Using finetuned model for inference...
batch processing time: 0.34s, Progress: 100.0%
Successfully wrote 37455 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_few_rank/KMYAFTLES.parquet

Peptide KMYAFTLES processing time: 11.45s

Processing peptide: KQIYKTPPI on device: cuda:0
Positive TCRs: 5, Negative TCRs: 37454
Total batches: 4
Loading support data from: ../data/few-alpha
Loading support data for peptide: KQIYKTPPI
Query data size: 37455

Processing batch 1/4 for peptide KQIYKTPPI - 2026-03-17 16:46:40
Finetuning model...
batch processing time: 9.91s, Progress: 25.0%

Processing batch 2/4 for peptide KQIYKTPPI - 2026-03-17 16:46:50
Using finetuned model for inference...
batch processing time: 0.47s, Progress: 50.0%

Processing batch 3/4 for peptide KQIYKTPPI - 2026-03-17 16:46:50
Using finetuned model for inference...
batch processing time: 0.40s, Progress: 75.0%

Processing batch 4/4 for peptide KQIYKTPPI - 2026-03-17 16:46:51
Using finetuned model for inference...
batch processing time: 0.28s, Progress: 100.0%
Successfully wrote 37455 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_few_rank/KQIYKTPPI.parquet

Peptide KQIYKTPPI processing time: 11.15s

Processing peptide: KSKRTPMGF on device: cuda:0
Positive TCRs: 79, Negative TCRs: 37380
Total batches: 4
Loading support data from: ../data/few-alpha
Loading support data for peptide: KSKRTPMGF
Query data size: 37455

Processing batch 1/4 for peptide KSKRTPMGF - 2026-03-17 16:46:51
Finetuning model...
batch processing time: 12.54s, Progress: 25.0%

Processing batch 2/4 for peptide KSKRTPMGF - 2026-03-17 16:47:04
Using finetuned model for inference...
batch processing time: 0.47s, Progress: 50.0%

Processing batch 3/4 for peptide KSKRTPMGF - 2026-03-17 16:47:04
Using finetuned model for inference...
batch processing time: 0.50s, Progress: 75.0%

Processing batch 4/4 for peptide KSKRTPMGF - 2026-03-17 16:47:05
Using finetuned model for inference...
batch processing time: 0.33s, Progress: 100.0%
Successfully wrote 37455 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_few_rank/KSKRTPMGF.parquet

Peptide KSKRTPMGF processing time: 13.95s

Processing peptide: KSVNITFEL on device: cuda:0
Positive TCRs: 16, Negative TCRs: 37443
Total batches: 4
Loading support data from: ../data/few-alpha
Loading support data for peptide: KSVNITFEL
Query data size: 37455

Processing batch 1/4 for peptide KSVNITFEL - 2026-03-17 16:47:05
Finetuning model...
batch processing time: 10.15s, Progress: 25.0%

Processing batch 2/4 for peptide KSVNITFEL - 2026-03-17 16:47:15
Using finetuned model for inference...
batch processing time: 0.46s, Progress: 50.0%

Processing batch 3/4 for peptide KSVNITFEL - 2026-03-17 16:47:16
Using finetuned model for inference...
batch processing time: 0.41s, Progress: 75.0%

Processing batch 4/4 for peptide KSVNITFEL - 2026-03-17 16:47:16
Using finetuned model for inference...
batch processing time: 0.29s, Progress: 100.0%
Successfully wrote 37455 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_few_rank/KSVNITFEL.parquet

Peptide KSVNITFEL processing time: 11.41s

Processing peptide: KVYPIILRL on device: cuda:0
Positive TCRs: 9, Negative TCRs: 37450
Total batches: 4
Loading support data from: ../data/few-alpha
Loading support data for peptide: KVYPIILRL
Query data size: 37455

Processing batch 1/4 for peptide KVYPIILRL - 2026-03-17 16:47:17
Finetuning model...
batch processing time: 10.13s, Progress: 25.0%

Processing batch 2/4 for peptide KVYPIILRL - 2026-03-17 16:47:27
Using finetuned model for inference...
batch processing time: 0.46s, Progress: 50.0%

Processing batch 3/4 for peptide KVYPIILRL - 2026-03-17 16:47:27
Using finetuned model for inference...
batch processing time: 0.43s, Progress: 75.0%

Processing batch 4/4 for peptide KVYPIILRL - 2026-03-17 16:47:28
Using finetuned model for inference...
batch processing time: 0.37s, Progress: 100.0%
Successfully wrote 37455 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_few_rank/KVYPIILRL.parquet

Peptide KVYPIILRL processing time: 11.52s

Processing peptide: LAVDGVLSV on device: cuda:0
Positive TCRs: 8, Negative TCRs: 37451
Total batches: 4
Loading support data from: ../data/few-alpha
Loading support data for peptide: LAVDGVLSV
Query data size: 37455

Processing batch 1/4 for peptide LAVDGVLSV - 2026-03-17 16:47:28
Finetuning model...
batch processing time: 12.61s, Progress: 25.0%

Processing batch 2/4 for peptide LAVDGVLSV - 2026-03-17 16:47:41
Using finetuned model for inference...
batch processing time: 0.42s, Progress: 50.0%

Processing batch 3/4 for peptide LAVDGVLSV - 2026-03-17 16:47:41
Using finetuned model for inference...
batch processing time: 0.45s, Progress: 75.0%

Processing batch 4/4 for peptide LAVDGVLSV - 2026-03-17 16:47:42
Using finetuned model for inference...
batch processing time: 0.29s, Progress: 100.0%
Successfully wrote 37455 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_few_rank/LAVDGVLSV.parquet

Peptide LAVDGVLSV processing time: 13.87s

Processing peptide: LLDDFVEII on device: cuda:0
Positive TCRs: 6, Negative TCRs: 37453
Total batches: 4
Loading support data from: ../data/few-alpha
Loading support data for peptide: LLDDFVEII
Query data size: 37455

Processing batch 1/4 for peptide LLDDFVEII - 2026-03-17 16:47:42
Finetuning model...
batch processing time: 9.81s, Progress: 25.0%

Processing batch 2/4 for peptide LLDDFVEII - 2026-03-17 16:47:52
Using finetuned model for inference...
batch processing time: 0.43s, Progress: 50.0%

Processing batch 3/4 for peptide LLDDFVEII - 2026-03-17 16:47:52
Using finetuned model for inference...
batch processing time: 0.43s, Progress: 75.0%

Processing batch 4/4 for peptide LLDDFVEII - 2026-03-17 16:47:53
Using finetuned model for inference...
batch processing time: 0.31s, Progress: 100.0%
Successfully wrote 37455 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_few_rank/LLDDFVEII.parquet

Peptide LLDDFVEII processing time: 11.09s

Processing peptide: LLFLVLIML on device: cuda:0
Positive TCRs: 5, Negative TCRs: 37454
Total batches: 4
Loading support data from: ../data/few-alpha
Loading support data for peptide: LLFLVLIML
Query data size: 37455

Processing batch 1/4 for peptide LLFLVLIML - 2026-03-17 16:47:53
Finetuning model...
batch processing time: 10.38s, Progress: 25.0%

Processing batch 2/4 for peptide LLFLVLIML - 2026-03-17 16:48:04
Using finetuned model for inference...
batch processing time: 0.47s, Progress: 50.0%

Processing batch 3/4 for peptide LLFLVLIML - 2026-03-17 16:48:04
Using finetuned model for inference...
batch processing time: 0.47s, Progress: 75.0%

Processing batch 4/4 for peptide LLFLVLIML - 2026-03-17 16:48:05
Using finetuned model for inference...
batch processing time: 0.37s, Progress: 100.0%
Successfully wrote 37455 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_few_rank/LLFLVLIML.parquet

Peptide LLFLVLIML processing time: 11.83s

Processing peptide: LLLEWLAMA on device: cuda:0
Positive TCRs: 9, Negative TCRs: 37450
Total batches: 4
Loading support data from: ../data/few-alpha
Loading support data for peptide: LLLEWLAMA
Query data size: 37455

Processing batch 1/4 for peptide LLLEWLAMA - 2026-03-17 16:48:08
Finetuning model...
batch processing time: 9.73s, Progress: 25.0%

Processing batch 2/4 for peptide LLLEWLAMA - 2026-03-17 16:48:17

In [16]:
import os
import pandas as pd

PARQUET_DIR = "../inference/PanPep_Weight_Inference/CASE4_few_rank"
CSV_PATH = "../data/fig5/reshuffling_few_0.csv"


OUTPUT_DIR = "./result"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "CASE4_few_scored.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

csv_df = pd.read_csv(CSV_PATH)

if "label" in csv_df.columns:
    csv_df = csv_df.rename(columns={"label": "Label"})

peptides = csv_df["peptide"].unique()

results = []
for pep in peptides:
    parquet_path = os.path.join(PARQUET_DIR, f"{pep}.parquet")
    if not os.path.exists(parquet_path):
        print(f"[SKIP] No parquet for {pep}")
        continue

    parquet_df = pd.read_parquet(parquet_path)[["CDR3", "Score"]].rename(
        columns={"CDR3": "binding_TCR"}
    )

    pep_rows = csv_df[csv_df["peptide"] == pep].copy()
    merged = pep_rows.merge(parquet_df, on="binding_TCR", how="left")
    results.append(merged)

    print(f"[OK] {pep}: {len(merged)} rows, {merged['Score'].notna().sum()} scored")

if results:
    final_df = pd.concat(results, ignore_index=True)
    final_df.to_csv(OUTPUT_PATH, index=False)

    print(f"\nSaved to {OUTPUT_PATH}")
    print(f"Total rows: {len(final_df)}, scored: {final_df['Score'].notna().sum()}")
else:
    print("No results to save.")

[OK] AAFKRSCLK: 6 rows, 6 scored
[OK] AEVQIDRLI: 10 rows, 10 scored
[OK] AIFYLITPV: 10 rows, 10 scored
[OK] AIIRILQQL: 6 rows, 6 scored
[OK] ALAGIGILTV: 154 rows, 154 scored
[OK] ALDIEIATY: 6 rows, 6 scored
[OK] ALKCKGFHV: 10 rows, 10 scored
[OK] ALSKGVHFV: 32 rows, 32 scored
[OK] ALWEIQQVV: 50 rows, 50 scored
[OK] ALWMRLLPL: 16 rows, 16 scored
[OK] ALWMRLLPLL: 2 rows, 2 scored
[OK] APRGPHGGAASGL: 10 rows, 10 scored
[OK] CLAVHECFV: 12 rows, 12 scored
[OK] CPLSKILL: 16 rows, 16 scored
[OK] DATYQRTRALVR: 186 rows, 186 scored
[OK] DPPALASTNAEVT: 8 rows, 8 scored
[OK] DTDFVNEFY: 8 rows, 8 scored
[OK] EEIEITTHF: 6 rows, 6 scored
[OK] ELAEYLYNI: 6 rows, 6 scored
[OK] ELRSRYWAI: 10 rows, 10 scored
[OK] FLAHIQWMV: 8 rows, 8 scored
[OK] FLALCADSI: 10 rows, 10 scored
[OK] FLHVTYVPA: 6 rows, 6 scored
[OK] FLLNKEMYL: 14 rows, 14 scored
[OK] FLNRFTTTL: 6 rows, 6 scored
[OK] FLPGVYSVI: 6 rows, 6 scored
[OK] FLPRVFSAV: 8 rows, 8 scored
[OK] FLWSVFWLI: 18 rows, 18 scored
[OK] FQQDKHYDL: 8 rows, 8 scored
[OK] FTSDYYQLY: 78 rows, 78 scored
[OK] FTVLCLTPV: 10 rows, 10 scored
[OK] FYAFSCYYDL: 6 rows, 6 scored
[OK] FYAFSYYYDL: 6 rows, 6 scored
[OK] GIIYIIYKL: 42 rows, 42 scored
[OK] GPEGAQGPRGEPGTP: 10 rows, 10 scored
[OK] GPRLGVRAT: 90 rows, 90 scored
[OK] GQVELGGGNAVEVCK: 36 rows, 36 scored
[OK] GQVELGGGNAVEVCKGS: 1000 rows, 1000 scored
[OK] GSHLVEALY: 12 rows, 12 scored
[OK] HIKEYLNKIQNSLST: 74 rows, 74 scored
[OK] HPNGYKSLSTL: 66 rows, 66 scored
[OK] HPVTKYIM: 94 rows, 94 scored
[OK] HSNLNDATY: 58 rows, 58 scored
[OK] HWFVTQRNFYEPQII: 24 rows, 24 scored
[OK] IHSLLDEGKQSLTKL: 18 rows, 18 scored
[OK] ILGFVFTLT: 6 rows, 6 scored
[OK] ILKGKFQTA: 10 rows, 10 scored
[OK] ILKISNKYHTKGDH: 8 rows, 8 scored
[OK] ILKLQVFL: 10 rows, 10 scored
[OK] ILSAHVATA: 10 rows, 10 scored
[OK] IMLCCMTSC: 8 rows, 8 scored
[OK] IMNDMPIYM: 106 rows, 106 scored
[OK] IQATVMIIV: 18 rows, 18 scored
[OK] KLFEFLVYGV: 6 rows, 6 scored
[OK] KLFIRQEEV: 6 rows, 6 scored
[OK] KLKDCVMYA: 10 rows, 10 scored
[OK] KLNEEIAII: 6 rows, 6 scored
[OK] KLQVFLIVL: 6 rows, 6 scored
[OK] KLVAMGINAV: 24 rows, 24 scored
[OK] KLWAQCVQL: 38 rows, 38 scored
[OK] KMYAFTLES: 10 rows, 10 scored
[OK] KQIYKTPPI: 6 rows, 6 scored
[OK] KSKRTPMGF: 154 rows, 154 scored
[OK] KSVNITFEL: 28 rows, 28 scored
[OK] KVYPIILRL: 14 rows, 14 scored
[OK] LAVDGVLSV: 12 rows, 12 scored
[OK] LLDDFVEII: 8 rows, 8 scored
[OK] LLEFYLAMPFATP: 20 rows, 20 scored
[OK] LLFLVLIML: 6 rows, 6 scored
[OK] LLFNILGGWV: 30 rows, 30 scored
[OK] LLLEWLAMA: 14 rows, 14 scored
[OK] LLPPLLEHL: 8 rows, 8 scored
[OK] LLSILCIWV: 6 rows, 6 scored
[OK] LLYDANYFL: 50 rows, 50 scored
[OK] LNIDLLWSV: 10 rows, 10 scored
[OK] LPRWYFYYL: 34 rows, 34 scored
[OK] LRLRLDQL: 8 rows, 8 scored
[OK] LRVMMLAPF: 32 rows, 32 scored
[OK] LTSLTILQLY: 56 rows, 56 scored
[OK] LVGPTPVNI: 12 rows, 12 scored
[OK] LVSDGGPNLY: 22 rows, 22 scored
[OK] LWLLWPVTL: 8 rows, 8 scored
[OK] LWMRLLPL: 6 rows, 6 scored
[OK] LWMRLLPLL: 8 rows, 8 scored
[OK] MAALPRLIAF: 6 rows, 6 scored
[OK] MALWMRLL: 24 rows, 24 scored
[OK] MEVTPSGTWL: 84 rows, 84 scored
[OK] MLDMYSVML: 6 rows, 6 scored
[OK] MMIARFKM: 22 rows, 22 scored
[OK] MPASWVMRI: 6 rows, 6 scored
[OK] MPYFFTLLL: 10 rows, 10 scored
[OK] NCTFEYVSQPFLMDL: 8 rows, 8 scored
[OK] NFIRMVISNPAAT: 14 rows, 14 scored
[OK] NFSQILPDPSKPSKR: 8 rows, 8 scored
[OK] NLIFKWIL: 26 rows, 26 scored
[OK] NLIFKWKSI: 6 rows, 6 scored
[OK] NNSYECDIPIGAGIC: 6 rows, 6 scored
[OK] NQKLIANQF: 138 rows, 138 scored
[OK] NSSTCMMCY: 8 rows, 8 scored
[OK] NTNSSPDDQIGYY: 10 rows, 10 scored
[OK] NVFAFPFTI: 10 rows, 10 scored
[OK] NYMPYFFTL: 12 rows, 12 scored
[OK] NYNYLYRLF: 108 rows, 108 scored
[OK] PFPQPELPY: 26 rows, 26 scored
[OK] PGVLLKEFTVSGNIL: 14 rows, 14 scored
[OK] PNANPNVDPNANPNV: 16 rows, 16 scored
[OK] PQPELPYPQ: 10 rows, 10 scored
[OK] PQPELPYPQPE: 30 rows, 30 scored
[OK] PQPELPYPQPQL: 32 rows, 32 scored
[OK] PQQPFPQPEQPFP: 8 rows, 8 scored
[OK] PSDKHIEQYLKKIQNSLSTEWSP: 10 rows, 10 scored
[OK] PSDKHIKEYLNKIQN: 74 rows, 74 scored
[OK] PTDNYITTY: 34 rows, 34 scored
[OK] PTEKGANEY: 6 rows, 6 scored
[OK] QAKWRLQTL: 100 rows, 100 scored
[OK] QELIRQGTDY: 14 rows, 14 scored
[OK] QLQPFPQPELPY: 46 rows, 46 scored
[OK] QMMVKAGL: 86 rows, 86 scored
[OK] RAQAPPPSW: 16 rows, 16 scored
[OK] RFYKTLRAEQASQ: 194 rows, 194 scored
[OK] RGPGRAFVTI: 60 rows, 60 scored
[OK] RIRGGDGKM: 6 rows, 6 scored
[OK] RISNCVADYSVLYNS: 6 rows, 6 scored
[OK] RLARLALVL: 24 rows, 24 scored
[OK] RLGPVQNEV: 14 rows, 14 scored
[OK] RLITGRLQSL: 14 rows, 14 scored
[OK] RLPGVLPRA: 74 rows, 74 scored
[OK] RPIIRPATL: 180 rows, 180 scored
[OK] RQFGPDWIVA: 10 rows, 10 scored
[OK] RQLLFVVEV: 12 rows, 12 scored
[OK] RTATKAYNV: 34 rows, 34 scored
[OK] RTATKQYNV: 96 rows, 96 scored
[OK] RVAGDSGFAAY: 40 rows, 40 scored
[OK] RYPLTFGW: 12 rows, 12 scored
[OK] RYSIFFDYM: 10 rows, 10 scored
[OK] SIIAYTMSL: 26 rows, 26 scored
[OK] SLFFSAQPFEITAST: 184 rows, 184 scored
[OK] SLPRLFPLL: 8 rows, 8 scored
[OK] SMMILSDDA: 8 rows, 8 scored
[OK] SMWALVISV: 6 rows, 6 scored
[OK] STNVGSNTY: 22 rows, 22 scored
[OK] STRQALRPRADGPVG: 6 rows, 6 scored
[OK] SVLYYQNNV: 8 rows, 8 scored
[OK] SYIPSAEKI: 52 rows, 52 scored
[OK] TFEYVSQPFLMDLE: 178 rows, 178 scored
[OK] TLKNTVCTV: 6 rows, 6 scored
[OK] TLLANVTAV: 14 rows, 14 scored
[OK] TLMNVITLV: 6 rows, 6 scored
[OK] TLMNVLTLV: 12 rows, 12 scored
[OK] TLWCSPIKV: 8 rows, 8 scored
[OK] TNFKYNYSVIEGGPI: 12 rows, 12 scored
[OK] TRLALIAPK: 6 rows, 6 scored
[OK] TSAMQTMLF: 6 rows, 6 scored
[OK] TSQWLTNIF: 16 rows, 16 scored
[OK] TTIQTIVEV: 6 rows, 6 scored
[OK] VFLVLLPLV: 10 rows, 10 scored
[OK] VGGNYNYLYRLFRKS: 14 rows, 14 scored
[OK] VITAFTEGLK: 46 rows, 46 scored
[OK] VMNILLQYV: 16 rows, 16 scored
[OK] VMVELVAEL: 22 rows, 22 scored
[OK] VSATAGTTVY: 22 rows, 22 scored
[OK] VTDAAHLLI: 38 rows, 38 scored
[OK] VYFLQSINF: 52 rows, 52 scored
[OK] VYIGDPAQL: 14 rows, 14 scored
[OK] WLLWPVTLA: 14 rows, 14 scored
[OK] WPTVRERM: 6 rows, 6 scored
[OK] WPVTLACFV: 24 rows, 24 scored
[OK] WPWYIWLGF: 8 rows, 8 scored
[OK] YADVFHLYL: 12 rows, 12 scored
[OK] YAKWKLCSA: 40 rows, 40 scored
[OK] YAYAKWKL: 46 rows, 46 scored
[OK] YERMCNIL: 10 rows, 10 scored
[OK] YLGGMSYYC: 6 rows, 6 scored
[OK] YLKDQQLL: 26 rows, 26 scored
[OK] YLKTNLFL: 8 rows, 8 scored
[OK] YLLPGWKL: 32 rows, 32 scored
[OK] YLNKIQNSLSTEWSP: 74 rows, 74 scored
[OK] YLQQNWWTL: 22 rows, 22 scored
[OK] YLYALVYFL: 10 rows, 10 scored
[OK] YMPYFFTLL: 12 rows, 12 scored
[OK] YVDNSSLTI: 8 rows, 8 scored
[OK] YVWKSYVHV: 6 rows, 6 scored

Saved to ./result/CASE4_few_scored.csv
Total rows: 6114, scored: 6114

In [17]:
!{sys.executable} ../metric_calculation/AUC.py \
                    --root_dir ./result \
                    --output_file ./CASE4_few_auc.csv

Finding CSV files...
Found 1 CSV files
Processed 1/1 files (100.0%)
Failed: 1

In [18]:
import pandas as pd

df = pd.read_csv("./CASE4_few_auc.csv")
df

,folder_path,file_name,roc_auc,pr_auc,status
0,./result,CASE4_few_scored.csv,0.500705,0.416821,success
1,./result,[FOLDER_SUMMARY],0.500705,0.416821,success (averaged over 1 files)

#### zero-shot

In [14]:
import sys

SCRIPT_DIR = "../inference/PanPep_Weight_Inference"
TEST_DATA = "../data/independent_dataset(alpha)/tcra_zero.csv"
NEGATIVE_DATA = "../data/independent_dataset(alpha)/Control dataset_tcra.txt" #This is also equivalent to running the rank.

!{sys.executable} {SCRIPT_DIR}/inference_zero_shot.py \
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "../data/fold1-alpha" \
    --result_dir "CASE4_zero"\
    --peptide_encoding "{SCRIPT_DIR}/peptide_ab.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_ab.npz" \
    --model default

Using 1 GPUs: [0]
Using model configuration: default

Processing peptide: HHLWAYRDLQTRKDIRNAAWHKHGW on device: cuda:0

Processing batch 1/4 for peptide HHLWAYRDLQTRKDIRNAAWHKHGW - 2026-03-17 17:05:41
batch processing time: 0.93s, Progress: 25.0%

Processing batch 2/4 for peptide HHLWAYRDLQTRKDIRNAAWHKHGW - 2026-03-17 17:05:42
batch processing time: 0.57s, Progress: 50.0%

Processing batch 3/4 for peptide HHLWAYRDLQTRKDIRNAAWHKHGW - 2026-03-17 17:05:42
batch processing time: 0.52s, Progress: 75.0%

Processing batch 4/4 for peptide HHLWAYRDLQTRKDIRNAAWHKHGW - 2026-03-17 17:05:43
batch processing time: 0.37s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/HHLWAYRDLQTRKDIRNAAWHKHGW.parquet

Peptide HHLWAYRDLQTRKDIRNAAWHKHGW processing time: 2.48s

Processing peptide: ILYCKRASLTELVSPRLPSHLSEYE on device: cuda:0

Processing batch 1/4 for peptide ILYCKRASLTELVSPRLPSHLSEYE - 2026-03-17 17:05:43
batch processing time: 0.50s, Progress: 25.0%

Processing batch 2/4 for peptide ILYCKRASLTELVSPRLPSHLSEYE - 2026-03-17 17:05:44
batch processing time: 0.68s, Progress: 50.0%

Processing batch 3/4 for peptide ILYCKRASLTELVSPRLPSHLSEYE - 2026-03-17 17:05:45
batch processing time: 0.49s, Progress: 75.0%

Processing batch 4/4 for peptide ILYCKRASLTELVSPRLPSHLSEYE - 2026-03-17 17:05:45
batch processing time: 0.35s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/ILYCKRASLTELVSPRLPSHLSEYE.parquet

Peptide ILYCKRASLTELVSPRLPSHLSEYE processing time: 2.11s

Processing peptide: KQHVCGGSILDPYWVLTAAHCFRKH on device: cuda:0

Processing batch 1/4 for peptide KQHVCGGSILDPYWVLTAAHCFRKH - 2026-03-17 17:05:46
batch processing time: 0.48s, Progress: 25.0%

Processing batch 2/4 for peptide KQHVCGGSILDPYWVLTAAHCFRKH - 2026-03-17 17:05:46
batch processing time: 0.52s, Progress: 50.0%

Processing batch 3/4 for peptide KQHVCGGSILDPYWVLTAAHCFRKH - 2026-03-17 17:05:47
batch processing time: 0.65s, Progress: 75.0%

Processing batch 4/4 for peptide KQHVCGGSILDPYWVLTAAHCFRKH - 2026-03-17 17:05:47
batch processing time: 0.42s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/KQHVCGGSILDPYWVLTAAHCFRKH.parquet

Peptide KQHVCGGSILDPYWVLTAAHCFRKH processing time: 2.15s

Processing peptide: PGISSQHFTYQGGVGGSWPVCSGLG on device: cuda:0

Processing batch 1/4 for peptide PGISSQHFTYQGGVGGSWPVCSGLG - 2026-03-17 17:05:48
batch processing time: 0.50s, Progress: 25.0%

Processing batch 2/4 for peptide PGISSQHFTYQGGVGGSWPVCSGLG - 2026-03-17 17:05:48
batch processing time: 0.50s, Progress: 50.0%

Processing batch 3/4 for peptide PGISSQHFTYQGGVGGSWPVCSGLG - 2026-03-17 17:05:49
batch processing time: 0.49s, Progress: 75.0%

Processing batch 4/4 for peptide PGISSQHFTYQGGVGGSWPVCSGLG - 2026-03-17 17:05:49
batch processing time: 0.37s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/PGISSQHFTYQGGVGGSWPVCSGLG.parquet

Peptide PGISSQHFTYQGGVGGSWPVCSGLG processing time: 1.93s

Processing peptide: PQDSQAFPEAAEGDWTVSLEHILAS on device: cuda:0

Processing batch 1/4 for peptide PQDSQAFPEAAEGDWTVSLEHILAS - 2026-03-17 17:05:50
batch processing time: 0.63s, Progress: 25.0%

Processing batch 2/4 for peptide PQDSQAFPEAAEGDWTVSLEHILAS - 2026-03-17 17:05:50
batch processing time: 0.54s, Progress: 50.0%

Processing batch 3/4 for peptide PQDSQAFPEAAEGDWTVSLEHILAS - 2026-03-17 17:05:51
batch processing time: 0.47s, Progress: 75.0%

Processing batch 4/4 for peptide PQDSQAFPEAAEGDWTVSLEHILAS - 2026-03-17 17:05:51
batch processing time: 0.39s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/PQDSQAFPEAAEGDWTVSLEHILAS.parquet

Peptide PQDSQAFPEAAEGDWTVSLEHILAS processing time: 2.13s

Processing peptide: PTPSAPCPATPAVPKGRVFVSPLAK on device: cuda:0

Processing batch 1/4 for peptide PTPSAPCPATPAVPKGRVFVSPLAK - 2026-03-17 17:05:52
batch processing time: 0.58s, Progress: 25.0%

Processing batch 2/4 for peptide PTPSAPCPATPAVPKGRVFVSPLAK - 2026-03-17 17:05:52
batch processing time: 0.55s, Progress: 50.0%

Processing batch 3/4 for peptide PTPSAPCPATPAVPKGRVFVSPLAK - 2026-03-17 17:05:53
batch processing time: 0.55s, Progress: 75.0%

Processing batch 4/4 for peptide PTPSAPCPATPAVPKGRVFVSPLAK - 2026-03-17 17:05:53
batch processing time: 0.49s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/PTPSAPCPATPAVPKGRVFVSPLAK.parquet

Peptide PTPSAPCPATPAVPKGRVFVSPLAK processing time: 2.26s

Processing peptide: RCSDSDGLAPPQNLIRVEGNLRVEY on device: cuda:0

Processing batch 1/4 for peptide RCSDSDGLAPPQNLIRVEGNLRVEY - 2026-03-17 17:05:54
batch processing time: 0.57s, Progress: 25.0%

Processing batch 2/4 for peptide RCSDSDGLAPPQNLIRVEGNLRVEY - 2026-03-17 17:05:55
batch processing time: 0.59s, Progress: 50.0%

Processing batch 3/4 for peptide RCSDSDGLAPPQNLIRVEGNLRVEY - 2026-03-17 17:05:55
batch processing time: 0.70s, Progress: 75.0%

Processing batch 4/4 for peptide RCSDSDGLAPPQNLIRVEGNLRVEY - 2026-03-17 17:05:56
batch processing time: 0.38s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/RCSDSDGLAPPQNLIRVEGNLRVEY.parquet

Peptide RCSDSDGLAPPQNLIRVEGNLRVEY processing time: 2.33s

Processing peptide: SFVNDIFERIAGVASRLAHYNKRST on device: cuda:0

Processing batch 1/4 for peptide SFVNDIFERIAGVASRLAHYNKRST - 2026-03-17 17:05:56
batch processing time: 0.52s, Progress: 25.0%

Processing batch 2/4 for peptide SFVNDIFERIAGVASRLAHYNKRST - 2026-03-17 17:05:57
batch processing time: 0.50s, Progress: 50.0%

Processing batch 3/4 for peptide SFVNDIFERIAGVASRLAHYNKRST - 2026-03-17 17:05:57
batch processing time: 0.58s, Progress: 75.0%

Processing batch 4/4 for peptide SFVNDIFERIAGVASRLAHYNKRST - 2026-03-17 17:05:58
batch processing time: 0.39s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/SFVNDIFERIAGVASRLAHYNKRST.parquet

Peptide SFVNDIFERIAGVASRLAHYNKRST processing time: 2.08s

Processing peptide: VISAEKAYHEQLTVAEITNACFEPA on device: cuda:0

Processing batch 1/4 for peptide VISAEKAYHEQLTVAEITNACFEPA - 2026-03-17 17:05:58
batch processing time: 0.54s, Progress: 25.0%

Processing batch 2/4 for peptide VISAEKAYHEQLTVAEITNACFEPA - 2026-03-17 17:05:59
batch processing time: 0.59s, Progress: 50.0%

Processing batch 3/4 for peptide VISAEKAYHEQLTVAEITNACFEPA - 2026-03-17 17:06:00
batch processing time: 0.58s, Progress: 75.0%

Processing batch 4/4 for peptide VISAEKAYHEQLTVAEITNACFEPA - 2026-03-17 17:06:00
batch processing time: 0.43s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/VISAEKAYHEQLTVAEITNACFEPA.parquet

Peptide VISAEKAYHEQLTVAEITNACFEPA processing time: 2.22s

Processing peptide: VRLAQGLTHLGKATLTLCPYHSDRQ on device: cuda:0

Processing batch 1/4 for peptide VRLAQGLTHLGKATLTLCPYHSDRQ - 2026-03-17 17:06:01
batch processing time: 3.14s, Progress: 25.0%

Processing batch 2/4 for peptide VRLAQGLTHLGKATLTLCPYHSDRQ - 2026-03-17 17:06:04
batch processing time: 0.60s, Progress: 50.0%

Processing batch 3/4 for peptide VRLAQGLTHLGKATLTLCPYHSDRQ - 2026-03-17 17:06:04
batch processing time: 0.80s, Progress: 75.0%

Processing batch 4/4 for peptide VRLAQGLTHLGKATLTLCPYHSDRQ - 2026-03-17 17:06:05
batch processing time: 0.38s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/VRLAQGLTHLGKATLTLCPYHSDRQ.parquet

Peptide VRLAQGLTHLGKATLTLCPYHSDRQ processing time: 5.00s

Processing peptide: YEPSLMTMCQDSSQNDERSKSLLLS on device: cuda:0

Processing batch 1/4 for peptide YEPSLMTMCQDSSQNDERSKSLLLS - 2026-03-17 17:06:06
batch processing time: 0.49s, Progress: 25.0%

Processing batch 2/4 for peptide YEPSLMTMCQDSSQNDERSKSLLLS - 2026-03-17 17:06:06
batch processing time: 0.48s, Progress: 50.0%

Processing batch 3/4 for peptide YEPSLMTMCQDSSQNDERSKSLLLS - 2026-03-17 17:06:07
batch processing time: 0.54s, Progress: 75.0%

Processing batch 4/4 for peptide YEPSLMTMCQDSSQNDERSKSLLLS - 2026-03-17 17:06:07
batch processing time: 0.47s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/YEPSLMTMCQDSSQNDERSKSLLLS.parquet

Peptide YEPSLMTMCQDSSQNDERSKSLLLS processing time: 2.07s

Processing peptide: MTEYKLVVVGADGVGKSALTIQLI on device: cuda:0

Processing batch 1/4 for peptide MTEYKLVVVGADGVGKSALTIQLI - 2026-03-17 17:06:08
batch processing time: 0.66s, Progress: 25.0%

Processing batch 2/4 for peptide MTEYKLVVVGADGVGKSALTIQLI - 2026-03-17 17:06:08
batch processing time: 0.48s, Progress: 50.0%

Processing batch 3/4 for peptide MTEYKLVVVGADGVGKSALTIQLI - 2026-03-17 17:06:09
batch processing time: 0.49s, Progress: 75.0%

Processing batch 4/4 for peptide MTEYKLVVVGADGVGKSALTIQLI - 2026-03-17 17:06:09
batch processing time: 0.37s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/MTEYKLVVVGADGVGKSALTIQLI.parquet

Peptide MTEYKLVVVGADGVGKSALTIQLI processing time: 2.08s

Processing peptide: MTEYKLVVVGAGDVGKSALTIQLI on device: cuda:0

Processing batch 1/4 for peptide MTEYKLVVVGAGDVGKSALTIQLI - 2026-03-17 17:06:10
batch processing time: 0.50s, Progress: 25.0%

Processing batch 2/4 for peptide MTEYKLVVVGAGDVGKSALTIQLI - 2026-03-17 17:06:10
batch processing time: 0.49s, Progress: 50.0%

Processing batch 3/4 for peptide MTEYKLVVVGAGDVGKSALTIQLI - 2026-03-17 17:06:11
batch processing time: 0.69s, Progress: 75.0%

Processing batch 4/4 for peptide MTEYKLVVVGAGDVGKSALTIQLI - 2026-03-17 17:06:12
batch processing time: 0.35s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/MTEYKLVVVGAGDVGKSALTIQLI.parquet

Peptide MTEYKLVVVGAGDVGKSALTIQLI processing time: 2.11s

Processing peptide: MTEYKLVVVGARGVGKSALTIQLI on device: cuda:0

Processing batch 1/4 for peptide MTEYKLVVVGARGVGKSALTIQLI - 2026-03-17 17:06:12
batch processing time: 0.48s, Progress: 25.0%

Processing batch 2/4 for peptide MTEYKLVVVGARGVGKSALTIQLI - 2026-03-17 17:06:12
batch processing time: 0.46s, Progress: 50.0%

Processing batch 3/4 for peptide MTEYKLVVVGARGVGKSALTIQLI - 2026-03-17 17:06:13
batch processing time: 0.50s, Progress: 75.0%

Processing batch 4/4 for peptide MTEYKLVVVGARGVGKSALTIQLI - 2026-03-17 17:06:13
batch processing time: 0.37s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/MTEYKLVVVGARGVGKSALTIQLI.parquet

Peptide MTEYKLVVVGARGVGKSALTIQLI processing time: 1.89s

Processing peptide: MTEYKLVVVGAVGVGKSALTIQLI on device: cuda:0

Processing batch 1/4 for peptide MTEYKLVVVGAVGVGKSALTIQLI - 2026-03-17 17:06:14
batch processing time: 0.58s, Progress: 25.0%

Processing batch 2/4 for peptide MTEYKLVVVGAVGVGKSALTIQLI - 2026-03-17 17:06:14
batch processing time: 0.53s, Progress: 50.0%

Processing batch 3/4 for peptide MTEYKLVVVGAVGVGKSALTIQLI - 2026-03-17 17:06:15
batch processing time: 0.51s, Progress: 75.0%

Processing batch 4/4 for peptide MTEYKLVVVGAVGVGKSALTIQLI - 2026-03-17 17:06:15
batch processing time: 0.39s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/MTEYKLVVVGAVGVGKSALTIQLI.parquet

Peptide MTEYKLVVVGAVGVGKSALTIQLI processing time: 2.08s

Processing peptide: SARDLTSGANNEQFFGPGTRLTVL on device: cuda:0

Processing batch 1/4 for peptide SARDLTSGANNEQFFGPGTRLTVL - 2026-03-17 17:06:16
batch processing time: 0.65s, Progress: 25.0%

Processing batch 2/4 for peptide SARDLTSGANNEQFFGPGTRLTVL - 2026-03-17 17:06:17
batch processing time: 0.45s, Progress: 50.0%

Processing batch 3/4 for peptide SARDLTSGANNEQFFGPGTRLTVL - 2026-03-17 17:06:17
batch processing time: 0.56s, Progress: 75.0%

Processing batch 4/4 for peptide SARDLTSGANNEQFFGPGTRLTVL - 2026-03-17 17:06:18
batch processing time: 0.40s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/SARDLTSGANNEQFFGPGTRLTVL.parquet

Peptide SARDLTSGANNEQFFGPGTRLTVL processing time: 2.14s

Processing peptide: ATDTTSGTYKYIFGTGTRLKVLA on device: cuda:0

Processing batch 1/4 for peptide ATDTTSGTYKYIFGTGTRLKVLA - 2026-03-17 17:06:18
batch processing time: 0.52s, Progress: 25.0%

Processing batch 2/4 for peptide ATDTTSGTYKYIFGTGTRLKVLA - 2026-03-17 17:06:19
batch processing time: 0.53s, Progress: 50.0%

Processing batch 3/4 for peptide ATDTTSGTYKYIFGTGTRLKVLA - 2026-03-17 17:06:19
batch processing time: 0.70s, Progress: 75.0%

Processing batch 4/4 for peptide ATDTTSGTYKYIFGTGTRLKVLA - 2026-03-17 17:06:20
batch processing time: 0.35s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/ATDTTSGTYKYIFGTGTRLKVLA.parquet

Peptide ATDTTSGTYKYIFGTGTRLKVLA processing time: 2.18s

Processing peptide: TTSEDNEVFGEADANQNNGTSS on device: cuda:0

Processing batch 1/4 for peptide TTSEDNEVFGEADANQNNGTSS - 2026-03-17 17:06:20
batch processing time: 0.47s, Progress: 25.0%

Processing batch 2/4 for peptide TTSEDNEVFGEADANQNNGTSS - 2026-03-17 17:06:21
batch processing time: 0.55s, Progress: 50.0%

Processing batch 3/4 for peptide TTSEDNEVFGEADANQNNGTSS - 2026-03-17 17:06:21
batch processing time: 0.53s, Progress: 75.0%

Processing batch 4/4 for peptide TTSEDNEVFGEADANQNNGTSS - 2026-03-17 17:06:22
batch processing time: 0.41s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/TTSEDNEVFGEADANQNNGTSS.parquet

Peptide TTSEDNEVFGEADANQNNGTSS processing time: 2.04s

Processing peptide: FNNFTVSFWLRVPKVSASHLE on device: cuda:0

Processing batch 1/4 for peptide FNNFTVSFWLRVPKVSASHLE - 2026-03-17 17:06:22
batch processing time: 0.51s, Progress: 25.0%

Processing batch 2/4 for peptide FNNFTVSFWLRVPKVSASHLE - 2026-03-17 17:06:23
batch processing time: 0.61s, Progress: 50.0%

Processing batch 3/4 for peptide FNNFTVSFWLRVPKVSASHLE - 2026-03-17 17:06:23
batch processing time: 0.48s, Progress: 75.0%

Processing batch 4/4 for peptide FNNFTVSFWLRVPKVSASHLE - 2026-03-17 17:06:24
batch processing time: 0.36s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/FNNFTVSFWLRVPKVSASHLE.parquet

Peptide FNNFTVSFWLRVPKVSASHLE processing time: 2.03s

Processing peptide: AHPADPGSRPHLIRLFSRDA on device: cuda:0

Processing batch 1/4 for peptide AHPADPGSRPHLIRLFSRDA - 2026-03-17 17:06:24
batch processing time: 0.54s, Progress: 25.0%

Processing batch 2/4 for peptide AHPADPGSRPHLIRLFSRDA - 2026-03-17 17:06:25
batch processing time: 0.47s, Progress: 50.0%

Processing batch 3/4 for peptide AHPADPGSRPHLIRLFSRDA - 2026-03-17 17:06:25
batch processing time: 0.49s, Progress: 75.0%

Processing batch 4/4 for peptide AHPADPGSRPHLIRLFSRDA - 2026-03-17 17:06:26
batch processing time: 0.39s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/AHPADPGSRPHLIRLFSRDA.parquet

Peptide AHPADPGSRPHLIRLFSRDA processing time: 1.98s

Processing peptide: AISRKMVELVHFLLLKYRAR on device: cuda:0

Processing batch 1/4 for peptide AISRKMVELVHFLLLKYRAR - 2026-03-17 17:06:26
batch processing time: 0.54s, Progress: 25.0%

Processing batch 2/4 for peptide AISRKMVELVHFLLLKYRAR - 2026-03-17 17:06:27
batch processing time: 0.54s, Progress: 50.0%

Processing batch 3/4 for peptide AISRKMVELVHFLLLKYRAR - 2026-03-17 17:06:27
batch processing time: 0.54s, Progress: 75.0%

Processing batch 4/4 for peptide AISRKMVELVHFLLLKYRAR - 2026-03-17 17:06:28
batch processing time: 0.50s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/AISRKMVELVHFLLLKYRAR.parquet

Peptide AISRKMVELVHFLLLKYRAR processing time: 2.21s

Processing peptide: DEPLTSLTPRCNTAWNRLKL on device: cuda:0

Processing batch 1/4 for peptide DEPLTSLTPRCNTAWNRLKL - 2026-03-17 17:06:28
batch processing time: 0.73s, Progress: 25.0%

Processing batch 2/4 for peptide DEPLTSLTPRCNTAWNRLKL - 2026-03-17 17:06:29
batch processing time: 0.49s, Progress: 50.0%

Processing batch 3/4 for peptide DEPLTSLTPRCNTAWNRLKL - 2026-03-17 17:06:30
batch processing time: 0.50s, Progress: 75.0%

Processing batch 4/4 for peptide DEPLTSLTPRCNTAWNRLKL - 2026-03-17 17:06:30
batch processing time: 0.36s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/DEPLTSLTPRCNTAWNRLKL.parquet

Peptide DEPLTSLTPRCNTAWNRLKL processing time: 2.16s

Processing peptide: KCNTATCATQRLANFLVRSS on device: cuda:0

Processing batch 1/4 for peptide KCNTATCATQRLANFLVRSS - 2026-03-17 17:06:31
batch processing time: 0.71s, Progress: 25.0%

Processing batch 2/4 for peptide KCNTATCATQRLANFLVRSS - 2026-03-17 17:06:31
batch processing time: 0.49s, Progress: 50.0%

Processing batch 3/4 for peptide KCNTATCATQRLANFLVRSS - 2026-03-17 17:06:32
batch processing time: 0.57s, Progress: 75.0%

Processing batch 4/4 for peptide KCNTATCATQRLANFLVRSS - 2026-03-17 17:06:32
batch processing time: 0.36s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/KCNTATCATQRLANFLVRSS.parquet

Peptide KCNTATCATQRLANFLVRSS processing time: 2.22s

Processing peptide: VFVQSVLPYFVATKLAKIRK on device: cuda:0

Processing batch 1/4 for peptide VFVQSVLPYFVATKLAKIRK - 2026-03-17 17:06:33
batch processing time: 0.56s, Progress: 25.0%

Processing batch 2/4 for peptide VFVQSVLPYFVATKLAKIRK - 2026-03-17 17:06:33
batch processing time: 0.54s, Progress: 50.0%

Processing batch 3/4 for peptide VFVQSVLPYFVATKLAKIRK - 2026-03-17 17:06:34
batch processing time: 0.56s, Progress: 75.0%

Processing batch 4/4 for peptide VFVQSVLPYFVATKLAKIRK - 2026-03-17 17:06:35
batch processing time: 0.45s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/VFVQSVLPYFVATKLAKIRK.parquet

Peptide VFVQSVLPYFVATKLAKIRK processing time: 2.19s

Processing peptide: VVVGAVGVGKSALTIQLIQN on device: cuda:0

Processing batch 1/4 for peptide VVVGAVGVGKSALTIQLIQN - 2026-03-17 17:06:35
batch processing time: 3.26s, Progress: 25.0%

Processing batch 2/4 for peptide VVVGAVGVGKSALTIQLIQN - 2026-03-17 17:06:38
batch processing time: 0.53s, Progress: 50.0%

Processing batch 3/4 for peptide VVVGAVGVGKSALTIQLIQN - 2026-03-17 17:06:39
batch processing time: 0.53s, Progress: 75.0%

Processing batch 4/4 for peptide VVVGAVGVGKSALTIQLIQN - 2026-03-17 17:06:39
batch processing time: 0.40s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/VVVGAVGVGKSALTIQLIQN.parquet

Peptide VVVGAVGVGKSALTIQLIQN processing time: 4.81s

Processing peptide: YNYIASFFIETGFCDSGILS on device: cuda:0

Processing batch 1/4 for peptide YNYIASFFIETGFCDSGILS - 2026-03-17 17:06:40
batch processing time: 0.58s, Progress: 25.0%

Processing batch 2/4 for peptide YNYIASFFIETGFCDSGILS - 2026-03-17 17:06:40
batch processing time: 0.56s, Progress: 50.0%

Processing batch 3/4 for peptide YNYIASFFIETGFCDSGILS - 2026-03-17 17:06:41
batch processing time: 0.61s, Progress: 75.0%

Processing batch 4/4 for peptide YNYIASFFIETGFCDSGILS - 2026-03-17 17:06:42
batch processing time: 0.39s, Progress: 100.0%
Successfully wrote 37459 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_zero/YNYIASFFIETGFCDSGILS.parquet

Peptide YNYIASFFIETGFCDSGILS processing time: 2.21s

Processing peptide: LSRFSWGAEGQRPGFGYGG on device: cuda:0


In [19]:
import os
import pandas as pd

PARQUET_DIR = "../inference/PanPep_Weight_Inference/CASE4_zero"
CSV_PATH = "../data/fig5/reshuffling_zero_0.csv"

OUTPUT_DIR = "./result"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "CASE4_zero_scored.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

csv_df = pd.read_csv(CSV_PATH)

if "label" in csv_df.columns:
    csv_df = csv_df.rename(columns={"label": "Label"})

peptides = csv_df["peptide"].unique()

results = []
for pep in peptides:
    parquet_path = os.path.join(PARQUET_DIR, f"{pep}.parquet")
    if not os.path.exists(parquet_path):
        print(f"[SKIP] No parquet for {pep}")
        continue

    parquet_df = pd.read_parquet(parquet_path)[["CDR3", "Score"]].rename(
        columns={"CDR3": "binding_TCR"}
    )

    pep_rows = csv_df[csv_df["peptide"] == pep].copy()
    merged = pep_rows.merge(parquet_df, on="binding_TCR", how="left")
    results.append(merged)

    print(f"[OK] {pep}: {len(merged)} rows, {merged['Score'].notna().sum()} scored")

if results:
    final_df = pd.concat(results, ignore_index=True)
    final_df.to_csv(OUTPUT_PATH, index=False)

    print(f"\nSaved to {OUTPUT_PATH}")
    print(f"Total rows: {len(final_df)}, scored: {final_df['Score'].notna().sum()}")
else:
    print("No results to save.")

[OK] AALALLLLDRLNQLE: 6 rows, 6 scored
[OK] AALPILFQV: 2 rows, 2 scored
[OK] AAQNVHFWKALNQL: 2 rows, 2 scored
[OK] AAQRIHFFKNLSLL: 2 rows, 2 scored
[OK] AARAVFLAL: 6 rows, 6 scored
[OK] AAVVRFQEAANKQKQ: 4 rows, 4 scored
[OK] ADGLAYFRSSFKGG: 2 rows, 2 scored
[OK] ADTLQSIGATTVASN: 8 rows, 8 scored
[OK] AENPVVHFFKNIATPR: 2 rows, 2 scored
[OK] AFLLFLVLI: 2 rows, 2 scored
[OK] AGSLQPLAL: 2 rows, 2 scored
[OK] AGSLQPLALE: 2 rows, 2 scored
[OK] AHIQWMVMF: 2 rows, 2 scored
[OK] AHPADPGSRPHLIRLFSRDA: 2 rows, 2 scored
[OK] AIILASFSA: 2 rows, 2 scored
[OK] AIKLDDKDP: 2 rows, 2 scored
[OK] AIMTRCLAV: 4 rows, 4 scored
[OK] AISRKMVELVHFLLLKYRAR: 4 rows, 4 scored
[OK] ALALLLLDR: 4 rows, 4 scored
[OK] ALASCMGLI: 2 rows, 2 scored
[OK] ALASCMGLIY: 8 rows, 8 scored
[OK] ALAVLHFYPDKGAKN: 2 rows, 2 scored
[OK] ALDPHSGHFV: 6 rows, 6 scored
[OK] ALEPGPVTA: 2 rows, 2 scored
[OK] ALHGGWTTK: 4 rows, 4 scored
[OK] ALLADKFPV: 2 rows, 2 scored
[OK] ALLETLSLLL: 2 rows, 2 scored
[OK] ALLLQLFTL: 2 rows, 2 scored
[OK] ALLPGLPAA: 8 rows, 8 scored
[OK] ALLSDLQDL: 2 rows, 2 scored
[OK] ALNLGETFV: 4 rows, 4 scored
[OK] ALNNIINNA: 4 rows, 4 scored
[OK] ALNTLVKQL: 4 rows, 4 scored
[OK] ALNTPKDHI: 2 rows, 2 scored
[OK] ALPETTADI: 2 rows, 2 scored
[OK] ALQIPFAMQM: 2 rows, 2 scored
[OK] ALSGVFCGV: 2 rows, 2 scored
[OK] ALTAVAEEV: 4 rows, 4 scored
[OK] ALWGFFPVL: 2 rows, 2 scored
[OK] ALWMRLLPLL: 2 rows, 2 scored
[OK] ALYYPSARI: 2 rows, 2 scored
[OK] AMDEFIEQY: 2 rows, 2 scored
[OK] AMDEFIERY: 4 rows, 4 scored
[OK] AMMFTSDLA: 2 rows, 2 scored
[OK] AMQTMLFTM: 6 rows, 6 scored
[OK] ANPVVHFFKNIVTPR: 2 rows, 2 scored
[OK] APARLERRHSA: 6 rows, 6 scored
[OK] APATVCGPK: 2 rows, 2 scored
[OK] APFSEQEQPVLG: 4 rows, 4 scored
[OK] APHGVVFLH: 2 rows, 2 scored
[OK] APISAMVRM: 2 rows, 2 scored
[OK] APLLSAGVF: 4 rows, 4 scored
[OK] APMPMPELPYP: 2 rows, 2 scored
[OK] APQPELPYPQPG: 2 rows, 2 scored
[OK] APRITFGGL: 2 rows, 2 scored
[OK] APSGEGSFQPSQENPQ: 2 rows, 2 scored
[OK] APTKVTFGV: 2 rows, 2 scored
[OK] AQWGPDPAAA: 4 rows, 4 scored
[OK] ARSVFHFFRGTALL: 2 rows, 2 scored
[OK] ASQARPSQR: 2 rows, 2 scored
[OK] ASQFRPSQR: 2 rows, 2 scored
[OK] ASQKRPSQR: 4 rows, 4 scored
[OK] ASQKRPSQRS: 2 rows, 2 scored
[OK] ASQYRPSQR: 2 rows, 2 scored
[OK] ATDTTSGTYKYIFGTGTRLKVLA: 2 rows, 2 scored
[OK] ATEGRVRVNSAYQDK: 2 rows, 2 scored
[OK] ATGFKQSSKALQRPVAS: 2 rows, 2 scored
[OK] ATRGATVVI: 2 rows, 2 scored
[OK] ATSRMLSYY: 2 rows, 2 scored
[OK] ATSRTLSYY: 2 rows, 2 scored
[OK] AVGVGKSAL: 2 rows, 2 scored
[OK] AVIKTLQPV: 2 rows, 2 scored
[OK] AVLDMCASL: 2 rows, 2 scored
[OK] AVVQSELPYPEGS: 2 rows, 2 scored
[OK] AVYDGREHTV: 2 rows, 2 scored
[OK] CFAYYFMRF: 2 rows, 2 scored
[OK] CISSCNPNL: 2 rows, 2 scored
[OK] CLAYYFMRF: 4 rows, 4 scored
[OK] CLEASFNYL: 6 rows, 6 scored
[OK] CLGSLIYST: 2 rows, 2 scored
[OK] CLTPVYSFL: 6 rows, 6 scored
[OK] CPACYNSEV: 6 rows, 6 scored
[OK] CPRERPEEL: 2 rows, 2 scored
[OK] CTDDNALAY: 2 rows, 2 scored
[OK] CTDDNALAYY: 6 rows, 6 scored
[OK] CVMYASAVV: 2 rows, 2 scored
[OK] DDKDPQFKD: 4 rows, 4 scored
[OK] DEPLTSLTPRCNTAWNRLKL: 4 rows, 4 scored
[OK] DFARVHFISALHGSG: 2 rows, 2 scored
[OK] DFHFEVFNFVPCSI: 8 rows, 8 scored
[OK] DKDPQFKDN: 2 rows, 2 scored
[OK] DKSMKVTVAFNQF: 8 rows, 8 scored
[OK] DLAGIGILTV: 2 rows, 2 scored
[OK] DLFMRIFTI: 2 rows, 2 scored
[OK] DLTSFLLSL: 2 rows, 2 scored
[OK] DNVILLNKH: 2 rows, 2 scored
[OK] DPIVRGLLARAA: 2 rows, 2 scored
[OK] DPLIRGLLARPA: 2 rows, 2 scored
[OK] DQVILLNKH: 6 rows, 6 scored
[OK] DRLNQLESK: 2 rows, 2 scored
[OK] DTLEKISNEIKIVATP: 8 rows, 8 scored
[OK] DVSKVHFFKGNGQT: 2 rows, 2 scored
[OK] DYKHYTPSF: 2 rows, 2 scored
[OK] DYTEISFML: 2 rows, 2 scored
[OK] EAKQKGFVPF: 6 rows, 6 scored
[OK] EAPVVHFFKNIVTPR: 2 rows, 2 scored
[OK] EEAAGIGIL: 2 rows, 2 scored
[OK] EFTVSGNIL: 2 rows, 2 scored
[OK] EGHLKRNIV: 4 rows, 4 scored
[OK] EGPRNQDWL: 2 rows, 2 scored
[OK] EGSRNQDWL: 2 rows, 2 scored
[OK] EIAGIGILTV: 2 rows, 2 scored
[OK] EIDPKLDNY: 2 rows, 2 scored
[OK] EIFDRYGEEV: 4 rows, 4 scored
[OK] EIRTQYEAM: 2 rows, 2 scored
[OK] EKPKFEAYKAAAAPA: 2 rows, 2 scored
[OK] EKPKVEAYKAAAAPA: 2 rows, 2 scored
[OK] EKPKYEAYKAAAAPA: 2 rows, 2 scored
[OK] ELAAIGILTV: 2 rows, 2 scored
[OK] ELAGIAILTV: 2 rows, 2 scored
[OK] ELAGIGIATV: 2 rows, 2 scored
[OK] ELAGIGIITV: 2 rows, 2 scored
[OK] ELAGIGILAV: 2 rows, 2 scored
[OK] ELAGIGILSV: 2 rows, 2 scored
[OK] ELAGIGILTA: 2 rows, 2 scored
[OK] ELAGIGILTI: 2 rows, 2 scored
[OK] ELAGIGLLTV: 2 rows, 2 scored
[OK] ELGGIGILTV: 2 rows, 2 scored
[OK] ELTSMKYFV: 4 rows, 4 scored
[OK] ELYHYQECV: 4 rows, 4 scored
[OK] ELYSPIFLI: 6 rows, 6 scored
[OK] EMLFSHGLVK: 2 rows, 2 scored
[OK] EMMLFDWKV: 2 rows, 2 scored
[OK] ENAVVHFFKNIVTPR: 2 rows, 2 scored
[OK] ENAVVHFFRSLVSS: 2 rows, 2 scored
[OK] ENPAVHFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVAHFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVDFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFFKAIVTPR: 2 rows, 2 scored
[OK] ENPVVHFFKDIVTPR: 2 rows, 2 scored
[OK] ENPVVHFFKNAVTPR: 2 rows, 2 scored
[OK] ENPVVHFFKNIVAPR: 2 rows, 2 scored
[OK] ENPVVHFFKNIVTAR: 2 rows, 2 scored
[OK] ENPVVHFFKNIVTP: 4 rows, 4 scored
[OK] ENPVVHFFKNIVTPA: 2 rows, 2 scored
[OK] ENPVVHFFKNIVTPR: 4 rows, 4 scored
[OK] ENPVVHFFRNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFHKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFIKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFMKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFVKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFWKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFYKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHGFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHMFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHYFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVIFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVLFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVMFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVNFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVRFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVTFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVVFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVWFFKNIVTPR: 2 rows, 2 scored
[OK] ESDPIVAQY: 2 rows, 2 scored
[OK] ESITGSLGPLL: 2 rows, 2 scored
[OK] ETALALLLL: 2 rows, 2 scored
[OK] EVDPIGHLY: 2 rows, 2 scored
[OK] EVKEKGMAA: 2 rows, 2 scored
[OK] EVLPFFLFF: 2 rows, 2 scored
[OK] FAFACPDGV: 6 rows, 6 scored
[OK] FAFPFTIYS: 4 rows, 4 scored
[OK] FAMQMAYRF: 6 rows, 6 scored
[OK] FAPGFFPYL: 2 rows, 2 scored
[OK] FATGIGIITV: 2 rows, 2 scored
[OK] FEDLRVLSF: 2 rows, 2 scored
[OK] FFAGGIGIRTI: 2 rows, 2 scored
[OK] FGDHPGHSY: 2 rows, 2 scored
[OK] FGDVGSTLF: 2 rows, 2 scored
[OK] FGVKIHFFKQRNSL: 2 rows, 2 scored
[OK] FIAGLIAIV: 6 rows, 6 scored
[OK] FIDIKRGVY: 2 rows, 2 scored
[OK] FIDTKRGVY: 2 rows, 2 scored
[OK] FISTCACEI: 4 rows, 4 scored
[OK] FITESKPSV: 6 rows, 6 scored
[OK] FKDNVILLN: 4 rows, 4 scored
[OK] FLAFVVFLL: 4 rows, 4 scored
[OK] FLAGGIGIRTL: 2 rows, 2 scored
[OK] FLCLFLLPS: 4 rows, 4 scored
[OK] FLCWHTNCY: 8 rows, 8 scored
[OK] FLCWHTSCY: 2 rows, 2 scored
[OK] FLDGSCGSV: 4 rows, 4 scored
[OK] FLEGETLPT: 2 rows, 2 scored
[OK] FLEYHDVRV: 2 rows, 2 scored
[OK] FLFAVGFYL: 2 rows, 2 scored
[OK] FLGIITTVA: 4 rows, 4 scored
[OK] FLGKIWPSYK: 8 rows, 8 scored
[OK] FLGRYMSAL: 2 rows, 2 scored
[OK] FLIGCNYLG: 4 rows, 4 scored
[OK] FLKKDAPYI: 2 rows, 2 scored
[OK] FLKKFHFLKGATLC: 2 rows, 2 scored
[OK] FLLPSLATV: 4 rows, 4 scored
[OK] FLNGSCGSV: 8 rows, 8 scored
[OK] FLNKVVSTT: 4 rows, 4 scored
[OK] FLPFAMGII: 2 rows, 2 scored
[OK] FLPFFSDVT: 4 rows, 4 scored
[OK] FLQDVMNIL: 2 rows, 2 scored
[OK] FLRDGWEIV: 2 rows, 2 scored
[OK] FLTENLLLY: 8 rows, 8 scored
[OK] FLTGIGIITV: 2 rows, 2 scored
[OK] FLVLLPLVS: 6 rows, 6 scored
[OK] FLVRSFYL: 2 rows, 2 scored
[OK] FLWLLWPVT: 4 rows, 4 scored
[OK] FLYENAFLP: 2 rows, 2 scored
[OK] FMCVEYCPI: 4 rows, 4 scored
[OK] FMGVTYEM: 2 rows, 2 scored
[OK] FMIDVQQWG: 4 rows, 4 scored
[OK] FMPDFDLHL: 2 rows, 2 scored
[OK] FMSEAKCWT: 2 rows, 2 scored
[OK] FNNFTVSFWLRVPKVSASHLE: 6 rows, 6 scored
[OK] FPDLNGDVV: 2 rows, 2 scored
[OK] FPFTSFGPL: 2 rows, 2 scored
[OK] FPLCANGQV: 4 rows, 4 scored
[OK] FPLKLRGTA: 2 rows, 2 scored
[OK] FPNITNLCP: 2 rows, 2 scored
[OK] FPQPEQPFPWQP: 6 rows, 6 scored
[OK] FPQSAPHGVVF: 2 rows, 2 scored
[OK] FQDYIKSYL: 2 rows, 2 scored
[OK] FSASTSAFV: 2 rows, 2 scored
[OK] FSAVGDICY: 2 rows, 2 scored
[OK] FSDVTWFHA: 2 rows, 2 scored
[OK] FSLKKGAAA: 2 rows, 2 scored
[OK] FSNVTWFHA: 2 rows, 2 scored
[OK] FSVVGNICY: 2 rows, 2 scored
[OK] FSWGAEGQRPGF: 2 rows, 2 scored
[OK] FSWGAEGQRPGFG: 2 rows, 2 scored
[OK] FSWGAEGQRPGFGSGG: 2 rows, 2 scored
[OK] FTISVTTEI: 2 rows, 2 scored
[OK] FTPLVPFWI: 4 rows, 4 scored
[OK] FVAAIFYLI: 4 rows, 4 scored
[OK] FVCDNIKFA: 6 rows, 6 scored
[OK] FVDGVPFVV: 2 rows, 2 scored
[OK] FVFPLNSII: 2 rows, 2 scored
[OK] FVLAAVYRI: 4 rows, 4 scored
[OK] FVMMSAPPA: 4 rows, 4 scored
[OK] FVNEFYAYL: 4 rows, 4 scored
[OK] FVSEETGTL: 4 rows, 4 scored
[OK] FVTVYSHLL: 4 rows, 4 scored
[OK] FVVFLLVTL: 4 rows, 4 scored
[OK] FVVPYMIYLL: 2 rows, 2 scored
[OK] FWIDLFETIG: 4 rows, 4 scored
[OK] FWITIAYII: 2 rows, 2 scored
[OK] FWLLGAWAL: 2 rows, 2 scored
[OK] FWLLPAWAL: 2 rows, 2 scored
[OK] FYWFFSNYL: 4 rows, 4 scored
[OK] GADGVGKSAL: 6 rows, 6 scored
[OK] GAHCIHFFKSAVCR: 2 rows, 2 scored
[OK] GAIKLDDKD: 2 rows, 2 scored
[OK] GAMKRHGLDNYRGYSLG: 2 rows, 2 scored
[OK] GARGVGKSAL: 2 rows, 2 scored
[OK] GAVGVGKSAL: 4 rows, 4 scored
[OK] GDAALALLL: 2 rows, 2 scored
[OK] GEEDGAGGHSL: 2 rows, 2 scored
[OK] GGETALALL: 4 rows, 4 scored
[OK] GIIAMSAFA: 6 rows, 6 scored
[OK] GILEFVFTL: 2 rows, 2 scored
[OK] GILGLVFTL: 2 rows, 2 scored
[OK] GLALYYPSA: 6 rows, 6 scored
[OK] GLFKDCSKV: 6 rows, 6 scored
[OK] GLIAIVMVT: 4 rows, 4 scored
[OK] GLMWLSYFI: 6 rows, 6 scored
[OK] GLMWLSYFV: 4 rows, 4 scored
[OK] GLNDNLLEI: 2 rows, 2 scored
[OK] GLPWNVVRI: 6 rows, 6 scored
[OK] GLSPNLNRFL: 2 rows, 2 scored
[OK] GLTVLPPLL: 4 rows, 4 scored
[OK] GMDYHNGHL: 2 rows, 2 scored
[OK] GPKVKQWPL: 4 rows, 4 scored
[OK] GPQQSFPEQEA: 2 rows, 2 scored
[OK] GQVELGGGNAVEVCKGS: 1000 rows, 1000 scored
[OK] GQVELGGGPGAESCQ: 2 rows, 2 scored
[OK] GQVELGGGSSPETCI: 2 rows, 2 scored
[OK] GQVELGGGTPIESCQ: 2 rows, 2 scored
[OK] GQVMVVAPR: 4 rows, 4 scored
[OK] GSEHSLAEY: 2 rows, 2 scored
[OK] GSLQPLALEGSLQKRGIV: 2 rows, 2 scored
[OK] GTDLEGNFY: 6 rows, 6 scored
[OK] GVYALIAGA: 6 rows, 6 scored
[OK] GVYDGREHTV: 4 rows, 4 scored
[OK] GVYDYLVST: 6 rows, 6 scored
[OK] GYNSYSVSNSEKHIM: 4 rows, 4 scored
[OK] HARIKLKV: 2 rows, 2 scored
[OK] HENVVHFFKDGELV: 2 rows, 2 scored
[OK] HFISNSWLM: 2 rows, 2 scored
[OK] HGAIKLDDK: 2 rows, 2 scored
[OK] HHLWAYRDLQTRKDIRNAAWHKHGW: 2 rows, 2 scored
[OK] HLCGSHLVEA: 2 rows, 2 scored
[OK] HLLLVAAGL: 2 rows, 2 scored
[OK] HLMSFPQSA: 8 rows, 8 scored
[OK] HLRMAGHSL: 2 rows, 2 scored
[OK] HLVEALYLV: 8 rows, 8 scored
[OK] HMLSFHFWKSRGQT: 2 rows, 2 scored
[OK] HMTEVVRHC: 8 rows, 8 scored
[OK] HPRYFNQL: 4 rows, 4 scored
[OK] HQNPVTGLLL: 2 rows, 2 scored
[OK] HRAKLHFFKDENLK: 2 rows, 2 scored
[OK] HRRGSRSYV: 2 rows, 2 scored
[OK] HSDKFTDGV: 4 rows, 4 scored
[OK] HSYFTSDYY: 2 rows, 2 scored
[OK] HTDLMAAYV: 2 rows, 2 scored
[OK] HYNYMCNSSCMGSMN: 4 rows, 4 scored
[OK] HYPYRLWHY: 8 rows, 8 scored
[OK] IAGLGLLTV: 2 rows, 2 scored
[OK] IEAAIHFYKGLAVY: 2 rows, 2 scored
[OK] IFFITGNTL: 2 rows, 2 scored
[OK] IFLWLLWPV: 2 rows, 2 scored
[OK] IIPAFHFLKSEKGL: 2 rows, 2 scored
[OK] IITTDNTFV: 2 rows, 2 scored
[OK] IKLDDKDPN: 4 rows, 4 scored
[OK] IKLDDKDPQ: 4 rows, 4 scored
[OK] ILAAFLHWL: 2 rows, 2 scored
[OK] ILAKFAHWL: 2 rows, 2 scored
[OK] ILAYCNKTV: 6 rows, 6 scored
[OK] ILDQVPFSV: 4 rows, 4 scored
[OK] ILDTAGKEEY: 8 rows, 8 scored
[OK] ILFTRFFYV: 6 rows, 6 scored
[OK] ILGALLSIL: 6 rows, 6 scored
[OK] ILGGQVVHTV: 4 rows, 4 scored
[OK] ILGLPTQTV: 2 rows, 2 scored
[OK] ILLLDQALV: 2 rows, 2 scored
[OK] ILLWQPIPV: 2 rows, 2 scored
[OK] ILMHCQTTL: 4 rows, 4 scored
[OK] ILMNDQEVGV: 2 rows, 2 scored
[OK] ILPDPSKPS: 2 rows, 2 scored
[OK] ILRKGGRTI: 2 rows, 2 scored
[OK] ILTSLLVLV: 2 rows, 2 scored
[OK] ILYCKRASLTELVSPRLPSHLSEYE: 4 rows, 4 scored
[OK] IPAAAGRFF: 2 rows, 2 scored
[OK] IPIQASLPF: 6 rows, 6 scored
[OK] IPLTEEAEL: 4 rows, 4 scored
[OK] IPLTTAAKL: 2 rows, 2 scored
[OK] IPLTTSSKL: 2 rows, 2 scored
[OK] IPRRNVATL: 6 rows, 6 scored
[OK] IPTITQMNL: 4 rows, 4 scored
[OK] IPVAYRKVL: 8 rows, 8 scored
[OK] IPVAYRNVL: 6 rows, 6 scored
[OK] IQPGQTFSV: 2 rows, 2 scored
[OK] ISDYDYYRY: 6 rows, 6 scored
[OK] ISQWLTNIF: 2 rows, 2 scored
[OK] ITFDNLKTL: 4 rows, 4 scored
[OK] ITNFKSVLY: 2 rows, 2 scored
[OK] ITREEKPAVTAAPKK: 2 rows, 2 scored
[OK] ITSGWTFGA: 2 rows, 2 scored
[OK] IVDTVSALV: 2 rows, 2 scored
[OK] IVNSVLLFL: 2 rows, 2 scored
[OK] IYLDLPWYL: 8 rows, 8 scored
[OK] KALARALKEGRIR: 2 rows, 2 scored
[OK] KASEKIFYV: 8 rows, 8 scored
[OK] KAYDVTQAF: 2 rows, 2 scored
[OK] KCNTATCATQRLANFLVRSS: 4 rows, 4 scored
[OK] KDNVILLNK: 6 rows, 6 scored
[OK] KDPQFKDNV: 2 rows, 2 scored
[OK] KIADPICTFI: 2 rows, 2 scored
[OK] KIILFLALI: 4 rows, 4 scored
[OK] KISEMHPAL: 2 rows, 2 scored
[OK] KITEHSWNA: 6 rows, 6 scored
[OK] KIVALGINAV: 8 rows, 8 scored
[OK] KIYSKHTPI: 2 rows, 2 scored
[OK] KLDDKDPNF: 2 rows, 2 scored
[OK] KLDDKDPQF: 2 rows, 2 scored
[OK] KLDGFMGRI: 6 rows, 6 scored
[OK] KLEFMDWRL: 2 rows, 2 scored
[OK] KLEQLDWTV: 2 rows, 2 scored
[OK] KLFEFLVHGV: 6 rows, 6 scored
[OK] KLIEYTDFA: 2 rows, 2 scored
[OK] KLLKSIAAT: 2 rows, 2 scored
[OK] KLMPVCVET: 2 rows, 2 scored
[OK] KLNIKLLGV: 6 rows, 6 scored
[OK] KLNVGDYFV: 2 rows, 2 scored
[OK] KLPDDFMGC: 4 rows, 4 scored
[OK] KLPDDFTGC: 4 rows, 4 scored
[OK] KLPDDFTGCV: 6 rows, 6 scored
[OK] KLSYGIATV: 6 rows, 6 scored
[OK] KLTESLHKV: 2 rows, 2 scored
[OK] KLVALGINNV: 4 rows, 4 scored
[OK] KLVALVINAV: 2 rows, 2 scored
[OK] KLVNKFLAL: 2 rows, 2 scored
[OK] KLVSSFLEM: 2 rows, 2 scored
[OK] KLYGLDWAEL: 6 rows, 6 scored
[OK] KMDYFSGQL: 2 rows, 2 scored
[OK] KMFDAYVNT: 2 rows, 2 scored
[OK] KMGVTYEM: 2 rows, 2 scored
[OK] KMVSLLSVL: 2 rows, 2 scored
[OK] KPADNSLKI: 2 rows, 2 scored
[OK] KPAPRELKV: 2 rows, 2 scored
[OK] KPASRELKV: 2 rows, 2 scored
[OK] KPLPEVKIL: 2 rows, 2 scored
[OK] KPRQKRTAT: 4 rows, 4 scored
[OK] KPVPEVKIL: 2 rows, 2 scored
[OK] KPYIKWDLL: 4 rows, 4 scored
[OK] KQHVCGGSILDPYWVLTAAHCFRKH: 2 rows, 2 scored
[OK] KQLIKVTLV: 4 rows, 4 scored
[OK] KQLPFFYYS: 6 rows, 6 scored
[OK] KQLSSNFGA: 6 rows, 6 scored
[OK] KQWLVWLFL: 4 rows, 4 scored
[OK] KQWLVWLLL: 2 rows, 2 scored
[OK] KRGIVEQCCTSISSL: 2 rows, 2 scored
[OK] KRGIVEQSSTSISSL: 6 rows, 6 scored
[OK] KSVDITFEL: 4 rows, 4 scored
[OK] KVDGVDVEL: 2 rows, 2 scored
[OK] KVDPIGHVY: 2 rows, 2 scored
[OK] KVITFIDL: 2 rows, 2 scored
[OK] KVPRNQDWL: 2 rows, 2 scored
[OK] KVSIWNLDY: 4 rows, 4 scored
[OK] KWPWYIWLG: 4 rows, 4 scored
[OK] LACFVLAAV: 6 rows, 6 scored
[OK] LALWGPDPAA: 6 rows, 6 scored
[OK] LAMPFATPM: 2 rows, 2 scored
[OK] LDDKDPNFK: 2 rows, 2 scored
[OK] LDDKDPQFK: 2 rows, 2 scored
[OK] LDRLNQLES: 2 rows, 2 scored
[OK] LESVVHFLRGQKVT: 2 rows, 2 scored
[OK] LFTRFFYVL: 2 rows, 2 scored
[OK] LGIGVITI: 2 rows, 2 scored
[OK] LIDFYLCFL: 8 rows, 8 scored
[OK] LIIMRTFKV: 8 rows, 8 scored
[OK] LITGRLQSL: 6 rows, 6 scored
[OK] LLDRLNQLE: 2 rows, 2 scored
[OK] LLEDLDWDV: 2 rows, 2 scored
[OK] LLEWLAMAV: 4 rows, 4 scored
[OK] LLFGLALIEV: 2 rows, 2 scored
[OK] LLFGYPVFV: 2 rows, 2 scored
[OK] LLFLMSFTV: 2 rows, 2 scored
[OK] LLFNKVTLA: 6 rows, 6 scored
[OK] LLIDLTSFL: 6 rows, 6 scored
[OK] LLIDLTSFLL: 2 rows, 2 scored
[OK] LLLARAASLSL: 6 rows, 6 scored
[OK] LLLDDFVEI: 2 rows, 2 scored
[OK] LLLDRLNQL: 8 rows, 8 scored
[OK] LLLTILTSL: 2 rows, 2 scored
[OK] LLMEGVPKSL: 4 rows, 4 scored
[OK] LLMPILTLT: 4 rows, 4 scored
[OK] LLNATDIAV: 6 rows, 6 scored
[OK] LLNKHIDAY: 8 rows, 8 scored
[OK] LLNVKLAL: 4 rows, 4 scored
[OK] LLQEYNWEL: 6 rows, 6 scored
[OK] LLSVCLGSL: 4 rows, 4 scored
[OK] LLTNMFTPL: 2 rows, 2 scored
[OK] LLWNTVWNM: 4 rows, 4 scored
[OK] LMCQPILLL: 8 rows, 8 scored
[OK] LMDMHNGQL: 2 rows, 2 scored
[OK] LMDYWQGQL: 2 rows, 2 scored
[OK] LMGHFAWWT: 4 rows, 4 scored
[OK] LMHCQTTL: 2 rows, 2 scored
[OK] LMIERFVSL: 8 rows, 8 scored
[OK] LMMPFSIVYI: 4 rows, 4 scored
[OK] LMNVLTLFY: 2 rows, 2 scored
[OK] LMNVLTLVY: 8 rows, 8 scored
[OK] LMWLIINLV: 2 rows, 2 scored
[OK] LMWLSYFIA: 4 rows, 4 scored
[OK] LNHLKATPI: 6 rows, 6 scored
[OK] LNKHIDAYK: 2 rows, 2 scored
[OK] LNKNIHFFKNLPLP: 2 rows, 2 scored
[OK] LPARTSPM: 2 rows, 2 scored
[OK] LPDDFMGCV: 4 rows, 4 scored
[OK] LPDDFTGCV: 4 rows, 4 scored
[OK] LPEGLPQGQLTAY: 2 rows, 2 scored
[OK] LPEPLPQGGLTAY: 2 rows, 2 scored
[OK] LPFDKATIM: 8 rows, 8 scored
[OK] LPFDKPTIM: 4 rows, 4 scored
[OK] LPFDKSTIM: 8 rows, 8 scored
[OK] LPFDKSTVM: 8 rows, 8 scored
[OK] LPFDKTTIM: 6 rows, 6 scored
[OK] LPFEKSTIM: 4 rows, 4 scored
[OK] LPFEKSTVM: 4 rows, 4 scored
[OK] LPFERATIM: 2 rows, 2 scored
[OK] LPGCDGGSL: 4 rows, 4 scored
[OK] LPKEITVAT: 6 rows, 6 scored
[OK] LPKGIMMNV: 6 rows, 6 scored
[OK] LPNNTASWF: 4 rows, 4 scored
[OK] LPPAYTNSF: 4 rows, 4 scored
[OK] LPPSYTNSF: 2 rows, 2 scored
[OK] LPSYAAFAT: 2 rows, 2 scored
[OK] LPSYAALAT: 8 rows, 8 scored
[OK] LQLGFSTGV: 2 rows, 2 scored
[OK] LQNNELSPV: 2 rows, 2 scored
[OK] LQPFPQPELPYGSGGS: 2 rows, 2 scored
[OK] LSDLQDLKW: 2 rows, 2 scored
[OK] LSDRVVFVL: 2 rows, 2 scored
[OK] LSFKELLVY: 6 rows, 6 scored
[OK] LSPFPFDL: 2 rows, 2 scored
[OK] LSRFSWGAEGQRPGFGYGG: 2 rows, 2 scored
[OK] LTALRLCAY: 2 rows, 2 scored
[OK] LTDEQRAAALEKAAA: 6 rows, 6 scored
[OK] LTGHMLDMY: 2 rows, 2 scored
[OK] LTNDDTSRY: 4 rows, 4 scored
[OK] LTNDNTSRY: 6 rows, 6 scored
[OK] LTSFLLSLF: 2 rows, 2 scored
[OK] LTSHTVMPL: 2 rows, 2 scored
[OK] LTYHGAIKL: 2 rows, 2 scored
[OK] LVGLMWLSY: 2 rows, 2 scored
[OK] LVLSVNPYV: 6 rows, 6 scored
[OK] LVMPFSIVYI: 4 rows, 4 scored
[OK] LVQSTQWSL: 4 rows, 4 scored
[OK] LYALVYFLH: 2 rows, 2 scored
[OK] LYALVYFLQ: 2 rows, 2 scored
[OK] LYPEFIASI: 2 rows, 2 scored
[OK] MASGGGETA: 2 rows, 2 scored
[OK] MCDIRQLLF: 2 rows, 2 scored
[OK] MCDVRQLLF: 2 rows, 2 scored
[OK] MDFARVHFISALHGSG: 2 rows, 2 scored
[OK] MEVDPIGHLY: 2 rows, 2 scored
[OK] MFDAYVNTF: 2 rows, 2 scored
[OK] MFLARGIVF: 4 rows, 4 scored
[OK] MHGNWHFFRNFLSN: 2 rows, 2 scored
[OK] MHQKRTAMFQDPQER: 2 rows, 2 scored
[OK] MHVSFVMAYPEMLAA: 8 rows, 8 scored
[OK] MIAQYTSAL: 2 rows, 2 scored
[OK] MLAKALRKV: 8 rows, 8 scored
[OK] MLFSHGLVK: 2 rows, 2 scored
[OK] MLFTMLRKL: 4 rows, 4 scored
[OK] MLIGIPVYV: 2 rows, 2 scored
[OK] MLNPNYEDL: 4 rows, 4 scored
[OK] MLSILALVRV: 4 rows, 4 scored
[OK] MLWCKDGHV: 2 rows, 2 scored
[OK] MMDFFNAQM: 2 rows, 2 scored
[OK] MMILSDDAV: 8 rows, 8 scored
[OK] MMISAGFSL: 2 rows, 2 scored
[OK] MMWDRGLGMM: 2 rows, 2 scored
[OK] MNASIHFLKALETY: 2 rows, 2 scored
[OK] MPLSAPTLL: 6 rows, 6 scored
[OK] MPNMLRIMA: 2 rows, 2 scored
[OK] MPYGYVLNEF: 2 rows, 2 scored
[OK] MQLFFSYFA: 2 rows, 2 scored
[OK] MQVESDDYI: 8 rows, 8 scored
[OK] MSAFAMMFV: 6 rows, 6 scored
[OK] MSDVKCTSV: 2 rows, 2 scored
[OK] MSQIMYNYPAMLGHA: 4 rows, 4 scored
[OK] MTEYKLVVVGADGVGKSALTIQLI: 2 rows, 2 scored
[OK] MTEYKLVVVGAGDVGKSALTIQLI: 2 rows, 2 scored
[OK] MTEYKLVVVGARGVGKSALTIQLI: 4 rows, 4 scored
[OK] MTEYKLVVVGAVGVGKSALTIQLI: 4 rows, 4 scored
[OK] MVNTVAGAMK: 2 rows, 2 scored
[OK] MVTNNTFTL: 6 rows, 6 scored
[OK] MVWESGCTV: 4 rows, 4 scored
[OK] MVWGPDPLYV: 4 rows, 4 scored
[OK] MYIEMLKSI: 2 rows, 2 scored
[OK] MYTEMLKSI: 2 rows, 2 scored
[OK] NANVLHFLKNIICQ: 2 rows, 2 scored
[OK] NHVVDISKSGLITIA: 2 rows, 2 scored
[OK] NLAQDLATV: 6 rows, 6 scored
[OK] NLAQTDLATV: 2 rows, 2 scored
[OK] NLDAVPTGY: 2 rows, 2 scored
[OK] NLDYIINLI: 2 rows, 2 scored
[OK] NLFLFLFAV: 8 rows, 8 scored
[OK] NLHPDSATL: 2 rows, 2 scored
[OK] NLIDSYFVV: 8 rows, 8 scored
[OK] NLLKDCPAV: 4 rows, 4 scored
[OK] NLQSNHDLY: 2 rows, 2 scored
[OK] NLSDRVVFV: 4 rows, 4 scored
[OK] NMEYMTWDV: 2 rows, 2 scored
[OK] NMLRIMASL: 2 rows, 2 scored
[OK] NMMVTNNTF: 2 rows, 2 scored
[OK] NMMWFQGQL: 2 rows, 2 scored
[OK] NPANNASIV: 2 rows, 2 scored
[OK] NPANNVAIV: 2 rows, 2 scored
[OK] NPQVIHFFKSLDLL: 2 rows, 2 scored
[OK] NPTIQKNVL: 6 rows, 6 scored
[OK] NPVVHFFKNIVTPR: 2 rows, 2 scored
[OK] NSAIGKIQY: 2 rows, 2 scored
[OK] NSKEETGHLENGN: 2 rows, 2 scored
[OK] NSTRFASVY: 4 rows, 4 scored
[OK] NTFSSTFNV: 6 rows, 6 scored
[OK] NTLQCIMLV: 2 rows, 2 scored
[OK] NTLTLAVPY: 2 rows, 2 scored
[OK] NTYGKRNAV: 2 rows, 2 scored
[OK] NVEYYDIKL: 2 rows, 2 scored
[OK] NVILLNKHI: 4 rows, 4 scored
[OK] NVLTLVYKV: 2 rows, 2 scored
[OK] PGISSQHFTYQGGVGGSWPVCSGLG: 2 rows, 2 scored

In [21]:
!{sys.executable} ../metric_calculation/AUC.py \
                    --root_dir ./result \
                    --output_file ./CASE4_zero_auc.csv

Finding CSV files...
Found 1 CSV files
Processed 1/1 files (100.0%)
Failed: 1

In [22]:
import pandas as pd

df = pd.read_csv("./CASE4_zero_auc.csv")
df

,folder_path,file_name,roc_auc,pr_auc,status
0,./result,CASE4_zero_scored.csv,0.299318,0.266584,success
1,./result,[FOLDER_SUMMARY],0.299318,0.266584,success (averaged over 1 files)

#### Meta-learner

In [15]:
import sys

SCRIPT_DIR = "../inference/PanPep_Weight_Inference"
TEST_DATA = "../data/independent_dataset(alpha)/tcra_zero.csv"
NEGATIVE_DATA = "../data/independent_dataset(alpha)/Control dataset_tcra.txt" #This is also equivalent to running the rank.

!{sys.executable} {SCRIPT_DIR}/inference_meta_learner.py \
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "../data/fold1-alpha" \
    --result_dir "CASE4_meta"\
    --peptide_encoding "{SCRIPT_DIR}/peptide_ab.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_ab.npz"

Using 1 GPUs: [0]
GPU 0 will process 931 peptides with approximately 1490 TCRs

Processing peptide: ADTLQSIGATTVASN on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide ADTLQSIGATTVASN - 2026-03-17 17:38:09
batch processing time: 0.67s, Progress: 25.0%

Processing batch 2/4 for peptide ADTLQSIGATTVASN - 2026-03-17 17:38:10
batch processing time: 0.40s, Progress: 50.0%

Processing batch 3/4 for peptide ADTLQSIGATTVASN - 2026-03-17 17:38:10
batch processing time: 0.42s, Progress: 75.0%

Processing batch 4/4 for peptide ADTLQSIGATTVASN - 2026-03-17 17:38:11
batch processing time: 0.29s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/ADTLQSIGATTVASN.parquet

Total time for peptide ADTLQSIGATTVASN: 2.16s

Processing peptide: ALASCMGLIY on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide ALASCMGLIY - 2026-03-17 17:38:11
batch processing time: 0.38s, Progress: 25.0%

Processing batch 2/4 for peptide ALASCMGLIY - 2026-03-17 17:38:12
batch processing time: 0.36s, Progress: 50.0%

Processing batch 3/4 for peptide ALASCMGLIY - 2026-03-17 17:38:12
batch processing time: 0.36s, Progress: 75.0%

Processing batch 4/4 for peptide ALASCMGLIY - 2026-03-17 17:38:13
batch processing time: 0.26s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/ALASCMGLIY.parquet

Total time for peptide ALASCMGLIY: 1.69s

Processing peptide: ALLPGLPAA on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide ALLPGLPAA - 2026-03-17 17:38:13
batch processing time: 0.38s, Progress: 25.0%

Processing batch 2/4 for peptide ALLPGLPAA - 2026-03-17 17:38:14
batch processing time: 0.36s, Progress: 50.0%

Processing batch 3/4 for peptide ALLPGLPAA - 2026-03-17 17:38:14
batch processing time: 0.36s, Progress: 75.0%

Processing batch 4/4 for peptide ALLPGLPAA - 2026-03-17 17:38:14
batch processing time: 0.26s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/ALLPGLPAA.parquet

Total time for peptide ALLPGLPAA: 1.68s

Processing peptide: DFHFEVFNFVPCSI on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide DFHFEVFNFVPCSI - 2026-03-17 17:38:15
batch processing time: 0.45s, Progress: 25.0%

Processing batch 2/4 for peptide DFHFEVFNFVPCSI - 2026-03-17 17:38:15
batch processing time: 0.43s, Progress: 50.0%

Processing batch 3/4 for peptide DFHFEVFNFVPCSI - 2026-03-17 17:38:16
batch processing time: 0.45s, Progress: 75.0%

Processing batch 4/4 for peptide DFHFEVFNFVPCSI - 2026-03-17 17:38:16
batch processing time: 0.31s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/DFHFEVFNFVPCSI.parquet

Total time for peptide DFHFEVFNFVPCSI: 1.95s

Processing peptide: DKSMKVTVAFNQF on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide DKSMKVTVAFNQF - 2026-03-17 17:38:17
batch processing time: 0.45s, Progress: 25.0%

Processing batch 2/4 for peptide DKSMKVTVAFNQF - 2026-03-17 17:38:17
batch processing time: 0.44s, Progress: 50.0%

Processing batch 3/4 for peptide DKSMKVTVAFNQF - 2026-03-17 17:38:18
batch processing time: 0.44s, Progress: 75.0%

Processing batch 4/4 for peptide DKSMKVTVAFNQF - 2026-03-17 17:38:18
batch processing time: 0.26s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/DKSMKVTVAFNQF.parquet

Total time for peptide DKSMKVTVAFNQF: 1.91s

Processing peptide: DTLEKISNEIKIVATP on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide DTLEKISNEIKIVATP - 2026-03-17 17:38:19
batch processing time: 0.40s, Progress: 25.0%

Processing batch 2/4 for peptide DTLEKISNEIKIVATP - 2026-03-17 17:38:19
batch processing time: 0.35s, Progress: 50.0%

Processing batch 3/4 for peptide DTLEKISNEIKIVATP - 2026-03-17 17:38:20
batch processing time: 0.36s, Progress: 75.0%

Processing batch 4/4 for peptide DTLEKISNEIKIVATP - 2026-03-17 17:38:20
batch processing time: 0.27s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/DTLEKISNEIKIVATP.parquet

Total time for peptide DTLEKISNEIKIVATP: 1.70s

Processing peptide: FLCWHTNCY on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide FLCWHTNCY - 2026-03-17 17:38:21
batch processing time: 0.45s, Progress: 25.0%

Processing batch 2/4 for peptide FLCWHTNCY - 2026-03-17 17:38:21
batch processing time: 0.44s, Progress: 50.0%

Processing batch 3/4 for peptide FLCWHTNCY - 2026-03-17 17:38:22
batch processing time: 0.42s, Progress: 75.0%

Processing batch 4/4 for peptide FLCWHTNCY - 2026-03-17 17:38:22
batch processing time: 0.33s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/FLCWHTNCY.parquet

Total time for peptide FLCWHTNCY: 1.99s

Processing peptide: FLGKIWPSYK on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide FLGKIWPSYK - 2026-03-17 17:38:23
batch processing time: 0.45s, Progress: 25.0%

Processing batch 2/4 for peptide FLGKIWPSYK - 2026-03-17 17:38:23
batch processing time: 0.43s, Progress: 50.0%

Processing batch 3/4 for peptide FLGKIWPSYK - 2026-03-17 17:38:24
batch processing time: 0.43s, Progress: 75.0%

Processing batch 4/4 for peptide FLGKIWPSYK - 2026-03-17 17:38:24
batch processing time: 0.31s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/FLGKIWPSYK.parquet

Total time for peptide FLGKIWPSYK: 1.95s

Processing peptide: FLNGSCGSV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide FLNGSCGSV - 2026-03-17 17:38:25
batch processing time: 0.43s, Progress: 25.0%

Processing batch 2/4 for peptide FLNGSCGSV - 2026-03-17 17:38:25
batch processing time: 0.36s, Progress: 50.0%

Processing batch 3/4 for peptide FLNGSCGSV - 2026-03-17 17:38:26
batch processing time: 0.36s, Progress: 75.0%

Processing batch 4/4 for peptide FLNGSCGSV - 2026-03-17 17:38:26
batch processing time: 0.29s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/FLNGSCGSV.parquet

Total time for peptide FLNGSCGSV: 1.78s

Processing peptide: FLTENLLLY on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide FLTENLLLY - 2026-03-17 17:38:27
batch processing time: 0.40s, Progress: 25.0%

Processing batch 2/4 for peptide FLTENLLLY - 2026-03-17 17:38:27
batch processing time: 0.44s, Progress: 50.0%

Processing batch 3/4 for peptide FLTENLLLY - 2026-03-17 17:38:28
batch processing time: 0.43s, Progress: 75.0%

Processing batch 4/4 for peptide FLTENLLLY - 2026-03-17 17:38:28
batch processing time: 0.33s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/FLTENLLLY.parquet

Total time for peptide FLTENLLLY: 1.94s

Processing peptide: HLMSFPQSA on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide HLMSFPQSA - 2026-03-17 17:38:29
batch processing time: 0.44s, Progress: 25.0%

Processing batch 2/4 for peptide HLMSFPQSA - 2026-03-17 17:38:29
batch processing time: 0.43s, Progress: 50.0%

Processing batch 3/4 for peptide HLMSFPQSA - 2026-03-17 17:38:30
batch processing time: 0.43s, Progress: 75.0%

Processing batch 4/4 for peptide HLMSFPQSA - 2026-03-17 17:38:30
batch processing time: 2.42s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/HLMSFPQSA.parquet

Total time for peptide HLMSFPQSA: 4.04s

Processing peptide: HLVEALYLV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide HLVEALYLV - 2026-03-17 17:38:33
batch processing time: 0.48s, Progress: 25.0%

Processing batch 2/4 for peptide HLVEALYLV - 2026-03-17 17:38:33
batch processing time: 0.47s, Progress: 50.0%

Processing batch 3/4 for peptide HLVEALYLV - 2026-03-17 17:38:34
batch processing time: 0.38s, Progress: 75.0%

Processing batch 4/4 for peptide HLVEALYLV - 2026-03-17 17:38:34
batch processing time: 0.28s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/HLVEALYLV.parquet

Total time for peptide HLVEALYLV: 1.96s

Processing peptide: HMTEVVRHC on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide HMTEVVRHC - 2026-03-17 17:38:35
batch processing time: 0.36s, Progress: 25.0%

Processing batch 2/4 for peptide HMTEVVRHC - 2026-03-17 17:38:35
batch processing time: 0.40s, Progress: 50.0%

Processing batch 3/4 for peptide HMTEVVRHC - 2026-03-17 17:38:36
batch processing time: 0.42s, Progress: 75.0%

Processing batch 4/4 for peptide HMTEVVRHC - 2026-03-17 17:38:36
batch processing time: 0.32s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/HMTEVVRHC.parquet

Total time for peptide HMTEVVRHC: 1.83s

Processing peptide: HYPYRLWHY on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide HYPYRLWHY - 2026-03-17 17:38:37
batch processing time: 0.46s, Progress: 25.0%

Processing batch 2/4 for peptide HYPYRLWHY - 2026-03-17 17:38:37
batch processing time: 0.44s, Progress: 50.0%

Processing batch 3/4 for peptide HYPYRLWHY - 2026-03-17 17:38:38
batch processing time: 0.43s, Progress: 75.0%

Processing batch 4/4 for peptide HYPYRLWHY - 2026-03-17 17:38:38
batch processing time: 0.32s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/HYPYRLWHY.parquet

Total time for peptide HYPYRLWHY: 1.98s

Processing peptide: ILDTAGKEEY on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide ILDTAGKEEY - 2026-03-17 17:38:39
batch processing time: 0.45s, Progress: 25.0%

Processing batch 2/4 for peptide ILDTAGKEEY - 2026-03-17 17:38:39
batch processing time: 0.35s, Progress: 50.0%

Processing batch 3/4 for peptide ILDTAGKEEY - 2026-03-17 17:38:40
batch processing time: 0.36s, Progress: 75.0%

Processing batch 4/4 for peptide ILDTAGKEEY - 2026-03-17 17:38:40
batch processing time: 0.27s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/ILDTAGKEEY.parquet

Total time for peptide ILDTAGKEEY: 1.76s

Processing peptide: IPVAYRKVL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide IPVAYRKVL - 2026-03-17 17:38:41
batch processing time: 0.37s, Progress: 25.0%

Processing batch 2/4 for peptide IPVAYRKVL - 2026-03-17 17:38:41
batch processing time: 0.44s, Progress: 50.0%

Processing batch 3/4 for peptide IPVAYRKVL - 2026-03-17 17:38:41
batch processing time: 0.44s, Progress: 75.0%

Processing batch 4/4 for peptide IPVAYRKVL - 2026-03-17 17:38:42
batch processing time: 0.33s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/IPVAYRKVL.parquet

Total time for peptide IPVAYRKVL: 1.90s

Processing peptide: IYLDLPWYL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide IYLDLPWYL - 2026-03-17 17:38:43
batch processing time: 0.45s, Progress: 25.0%

Processing batch 2/4 for peptide IYLDLPWYL - 2026-03-17 17:38:43
batch processing time: 0.44s, Progress: 50.0%

Processing batch 3/4 for peptide IYLDLPWYL - 2026-03-17 17:38:44
batch processing time: 0.43s, Progress: 75.0%

Processing batch 4/4 for peptide IYLDLPWYL - 2026-03-17 17:38:44
batch processing time: 0.32s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/IYLDLPWYL.parquet

Total time for peptide IYLDLPWYL: 1.97s

Processing peptide: KASEKIFYV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide KASEKIFYV - 2026-03-17 17:38:45
batch processing time: 0.45s, Progress: 25.0%

Processing batch 2/4 for peptide KASEKIFYV - 2026-03-17 17:38:45
batch processing time: 0.36s, Progress: 50.0%

Processing batch 3/4 for peptide KASEKIFYV - 2026-03-17 17:38:46
batch processing time: 0.36s, Progress: 75.0%

Processing batch 4/4 for peptide KASEKIFYV - 2026-03-17 17:38:46
batch processing time: 0.27s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/KASEKIFYV.parquet

Total time for peptide KASEKIFYV: 1.77s

Processing peptide: KIVALGINAV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide KIVALGINAV - 2026-03-17 17:38:46
batch processing time: 0.47s, Progress: 25.0%

Processing batch 2/4 for peptide KIVALGINAV - 2026-03-17 17:38:47
batch processing time: 0.42s, Progress: 50.0%

Processing batch 3/4 for peptide KIVALGINAV - 2026-03-17 17:38:47
batch processing time: 0.43s, Progress: 75.0%

Processing batch 4/4 for peptide KIVALGINAV - 2026-03-17 17:38:48
batch processing time: 0.32s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/KIVALGINAV.parquet

Total time for peptide KIVALGINAV: 1.97s

Processing peptide: LIDFYLCFL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide LIDFYLCFL - 2026-03-17 17:38:48
batch processing time: 0.45s, Progress: 25.0%

Processing batch 2/4 for peptide LIDFYLCFL - 2026-03-17 17:38:49
batch processing time: 0.43s, Progress: 50.0%

Processing batch 3/4 for peptide LIDFYLCFL - 2026-03-17 17:38:49
batch processing time: 0.43s, Progress: 75.0%

Processing batch 4/4 for peptide LIDFYLCFL - 2026-03-17 17:38:50
batch processing time: 0.27s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/LIDFYLCFL.parquet

Total time for peptide LIDFYLCFL: 1.90s

Processing peptide: LIIMRTFKV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide LIIMRTFKV - 2026-03-17 17:38:50
batch processing time: 0.37s, Progress: 25.0%

Processing batch 2/4 for peptide LIIMRTFKV - 2026-03-17 17:38:51
batch processing time: 0.36s, Progress: 50.0%

Processing batch 3/4 for peptide LIIMRTFKV - 2026-03-17 17:38:51
batch processing time: 0.35s, Progress: 75.0%

Processing batch 4/4 for peptide LIIMRTFKV - 2026-03-17 17:38:52
batch processing time: 0.32s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/LIIMRTFKV.parquet

Total time for peptide LIIMRTFKV: 1.73s

Processing peptide: LLLDRLNQL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide LLLDRLNQL - 2026-03-17 17:38:52
batch processing time: 0.45s, Progress: 25.0%

Processing batch 2/4 for peptide LLLDRLNQL - 2026-03-17 17:38:53
batch processing time: 0.44s, Progress: 50.0%

Processing batch 3/4 for peptide LLLDRLNQL - 2026-03-17 17:38:53
batch processing time: 0.43s, Progress: 75.0%

Processing batch 4/4 for peptide LLLDRLNQL - 2026-03-17 17:38:54
batch processing time: 0.33s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/LLLDRLNQL.parquet

Total time for peptide LLLDRLNQL: 1.97s

Processing peptide: LLNKHIDAY on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide LLNKHIDAY - 2026-03-17 17:38:54
batch processing time: 0.45s, Progress: 25.0%

Processing batch 2/4 for peptide LLNKHIDAY - 2026-03-17 17:38:55
batch processing time: 0.44s, Progress: 50.0%

Processing batch 3/4 for peptide LLNKHIDAY - 2026-03-17 17:38:55
batch processing time: 0.42s, Progress: 75.0%

Processing batch 4/4 for peptide LLNKHIDAY - 2026-03-17 17:38:56
batch processing time: 0.31s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/LLNKHIDAY.parquet

Total time for peptide LLNKHIDAY: 1.95s

Processing peptide: LMCQPILLL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide LMCQPILLL - 2026-03-17 17:38:56
batch processing time: 0.45s, Progress: 25.0%

Processing batch 2/4 for peptide LMCQPILLL - 2026-03-17 17:38:57
batch processing time: 0.40s, Progress: 50.0%

Processing batch 3/4 for peptide LMCQPILLL - 2026-03-17 17:38:57
batch processing time: 0.40s, Progress: 75.0%

Processing batch 4/4 for peptide LMCQPILLL - 2026-03-17 17:38:58
batch processing time: 0.31s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/LMCQPILLL.parquet

Total time for peptide LMCQPILLL: 1.88s

Processing peptide: LMIERFVSL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide LMIERFVSL - 2026-03-17 17:38:58
batch processing time: 0.46s, Progress: 25.0%

Processing batch 2/4 for peptide LMIERFVSL - 2026-03-17 17:38:59
batch processing time: 0.44s, Progress: 50.0%

Processing batch 3/4 for peptide LMIERFVSL - 2026-03-17 17:38:59
batch processing time: 0.43s, Progress: 75.0%

Processing batch 4/4 for peptide LMIERFVSL - 2026-03-17 17:39:00
batch processing time: 0.31s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/LMIERFVSL.parquet

Total time for peptide LMIERFVSL: 1.96s

Processing peptide: LMNVLTLVY on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide LMNVLTLVY - 2026-03-17 17:39:00
batch processing time: 0.45s, Progress: 25.0%

Processing batch 2/4 for peptide LMNVLTLVY - 2026-03-17 17:39:01
batch processing time: 0.47s, Progress: 50.0%

Processing batch 3/4 for peptide LMNVLTLVY - 2026-03-17 17:39:01
batch processing time: 0.47s, Progress: 75.0%

Processing batch 4/4 for peptide LMNVLTLVY - 2026-03-17 17:39:02
batch processing time: 0.34s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/CASE4_meta/LMNVLTLVY.parquet

Total time for peptide LMNVLTLVY: 2.09s

Processing peptide: LPFDKATIM on device: cuda:0
Positive TCRs: 4, Negative TCRs: 37457
Total batches: 4
Query data size: 37461

Processing batch 1/4 for peptide LPFDKATIM - 2026-03-17 17:39:02
batch processing time: 0.46s, Progress: 25.0%

Processing batch 2/4 for peptide LPFDKATIM - 2026-03-17 17:39:03
batch processing time: 0.43s, Progress: 50.0%

Processing batch 3/4 for peptide LPFDKATIM - 2026-03-17 17:39:03
batch processing time: 0.42s, Progress: 75.0%

Processing batch 4/4 for peptide LPFDKATIM - 2026-03-17 17:39:04
batch processing time: 0.32s, Progress: 100.0%

In [23]:
import os
import pandas as pd

PARQUET_DIR = "../inference/PanPep_Weight_Inference/CASE4_meta"
CSV_PATH = "../data/fig5/reshuffling_zero_0.csv"

OUTPUT_DIR = "./result"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "CASE4_meta_scored.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

csv_df = pd.read_csv(CSV_PATH)

if "label" in csv_df.columns:
    csv_df = csv_df.rename(columns={"label": "Label"})

peptides = csv_df["peptide"].unique()

results = []
for pep in peptides:
    parquet_path = os.path.join(PARQUET_DIR, f"{pep}.parquet")
    if not os.path.exists(parquet_path):
        print(f"[SKIP] No parquet for {pep}")
        continue

    parquet_df = pd.read_parquet(parquet_path)[["CDR3", "Score"]].rename(
        columns={"CDR3": "binding_TCR"}
    )

    pep_rows = csv_df[csv_df["peptide"] == pep].copy()
    merged = pep_rows.merge(parquet_df, on="binding_TCR", how="left")
    results.append(merged)

    print(f"[OK] {pep}: {len(merged)} rows, {merged['Score'].notna().sum()} scored")

if results:
    final_df = pd.concat(results, ignore_index=True)
    final_df.to_csv(OUTPUT_PATH, index=False)

    print(f"\nSaved to {OUTPUT_PATH}")
    print(f"Total rows: {len(final_df)}, scored: {final_df['Score'].notna().sum()}")
else:
    print("No results to save.")

[OK] AALALLLLDRLNQLE: 6 rows, 6 scored
[OK] AALPILFQV: 2 rows, 2 scored
[OK] AAQNVHFWKALNQL: 2 rows, 2 scored
[OK] AAQRIHFFKNLSLL: 2 rows, 2 scored
[OK] AARAVFLAL: 6 rows, 6 scored
[OK] AAVVRFQEAANKQKQ: 4 rows, 4 scored
[OK] ADGLAYFRSSFKGG: 2 rows, 2 scored
[OK] ADTLQSIGATTVASN: 8 rows, 8 scored
[OK] AENPVVHFFKNIATPR: 2 rows, 2 scored
[OK] AFLLFLVLI: 2 rows, 2 scored
[OK] AGSLQPLAL: 2 rows, 2 scored
[OK] AGSLQPLALE: 2 rows, 2 scored
[OK] AHIQWMVMF: 2 rows, 2 scored
[OK] AHPADPGSRPHLIRLFSRDA: 2 rows, 2 scored
[OK] AIILASFSA: 2 rows, 2 scored
[OK] AIKLDDKDP: 2 rows, 2 scored
[OK] AIMTRCLAV: 4 rows, 4 scored
[OK] AISRKMVELVHFLLLKYRAR: 4 rows, 4 scored
[OK] ALALLLLDR: 4 rows, 4 scored
[OK] ALASCMGLI: 2 rows, 2 scored
[OK] ALASCMGLIY: 8 rows, 8 scored
[OK] ALAVLHFYPDKGAKN: 2 rows, 2 scored
[OK] ALDPHSGHFV: 6 rows, 6 scored
[OK] ALEPGPVTA: 2 rows, 2 scored
[OK] ALHGGWTTK: 4 rows, 4 scored
[OK] ALLADKFPV: 2 rows, 2 scored
[OK] ALLETLSLLL: 2 rows, 2 scored
[OK] ALLLQLFTL: 2 rows, 2 scored
[OK] ALLPGLPAA: 8 rows, 8 scored
[OK] ALLSDLQDL: 2 rows, 2 scored
[OK] ALNLGETFV: 4 rows, 4 scored
[OK] ALNNIINNA: 4 rows, 4 scored
[OK] ALNTLVKQL: 4 rows, 4 scored
[OK] ALNTPKDHI: 2 rows, 2 scored
[OK] ALPETTADI: 2 rows, 2 scored
[OK] ALQIPFAMQM: 2 rows, 2 scored
[OK] ALSGVFCGV: 2 rows, 2 scored
[OK] ALTAVAEEV: 4 rows, 4 scored
[OK] ALWGFFPVL: 2 rows, 2 scored
[OK] ALWMRLLPLL: 2 rows, 2 scored
[OK] ALYYPSARI: 2 rows, 2 scored
[OK] AMDEFIEQY: 2 rows, 2 scored
[OK] AMDEFIERY: 4 rows, 4 scored
[OK] AMMFTSDLA: 2 rows, 2 scored
[OK] AMQTMLFTM: 6 rows, 6 scored
[OK] ANPVVHFFKNIVTPR: 2 rows, 2 scored
[OK] APARLERRHSA: 6 rows, 6 scored
[OK] APATVCGPK: 2 rows, 2 scored
[OK] APFSEQEQPVLG: 4 rows, 4 scored
[OK] APHGVVFLH: 2 rows, 2 scored
[OK] APISAMVRM: 2 rows, 2 scored
[OK] APLLSAGVF: 4 rows, 4 scored
[OK] APMPMPELPYP: 2 rows, 2 scored
[OK] APQPELPYPQPG: 2 rows, 2 scored
[OK] APRITFGGL: 2 rows, 2 scored
[OK] APSGEGSFQPSQENPQ: 2 rows, 2 scored
[OK] APTKVTFGV: 2 rows, 2 scored
[OK] AQWGPDPAAA: 4 rows, 4 scored
[OK] ARSVFHFFRGTALL: 2 rows, 2 scored
[OK] ASQARPSQR: 2 rows, 2 scored
[OK] ASQFRPSQR: 2 rows, 2 scored
[OK] ASQKRPSQR: 4 rows, 4 scored
[OK] ASQKRPSQRS: 2 rows, 2 scored
[OK] ASQYRPSQR: 2 rows, 2 scored
[OK] ATDTTSGTYKYIFGTGTRLKVLA: 2 rows, 2 scored
[OK] ATEGRVRVNSAYQDK: 2 rows, 2 scored
[OK] ATGFKQSSKALQRPVAS: 2 rows, 2 scored
[OK] ATRGATVVI: 2 rows, 2 scored
[OK] ATSRMLSYY: 2 rows, 2 scored
[OK] ATSRTLSYY: 2 rows, 2 scored
[OK] AVGVGKSAL: 2 rows, 2 scored
[OK] AVIKTLQPV: 2 rows, 2 scored
[OK] AVLDMCASL: 2 rows, 2 scored
[OK] AVVQSELPYPEGS: 2 rows, 2 scored
[OK] AVYDGREHTV: 2 rows, 2 scored
[OK] CFAYYFMRF: 2 rows, 2 scored
[OK] CISSCNPNL: 2 rows, 2 scored
[OK] CLAYYFMRF: 4 rows, 4 scored
[OK] CLEASFNYL: 6 rows, 6 scored
[OK] CLGSLIYST: 2 rows, 2 scored
[OK] CLTPVYSFL: 6 rows, 6 scored
[OK] CPACYNSEV: 6 rows, 6 scored
[OK] CPRERPEEL: 2 rows, 2 scored
[OK] CTDDNALAY: 2 rows, 2 scored
[OK] CTDDNALAYY: 6 rows, 6 scored
[OK] CVMYASAVV: 2 rows, 2 scored
[OK] DDKDPQFKD: 4 rows, 4 scored
[OK] DEPLTSLTPRCNTAWNRLKL: 4 rows, 4 scored
[OK] DFARVHFISALHGSG: 2 rows, 2 scored
[OK] DFHFEVFNFVPCSI: 8 rows, 8 scored
[OK] DKDPQFKDN: 2 rows, 2 scored
[OK] DKSMKVTVAFNQF: 8 rows, 8 scored
[OK] DLAGIGILTV: 2 rows, 2 scored
[OK] DLFMRIFTI: 2 rows, 2 scored
[OK] DLTSFLLSL: 2 rows, 2 scored
[OK] DNVILLNKH: 2 rows, 2 scored
[OK] DPIVRGLLARAA: 2 rows, 2 scored
[OK] DPLIRGLLARPA: 2 rows, 2 scored
[OK] DQVILLNKH: 6 rows, 6 scored
[OK] DRLNQLESK: 2 rows, 2 scored
[OK] DTLEKISNEIKIVATP: 8 rows, 8 scored
[OK] DVSKVHFFKGNGQT: 2 rows, 2 scored
[OK] DYKHYTPSF: 2 rows, 2 scored
[OK] DYTEISFML: 2 rows, 2 scored
[OK] EAKQKGFVPF: 6 rows, 6 scored
[OK] EAPVVHFFKNIVTPR: 2 rows, 2 scored
[OK] EEAAGIGIL: 2 rows, 2 scored
[OK] EFTVSGNIL: 2 rows, 2 scored
[OK] EGHLKRNIV: 4 rows, 4 scored
[OK] EGPRNQDWL: 2 rows, 2 scored
[OK] EGSRNQDWL: 2 rows, 2 scored
[OK] EIAGIGILTV: 2 rows, 2 scored
[OK] EIDPKLDNY: 2 rows, 2 scored
[OK] EIFDRYGEEV: 4 rows, 4 scored
[OK] EIRTQYEAM: 2 rows, 2 scored
[OK] EKPKFEAYKAAAAPA: 2 rows, 2 scored
[OK] EKPKVEAYKAAAAPA: 2 rows, 2 scored
[OK] EKPKYEAYKAAAAPA: 2 rows, 2 scored
[OK] ELAAIGILTV: 2 rows, 2 scored
[OK] ELAGIAILTV: 2 rows, 2 scored
[OK] ELAGIGIATV: 2 rows, 2 scored
[OK] ELAGIGIITV: 2 rows, 2 scored
[OK] ELAGIGILAV: 2 rows, 2 scored
[OK] ELAGIGILSV: 2 rows, 2 scored
[OK] ELAGIGILTA: 2 rows, 2 scored
[OK] ELAGIGILTI: 2 rows, 2 scored
[OK] ELAGIGLLTV: 2 rows, 2 scored
[OK] ELGGIGILTV: 2 rows, 2 scored
[OK] ELTSMKYFV: 4 rows, 4 scored
[OK] ELYHYQECV: 4 rows, 4 scored
[OK] ELYSPIFLI: 6 rows, 6 scored
[OK] EMLFSHGLVK: 2 rows, 2 scored
[OK] EMMLFDWKV: 2 rows, 2 scored
[OK] ENAVVHFFKNIVTPR: 2 rows, 2 scored
[OK] ENAVVHFFRSLVSS: 2 rows, 2 scored
[OK] ENPAVHFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVAHFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVDFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFFKAIVTPR: 2 rows, 2 scored
[OK] ENPVVHFFKDIVTPR: 2 rows, 2 scored
[OK] ENPVVHFFKNAVTPR: 2 rows, 2 scored
[OK] ENPVVHFFKNIVAPR: 2 rows, 2 scored
[OK] ENPVVHFFKNIVTAR: 2 rows, 2 scored
[OK] ENPVVHFFKNIVTP: 4 rows, 4 scored
[OK] ENPVVHFFKNIVTPA: 2 rows, 2 scored
[OK] ENPVVHFFKNIVTPR: 4 rows, 4 scored
[OK] ENPVVHFFRNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFHKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFIKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFMKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFVKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFWKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHFYKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHGFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHMFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVHYFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVIFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVLFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVMFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVNFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVRFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVTFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVVFFKNIVTPR: 2 rows, 2 scored
[OK] ENPVVWFFKNIVTPR: 2 rows, 2 scored
[OK] ESDPIVAQY: 2 rows, 2 scored
[OK] ESITGSLGPLL: 2 rows, 2 scored
[OK] ETALALLLL: 2 rows, 2 scored
[OK] EVDPIGHLY: 2 rows, 2 scored
[OK] EVKEKGMAA: 2 rows, 2 scored
[OK] EVLPFFLFF: 2 rows, 2 scored
[OK] FAFACPDGV: 6 rows, 6 scored
[OK] FAFPFTIYS: 4 rows, 4 scored
[OK] FAMQMAYRF: 6 rows, 6 scored
[OK] FAPGFFPYL: 2 rows, 2 scored
[OK] FATGIGIITV: 2 rows, 2 scored
[OK] FEDLRVLSF: 2 rows, 2 scored
[OK] FFAGGIGIRTI: 2 rows, 2 scored
[OK] FGDHPGHSY: 2 rows, 2 scored
[OK] FGDVGSTLF: 2 rows, 2 scored
[OK] FGVKIHFFKQRNSL: 2 rows, 2 scored
[OK] FIAGLIAIV: 6 rows, 6 scored
[OK] FIDIKRGVY: 2 rows, 2 scored
[OK] FIDTKRGVY: 2 rows, 2 scored
[OK] FISTCACEI: 4 rows, 4 scored
[OK] FITESKPSV: 6 rows, 6 scored
[OK] FKDNVILLN: 4 rows, 4 scored
[OK] FLAFVVFLL: 4 rows, 4 scored
[OK] FLAGGIGIRTL: 2 rows, 2 scored
[OK] FLCLFLLPS: 4 rows, 4 scored
[OK] FLCWHTNCY: 8 rows, 8 scored
[OK] FLCWHTSCY: 2 rows, 2 scored
[OK] FLDGSCGSV: 4 rows, 4 scored
[OK] FLEGETLPT: 2 rows, 2 scored
[OK] FLEYHDVRV: 2 rows, 2 scored
[OK] FLFAVGFYL: 2 rows, 2 scored
[OK] FLGIITTVA: 4 rows, 4 scored
[OK] FLGKIWPSYK: 8 rows, 8 scored
[OK] FLGRYMSAL: 2 rows, 2 scored
[OK] FLIGCNYLG: 4 rows, 4 scored
[OK] FLKKDAPYI: 2 rows, 2 scored
[OK] FLKKFHFLKGATLC: 2 rows, 2 scored
[OK] FLLPSLATV: 4 rows, 4 scored
[OK] FLNGSCGSV: 8 rows, 8 scored
[OK] FLNKVVSTT: 4 rows, 4 scored
[OK] FLPFAMGII: 2 rows, 2 scored
[OK] FLPFFSDVT: 4 rows, 4 scored
[OK] FLQDVMNIL: 2 rows, 2 scored
[OK] FLRDGWEIV: 2 rows, 2 scored
[OK] FLTENLLLY: 8 rows, 8 scored
[OK] FLTGIGIITV: 2 rows, 2 scored
[OK] FLVLLPLVS: 6 rows, 6 scored
[OK] FLVRSFYL: 2 rows, 2 scored
[OK] FLWLLWPVT: 4 rows, 4 scored
[OK] FLYENAFLP: 2 rows, 2 scored
[OK] FMCVEYCPI: 4 rows, 4 scored
[OK] FMGVTYEM: 2 rows, 2 scored
[OK] FMIDVQQWG: 4 rows, 4 scored
[OK] FMPDFDLHL: 2 rows, 2 scored
[OK] FMSEAKCWT: 2 rows, 2 scored
[OK] FNNFTVSFWLRVPKVSASHLE: 6 rows, 6 scored
[OK] FPDLNGDVV: 2 rows, 2 scored
[OK] FPFTSFGPL: 2 rows, 2 scored
[OK] FPLCANGQV: 4 rows, 4 scored
[OK] FPLKLRGTA: 2 rows, 2 scored
[OK] FPNITNLCP: 2 rows, 2 scored
[OK] FPQPEQPFPWQP: 6 rows, 6 scored
[OK] FPQSAPHGVVF: 2 rows, 2 scored
[OK] FQDYIKSYL: 2 rows, 2 scored
[OK] FSASTSAFV: 2 rows, 2 scored
[OK] FSAVGDICY: 2 rows, 2 scored
[OK] FSDVTWFHA: 2 rows, 2 scored
[OK] FSLKKGAAA: 2 rows, 2 scored
[OK] FSNVTWFHA: 2 rows, 2 scored
[OK] FSVVGNICY: 2 rows, 2 scored
[OK] FSWGAEGQRPGF: 2 rows, 2 scored
[OK] FSWGAEGQRPGFG: 2 rows, 2 scored
[OK] FSWGAEGQRPGFGSGG: 2 rows, 2 scored
[OK] FTISVTTEI: 2 rows, 2 scored
[OK] FTPLVPFWI: 4 rows, 4 scored
[OK] FVAAIFYLI: 4 rows, 4 scored
[OK] FVCDNIKFA: 6 rows, 6 scored
[OK] FVDGVPFVV: 2 rows, 2 scored
[OK] FVFPLNSII: 2 rows, 2 scored
[OK] FVLAAVYRI: 4 rows, 4 scored
[OK] FVMMSAPPA: 4 rows, 4 scored
[OK] FVNEFYAYL: 4 rows, 4 scored
[OK] FVSEETGTL: 4 rows, 4 scored
[OK] FVTVYSHLL: 4 rows, 4 scored
[OK] FVVFLLVTL: 4 rows, 4 scored
[OK] FVVPYMIYLL: 2 rows, 2 scored
[OK] FWIDLFETIG: 4 rows, 4 scored
[OK] FWITIAYII: 2 rows, 2 scored
[OK] FWLLGAWAL: 2 rows, 2 scored
[OK] FWLLPAWAL: 2 rows, 2 scored
[OK] FYWFFSNYL: 4 rows, 4 scored
[OK] GADGVGKSAL: 6 rows, 6 scored
[OK] GAHCIHFFKSAVCR: 2 rows, 2 scored
[OK] GAIKLDDKD: 2 rows, 2 scored
[OK] GAMKRHGLDNYRGYSLG: 2 rows, 2 scored
[OK] GARGVGKSAL: 2 rows, 2 scored
[OK] GAVGVGKSAL: 4 rows, 4 scored
[OK] GDAALALLL: 2 rows, 2 scored
[OK] GEEDGAGGHSL: 2 rows, 2 scored
[OK] GGETALALL: 4 rows, 4 scored
[OK] GIIAMSAFA: 6 rows, 6 scored
[OK] GILEFVFTL: 2 rows, 2 scored
[OK] GILGLVFTL: 2 rows, 2 scored
[OK] GLALYYPSA: 6 rows, 6 scored
[OK] GLFKDCSKV: 6 rows, 6 scored
[OK] GLIAIVMVT: 4 rows, 4 scored
[OK] GLMWLSYFI: 6 rows, 6 scored
[OK] GLMWLSYFV: 4 rows, 4 scored
[OK] GLNDNLLEI: 2 rows, 2 scored
[OK] GLPWNVVRI: 6 rows, 6 scored
[OK] GLSPNLNRFL: 2 rows, 2 scored
[OK] GLTVLPPLL: 4 rows, 4 scored
[OK] GMDYHNGHL: 2 rows, 2 scored
[OK] GPKVKQWPL: 4 rows, 4 scored
[OK] GPQQSFPEQEA: 2 rows, 2 scored
[OK] GQVELGGGNAVEVCKGS: 1000 rows, 1000 scored
[OK] GQVELGGGPGAESCQ: 2 rows, 2 scored
[OK] GQVELGGGSSPETCI: 2 rows, 2 scored
[OK] GQVELGGGTPIESCQ: 2 rows, 2 scored
[OK] GQVMVVAPR: 4 rows, 4 scored
[OK] GSEHSLAEY: 2 rows, 2 scored
[OK] GSLQPLALEGSLQKRGIV: 2 rows, 2 scored
[OK] GTDLEGNFY: 6 rows, 6 scored
[OK] GVYALIAGA: 6 rows, 6 scored
[OK] GVYDGREHTV: 4 rows, 4 scored
[OK] GVYDYLVST: 6 rows, 6 scored
[OK] GYNSYSVSNSEKHIM: 4 rows, 4 scored
[OK] HARIKLKV: 2 rows, 2 scored
[OK] HENVVHFFKDGELV: 2 rows, 2 scored
[OK] HFISNSWLM: 2 rows, 2 scored
[OK] HGAIKLDDK: 2 rows, 2 scored
[OK] HHLWAYRDLQTRKDIRNAAWHKHGW: 2 rows, 2 scored
[OK] HLCGSHLVEA: 2 rows, 2 scored
[OK] HLLLVAAGL: 2 rows, 2 scored
[OK] HLMSFPQSA: 8 rows, 8 scored
[OK] HLRMAGHSL: 2 rows, 2 scored
[OK] HLVEALYLV: 8 rows, 8 scored
[OK] HMLSFHFWKSRGQT: 2 rows, 2 scored
[OK] HMTEVVRHC: 8 rows, 8 scored
[OK] HPRYFNQL: 4 rows, 4 scored
[OK] HQNPVTGLLL: 2 rows, 2 scored
[OK] HRAKLHFFKDENLK: 2 rows, 2 scored
[OK] HRRGSRSYV: 2 rows, 2 scored
[OK] HSDKFTDGV: 4 rows, 4 scored
[OK] HSYFTSDYY: 2 rows, 2 scored
[OK] HTDLMAAYV: 2 rows, 2 scored
[OK] HYNYMCNSSCMGSMN: 4 rows, 4 scored
[OK] HYPYRLWHY: 8 rows, 8 scored
[OK] IAGLGLLTV: 2 rows, 2 scored
[OK] IEAAIHFYKGLAVY: 2 rows, 2 scored
[OK] IFFITGNTL: 2 rows, 2 scored
[OK] IFLWLLWPV: 2 rows, 2 scored
[OK] IIPAFHFLKSEKGL: 2 rows, 2 scored
[OK] IITTDNTFV: 2 rows, 2 scored
[OK] IKLDDKDPN: 4 rows, 4 scored
[OK] IKLDDKDPQ: 4 rows, 4 scored
[OK] ILAAFLHWL: 2 rows, 2 scored
[OK] ILAKFAHWL: 2 rows, 2 scored
[OK] ILAYCNKTV: 6 rows, 6 scored
[OK] ILDQVPFSV: 4 rows, 4 scored
[OK] ILDTAGKEEY: 8 rows, 8 scored
[OK] ILFTRFFYV: 6 rows, 6 scored
[OK] ILGALLSIL: 6 rows, 6 scored
[OK] ILGGQVVHTV: 4 rows, 4 scored
[OK] ILGLPTQTV: 2 rows, 2 scored
[OK] ILLLDQALV: 2 rows, 2 scored
[OK] ILLWQPIPV: 2 rows, 2 scored
[OK] ILMHCQTTL: 4 rows, 4 scored
[OK] ILMNDQEVGV: 2 rows, 2 scored
[OK] ILPDPSKPS: 2 rows, 2 scored
[OK] ILRKGGRTI: 2 rows, 2 scored
[OK] ILTSLLVLV: 2 rows, 2 scored
[OK] ILYCKRASLTELVSPRLPSHLSEYE: 4 rows, 4 scored
[OK] IPAAAGRFF: 2 rows, 2 scored
[OK] IPIQASLPF: 6 rows, 6 scored
[OK] IPLTEEAEL: 4 rows, 4 scored
[OK] IPLTTAAKL: 2 rows, 2 scored
[OK] IPLTTSSKL: 2 rows, 2 scored
[OK] IPRRNVATL: 6 rows, 6 scored
[OK] IPTITQMNL: 4 rows, 4 scored
[OK] IPVAYRKVL: 8 rows, 8 scored
[OK] IPVAYRNVL: 6 rows, 6 scored
[OK] IQPGQTFSV: 2 rows, 2 scored
[OK] ISDYDYYRY: 6 rows, 6 scored
[OK] ISQWLTNIF: 2 rows, 2 scored
[OK] ITFDNLKTL: 4 rows, 4 scored
[OK] ITNFKSVLY: 2 rows, 2 scored
[OK] ITREEKPAVTAAPKK: 2 rows, 2 scored
[OK] ITSGWTFGA: 2 rows, 2 scored
[OK] IVDTVSALV: 2 rows, 2 scored
[OK] IVNSVLLFL: 2 rows, 2 scored
[OK] IYLDLPWYL: 8 rows, 8 scored
[OK] KALARALKEGRIR: 2 rows, 2 scored
[OK] KASEKIFYV: 8 rows, 8 scored
[OK] KAYDVTQAF: 2 rows, 2 scored
[OK] KCNTATCATQRLANFLVRSS: 4 rows, 4 scored
[OK] KDNVILLNK: 6 rows, 6 scored
[OK] KDPQFKDNV: 2 rows, 2 scored
[OK] KIADPICTFI: 2 rows, 2 scored
[OK] KIILFLALI: 4 rows, 4 scored
[OK] KISEMHPAL: 2 rows, 2 scored
[OK] KITEHSWNA: 6 rows, 6 scored
[OK] KIVALGINAV: 8 rows, 8 scored
[OK] KIYSKHTPI: 2 rows, 2 scored
[OK] KLDDKDPNF: 2 rows, 2 scored
[OK] KLDDKDPQF: 2 rows, 2 scored
[OK] KLDGFMGRI: 6 rows, 6 scored
[OK] KLEFMDWRL: 2 rows, 2 scored
[OK] KLEQLDWTV: 2 rows, 2 scored
[OK] KLFEFLVHGV: 6 rows, 6 scored
[OK] KLIEYTDFA: 2 rows, 2 scored
[OK] KLLKSIAAT: 2 rows, 2 scored
[OK] KLMPVCVET: 2 rows, 2 scored
[OK] KLNIKLLGV: 6 rows, 6 scored
[OK] KLNVGDYFV: 2 rows, 2 scored
[OK] KLPDDFMGC: 4 rows, 4 scored
[OK] KLPDDFTGC: 4 rows, 4 scored
[OK] KLPDDFTGCV: 6 rows, 6 scored
[OK] KLSYGIATV: 6 rows, 6 scored
[OK] KLTESLHKV: 2 rows, 2 scored
[OK] KLVALGINNV: 4 rows, 4 scored
[OK] KLVALVINAV: 2 rows, 2 scored
[OK] KLVNKFLAL: 2 rows, 2 scored
[OK] KLVSSFLEM: 2 rows, 2 scored
[OK] KLYGLDWAEL: 6 rows, 6 scored
[OK] KMDYFSGQL: 2 rows, 2 scored
[OK] KMFDAYVNT: 2 rows, 2 scored
[OK] KMGVTYEM: 2 rows, 2 scored
[OK] KMVSLLSVL: 2 rows, 2 scored
[OK] KPADNSLKI: 2 rows, 2 scored
[OK] KPAPRELKV: 2 rows, 2 scored
[OK] KPASRELKV: 2 rows, 2 scored
[OK] KPLPEVKIL: 2 rows, 2 scored
[OK] KPRQKRTAT: 4 rows, 4 scored
[OK] KPVPEVKIL: 2 rows, 2 scored
[OK] KPYIKWDLL: 4 rows, 4 scored
[OK] KQHVCGGSILDPYWVLTAAHCFRKH: 2 rows, 2 scored
[OK] KQLIKVTLV: 4 rows, 4 scored
[OK] KQLPFFYYS: 6 rows, 6 scored
[OK] KQLSSNFGA: 6 rows, 6 scored
[OK] KQWLVWLFL: 4 rows, 4 scored
[OK] KQWLVWLLL: 2 rows, 2 scored
[OK] KRGIVEQCCTSISSL: 2 rows, 2 scored
[OK] KRGIVEQSSTSISSL: 6 rows, 6 scored
[OK] KSVDITFEL: 4 rows, 4 scored
[OK] KVDGVDVEL: 2 rows, 2 scored
[OK] KVDPIGHVY: 2 rows, 2 scored
[OK] KVITFIDL: 2 rows, 2 scored
[OK] KVPRNQDWL: 2 rows, 2 scored
[OK] KVSIWNLDY: 4 rows, 4 scored
[OK] KWPWYIWLG: 4 rows, 4 scored
[OK] LACFVLAAV: 6 rows, 6 scored
[OK] LALWGPDPAA: 6 rows, 6 scored
[OK] LAMPFATPM: 2 rows, 2 scored
[OK] LDDKDPNFK: 2 rows, 2 scored
[OK] LDDKDPQFK: 2 rows, 2 scored
[OK] LDRLNQLES: 2 rows, 2 scored
[OK] LESVVHFLRGQKVT: 2 rows, 2 scored
[OK] LFTRFFYVL: 2 rows, 2 scored
[OK] LGIGVITI: 2 rows, 2 scored
[OK] LIDFYLCFL: 8 rows, 8 scored
[OK] LIIMRTFKV: 8 rows, 8 scored
[OK] LITGRLQSL: 6 rows, 6 scored
[OK] LLDRLNQLE: 2 rows, 2 scored
[OK] LLEDLDWDV: 2 rows, 2 scored
[OK] LLEWLAMAV: 4 rows, 4 scored
[OK] LLFGLALIEV: 2 rows, 2 scored
[OK] LLFGYPVFV: 2 rows, 2 scored
[OK] LLFLMSFTV: 2 rows, 2 scored
[OK] LLFNKVTLA: 6 rows, 6 scored
[OK] LLIDLTSFL: 6 rows, 6 scored
[OK] LLIDLTSFLL: 2 rows, 2 scored
[OK] LLLARAASLSL: 6 rows, 6 scored
[OK] LLLDDFVEI: 2 rows, 2 scored
[OK] LLLDRLNQL: 8 rows, 8 scored
[OK] LLLTILTSL: 2 rows, 2 scored
[OK] LLMEGVPKSL: 4 rows, 4 scored
[OK] LLMPILTLT: 4 rows, 4 scored
[OK] LLNATDIAV: 6 rows, 6 scored
[OK] LLNKHIDAY: 8 rows, 8 scored
[OK] LLNVKLAL: 4 rows, 4 scored
[OK] LLQEYNWEL: 6 rows, 6 scored
[OK] LLSVCLGSL: 4 rows, 4 scored
[OK] LLTNMFTPL: 2 rows, 2 scored
[OK] LLWNTVWNM: 4 rows, 4 scored
[OK] LMCQPILLL: 8 rows, 8 scored
[OK] LMDMHNGQL: 2 rows, 2 scored
[OK] LMDYWQGQL: 2 rows, 2 scored
[OK] LMGHFAWWT: 4 rows, 4 scored
[OK] LMHCQTTL: 2 rows, 2 scored
[OK] LMIERFVSL: 8 rows, 8 scored
[OK] LMMPFSIVYI: 4 rows, 4 scored
[OK] LMNVLTLFY: 2 rows, 2 scored
[OK] LMNVLTLVY: 8 rows, 8 scored
[OK] LMWLIINLV: 2 rows, 2 scored
[OK] LMWLSYFIA: 4 rows, 4 scored
[OK] LNHLKATPI: 6 rows, 6 scored
[OK] LNKHIDAYK: 2 rows, 2 scored
[OK] LNKNIHFFKNLPLP: 2 rows, 2 scored
[OK] LPARTSPM: 2 rows, 2 scored
[OK] LPDDFMGCV: 4 rows, 4 scored
[OK] LPDDFTGCV: 4 rows, 4 scored
[OK] LPEGLPQGQLTAY: 2 rows, 2 scored
[OK] LPEPLPQGGLTAY: 2 rows, 2 scored
[OK] LPFDKATIM: 8 rows, 8 scored
[OK] LPFDKPTIM: 4 rows, 4 scored
[OK] LPFDKSTIM: 8 rows, 8 scored
[OK] LPFDKSTVM: 8 rows, 8 scored
[OK] LPFDKTTIM: 6 rows, 6 scored
[OK] LPFEKSTIM: 4 rows, 4 scored
[OK] LPFEKSTVM: 4 rows, 4 scored
[OK] LPFERATIM: 2 rows, 2 scored
[OK] LPGCDGGSL: 4 rows, 4 scored
[OK] LPKEITVAT: 6 rows, 6 scored
[OK] LPKGIMMNV: 6 rows, 6 scored
[OK] LPNNTASWF: 4 rows, 4 scored
[OK] LPPAYTNSF: 4 rows, 4 scored
[OK] LPPSYTNSF: 2 rows, 2 scored
[OK] LPSYAAFAT: 2 rows, 2 scored
[OK] LPSYAALAT: 8 rows, 8 scored
[OK] LQLGFSTGV: 2 rows, 2 scored
[OK] LQNNELSPV: 2 rows, 2 scored
[OK] LQPFPQPELPYGSGGS: 2 rows, 2 scored
[OK] LSDLQDLKW: 2 rows, 2 scored
[OK] LSDRVVFVL: 2 rows, 2 scored
[OK] LSFKELLVY: 6 rows, 6 scored
[OK] LSPFPFDL: 2 rows, 2 scored
[OK] LSRFSWGAEGQRPGFGYGG: 2 rows, 2 scored
[OK] LTALRLCAY: 2 rows, 2 scored
[OK] LTDEQRAAALEKAAA: 6 rows, 6 scored
[OK] LTGHMLDMY: 2 rows, 2 scored
[OK] LTNDDTSRY: 4 rows, 4 scored
[OK] LTNDNTSRY: 6 rows, 6 scored
[OK] LTSFLLSLF: 2 rows, 2 scored
[OK] LTSHTVMPL: 2 rows, 2 scored
[OK] LTYHGAIKL: 2 rows, 2 scored
[OK] LVGLMWLSY: 2 rows, 2 scored
[OK] LVLSVNPYV: 6 rows, 6 scored
[OK] LVMPFSIVYI: 4 rows, 4 scored
[OK] LVQSTQWSL: 4 rows, 4 scored
[OK] LYALVYFLH: 2 rows, 2 scored
[OK] LYALVYFLQ: 2 rows, 2 scored
[OK] LYPEFIASI: 2 rows, 2 scored
[OK] MASGGGETA: 2 rows, 2 scored
[OK] MCDIRQLLF: 2 rows, 2 scored
[OK] MCDVRQLLF: 2 rows, 2 scored
[OK] MDFARVHFISALHGSG: 2 rows, 2 scored
[OK] MEVDPIGHLY: 2 rows, 2 scored
[OK] MFDAYVNTF: 2 rows, 2 scored
[OK] MFLARGIVF: 4 rows, 4 scored
[OK] MHGNWHFFRNFLSN: 2 rows, 2 scored
[OK] MHQKRTAMFQDPQER: 2 rows, 2 scored
[OK] MHVSFVMAYPEMLAA: 8 rows, 8 scored
[OK] MIAQYTSAL: 2 rows, 2 scored
[OK] MLAKALRKV: 8 rows, 8 scored
[OK] MLFSHGLVK: 2 rows, 2 scored
[OK] MLFTMLRKL: 4 rows, 4 scored
[OK] MLIGIPVYV: 2 rows, 2 scored
[OK] MLNPNYEDL: 4 rows, 4 scored
[OK] MLSILALVRV: 4 rows, 4 scored
[OK] MLWCKDGHV: 2 rows, 2 scored
[OK] MMDFFNAQM: 2 rows, 2 scored
[OK] MMILSDDAV: 8 rows, 8 scored
[OK] MMISAGFSL: 2 rows, 2 scored
[OK] MMWDRGLGMM: 2 rows, 2 scored
[OK] MNASIHFLKALETY: 2 rows, 2 scored
[OK] MPLSAPTLL: 6 rows, 6 scored
[OK] MPNMLRIMA: 2 rows, 2 scored
[OK] MPYGYVLNEF: 2 rows, 2 scored
[OK] MQLFFSYFA: 2 rows, 2 scored
[OK] MQVESDDYI: 8 rows, 8 scored
[OK] MSAFAMMFV: 6 rows, 6 scored
[OK] MSDVKCTSV: 2 rows, 2 scored
[OK] MSQIMYNYPAMLGHA: 4 rows, 4 scored
[OK] MTEYKLVVVGADGVGKSALTIQLI: 2 rows, 2 scored
[OK] MTEYKLVVVGAGDVGKSALTIQLI: 2 rows, 2 scored
[OK] MTEYKLVVVGARGVGKSALTIQLI: 4 rows, 4 scored
[OK] MTEYKLVVVGAVGVGKSALTIQLI: 4 rows, 4 scored
[OK] MVNTVAGAMK: 2 rows, 2 scored
[OK] MVTNNTFTL: 6 rows, 6 scored
[OK] MVWESGCTV: 4 rows, 4 scored
[OK] MVWGPDPLYV: 4 rows, 4 scored
[OK] MYIEMLKSI: 2 rows, 2 scored
[OK] MYTEMLKSI: 2 rows, 2 scored
[OK] NANVLHFLKNIICQ: 2 rows, 2 scored
[OK] NHVVDISKSGLITIA: 2 rows, 2 scored
[OK] NLAQDLATV: 6 rows, 6 scored
[OK] NLAQTDLATV: 2 rows, 2 scored
[OK] NLDAVPTGY: 2 rows, 2 scored
[OK] NLDYIINLI: 2 rows, 2 scored
[OK] NLFLFLFAV: 8 rows, 8 scored
[OK] NLHPDSATL: 2 rows, 2 scored
[OK] NLIDSYFVV: 8 rows, 8 scored
[OK] NLLKDCPAV: 4 rows, 4 scored
[OK] NLQSNHDLY: 2 rows, 2 scored
[OK] NLSDRVVFV: 4 rows, 4 scored
[OK] NMEYMTWDV: 2 rows, 2 scored
[OK] NMLRIMASL: 2 rows, 2 scored
[OK] NMMVTNNTF: 2 rows, 2 scored
[OK] NMMWFQGQL: 2 rows, 2 scored
[OK] NPANNASIV: 2 rows, 2 scored
[OK] NPANNVAIV: 2 rows, 2 scored
[OK] NPQVIHFFKSLDLL: 2 rows, 2 scored
[OK] NPTIQKNVL: 6 rows, 6 scored
[OK] NPVVHFFKNIVTPR: 2 rows, 2 scored
[OK] NSAIGKIQY: 2 rows, 2 scored
[OK] NSKEETGHLENGN: 2 rows, 2 scored
[OK] NSTRFASVY: 4 rows, 4 scored
[OK] NTFSSTFNV: 6 rows, 6 scored
[OK] NTLQCIMLV: 2 rows, 2 scored
[OK] NTLTLAVPY: 2 rows, 2 scored
[OK] NTYGKRNAV: 2 rows, 2 scored
[OK] NVEYYDIKL: 2 rows, 2 scored
[OK] NVILLNKHI: 4 rows, 4 scored
[OK] NVLTLVYKV: 2 rows, 2 scored
[OK] PGISSQHFTYQGGVGGSWPVCSGLG: 2 rows, 2 scored

In [24]:
!{sys.executable} ../metric_calculation/AUC.py \
                    --root_dir ./result \
                    --output_file ./CASE4_meta_auc.csv

Finding CSV files...
Found 1 CSV files
Processed 1/1 files (100.0%)
Failed: 1

In [25]:
import pandas as pd

df = pd.read_csv("./CASE4_meta_auc.csv")
df

,folder_path,file_name,roc_auc,pr_auc,status
0,./result,CASE4_meta_scored.csv,0.303142,0.267378,success
1,./result,[FOLDER_SUMMARY],0.303142,0.267378,success (averaged over 1 files)

### Other method

If you would like to reproduce other methods, you can use their web servers. For DLpTCR, you can use http://jianglab.org.cn/DLpTCR/ and select pTCRβ. For ERGO-II, you can use http://tcr2.cs.biu.ac.il/home and choose VDJdb mode.

## rank

For demonstration purposes, since running on the full background pool would be too time-consuming, we constructed a subset pool by randomly sampling 0.1% of the background library and used it for reproduction and result presentation. If you would like to reproduce the full original results, you can simply replace the subset background pool with the complete background library and rerun the same pipeline. In other words, the current setup is only for demonstration efficiency, while the full results can be recovered by using the original background pool.

In [ ]:
!{sys.executable} ../metric_calculation/sort.py \
                    --input_dir ./CASE4_majority_rank \
                    --output_dir ./CASE4_majority_sort

Found 11 files to process:
  CSV files: 0
  Parquet files: 11

Completed processing 11 files

In [ ]:
!{sys.executable} ../metric_calculation/bedroc.py \
                    -i ./CASE4_majority_sort/CASE4_majority_rank \
                    -o ./CASE4_majority_bedroc

2026-03-17 18:23:30,945 - INFO - Input directory: /mnt/d/PanPep_Reusability/jupter/inference/PanPep_Weight_Inference/CASE4_majority_rank
2026-03-17 18:23:30,946 - INFO - Output directory: ./CASE4_majority_bedroc
2026-03-17 18:23:30,946 - INFO - Number of processes: 8
Total: 11 files, To process: 11 files
Processing files:   0%|                                  | 0/11 [00:00<?, ?it/s]
File: ATDALMTGF_sorted.parquet

File: LLAGIGTVPI_sorted.parquet

File: TTDPSFLGRY_sorted.parquet

File: SPRWYFYYL_sorted.parquet

File: KTFPPTEPK_sorted.parquet

File: LTDEMIAQY_sorted.parquet

File: QYIKWPWYI_sorted.parquet

File: FLCMKALLL_sorted.parquet
Processing files:   9%|██▎                       | 1/11 [00:00<00:01,  7.89it/s]
File: VMATRRNVL_sorted.parquet

File: VMTTVLATL_sorted.parquet

File: YLQPRTFLL_sorted.parquet
Processing files: 100%|█████████████████████████| 11/11 [00:00<00:00, 64.35it/s]
2026-03-17 18:23:31,200 - INFO - Successfully processed 11 files.
2026-03-17 18:23:31,200 - INFO - Detailed results stored in: ./CASE4_majority_bedroc/
2026-03-17 18:23:31,200 - INFO - Starting summary calculation...
2026-03-17 18:23:31,203 - INFO - Reading 11 result files...
Reading detailed results: 100%|████████████████| 11/11 [00:00<00:00, 177.99it/s]
2026-03-17 18:23:31,285 - INFO - Summary saved to: ./CASE4_majority_bedroc/summary_by_directory.csv
2026-03-17 18:23:31,286 - INFO - Total files processed: 11
2026-03-17 18:23:31,286 - INFO - Total unique directories: 1
2026-03-17 18:23:31,286 - INFO - Global mean BEDROC score: 0.1192
Top 10 directories by BEDROC score:
                                                                             Directory  BEDROC_Mean  BEDROC_Std  File_Count
/mnt/d/PanPep_Reusability/jupter/inference/PanPep_Weight_Inference/CASE4_majority_rank     0.119206    0.121052          11
2026-03-17 18:23:31,289 - INFO - Starting per-directory merge of detailed results...
2026-03-17 18:23:31,292 - WARNING - No directories found for merging.

In [ ]:
import os
import glob
import pandas as pd

detailed_dir = "./CASE4_majority_bedroc"

# Print all CSV files in the detailed results directory
csv_files = sorted(glob.glob(os.path.join(detailed_dir, "*.csv")))

print(f"Found {len(csv_files)} CSV file(s) in: {detailed_dir}\n")

for file_path in csv_files:
    print("=" * 100)
    print(f"File: {file_path}")
    print("=" * 100)
    df = pd.read_csv(file_path)
    print(df)
    print("\n")

Found 12 CSV file(s) in: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc

====================================================================================================
File: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc/summary_by_directory.csv
====================================================================================================
                                           Directory  BEDROC_Mean  BEDROC_Std  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...     0.119206    0.121052

   File_Count
0          11


====================================================================================================
File: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc/temp_ATDALMTGF_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                   Filename  BEDROC_Score  Alpha
0  ATDALMTGF_sorted.parquet      0.143054     20


====================================================================================================
File: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc/temp_FLCMKALLL_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                   Filename  BEDROC_Score  Alpha
0  FLCMKALLL_sorted.parquet      0.026134     20


====================================================================================================
File: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc/temp_KTFPPTEPK_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                   Filename  BEDROC_Score  Alpha
0  KTFPPTEPK_sorted.parquet      0.067614     20


====================================================================================================
File: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc/temp_LLAGIGTVPI_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                    Filename  BEDROC_Score  Alpha
0  LLAGIGTVPI_sorted.parquet      0.392011     20


====================================================================================================
File: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc/temp_LTDEMIAQY_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                   Filename  BEDROC_Score  Alpha
0  LTDEMIAQY_sorted.parquet      0.076278     20


====================================================================================================
File: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc/temp_QYIKWPWYI_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                   Filename  BEDROC_Score  Alpha
0  QYIKWPWYI_sorted.parquet      0.065334     20


====================================================================================================
File: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc/temp_SPRWYFYYL_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                   Filename  BEDROC_Score  Alpha
0  SPRWYFYYL_sorted.parquet      0.033069     20


====================================================================================================
File: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc/temp_TTDPSFLGRY_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                    Filename  BEDROC_Score  Alpha
0  TTDPSFLGRY_sorted.parquet      0.064633     20


====================================================================================================
File: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc/temp_VMATRRNVL_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                   Filename  BEDROC_Score  Alpha
0  VMATRRNVL_sorted.parquet      0.113362     20


====================================================================================================
File: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc/temp_VMTTVLATL_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                   Filename  BEDROC_Score  Alpha
0  VMTTVLATL_sorted.parquet      0.021937     20


====================================================================================================
File: /mnt/d/PanPep_Reusability/jupter/CASE4_majority_bedroc/temp_YLQPRTFLL_sorted.csv
====================================================================================================
                                           Directory  \
0  /mnt/d/PanPep_Reusability/jupter/inference/Pan...

                   Filename  BEDROC_Score  Alpha
0  YLQPRTFLL_sorted.parquet      0.307836     20

In [ ]:
!{sys.executable} "../metric_calculation/success_rate&hit_rate.py" \
    --root_dir "./CASE4_majority_sort/CASE4_majority_rank" \
    --output "CASE4_majority_sort" \
    --output_dir "./CASE4_majority_success"

2026-03-17 18:27:31,066 - INFO - Multiprocessing start method set to 'spawn'.
2026-03-17 18:27:31,169 - INFO - Configuration: ProcessingConfig(root_dir='/mnt/d/PanPep_Reusability/jupter/inference/PanPep_Weight_Inference/CASE4_majority_rank', top_k_ratio=1, batch_size=150, num_gpus=1, output_file='CASE4_majority_sort', output_dir='./CASE4_majority_success', gpu_id=None)
2026-03-17 18:27:31,169 - INFO - Detected 1 GPU(s)
Processing directories:   0%|                             | 0/1 [00:00<?, ?it/s]2026-03-17 18:27:32,834 - INFO - Process 157167 using device: cuda:0
Processing directories: 100%|█████████████████████| 1/1 [00:02<00:00,  2.26s/it]
2026-03-17 18:27:33,466 - INFO - Combining 1 DataFrames...
2026-03-17 18:27:33,663 - INFO - Final results saved to CASE4_majority_success/CASE4_majority_sort.csv and CASE4_majority_success/CASE4_majority_sort.parquet

In [ ]:
!{sys.executable} "../metric_calculation/get_success_AUC.py" \
    --input "./CASE4_majority_success/CASE4_majority_sort.parquet" \
    --output "CASE4_majority_success_AUC"

Found 1 directories.
1. '/mnt/d/PanPep_Reusability/jupter/inference/PanPep_Weight_Inference/CASE4_majority_rank'
['/mnt/d/PanPep_Reusability/jupter/inference/PanPep_Weight_Inference/CASE4_majority_rank'] n=37299  Top_K range=(1, 37299)  y range=(0, 1)
/mnt/d/PanPep_Reusability/jupter/../metric_calculation/get_success_AUC.py:190: DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.
  area = float(np.trapz(ys, xs_norm))
  AUC@0.0100%: area=0
  AUC@0.1000%: area=3.91939e-06
  AUC@1.0000%: area=0.000224162
  AUC@5.0000%: area=0.00386248
  AUC@10.0000%: area=0.0120037
  AUC@20.0000%: area=0.0409374
  AUC@100.0000%: area=0.603073

Saved results to: CASE4_majority_success_AUC