# CASE 1: Inference Reproducibility with Original Dataset #

Because the number of classification folds across the 100 runs is too large, we only provide the Jupyter notebook for one fold here, namely the first fold of the reshuffling process. This notebook reproduces the zero setting for the Meta-learner model. To reproduce the other results, simply follow the same workflow and continue running the remaining folds.

## classification

### PanPep

##### majority

In [ ]:
import sys

SCRIPT_DIR = "./"
TEST_DATA = "../../data/fig2/reshuffling_majority_0.csv"
NEGATIVE_DATA = "../../data/Control_dataset.txt"  #Blank file

!{sys.executable} {SCRIPT_DIR}/inference_majority.py \
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "{SCRIPT_DIR}/Requirements" \
    --support_dir "../../data/majority_paper" \
    --peptide_encoding "{SCRIPT_DIR}/peptide_b.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_b.npz" \
    --result_dir "{SCRIPT_DIR}/CASE1_majority"

Using 1 GPUs: [0]
Using model configuration: default

Processing peptide: EAAGIGILTV on device: cuda:0
Skipping peptide EAAGIGILTV - result file already exists

Processing peptide: ELAGIGILTV on device: cuda:0
Skipping peptide ELAGIGILTV - result file already exists

Processing peptide: LPRRSGAAGA on device: cuda:0
Skipping peptide LPRRSGAAGA - result file already exists

Processing peptide: TPRVTGGGAM on device: cuda:0
Skipping peptide TPRVTGGGAM - result file already exists

Processing peptide: ATDALMTGY on device: cuda:0
Skipping peptide ATDALMTGY - result file already exists

Processing peptide: CINGVCWTV on device: cuda:0
Skipping peptide CINGVCWTV - result file already exists

Processing peptide: CRVLCCYVL on device: cuda:0
Skipping peptide CRVLCCYVL - result file already exists

Processing peptide: FPRPWLHGL on device: cuda:0
Skipping peptide FPRPWLHGL - result file already exists

Processing peptide: FRCPRRFCF on device: cuda:0
Skipping peptide FRCPRRFCF - result file already exists

Processing peptide: GILGFVFTL on device: cuda:0
Positive TCRs: 7192, Negative TCRs: 9551
Total batches: 1
Loading support data from: ../../data/majority_paper
Loading support data for peptide: GILGFVFTL
Query data size: 16743

Processing batch 1/1 for peptide GILGFVFTL - 2026-03-16 01:57:17
Finetuning model...
batch processing time: 29.11s, Progress: 100.0%
Successfully wrote 16743 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority/GILGFVFTL.parquet

Peptide GILGFVFTL processing time: 29.19s

Processing peptide: GLCTLVAML on device: cuda:0
Skipping peptide GLCTLVAML - result file already exists

Processing peptide: LLWNGPMAV on device: cuda:0
Skipping peptide LLWNGPMAV - result file already exists

Processing peptide: NLVPMVATV on device: cuda:0
Positive TCRs: 7668, Negative TCRs: 9551
Total batches: 1
Loading support data from: ../../data/majority_paper
Loading support data for peptide: NLVPMVATV
Query data size: 17219

Processing batch 1/1 for peptide NLVPMVATV - 2026-03-16 01:57:47
Finetuning model...
batch processing time: 22.20s, Progress: 100.0%
Successfully wrote 17219 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority/NLVPMVATV.parquet

Peptide NLVPMVATV processing time: 22.27s

Processing peptide: RLRAEAQVK on device: cuda:0
Skipping peptide RLRAEAQVK - result file already exists

Processing peptide: SFHSLHLLF on device: cuda:0
Skipping peptide SFHSLHLLF - result file already exists

Processing peptide: TPQDLNTML on device: cuda:0
Skipping peptide TPQDLNTML - result file already exists

Processing peptide: VTEHDTLLY on device: cuda:0
Skipping peptide VTEHDTLLY - result file already exists

Processing peptide: YVLDHLIVV on device: cuda:0
Skipping peptide YVLDHLIVV - result file already exists

Processing peptide: RAKFKQLL on device: cuda:0
Skipping peptide RAKFKQLL - result file already exists

Total execution time: 54.08s (0.02 hours)

In [ ]:
import os
import pandas as pd

PARQUET_DIR = "./CASE1_majority"
CSV_PATH = "../../data/fig2/reshuffling_majority_0.csv"

OUTPUT_DIR = "./result"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "CASE1_majority_scored.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

csv_df = pd.read_csv(CSV_PATH)

if "label" in csv_df.columns:
    csv_df = csv_df.rename(columns={"label": "Label"})

peptides = csv_df["peptide"].unique()

results = []
for pep in peptides:
    parquet_path = os.path.join(PARQUET_DIR, f"{pep}.parquet")
    if not os.path.exists(parquet_path):
        print(f"[SKIP] No parquet for {pep}")
        continue

    parquet_df = pd.read_parquet(parquet_path)[["CDR3", "Score"]].rename(
        columns={"CDR3": "binding_TCR"}
    )

    pep_rows = csv_df[csv_df["peptide"] == pep].copy()
    merged = pep_rows.merge(parquet_df, on="binding_TCR", how="left")
    results.append(merged)

    print(f"[OK] {pep}: {len(merged)} rows, {merged['Score'].notna().sum()} scored")

if results:
    final_df = pd.concat(results, ignore_index=True)
    final_df.to_csv(OUTPUT_PATH, index=False)

    print(f"\nSaved to {OUTPUT_PATH}")
    print(f"Total rows: {len(final_df)}, scored: {final_df['Score'].notna().sum()}")
else:
    print("No results to save.")

[OK] ATDALMTGY: 120 rows, 120 scored
[OK] CINGVCWTV: 488 rows, 488 scored
[OK] CRVLCCYVL: 158 rows, 158 scored
[OK] EAAGIGILTV: 78 rows, 78 scored
[OK] ELAGIGILTV: 2204 rows, 2204 scored
[OK] FPRPWLHGL: 80 rows, 80 scored
[OK] FRCPRRFCF: 96 rows, 96 scored
[OK] GILGFVFTL: 7192 rows, 7192 scored
[OK] GLCTLVAML: 934 rows, 934 scored
[OK] LLWNGPMAV: 90 rows, 90 scored
[OK] LPRRSGAAGA: 880 rows, 880 scored
[OK] NLVPMVATV: 7668 rows, 7668 scored
[OK] RAKFKQLL: 2524 rows, 2524 scored
[OK] RLRAEAQVK: 182 rows, 182 scored
[OK] SFHSLHLLF: 74 rows, 74 scored
[OK] TPQDLNTML: 82 rows, 82 scored
[OK] TPRVTGGGAM: 226 rows, 226 scored
[OK] VTEHDTLLY: 34 rows, 34 scored
[OK] YVLDHLIVV: 680 rows, 680 scored

Saved to ./result/CASE1_majority_scored.csv
Total rows: 23790, scored: 23790

In [40]:
!{sys.executable} ../../metric_calculation/AUC.py \
                    --root_dir ./result \
                    --output_file ./CASE1_majority_auc.csv

Finding CSV files...
Found 1 CSV files
Processed 1/1 files (100.0%)
Failed: 1

In [41]:
import pandas as pd

df = pd.read_csv("./CASE1_majority_auc.csv")
df

,folder_path,file_name,roc_auc,pr_auc,status
0,./result,CASE1_majority_scored.csv,0.54182,0.544373,success
1,./result,[FOLDER_SUMMARY],0.54182,0.544373,success (averaged over 1 files)

##### few-shot

In [ ]:
import sys

SCRIPT_DIR = "./"
TEST_DATA = "../../data/fig2/reshuffling_few_0.csv"
NEGATIVE_DATA = "../../data/Control_dataset.txt"

!{sys.executable} {SCRIPT_DIR}/inference_few_shot.py \
    --mode single \
    --model default\
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "{SCRIPT_DIR}/Requirements" \
    --support_dir "../../data/few-paper" \
    --peptide_encoding "{SCRIPT_DIR}/peptide_b.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_b.npz" \
    --result_dir "{SCRIPT_DIR}/CASE1_few"

Using 1 GPUs: [0]
Using model configuration: default
Inference mode: single
support_dir enabled: will load k-shot data from ../../data/few-paper

Processing peptide: RKTVRARSRTPSCRSRSHTPSRRRR on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide RKTVRARSRTPSCRSRSHTPSRRRR - 2026-03-16 01:48:50
Finetuning model...
batch processing time: 0.72s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/RKTVRARSRTPSCRSRSHTPSRRRR.parquet

Total time for peptide RKTVRARSRTPSCRSRSHTPSRRRR: 0.75s

Processing peptide: APRGPHGGAASGL on device: cuda:0
Positive TCRs: 12, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3398

Processing batch 1/1 for peptide APRGPHGGAASGL - 2026-03-16 01:48:50
Finetuning model...
batch processing time: 0.25s, Progress: 100.0%
Successfully wrote 3398 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/APRGPHGGAASGL.parquet

Total time for peptide APRGPHGGAASGL: 0.28s

Processing peptide: APARLERRHSA on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide APARLERRHSA - 2026-03-16 01:48:51
Finetuning model...
batch processing time: 0.27s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/APARLERRHSA.parquet

Total time for peptide APARLERRHSA: 0.30s

Processing peptide: AVYDGREHTV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide AVYDGREHTV - 2026-03-16 01:48:51
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/AVYDGREHTV.parquet

Total time for peptide AVYDGREHTV: 0.27s

Processing peptide: CLLGTYTQDV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide CLLGTYTQDV - 2026-03-16 01:48:51
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/CLLGTYTQDV.parquet

Total time for peptide CLLGTYTQDV: 0.27s

Processing peptide: CLLWSFQTSA on device: cuda:0
Positive TCRs: 22, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3408

Processing batch 1/1 for peptide CLLWSFQTSA - 2026-03-16 01:48:51
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3408 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/CLLWSFQTSA.parquet

Total time for peptide CLLWSFQTSA: 0.26s

Processing peptide: ESEERPPTPY on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide ESEERPPTPY - 2026-03-16 01:48:52
Finetuning model...
batch processing time: 0.25s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/ESEERPPTPY.parquet

Total time for peptide ESEERPPTPY: 0.28s

Processing peptide: GTSGAPIVNR on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide GTSGAPIVNR - 2026-03-16 01:48:52
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/GTSGAPIVNR.parquet

Total time for peptide GTSGAPIVNR: 0.27s

Processing peptide: GTSGSPIVAR on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide GTSGSPIVAR - 2026-03-16 01:48:52
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/GTSGSPIVAR.parquet

Total time for peptide GTSGSPIVAR: 0.27s

Processing peptide: GTSGSPIVDR on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide GTSGSPIVDR - 2026-03-16 01:48:53
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/GTSGSPIVDR.parquet

Total time for peptide GTSGSPIVDR: 0.26s

Processing peptide: KLFEFLVHGV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide KLFEFLVHGV - 2026-03-16 01:48:53
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/KLFEFLVHGV.parquet

Total time for peptide KLFEFLVHGV: 0.26s

Processing peptide: LMMPFSIVYI on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide LMMPFSIVYI - 2026-03-16 01:48:53
Finetuning model...
batch processing time: 0.23s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/LMMPFSIVYI.parquet

Total time for peptide LMMPFSIVYI: 0.25s

Processing peptide: LVMPFSIVYI on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide LVMPFSIVYI - 2026-03-16 01:48:53
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/LVMPFSIVYI.parquet

Total time for peptide LVMPFSIVYI: 0.26s

Processing peptide: MLSILALVRV on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide MLSILALVRV - 2026-03-16 01:48:54
Finetuning model...
batch processing time: 0.23s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/MLSILALVRV.parquet

Total time for peptide MLSILALVRV: 0.26s

Processing peptide: RPHERNGFTV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide RPHERNGFTV - 2026-03-16 01:48:54
Finetuning model...
batch processing time: 0.23s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/RPHERNGFTV.parquet

Total time for peptide RPHERNGFTV: 0.26s

Processing peptide: SSCMGGMNWR on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide SSCMGGMNWR - 2026-03-16 01:48:54
Finetuning model...
batch processing time: 0.22s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/SSCMGGMNWR.parquet

Total time for peptide SSCMGGMNWR: 0.26s

Processing peptide: TMSFSHLFYL on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide TMSFSHLFYL - 2026-03-16 01:48:54
Finetuning model...
batch processing time: 0.23s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/TMSFSHLFYL.parquet

Total time for peptide TMSFSHLFYL: 0.25s

Processing peptide: VLENFTIFLV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide VLENFTIFLV - 2026-03-16 01:48:55
Finetuning model...
batch processing time: 0.31s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/VLENFTIFLV.parquet

Total time for peptide VLENFTIFLV: 0.34s

Processing peptide: VLMGGVPGVE on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide VLMGGVPGVE - 2026-03-16 01:48:55
Finetuning model...
batch processing time: 0.33s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/VLMGGVPGVE.parquet

Total time for peptide VLMGGVPGVE: 0.36s

Processing peptide: VYALIAGATL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide VYALIAGATL - 2026-03-16 01:48:55
Finetuning model...
batch processing time: 0.29s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/VYALIAGATL.parquet

Total time for peptide VYALIAGATL: 0.32s

Processing peptide: AAFKRSCLK on device: cuda:0
Positive TCRs: 6, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3392

Processing batch 1/1 for peptide AAFKRSCLK - 2026-03-16 01:48:56
Finetuning model...
batch processing time: 0.39s, Progress: 100.0%
Successfully wrote 3392 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/AAFKRSCLK.parquet

Total time for peptide AAFKRSCLK: 0.41s

Processing peptide: AEMEFCPCC on device: cuda:0
Positive TCRs: 28, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3414

Processing batch 1/1 for peptide AEMEFCPCC - 2026-03-16 01:48:56
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3414 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/AEMEFCPCC.parquet

Total time for peptide AEMEFCPCC: 0.27s

Processing peptide: ALIHHNTHL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide ALIHHNTHL - 2026-03-16 01:48:56
Finetuning model...
batch processing time: 0.23s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/ALIHHNTHL.parquet

Total time for peptide ALIHHNTHL: 0.25s

Processing peptide: ALIHHNTYL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide ALIHHNTYL - 2026-03-16 01:48:57
Finetuning model...
batch processing time: 0.23s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/ALIHHNTYL.parquet

Total time for peptide ALIHHNTYL: 0.26s

Processing peptide: ALSYTPAEV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide ALSYTPAEV - 2026-03-16 01:48:57
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/ALSYTPAEV.parquet

Total time for peptide ALSYTPAEV: 0.27s

Processing peptide: AMAGSLVFL on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide AMAGSLVFL - 2026-03-16 01:48:57
Finetuning model...
batch processing time: 0.23s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/AMAGSLVFL.parquet

Total time for peptide AMAGSLVFL: 0.26s

Processing peptide: AVGSHVYSV on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide AVGSHVYSV - 2026-03-16 01:48:57
Finetuning model...
batch processing time: 0.23s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/AVGSHVYSV.parquet

Total time for peptide AVGSHVYSV: 0.26s

Processing peptide: CCIEVINNT on device: cuda:0
Positive TCRs: 12, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3398

Processing batch 1/1 for peptide CCIEVINNT - 2026-03-16 01:48:58
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3398 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/CCIEVINNT.parquet

Total time for peptide CCIEVINNT: 0.27s

Processing peptide: CFLLILPNC on device: cuda:0
Positive TCRs: 24, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3410

Processing batch 1/1 for peptide CFLLILPNC - 2026-03-16 01:48:58
Finetuning model...
batch processing time: 0.25s, Progress: 100.0%
Successfully wrote 3410 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/CFLLILPNC.parquet

Total time for peptide CFLLILPNC: 0.28s

Processing peptide: CHIPVEPNT on device: cuda:0
Positive TCRs: 8, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3394

Processing batch 1/1 for peptide CHIPVEPNT - 2026-03-16 01:48:58
Finetuning model...
batch processing time: 0.28s, Progress: 100.0%
Successfully wrote 3394 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/CHIPVEPNT.parquet

Total time for peptide CHIPVEPNT: 0.31s

Processing peptide: CLGGLLTMV on device: cuda:0
Positive TCRs: 180, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3566

Processing batch 1/1 for peptide CLGGLLTMV - 2026-03-16 01:48:58
Finetuning model...
batch processing time: 0.43s, Progress: 100.0%
Successfully wrote 3566 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/CLGGLLTMV.parquet

Total time for peptide CLGGLLTMV: 0.46s

Processing peptide: EIQEFCPNT on device: cuda:0
Positive TCRs: 28, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3414

Processing batch 1/1 for peptide EIQEFCPNT - 2026-03-16 01:48:59
Finetuning model...
batch processing time: 0.30s, Progress: 100.0%
Successfully wrote 3414 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/EIQEFCPNT.parquet

Total time for peptide EIQEFCPNT: 0.33s

Processing peptide: FDVMVMPNL on device: cuda:0
Positive TCRs: 8, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3394

Processing batch 1/1 for peptide FDVMVMPNL - 2026-03-16 01:48:59
Finetuning model...
batch processing time: 0.25s, Progress: 100.0%
Successfully wrote 3394 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/FDVMVMPNL.parquet

Total time for peptide FDVMVMPNL: 0.28s

Processing peptide: FIDCYLLAI on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide FIDCYLLAI - 2026-03-16 01:49:00
Finetuning model...
batch processing time: 0.26s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/FIDCYLLAI.parquet

Total time for peptide FIDCYLLAI: 0.29s

Processing peptide: FIDQYYSSI on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide FIDQYYSSI - 2026-03-16 01:49:00
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/FIDQYYSSI.parquet

Total time for peptide FIDQYYSSI: 0.27s

Processing peptide: FIFSYVVAV on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide FIFSYVVAV - 2026-03-16 01:49:00
Finetuning model...
batch processing time: 0.24s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/FIFSYVVAV.parquet

Total time for peptide FIFSYVVAV: 0.27s

Processing peptide: FILDAVQRV on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide FILDAVQRV - 2026-03-16 01:49:00
Finetuning model...
batch processing time: 0.29s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/FILDAVQRV.parquet

Total time for peptide FILDAVQRV: 0.32s

Processing peptide: FIYQYYSSI on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide FIYQYYSSI - 2026-03-16 01:49:01
Finetuning model...
batch processing time: 0.31s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/FIYQYYSSI.parquet

Total time for peptide FIYQYYSSI: 0.35s

Processing peptide: FLDEFMEAV on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide FLDEFMEAV - 2026-03-16 01:49:01
Finetuning model...
batch processing time: 0.30s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/FLDEFMEAV.parquet

Total time for peptide FLDEFMEAV: 0.33s

Processing peptide: FLFMYLVTV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3390

Processing batch 1/1 for peptide FLFMYLVTV - 2026-03-16 01:49:01
Finetuning model...
batch processing time: 0.32s, Progress: 100.0%
Successfully wrote 3390 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/FLFMYLVTV.parquet

Total time for peptide FLFMYLVTV: 0.36s

Processing peptide: FLFTFFASI on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide FLFTFFASI - 2026-03-16 01:49:02
Finetuning model...
batch processing time: 0.28s, Progress: 100.0%
Successfully wrote 3388 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_few/FLFTFFASI.parquet

Total time for peptide FLFTFFASI: 0.32s

Processing peptide: FLNDLLSVL on device: cuda:0
Positive TCRs: 2, Negative TCRs: 3386
Total batches: 1
Loading k-shot data from: ../../data/few-paper
Query data size: 3388

Processing batch 1/1 for peptide FLNDLLSVL - 2026-03-16 01:49:02
Finetuning model...

In [ ]:
import os
import pandas as pd

PARQUET_DIR = "./CASE1_few"
CSV_PATH = "../../data/fig2/reshuffling_few_0.csv"

OUTPUT_DIR = "./result"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "CASE1_few_scored.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

csv_df = pd.read_csv(CSV_PATH)

if "label" in csv_df.columns:
    csv_df = csv_df.rename(columns={"label": "Label"})

peptides = csv_df["peptide"].unique()

results = []
for pep in peptides:
    parquet_path = os.path.join(PARQUET_DIR, f"{pep}.parquet")
    if not os.path.exists(parquet_path):
        print(f"[SKIP] No parquet for {pep}")
        continue

    parquet_df = pd.read_parquet(parquet_path)[["CDR3", "Score"]].rename(
        columns={"CDR3": "binding_TCR"}
    )

    pep_rows = csv_df[csv_df["peptide"] == pep].copy()
    merged = pep_rows.merge(parquet_df, on="binding_TCR", how="left")
    results.append(merged)

    print(f"[OK] {pep}: {len(merged)} rows, {merged['Score'].notna().sum()} scored")

if results:
    final_df = pd.concat(results, ignore_index=True)
    final_df.to_csv(OUTPUT_PATH, index=False)

    print(f"\nSaved to {OUTPUT_PATH}")
    print(f"Total rows: {len(final_df)}, scored: {final_df['Score'].notna().sum()}")
else:
    print("No results to save.")

[OK] AAFKRSCLK: 6 rows, 6 scored
[OK] AEMEFCPCC: 28 rows, 28 scored
[OK] ALIHHNTHL: 4 rows, 4 scored
[OK] ALIHHNTYL: 4 rows, 4 scored
[OK] ALSYTPAEV: 4 rows, 4 scored
[OK] AMAGSLVFL: 2 rows, 2 scored
[OK] APARLERRHSA: 4 rows, 4 scored
[OK] APRGPHGGAASGL: 12 rows, 12 scored
[OK] AVGSHVYSV: 2 rows, 2 scored
[OK] AVYDGREHTV: 4 rows, 4 scored
[OK] CCIEVINNT: 12 rows, 12 scored
[OK] CFLLILPNC: 24 rows, 24 scored
[OK] CHIPVEPNT: 8 rows, 8 scored
[OK] CLGGLLTMV: 180 rows, 180 scored
[OK] CLLGTYTQDV: 4 rows, 4 scored
[OK] CLLWSFQTSA: 22 rows, 22 scored
[OK] EIQEFCPNT: 28 rows, 28 scored
[OK] ESEERPPTPY: 4 rows, 4 scored
[OK] FDVMVMPNL: 8 rows, 8 scored
[OK] FIDCYLLAI: 2 rows, 2 scored
[OK] FIDQYYSSI: 2 rows, 2 scored
[OK] FIFSYVVAV: 2 rows, 2 scored
[OK] FILDAVQRV: 2 rows, 2 scored
[OK] FIYQYYSSI: 4 rows, 4 scored
[OK] FLDEFMEAV: 2 rows, 2 scored
[OK] FLFMYLVTV: 4 rows, 4 scored
[OK] FLFTFFASI: 2 rows, 2 scored
[OK] FLKEMGGL: 4 rows, 4 scored
[OK] FLKEQGGL: 4 rows, 4 scored
[OK] FLKETGGL: 4 rows, 4 scored
[OK] FLNDLLSVL: 2 rows, 2 scored
[OK] FLNDLLSVM: 2 rows, 2 scored
[OK] FLNVLFPLL: 4 rows, 4 scored
[OK] FLTYLDVSV: 6 rows, 6 scored
[OK] FMIGYASAL: 2 rows, 2 scored
[OK] FYGKTILWF: 4 rows, 4 scored
[OK] GAVECCPNC: 8 rows, 8 scored
[OK] GILEFVFTL: 2 rows, 2 scored
[OK] GLMAIAWFI: 2 rows, 2 scored
[OK] GPGMKARVL: 14 rows, 14 scored
[OK] GQFLTPNSH: 4 rows, 4 scored
[OK] GTSGAPIVNR: 2 rows, 2 scored
[OK] GTSGSPIVAR: 2 rows, 2 scored
[OK] GTSGSPIVDR: 2 rows, 2 scored
[OK] HMTEVVRHC: 4 rows, 4 scored
[OK] ILIVMVPFL: 2 rows, 2 scored
[OK] ILLDWAANI: 2 rows, 2 scored
[OK] ILLDWAANV: 2 rows, 2 scored
[OK] ILNVDVFTL: 12 rows, 12 scored
[OK] IMIEFCPGG: 8 rows, 8 scored
[OK] KLFEFLVHGV: 4 rows, 4 scored
[OK] KLLEIAPNC: 32 rows, 32 scored
[OK] KLMNIQQQL: 14 rows, 14 scored
[OK] KLNTITAVV: 4 rows, 4 scored
[OK] KLPLDINPV: 2 rows, 2 scored
[OK] KLSHQLVLL: 4 rows, 4 scored
[OK] KTVGIYPNA: 8 rows, 8 scored
[OK] LAMPFATPM: 2 rows, 2 scored
[OK] LHMEFCSCC: 8 rows, 8 scored
[OK] LIFNMFYWI: 2 rows, 2 scored
[OK] LIFNMLYWI: 2 rows, 2 scored
[OK] LLAGTLAVV: 6 rows, 6 scored
[OK] LLAIKVPNV: 4 rows, 4 scored
[OK] LLAILPYYV: 8 rows, 8 scored
[OK] LLAILTYYV: 10 rows, 10 scored
[OK] LLAMKVPNV: 2 rows, 2 scored
[OK] LLFGFPVYV: 2 rows, 2 scored
[OK] LLFGMTPCL: 12 rows, 12 scored
[OK] LLLNMLIVL: 4 rows, 4 scored
[OK] LMMPFSIVYI: 4 rows, 4 scored
[OK] LMVLHSPSL: 2 rows, 2 scored
[OK] LVMPFSIVYI: 2 rows, 2 scored
[OK] MLSILALVRV: 2 rows, 2 scored
[OK] NMIHFAPNV: 20 rows, 20 scored
[OK] NNILIATCV: 8 rows, 8 scored
[OK] QLLVSLWGL: 2 rows, 2 scored
[OK] RCMLQCPSV: 8 rows, 8 scored
[OK] RKTVRARSRTPSCRSRSHTPSRRRR: 4 rows, 4 scored
[OK] RMAAISNTV: 4 rows, 4 scored
[OK] RPHERNGFTV: 4 rows, 4 scored
[OK] SIIGRLLEV: 4 rows, 4 scored
[OK] SILDAVQRV: 2 rows, 2 scored
[OK] SLAPLSPRA: 6 rows, 6 scored
[OK] SSCMGGMNWR: 2 rows, 2 scored
[OK] TAMDIFVTV: 4 rows, 4 scored
[OK] THLMVLCCV: 20 rows, 20 scored
[OK] TLNAWVKVV: 26 rows, 26 scored
[OK] TMAAISNTV: 2 rows, 2 scored
[OK] TMSFSHLFYL: 2 rows, 2 scored
[OK] VLENFTIFLV: 4 rows, 4 scored
[OK] VLFHRAFLV: 14 rows, 14 scored
[OK] VLMGGVPGVE: 2 rows, 2 scored
[OK] VLNPFIYTL: 4 rows, 4 scored
[OK] VLNYFKPYL: 12 rows, 12 scored
[OK] VMAPRTLIL: 4 rows, 4 scored
[OK] VQYLGMFPV: 4 rows, 4 scored
[OK] VVTGVLVYL: 54 rows, 54 scored
[OK] VYALIAGATL: 4 rows, 4 scored
[OK] WLSLLVPFV: 2 rows, 2 scored
[OK] YHSIEWAI: 2 rows, 2 scored
[OK] YLDELIRNT: 4 rows, 4 scored
[OK] YLEAGPVTA: 2 rows, 2 scored
[OK] YLEPGAVTA: 2 rows, 2 scored
[OK] YLEPGPATA: 2 rows, 2 scored
[OK] YLEPGPVAA: 2 rows, 2 scored
[OK] YLLAIFSGL: 2 rows, 2 scored
[OK] YLLFMIGYT: 4 rows, 4 scored
[OK] YLQDSMATT: 2 rows, 2 scored
[OK] YMDGTMSQV: 2 rows, 2 scored
[OK] YMFLASPSV: 2 rows, 2 scored
[OK] YVLTWIVGA: 8 rows, 8 scored
[OK] YVVTWIVGA: 2 rows, 2 scored

Saved to ./result/CASE1_few_scored.csv
Total rows: 876, scored: 876

In [43]:
!{sys.executable} ../../metric_calculation/AUC.py \
                    --root_dir ./result \
                    --output_file ./CASE1_few_auc.csv

Finding CSV files...
Found 1 CSV files
Processed 1/1 files (100.0%)
Failed: 1

In [44]:
import pandas as pd

df = pd.read_csv("./CASE1_few_auc.csv")
df

,folder_path,file_name,roc_auc,pr_auc,status
0,./result,CASE1_few_scored.csv,0.633369,0.654649,success
1,./result,[FOLDER_SUMMARY],0.633369,0.654649,success (averaged over 1 files)

#### zero-shot

In [ ]:
import sys

SCRIPT_DIR = "./"
TEST_DATA = "../../data/fig2/reshuffling_zero_0.csv"
NEGATIVE_DATA = "../../data/Control_dataset.txt"

!{sys.executable} {SCRIPT_DIR}/inference_zero_shot.py \
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "{SCRIPT_DIR}/Requirements" \
    --result_dir "{SCRIPT_DIR}/CASE1_zero"\
    --peptide_encoding "{SCRIPT_DIR}/peptide_b.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_b.npz" \
    --model default

Using 1 GPUs: [0]
Using model configuration: default

Processing peptide: SWISDIRAGTAPLCRNHIKSSCSLI on device: cuda:0

Processing batch 1/1 for peptide SWISDIRAGTAPLCRNHIKSSCSLI - 2026-03-16 02:17:07
batch processing time: 0.99s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/SWISDIRAGTAPLCRNHIKSSCSLI.parquet

Peptide SWISDIRAGTAPLCRNHIKSSCSLI processing time: 1.03s

Processing peptide: APAGPHGGAASGL on device: cuda:0

Processing batch 1/1 for peptide APAGPHGGAASGL - 2026-03-16 02:17:08
batch processing time: 0.65s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/APAGPHGGAASGL.parquet

Peptide APAGPHGGAASGL processing time: 0.68s

Processing peptide: APRGAHGGAASGL on device: cuda:0

Processing batch 1/1 for peptide APRGAHGGAASGL - 2026-03-16 02:17:09
batch processing time: 0.64s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/APRGAHGGAASGL.parquet

Peptide APRGAHGGAASGL processing time: 0.67s

Processing peptide: APRGPAGGAASGL on device: cuda:0

Processing batch 1/1 for peptide APRGPAGGAASGL - 2026-03-16 02:17:09
batch processing time: 0.66s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/APRGPAGGAASGL.parquet

Peptide APRGPAGGAASGL processing time: 0.69s

Processing peptide: LPEALPQGQLTAY on device: cuda:0

Processing batch 1/1 for peptide LPEALPQGQLTAY - 2026-03-16 02:17:10
batch processing time: 0.71s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LPEALPQGQLTAY.parquet

Peptide LPEALPQGQLTAY processing time: 0.73s

Processing peptide: LPEPLPQGALTAY on device: cuda:0

Processing batch 1/1 for peptide LPEPLPQGALTAY - 2026-03-16 02:17:11
batch processing time: 0.70s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LPEPLPQGALTAY.parquet

Peptide LPEPLPQGALTAY processing time: 0.73s

Processing peptide: LPEPLPQGQATAY on device: cuda:0

Processing batch 1/1 for peptide LPEPLPQGQATAY - 2026-03-16 02:17:11
batch processing time: 0.68s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LPEPLPQGQATAY.parquet

Peptide LPEPLPQGQATAY processing time: 0.71s

Processing peptide: ASFRPELAEFW on device: cuda:0

Processing batch 1/1 for peptide ASFRPELAEFW - 2026-03-16 02:17:12
batch processing time: 0.85s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/ASFRPELAEFW.parquet

Peptide ASFRPELAEFW processing time: 0.88s

Processing peptide: ASFSPELRMAW on device: cuda:0

Processing batch 1/1 for peptide ASFSPELRMAW - 2026-03-16 02:17:13
batch processing time: 0.73s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/ASFSPELRMAW.parquet

Peptide ASFSPELRMAW processing time: 0.75s

Processing peptide: ESITGSLGPLL on device: cuda:0

Processing batch 1/1 for peptide ESITGSLGPLL - 2026-03-16 02:17:14
batch processing time: 1.88s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/ESITGSLGPLL.parquet

Peptide ESITGSLGPLL processing time: 1.93s

Processing peptide: FFAGGIGIRTI on device: cuda:0

Processing batch 1/1 for peptide FFAGGIGIRTI - 2026-03-16 02:17:16
batch processing time: 0.86s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/FFAGGIGIRTI.parquet

Peptide FFAGGIGIRTI processing time: 0.89s

Processing peptide: FLAGGIGIRTL on device: cuda:0

Processing batch 1/1 for peptide FLAGGIGIRTL - 2026-03-16 02:17:17
batch processing time: 1.08s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/FLAGGIGIRTL.parquet

Peptide FLAGGIGIRTL processing time: 1.11s

Processing peptide: GSLAPEIRMYW on device: cuda:0

Processing batch 1/1 for peptide GSLAPEIRMYW - 2026-03-16 02:17:18
batch processing time: 0.71s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/GSLAPEIRMYW.parquet

Peptide GSLAPEIRMYW processing time: 0.74s

Processing peptide: GSLSPELRPIF on device: cuda:0

Processing batch 1/1 for peptide GSLSPELRPIF - 2026-03-16 02:17:18
batch processing time: 0.78s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/GSLSPELRPIF.parquet

Peptide GSLSPELRPIF processing time: 0.81s

Processing peptide: GTIRPEIPDYF on device: cuda:0

Processing batch 1/1 for peptide GTIRPEIPDYF - 2026-03-16 02:17:19
batch processing time: 0.66s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/GTIRPEIPDYF.parquet

Peptide GTIRPEIPDYF processing time: 0.69s

Processing peptide: GTIRPEIREMW on device: cuda:0

Processing batch 1/1 for peptide GTIRPEIREMW - 2026-03-16 02:17:20
batch processing time: 0.78s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/GTIRPEIREMW.parquet

Peptide GTIRPEIREMW processing time: 0.81s

Processing peptide: HPVAEADYFEY on device: cuda:0

Processing batch 1/1 for peptide HPVAEADYFEY - 2026-03-16 02:17:21
batch processing time: 0.91s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/HPVAEADYFEY.parquet

Peptide HPVAEADYFEY processing time: 0.95s

Processing peptide: KSCTPEVREYF on device: cuda:0

Processing batch 1/1 for peptide KSCTPEVREYF - 2026-03-16 02:17:22
batch processing time: 0.72s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/KSCTPEVREYF.parquet

Peptide KSCTPEVREYF processing time: 0.75s

Processing peptide: KSFVPELKPAF on device: cuda:0

Processing batch 1/1 for peptide KSFVPELKPAF - 2026-03-16 02:17:22
batch processing time: 0.74s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/KSFVPELKPAF.parquet

Peptide KSFVPELKPAF processing time: 0.77s

Processing peptide: KSLAPEVRDLF on device: cuda:0

Processing batch 1/1 for peptide KSLAPEVRDLF - 2026-03-16 02:17:23
batch processing time: 0.72s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/KSLAPEVRDLF.parquet

Peptide KSLAPEVRDLF processing time: 0.75s

Processing peptide: KSLTPEVRGYW on device: cuda:0

Processing batch 1/1 for peptide KSLTPEVRGYW - 2026-03-16 02:17:24
batch processing time: 0.70s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/KSLTPEVRGYW.parquet

Peptide KSLTPEVRGYW processing time: 0.74s

Processing peptide: LAITPEIAPYF on device: cuda:0

Processing batch 1/1 for peptide LAITPEIAPYF - 2026-03-16 02:17:25
batch processing time: 0.82s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LAITPEIAPYF.parquet

Peptide LAITPEIAPYF processing time: 0.85s

Processing peptide: LSITPEIAPYF on device: cuda:0

Processing batch 1/1 for peptide LSITPEIAPYF - 2026-03-16 02:17:26
batch processing time: 0.85s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LSITPEIAPYF.parquet

Peptide LSITPEIAPYF processing time: 0.88s

Processing peptide: LSITPEISPYF on device: cuda:0

Processing batch 1/1 for peptide LSITPEISPYF - 2026-03-16 02:17:26
batch processing time: 0.83s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LSITPEISPYF.parquet

Peptide LSITPEISPYF processing time: 0.85s

Processing peptide: LSLRPEIPLFF on device: cuda:0

Processing batch 1/1 for peptide LSLRPEIPLFF - 2026-03-16 02:17:27
batch processing time: 0.64s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LSLRPEIPLFF.parquet

Peptide LSLRPEIPLFF processing time: 0.67s

Processing peptide: LTISPEIPPYF on device: cuda:0

Processing batch 1/1 for peptide LTISPEIPPYF - 2026-03-16 02:17:28
batch processing time: 0.69s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LTISPEIPPYF.parquet

Peptide LTISPEIPPYF processing time: 0.72s

Processing peptide: LTISPEIPSYF on device: cuda:0

Processing batch 1/1 for peptide LTISPEIPSYF - 2026-03-16 02:17:29
batch processing time: 0.72s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LTISPEIPSYF.parquet

Peptide LTISPEIPSYF processing time: 0.75s

Processing peptide: LTITPEIAPFF on device: cuda:0

Processing batch 1/1 for peptide LTITPEIAPFF - 2026-03-16 02:17:29
batch processing time: 0.89s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LTITPEIAPFF.parquet

Peptide LTITPEIAPFF processing time: 0.92s

Processing peptide: LTITPEIAPYF on device: cuda:0

Processing batch 1/1 for peptide LTITPEIAPYF - 2026-03-16 02:17:30
batch processing time: 0.87s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LTITPEIAPYF.parquet

Peptide LTITPEIAPYF processing time: 0.90s

Processing peptide: LTITPEIRPYF on device: cuda:0

Processing batch 1/1 for peptide LTITPEIRPYF - 2026-03-16 02:17:31
batch processing time: 0.66s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LTITPEIRPYF.parquet

Peptide LTITPEIRPYF processing time: 0.68s

Processing peptide: LTLTPEIAPYF on device: cuda:0

Processing batch 1/1 for peptide LTLTPEIAPYF - 2026-03-16 02:17:32
batch processing time: 0.74s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/LTLTPEIAPYF.parquet

Peptide LTLTPEIAPYF processing time: 0.77s

Processing peptide: NSFRPEVAMKY on device: cuda:0

Processing batch 1/1 for peptide NSFRPEVAMKY - 2026-03-16 02:17:33
batch processing time: 0.65s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/NSFRPEVAMKY.parquet

Peptide NSFRPEVAMKY processing time: 0.68s

Processing peptide: NSLKPEIPDYF on device: cuda:0

Processing batch 1/1 for peptide NSLKPEIPDYF - 2026-03-16 02:17:33
batch processing time: 0.70s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/NSLKPEIPDYF.parquet

Peptide NSLKPEIPDYF processing time: 0.73s

Processing peptide: NSVKPEIRPVW on device: cuda:0

Processing batch 1/1 for peptide NSVKPEIRPVW - 2026-03-16 02:17:34
batch processing time: 0.66s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/NSVKPEIRPVW.parquet

Peptide NSVKPEIRPVW processing time: 0.69s

Processing peptide: RSFVPEIGMGF on device: cuda:0

Processing batch 1/1 for peptide RSFVPEIGMGF - 2026-03-16 02:17:35
batch processing time: 0.99s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/RSFVPEIGMGF.parquet

Peptide RSFVPEIGMGF processing time: 1.03s

Processing peptide: RSLAPEVRGYW on device: cuda:0

Processing batch 1/1 for peptide RSLAPEVRGYW - 2026-03-16 02:17:36
batch processing time: 0.67s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/RSLAPEVRGYW.parquet

Peptide RSLAPEVRGYW processing time: 0.70s

Processing peptide: RTYVPEIKHRW on device: cuda:0

Processing batch 1/1 for peptide RTYVPEIKHRW - 2026-03-16 02:17:37
batch processing time: 0.80s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/RTYVPEIKHRW.parquet

Peptide RTYVPEIKHRW processing time: 0.84s

Processing peptide: SALRPEIRLLW on device: cuda:0

Processing batch 1/1 for peptide SALRPEIRLLW - 2026-03-16 02:17:37
batch processing time: 0.69s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/SALRPEIRLLW.parquet

Peptide SALRPEIRLLW processing time: 0.71s

Processing peptide: SSFSPELRMRW on device: cuda:0

Processing batch 1/1 for peptide SSFSPELRMRW - 2026-03-16 02:17:38
batch processing time: 0.68s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/SSFSPELRMRW.parquet

Peptide SSFSPELRMRW processing time: 0.71s

Processing peptide: SSGVPEVRMMF on device: cuda:0

Processing batch 1/1 for peptide SSGVPEVRMMF - 2026-03-16 02:17:39
batch processing time: 0.67s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/SSGVPEVRMMF.parquet

Peptide SSGVPEVRMMF processing time: 0.70s

Processing peptide: WTYRPEVRGVW on device: cuda:0

Processing batch 1/1 for peptide WTYRPEVRGVW - 2026-03-16 02:17:39
batch processing time: 0.83s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/WTYRPEVRGVW.parquet

Peptide WTYRPEVRGVW processing time: 0.86s

Processing peptide: YLSHLPLTCKF on device: cuda:0

Processing batch 1/1 for peptide YLSHLPLTCKF - 2026-03-16 02:17:40
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/YLSHLPLTCKF.parquet

Peptide YLSHLPLTCKF processing time: 0.65s

Processing peptide: YSFKPELKEIF on device: cuda:0

Processing batch 1/1 for peptide YSFKPELKEIF - 2026-03-16 02:17:41
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/YSFKPELKEIF.parquet

Peptide YSFKPELKEIF processing time: 0.65s

Processing peptide: ACDPHSGHFV on device: cuda:0

Processing batch 1/1 for peptide ACDPHSGHFV - 2026-03-16 02:17:42
batch processing time: 0.75s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/ACDPHSGHFV.parquet

Peptide ACDPHSGHFV processing time: 0.78s

Processing peptide: ALLETLSLLL on device: cuda:0

Processing batch 1/1 for peptide ALLETLSLLL - 2026-03-16 02:17:42
batch processing time: 0.75s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/ALLETLSLLL.parquet

Peptide ALLETLSLLL processing time: 0.79s

Processing peptide: APQPAPENAY on device: cuda:0

Processing batch 1/1 for peptide APQPAPENAY - 2026-03-16 02:17:43
batch processing time: 0.72s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/APQPAPENAY.parquet

Peptide APQPAPENAY processing time: 0.75s

Processing peptide: DLAGIGILTV on device: cuda:0

Processing batch 1/1 for peptide DLAGIGILTV - 2026-03-16 02:17:44
batch processing time: 0.84s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/DLAGIGILTV.parquet

Peptide DLAGIGILTV processing time: 0.86s

Processing peptide: EFFWDANDIY on device: cuda:0

Processing batch 1/1 for peptide EFFWDANDIY - 2026-03-16 02:17:45
batch processing time: 0.62s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/EFFWDANDIY.parquet

Peptide EFFWDANDIY processing time: 0.64s

Processing peptide: EIAGIGILTV on device: cuda:0

Processing batch 1/1 for peptide EIAGIGILTV - 2026-03-16 02:17:45
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/EIAGIGILTV.parquet

Peptide EIAGIGILTV processing time: 0.67s

Processing peptide: ELAGIGALTV on device: cuda:0

Processing batch 1/1 for peptide ELAGIGALTV - 2026-03-16 02:17:46
batch processing time: 0.88s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/ELAGIGALTV.parquet

Peptide ELAGIGALTV processing time: 0.91s

Processing peptide: ELAGIGIITV on device: cuda:0

Processing batch 1/1 for peptide ELAGIGIITV - 2026-03-16 02:17:47
batch processing time: 1.25s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/ELAGIGIITV.parquet

Peptide ELAGIGIITV processing time: 1.28s

Processing peptide: ELAGIGILSV on device: cuda:0

Processing batch 1/1 for peptide ELAGIGILSV - 2026-03-16 02:17:48
batch processing time: 0.65s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/ELAGIGILSV.parquet

Peptide ELAGIGILSV processing time: 0.68s

Processing peptide: ELAGIGILTA on device: cuda:0

Processing batch 1/1 for peptide ELAGIGILTA - 2026-03-16 02:17:49
batch processing time: 0.80s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/ELAGIGILTA.parquet

Peptide ELAGIGILTA processing time: 0.83s

Processing peptide: ELAGIGILTI on device: cuda:0

Processing batch 1/1 for peptide ELAGIGILTI - 2026-03-16 02:17:50
batch processing time: 0.65s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/ELAGIGILTI.parquet

Peptide ELAGIGILTI processing time: 0.67s

Processing peptide: ELAGIGLLTV on device: cuda:0

Processing batch 1/1 for peptide ELAGIGLLTV - 2026-03-16 02:17:50
batch processing time: 0.63s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/ELAGIGLLTV.parquet

Peptide ELAGIGLLTV processing time: 0.66s

Processing peptide: ELGGIGILTV on device: cuda:0

Processing batch 1/1 for peptide ELGGIGILTV - 2026-03-16 02:17:51
batch processing time: 0.74s, Progress: 100.0%
Successfully wrote 9558 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/ELGGIGILTV.parquet

Peptide ELGGIGILTV processing time: 0.77s

Processing peptide: EMLFSHGLVK on device: cuda:0

Processing batch 1/1 for peptide EMLFSHGLVK - 2026-03-16 02:17:52
batch processing time: 0.66s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/EMLFSHGLVK.parquet

Peptide EMLFSHGLVK processing time: 0.69s

Processing peptide: FATGIGIITV on device: cuda:0

Processing batch 1/1 for peptide FATGIGIITV - 2026-03-16 02:17:53
batch processing time: 0.67s, Progress: 100.0%
Successfully wrote 9556 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_zero/FATGIGIITV.parquet

Peptide FATGIGIITV processing time: 0.70s

Processing peptide: FLGIYTVTVV on device: cuda:0

Processing batch 1/1 for peptide FLGIYTVTVV - 2026-03-16 02:17:53
batch processing time: 0.68s, Progress: 100.0%

In [49]:
import os
import pandas as pd

PARQUET_DIR = "./CASE1_zero"
CSV_PATH = "../../data/fig2/reshuffling_zero_0.csv"

OUTPUT_DIR = "./result"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "CASE1_zero_scored.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

csv_df = pd.read_csv(CSV_PATH)

if "label" in csv_df.columns:
    csv_df = csv_df.rename(columns={"label": "Label"})

peptides = csv_df["peptide"].unique()

results = []
for pep in peptides:
    parquet_path = os.path.join(PARQUET_DIR, f"{pep}.parquet")
    if not os.path.exists(parquet_path):
        print(f"[SKIP] No parquet for {pep}")
        continue

    parquet_df = pd.read_parquet(parquet_path)[["CDR3", "Score"]].rename(
        columns={"CDR3": "binding_TCR"}
    )

    pep_rows = csv_df[csv_df["peptide"] == pep].copy()
    merged = pep_rows.merge(parquet_df, on="binding_TCR", how="left")
    results.append(merged)

    print(f"[OK] {pep}: {len(merged)} rows, {merged['Score'].notna().sum()} scored")

if results:
    final_df = pd.concat(results, ignore_index=True)
    final_df.to_csv(OUTPUT_PATH, index=False)

    print(f"\nSaved to {OUTPUT_PATH}")
    print(f"Total rows: {len(final_df)}, scored: {final_df['Score'].notna().sum()}")
else:
    print("No results to save.")

[OK] ACDPHSGHFV: 4 rows, 4 scored
[OK] AIMDKNIIL: 4 rows, 4 scored
[OK] ALGGLLTMV: 4 rows, 4 scored
[OK] ALGIGILTV: 98 rows, 98 scored
[OK] ALLETLSLLL: 4 rows, 4 scored
[OK] ALLQVTLLL: 4 rows, 4 scored
[OK] ALSYTPVEV: 4 rows, 4 scored
[OK] ALVGAIPSI: 4 rows, 4 scored
[OK] ALVPMVATV: 4 rows, 4 scored
[OK] ALWGFFPVL: 6 rows, 6 scored
[OK] ALWGPDPAA: 4 rows, 4 scored
[OK] AMAGSPVFL: 4 rows, 4 scored
[OK] AMAVLYLAL: 4 rows, 4 scored
[OK] APAGPHGGAASGL: 4 rows, 4 scored
[OK] APQPAPENAY: 4 rows, 4 scored
[OK] APRGAHGGAASGL: 4 rows, 4 scored
[OK] APRGPAGGAASGL: 4 rows, 4 scored
[OK] ASFRPELAEFW: 4 rows, 4 scored
[OK] ASFSPELRMAW: 4 rows, 4 scored
[OK] CISSCNPNL: 4 rows, 4 scored
[OK] CLAGLLTMV: 4 rows, 4 scored
[OK] CLGALLTMV: 4 rows, 4 scored
[OK] CLGGLATMV: 4 rows, 4 scored
[OK] CLGGLLAMV: 4 rows, 4 scored
[OK] DLAGIGILTV: 6 rows, 6 scored
[OK] EEAAGIGIL: 6 rows, 6 scored
[OK] EFFWDANDIY: 4 rows, 4 scored
[OK] EFTVSGNIL: 6 rows, 6 scored
[OK] EHEGSGPEL: 4 rows, 4 scored
[OK] EIAGIGILTV: 6 rows, 6 scored
[OK] ELAGIGALTV: 4 rows, 4 scored
[OK] ELAGIGIITV: 6 rows, 6 scored
[OK] ELAGIGILSV: 6 rows, 6 scored
[OK] ELAGIGILTA: 6 rows, 6 scored
[OK] ELAGIGILTI: 6 rows, 6 scored
[OK] ELAGIGLLTV: 6 rows, 6 scored
[OK] ELGGIGILTV: 6 rows, 6 scored
[OK] EMLFSHGLVK: 4 rows, 4 scored
[OK] EMMLFDWKV: 4 rows, 4 scored
[OK] ESITGSLGPLL: 6 rows, 6 scored
[OK] EVLPFFLFF: 4 rows, 4 scored
[OK] FATGIGIITV: 4 rows, 4 scored
[OK] FFAGGIGIRTI: 4 rows, 4 scored
[OK] FGDVGSTLF: 4 rows, 4 scored
[OK] FITGISILL: 4 rows, 4 scored
[OK] FLAGGIGIRTL: 4 rows, 4 scored
[OK] FLEIYTVTV: 4 rows, 4 scored
[OK] FLGIYTVTVV: 4 rows, 4 scored
[OK] FLNVFFPLL: 4 rows, 4 scored
[OK] FLPDLNVNA: 4 rows, 4 scored
[OK] FLPSDFFPSV: 4 rows, 4 scored
[OK] FLRGRFYGL: 4 rows, 4 scored
[OK] FLTGIGIITV: 4 rows, 4 scored
[OK] FLWSVFMLI: 12 rows, 12 scored
[OK] FMGVTYEM: 4 rows, 4 scored
[OK] FMLYLVTLM: 4 rows, 4 scored
[OK] FMSAYSGVL: 4 rows, 4 scored
[OK] FMYSDFHFI: 18 rows, 18 scored
[OK] FQDYIKSYL: 6 rows, 6 scored
[OK] FQLNQSFEI: 4 rows, 4 scored
[OK] FRNEGIHL: 4 rows, 4 scored
[OK] FSFPLDFLV: 4 rows, 4 scored
[OK] FSSEVLNLV: 4 rows, 4 scored
[OK] FVGEFFTDV: 4 rows, 4 scored
[OK] FVVPYMIYLL: 4 rows, 4 scored
[OK] FVYVFTTHL: 4 rows, 4 scored
[OK] FWLLGAWAL: 4 rows, 4 scored
[OK] FWLLPAWAL: 4 rows, 4 scored
[OK] GIWGFVFTL: 4 rows, 4 scored
[OK] GLLHHAPSL: 4 rows, 4 scored
[OK] GLSPNLNRFL: 4 rows, 4 scored
[OK] GMDYHNGHL: 4 rows, 4 scored
[OK] GSLAPEIRMYW: 4 rows, 4 scored
[OK] GSLSPELRPIF: 4 rows, 4 scored
[OK] GTIRPEIPDYF: 4 rows, 4 scored
[OK] GTIRPEIREMW: 4 rows, 4 scored
[OK] HIAKSPFEV: 4 rows, 4 scored
[OK] HIMPDTAEI: 4 rows, 4 scored
[OK] HIVEISTPV: 4 rows, 4 scored
[OK] HPVAEADYFEY: 4 rows, 4 scored
[OK] HQLGGVVEV: 4 rows, 4 scored
[OK] HQNPVTGLLL: 4 rows, 4 scored
[OK] HRRGSRSYV: 6 rows, 6 scored
[OK] HSKKKCDEI: 4 rows, 4 scored
[OK] HSKRKCDEL: 4 rows, 4 scored
[OK] HSRKKCDEL: 4 rows, 4 scored
[OK] IAGLGLLTV: 6 rows, 6 scored
[OK] IAMAVLYLA: 4 rows, 4 scored
[OK] ILAAFLHWL: 4 rows, 4 scored
[OK] ILAKFAHWL: 4 rows, 4 scored
[OK] ILCETCLIV: 4 rows, 4 scored
[OK] ILITQVLGL: 4 rows, 4 scored
[OK] KAANIVLTV: 6 rows, 6 scored
[OK] KIFGSLAFL: 4 rows, 4 scored
[OK] KLAKPLPYT: 4 rows, 4 scored
[OK] KLEFMDWRL: 4 rows, 4 scored
[OK] KLEQLDWTV: 4 rows, 4 scored
[OK] KLLAGDEIV: 4 rows, 4 scored
[OK] KLQCVDLHV: 6 rows, 6 scored
[OK] KLSEGDLLA: 4 rows, 4 scored
[OK] KLSELHAYI: 4 rows, 4 scored
[OK] KLSHQPVLL: 4 rows, 4 scored
[OK] KLTESLHKV: 4 rows, 4 scored
[OK] KLVALGINNV: 8 rows, 8 scored
[OK] KLVALVINAV: 4 rows, 4 scored
[OK] KMGVTYEM: 4 rows, 4 scored
[OK] KQWLVWLFL: 8 rows, 8 scored
[OK] KSCTPEVREYF: 4 rows, 4 scored
[OK] KSFVPELKPAF: 4 rows, 4 scored
[OK] KSLAPEVRDLF: 4 rows, 4 scored
[OK] KSLTPEVRGYW: 4 rows, 4 scored
[OK] KVAELVHFL: 6 rows, 6 scored
[OK] LAITPEIAPYF: 4 rows, 4 scored
[OK] LASYFFWGL: 4 rows, 4 scored
[OK] LGIGVITI: 6 rows, 6 scored
[OK] LLEDLDWDV: 4 rows, 4 scored
[OK] LLFAAFSSA: 4 rows, 4 scored
[OK] LLFGKPVYV: 4 rows, 4 scored
[OK] LLFGLALIEV: 4 rows, 4 scored
[OK] LLFGPVYV: 4 rows, 4 scored
[OK] LLFGYPVFV: 4 rows, 4 scored
[OK] LLHGFSFYL: 72 rows, 72 scored
[OK] LLIDLTSFLL: 4 rows, 4 scored
[OK] LLQCTQQAV: 4 rows, 4 scored
[OK] LLWNTVWNM: 4 rows, 4 scored
[OK] LLYGFVNYI: 4 rows, 4 scored
[OK] LLYGFVNYV: 4 rows, 4 scored
[OK] LMASISSFL: 4 rows, 4 scored
[OK] LMDMHNGQL: 4 rows, 4 scored
[OK] LPEALPQGQLTAY: 4 rows, 4 scored
[OK] LPEPLPQGALTAY: 4 rows, 4 scored
[OK] LPEPLPQGQATAY: 4 rows, 4 scored
[OK] LPLKMLNI: 4 rows, 4 scored
[OK] LSITPEIAPYF: 4 rows, 4 scored
[OK] LSITPEISPYF: 4 rows, 4 scored
[OK] LSLRPEIPLFF: 4 rows, 4 scored
[OK] LTISPEIPPYF: 4 rows, 4 scored
[OK] LTISPEIPSYF: 4 rows, 4 scored
[OK] LTITPEIAPFF: 4 rows, 4 scored
[OK] LTITPEIAPYF: 4 rows, 4 scored
[OK] LTITPEIRPYF: 4 rows, 4 scored
[OK] LTLTPEIAPYF: 4 rows, 4 scored
[OK] LVFPLVMGV: 4 rows, 4 scored
[OK] LVIGMPPPV: 4 rows, 4 scored
[OK] LYPEFIASI: 4 rows, 4 scored
[OK] MEVDPIGHLY: 6 rows, 6 scored
[OK] MLFSHGLVK: 4 rows, 4 scored
[OK] MLGERLFPL: 4 rows, 4 scored
[OK] MLIGIPVYV: 4 rows, 4 scored
[OK] MLMLAVIVA: 4 rows, 4 scored
[OK] MMWDRGLGMM: 4 rows, 4 scored
[OK] MPYGYVLNEF: 4 rows, 4 scored
[OK] MVIGIPVYV: 4 rows, 4 scored
[OK] MVNTVAGAMK: 4 rows, 4 scored
[OK] NLAPMVATV: 4 rows, 4 scored
[OK] NLAQTDLATV: 4 rows, 4 scored
[OK] NLFNRYLAL: 4 rows, 4 scored
[OK] NLNRCSVPV: 4 rows, 4 scored
[OK] NLVGMVATV: 4 rows, 4 scored
[OK] NLVPMVAAV: 4 rows, 4 scored
[OK] NLVPMVASV: 4 rows, 4 scored
[OK] NLVPQVATV: 4 rows, 4 scored
[OK] NLVPTVATV: 4 rows, 4 scored
[OK] NLVPVVATV: 4 rows, 4 scored
[OK] NMEYMTWDV: 4 rows, 4 scored
[OK] NSFRPEVAMKY: 4 rows, 4 scored
[OK] NSLKPEIPDYF: 4 rows, 4 scored
[OK] NSVKPEIRPVW: 4 rows, 4 scored
[OK] NVEYYDIKL: 4 rows, 4 scored
[OK] QLCDVMFYL: 4 rows, 4 scored
[OK] QLIPCMDVV: 4 rows, 4 scored
[OK] QTNPVTLQY: 4 rows, 4 scored
[OK] RIAAWMATY: 6 rows, 6 scored
[OK] RILLVAASY: 4 rows, 4 scored
[OK] RLDAMNGQL: 4 rows, 4 scored
[OK] RLHDLVFPL: 4 rows, 4 scored
[OK] RLHDLVLPL: 4 rows, 4 scored
[OK] RLLCALTSL: 4 rows, 4 scored
[OK] RLLQCTQQAV: 4 rows, 4 scored
[OK] RLSDFSEQL: 24 rows, 24 scored
[OK] RLWEPLRVV: 4 rows, 4 scored
[OK] RMDYNNMQM: 4 rows, 4 scored
[OK] RMEQVDWTV: 4 rows, 4 scored
[OK] RSFVPEIGMGF: 4 rows, 4 scored
[OK] RSGGFSFGK: 4 rows, 4 scored
[OK] RSLAPEVRGYW: 4 rows, 4 scored
[OK] RTYVPEIKHRW: 4 rows, 4 scored
[OK] RVRFFFPSL: 6 rows, 6 scored
[OK] RVSTLRVSL: 4 rows, 4 scored
[OK] RYGSFSVTL: 6 rows, 6 scored
[OK] SALRPEIRLLW: 4 rows, 4 scored
[OK] SLDPTTSPV: 4 rows, 4 scored
[OK] SLLLLPVSV: 4 rows, 4 scored
[OK] SLLLLSVSV: 4 rows, 4 scored
[OK] SLLQGSPHL: 4 rows, 4 scored
[OK] SLLQGSPHV: 4 rows, 4 scored
[OK] SLSKILDTV: 6 rows, 6 scored
[OK] SLVALGINAV: 12 rows, 12 scored
[OK] SLYNTVATLY: 22 rows, 22 scored
[OK] SMGVTYEM: 4 rows, 4 scored
[OK] SMLGIGIVPV: 6 rows, 6 scored
[OK] SSFSPELRMRW: 4 rows, 4 scored
[OK] SSGVPEVRMMF: 4 rows, 4 scored
[OK] SVASTITGV: 4 rows, 4 scored
[OK] SWISDIRAGTAPLCRNHIKSSCSLI: 4 rows, 4 scored
[OK] SYMIMEIE: 4 rows, 4 scored
[OK] TLEELDWCL: 4 rows, 4 scored
[OK] TLEYMDWLV: 4 rows, 4 scored
[OK] TLFTMVGTV: 4 rows, 4 scored
[OK] TLREIRRYQK: 4 rows, 4 scored
[OK] TLYSLTLLY: 4 rows, 4 scored
[OK] TMDFYQGQL: 4 rows, 4 scored
[OK] TMETIDWKV: 4 rows, 4 scored
[OK] TMSSSHLFYL: 4 rows, 4 scored
[OK] TYDTVHRHL: 4 rows, 4 scored
[OK] VLASPSVPL: 4 rows, 4 scored
[OK] VLDLFQGQL: 4 rows, 4 scored
[OK] VLEEVDWLI: 4 rows, 4 scored
[OK] VLFAAFSSA: 4 rows, 4 scored
[OK] VLNGTVHPV: 4 rows, 4 scored
[OK] VMIIVSSLAV: 4 rows, 4 scored
[OK] VPLTEDAEL: 4 rows, 4 scored
[OK] VYAIFIFQL: 4 rows, 4 scored
[OK] VYFFLPDHL: 4 rows, 4 scored
[OK] WLDNFELCL: 4 rows, 4 scored
[OK] WLLPAWGV: 4 rows, 4 scored
[OK] WLLPTWGV: 4 rows, 4 scored
[OK] WLWEPLRVV: 4 rows, 4 scored
[OK] WSYDSTLLAY: 4 rows, 4 scored
[OK] WTYRPEVRGVW: 4 rows, 4 scored
[OK] YIDDVVLGA: 4 rows, 4 scored
[OK] YIFLGNLAL: 4 rows, 4 scored
[OK] YLCLQNNFI: 4 rows, 4 scored
[OK] YLCSGSSYF: 4 rows, 4 scored
[OK] YLCSGSSYFV: 4 rows, 4 scored
[OK] YLDELIKNT: 4 rows, 4 scored
[OK] YLLPAIVHI: 4 rows, 4 scored
[OK] YLNELVVFV: 4 rows, 4 scored
[OK] YLQDSLATT: 4 rows, 4 scored
[OK] YLQQNWWTL: 36 rows, 36 scored
[OK] YLSFYTAEQL: 4 rows, 4 scored
[OK] YLSHLPLTCKF: 4 rows, 4 scored
[OK] YLSNIIPAL: 4 rows, 4 scored
[OK] YLVALGINAV: 12 rows, 12 scored
[OK] YLVALGVNAV: 6 rows, 6 scored
[OK] YLYDRLLRI: 4 rows, 4 scored
[OK] YLYDRLLRV: 4 rows, 4 scored
[OK] YMDDVVLGA: 4 rows, 4 scored
[OK] YMGVSYEM: 4 rows, 4 scored
[OK] YMGVVYEM: 4 rows, 4 scored
[OK] YMLDLQPETT: 4 rows, 4 scored
[OK] YMLTLHTKL: 4 rows, 4 scored
[OK] YMPTTIIAA: 4 rows, 4 scored
[OK] YMVLASPSV: 4 rows, 4 scored
[OK] YSFKPELKEIF: 4 rows, 4 scored
[OK] YTSEILSPI: 4 rows, 4 scored
[OK] YVDDVVLGA: 4 rows, 4 scored
[OK] YVNELVVFV: 4 rows, 4 scored
[OK] YVTAMDIFV: 4 rows, 4 scored
[OK] YVTAMDLFV: 4 rows, 4 scored

Saved to ./result/CASE1_zero_scored.csv
Total rows: 1370, scored: 1370

In [ ]:
!{sys.executable} ../../metric_calculation/AUC.py \
                    --root_dir ./result \
                    --output_file ./CASE1_zero_auc.csv

Finding CSV files...
Found 1 CSV files
Processed 1/1 files (100.0%)
Failed: 1

In [ ]:
import pandas as pd

df = pd.read_csv("./CASE1_zero_auc.csv")
df

,folder_path,file_name,roc_auc,pr_auc,status
0,./result,CASE1_zero_scored.csv,0.506968,0.531179,success
1,./result,[FOLDER_SUMMARY],0.506968,0.531179,success (averaged over 1 files)

#### Meta-learner

In [53]:
import sys

SCRIPT_DIR = "./"
TEST_DATA = "../../data/fig2/reshuffling_zero_0.csv"
NEGATIVE_DATA = "../../data/Control_dataset.txt"

!{sys.executable} {SCRIPT_DIR}/inference_meta_learner.py \
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "{SCRIPT_DIR}/Requirements" \
    --result_dir "{SCRIPT_DIR}/CASE1_meta"\
    --peptide_encoding "{SCRIPT_DIR}/peptide_b.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_b.npz"

Using 1 GPUs: [0]
GPU 0 will process 260 peptides with approximately 1370 TCRs

Processing peptide: ALGIGILTV on device: cuda:0
Positive TCRs: 98, Negative TCRs: 9553
Total batches: 1
Query data size: 9651

Processing batch 1/1 for peptide ALGIGILTV - 2026-03-16 02:25:37
batch processing time: 0.90s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ALGIGILTV.parquet

Total time for peptide ALGIGILTV: 1.02s

Processing peptide: LLHGFSFYL on device: cuda:0
Positive TCRs: 72, Negative TCRs: 9553
Total batches: 1
Query data size: 9625

Processing batch 1/1 for peptide LLHGFSFYL - 2026-03-16 02:25:38
batch processing time: 0.70s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/LLHGFSFYL.parquet

Total time for peptide LLHGFSFYL: 0.81s

Processing peptide: YLQQNWWTL on device: cuda:0
Positive TCRs: 36, Negative TCRs: 9553
Total batches: 1
Query data size: 9589

Processing batch 1/1 for peptide YLQQNWWTL - 2026-03-16 02:25:39
batch processing time: 0.58s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/YLQQNWWTL.parquet

Total time for peptide YLQQNWWTL: 0.67s

Processing peptide: RLSDFSEQL on device: cuda:0
Positive TCRs: 24, Negative TCRs: 9553
Total batches: 1
Query data size: 9577

Processing batch 1/1 for peptide RLSDFSEQL - 2026-03-16 02:25:39
batch processing time: 0.56s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/RLSDFSEQL.parquet

Total time for peptide RLSDFSEQL: 0.65s

Processing peptide: SLYNTVATLY on device: cuda:0
Positive TCRs: 22, Negative TCRs: 9553
Total batches: 1
Query data size: 9575

Processing batch 1/1 for peptide SLYNTVATLY - 2026-03-16 02:25:40
batch processing time: 0.58s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/SLYNTVATLY.parquet

Total time for peptide SLYNTVATLY: 0.67s

Processing peptide: FMYSDFHFI on device: cuda:0
Positive TCRs: 18, Negative TCRs: 9553
Total batches: 1
Query data size: 9571

Processing batch 1/1 for peptide FMYSDFHFI - 2026-03-16 02:25:41
batch processing time: 0.56s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/FMYSDFHFI.parquet

Total time for peptide FMYSDFHFI: 0.66s

Processing peptide: FLWSVFMLI on device: cuda:0
Positive TCRs: 12, Negative TCRs: 9553
Total batches: 1
Query data size: 9565

Processing batch 1/1 for peptide FLWSVFMLI - 2026-03-16 02:25:42
batch processing time: 0.60s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/FLWSVFMLI.parquet

Total time for peptide FLWSVFMLI: 0.70s

Processing peptide: SLVALGINAV on device: cuda:0
Positive TCRs: 12, Negative TCRs: 9553
Total batches: 1
Query data size: 9565

Processing batch 1/1 for peptide SLVALGINAV - 2026-03-16 02:25:42
batch processing time: 0.66s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/SLVALGINAV.parquet

Total time for peptide SLVALGINAV: 0.75s

Processing peptide: YLVALGINAV on device: cuda:0
Positive TCRs: 12, Negative TCRs: 9553
Total batches: 1
Query data size: 9565

Processing batch 1/1 for peptide YLVALGINAV - 2026-03-16 02:25:43
batch processing time: 0.67s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/YLVALGINAV.parquet

Total time for peptide YLVALGINAV: 0.77s

Processing peptide: KLVALGINNV on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide KLVALGINNV - 2026-03-16 02:25:44
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/KLVALGINNV.parquet

Total time for peptide KLVALGINNV: 0.75s

Processing peptide: KQWLVWLFL on device: cuda:0
Positive TCRs: 8, Negative TCRs: 9553
Total batches: 1
Query data size: 9561

Processing batch 1/1 for peptide KQWLVWLFL - 2026-03-16 02:25:45
batch processing time: 0.73s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/KQWLVWLFL.parquet

Total time for peptide KQWLVWLFL: 0.82s

Processing peptide: ALWGFFPVL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide ALWGFFPVL - 2026-03-16 02:25:46
batch processing time: 0.66s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ALWGFFPVL.parquet

Total time for peptide ALWGFFPVL: 0.76s

Processing peptide: DLAGIGILTV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide DLAGIGILTV - 2026-03-16 02:25:47
batch processing time: 0.63s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/DLAGIGILTV.parquet

Total time for peptide DLAGIGILTV: 0.72s

Processing peptide: EEAAGIGIL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide EEAAGIGIL - 2026-03-16 02:25:47
batch processing time: 0.73s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/EEAAGIGIL.parquet

Total time for peptide EEAAGIGIL: 0.82s

Processing peptide: EFTVSGNIL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide EFTVSGNIL - 2026-03-16 02:25:48
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/EFTVSGNIL.parquet

Total time for peptide EFTVSGNIL: 0.74s

Processing peptide: EIAGIGILTV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide EIAGIGILTV - 2026-03-16 02:25:49
batch processing time: 0.70s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/EIAGIGILTV.parquet

Total time for peptide EIAGIGILTV: 0.80s

Processing peptide: ELAGIGIITV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide ELAGIGIITV - 2026-03-16 02:25:50
batch processing time: 0.66s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ELAGIGIITV.parquet

Total time for peptide ELAGIGIITV: 0.76s

Processing peptide: ELAGIGILSV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide ELAGIGILSV - 2026-03-16 02:25:51
batch processing time: 0.82s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ELAGIGILSV.parquet

Total time for peptide ELAGIGILSV: 0.93s

Processing peptide: ELAGIGILTA on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide ELAGIGILTA - 2026-03-16 02:25:52
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ELAGIGILTA.parquet

Total time for peptide ELAGIGILTA: 0.75s

Processing peptide: ELAGIGILTI on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide ELAGIGILTI - 2026-03-16 02:25:53
batch processing time: 0.61s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ELAGIGILTI.parquet

Total time for peptide ELAGIGILTI: 0.70s

Processing peptide: ELAGIGLLTV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide ELAGIGLLTV - 2026-03-16 02:25:53
batch processing time: 0.62s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ELAGIGLLTV.parquet

Total time for peptide ELAGIGLLTV: 0.71s

Processing peptide: ELGGIGILTV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide ELGGIGILTV - 2026-03-16 02:25:54
batch processing time: 0.60s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ELGGIGILTV.parquet

Total time for peptide ELGGIGILTV: 0.69s

Processing peptide: ESITGSLGPLL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide ESITGSLGPLL - 2026-03-16 02:25:55
batch processing time: 0.59s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ESITGSLGPLL.parquet

Total time for peptide ESITGSLGPLL: 0.69s

Processing peptide: FQDYIKSYL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide FQDYIKSYL - 2026-03-16 02:25:56
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/FQDYIKSYL.parquet

Total time for peptide FQDYIKSYL: 0.74s

Processing peptide: HRRGSRSYV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide HRRGSRSYV - 2026-03-16 02:25:57
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/HRRGSRSYV.parquet

Total time for peptide HRRGSRSYV: 0.75s

Processing peptide: IAGLGLLTV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide IAGLGLLTV - 2026-03-16 02:25:57
batch processing time: 0.76s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/IAGLGLLTV.parquet

Total time for peptide IAGLGLLTV: 0.85s

Processing peptide: KAANIVLTV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide KAANIVLTV - 2026-03-16 02:25:58
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/KAANIVLTV.parquet

Total time for peptide KAANIVLTV: 0.73s

Processing peptide: KLQCVDLHV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide KLQCVDLHV - 2026-03-16 02:25:59
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/KLQCVDLHV.parquet

Total time for peptide KLQCVDLHV: 0.74s

Processing peptide: KVAELVHFL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide KVAELVHFL - 2026-03-16 02:26:00
batch processing time: 0.72s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/KVAELVHFL.parquet

Total time for peptide KVAELVHFL: 0.83s

Processing peptide: LGIGVITI on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide LGIGVITI - 2026-03-16 02:26:01
batch processing time: 0.88s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/LGIGVITI.parquet

Total time for peptide LGIGVITI: 0.98s

Processing peptide: MEVDPIGHLY on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide MEVDPIGHLY - 2026-03-16 02:26:02
batch processing time: 0.62s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/MEVDPIGHLY.parquet

Total time for peptide MEVDPIGHLY: 0.71s

Processing peptide: RIAAWMATY on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide RIAAWMATY - 2026-03-16 02:26:03
batch processing time: 0.63s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/RIAAWMATY.parquet

Total time for peptide RIAAWMATY: 0.72s

Processing peptide: RVRFFFPSL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide RVRFFFPSL - 2026-03-16 02:26:03
batch processing time: 1.41s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/RVRFFFPSL.parquet

Total time for peptide RVRFFFPSL: 1.50s

Processing peptide: RYGSFSVTL on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide RYGSFSVTL - 2026-03-16 02:26:05
batch processing time: 0.57s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/RYGSFSVTL.parquet

Total time for peptide RYGSFSVTL: 0.66s

Processing peptide: SLSKILDTV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide SLSKILDTV - 2026-03-16 02:26:06
batch processing time: 0.55s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/SLSKILDTV.parquet

Total time for peptide SLSKILDTV: 0.64s

Processing peptide: SMLGIGIVPV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide SMLGIGIVPV - 2026-03-16 02:26:07
batch processing time: 0.62s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/SMLGIGIVPV.parquet

Total time for peptide SMLGIGIVPV: 0.73s

Processing peptide: YLVALGVNAV on device: cuda:0
Positive TCRs: 6, Negative TCRs: 9553
Total batches: 1
Query data size: 9559

Processing batch 1/1 for peptide YLVALGVNAV - 2026-03-16 02:26:07
batch processing time: 0.62s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/YLVALGVNAV.parquet

Total time for peptide YLVALGVNAV: 0.72s

Processing peptide: ACDPHSGHFV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1
Query data size: 9557

Processing batch 1/1 for peptide ACDPHSGHFV - 2026-03-16 02:26:08
batch processing time: 0.63s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ACDPHSGHFV.parquet

Total time for peptide ACDPHSGHFV: 0.71s

Processing peptide: AIMDKNIIL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1
Query data size: 9557

Processing batch 1/1 for peptide AIMDKNIIL - 2026-03-16 02:26:09
batch processing time: 0.62s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/AIMDKNIIL.parquet

Total time for peptide AIMDKNIIL: 0.72s

Processing peptide: ALGGLLTMV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1
Query data size: 9557

Processing batch 1/1 for peptide ALGGLLTMV - 2026-03-16 02:26:10
batch processing time: 0.63s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ALGGLLTMV.parquet

Total time for peptide ALGGLLTMV: 0.72s

Processing peptide: ALLETLSLLL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1
Query data size: 9557

Processing batch 1/1 for peptide ALLETLSLLL - 2026-03-16 02:26:10
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ALLETLSLLL.parquet

Total time for peptide ALLETLSLLL: 0.74s

Processing peptide: ALLQVTLLL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1
Query data size: 9557

Processing batch 1/1 for peptide ALLQVTLLL - 2026-03-16 02:26:11
batch processing time: 0.64s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ALLQVTLLL.parquet

Total time for peptide ALLQVTLLL: 0.73s

Processing peptide: ALSYTPVEV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1
Query data size: 9557

Processing batch 1/1 for peptide ALSYTPVEV - 2026-03-16 02:26:12
batch processing time: 0.63s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ALSYTPVEV.parquet

Total time for peptide ALSYTPVEV: 0.73s

Processing peptide: ALVGAIPSI on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1
Query data size: 9557

Processing batch 1/1 for peptide ALVGAIPSI - 2026-03-16 02:26:13
batch processing time: 0.89s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ALVGAIPSI.parquet

Total time for peptide ALVGAIPSI: 0.99s

Processing peptide: ALVPMVATV on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1
Query data size: 9557

Processing batch 1/1 for peptide ALVPMVATV - 2026-03-16 02:26:14
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ALVPMVATV.parquet

Total time for peptide ALVPMVATV: 0.75s

Processing peptide: ALWGPDPAA on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1
Query data size: 9557

Processing batch 1/1 for peptide ALWGPDPAA - 2026-03-16 02:26:15
batch processing time: 0.65s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/ALWGPDPAA.parquet

Total time for peptide ALWGPDPAA: 0.75s

Processing peptide: AMAGSPVFL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1
Query data size: 9557

Processing batch 1/1 for peptide AMAGSPVFL - 2026-03-16 02:26:16
batch processing time: 0.59s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/AMAGSPVFL.parquet

Total time for peptide AMAGSPVFL: 0.68s

Processing peptide: AMAVLYLAL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1
Query data size: 9557

Processing batch 1/1 for peptide AMAVLYLAL - 2026-03-16 02:26:16
batch processing time: 0.67s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/AMAVLYLAL.parquet

Total time for peptide AMAVLYLAL: 0.76s

Processing peptide: APAGPHGGAASGL on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1
Query data size: 9557

Processing batch 1/1 for peptide APAGPHGGAASGL - 2026-03-16 02:26:17
batch processing time: 0.67s, Progress: 100.0%
Successfully saved results to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_meta/APAGPHGGAASGL.parquet

Total time for peptide APAGPHGGAASGL: 0.77s

Processing peptide: APQPAPENAY on device: cuda:0
Positive TCRs: 4, Negative TCRs: 9553
Total batches: 1

In [58]:
import os
import pandas as pd

PARQUET_DIR = "./CASE1_meta"
CSV_PATH = "../../data/fig2/reshuffling_zero_0.csv"

OUTPUT_DIR = "./result"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "CASE1_meta_scored.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)

csv_df = pd.read_csv(CSV_PATH)

if "label" in csv_df.columns:
    csv_df = csv_df.rename(columns={"label": "Label"})

peptides = csv_df["peptide"].unique()

results = []
for pep in peptides:
    parquet_path = os.path.join(PARQUET_DIR, f"{pep}.parquet")
    if not os.path.exists(parquet_path):
        print(f"[SKIP] No parquet for {pep}")
        continue

    parquet_df = pd.read_parquet(parquet_path)[["CDR3", "Score"]].rename(
        columns={"CDR3": "binding_TCR"}
    )

    pep_rows = csv_df[csv_df["peptide"] == pep].copy()
    merged = pep_rows.merge(parquet_df, on="binding_TCR", how="left")
    results.append(merged)

    print(f"[OK] {pep}: {len(merged)} rows, {merged['Score'].notna().sum()} scored")

if results:
    final_df = pd.concat(results, ignore_index=True)
    final_df.to_csv(OUTPUT_PATH, index=False)

    print(f"\nSaved to {OUTPUT_PATH}")
    print(f"Total rows: {len(final_df)}, scored: {final_df['Score'].notna().sum()}")
else:
    print("No results to save.")

[OK] ACDPHSGHFV: 4 rows, 4 scored
[OK] AIMDKNIIL: 4 rows, 4 scored
[OK] ALGGLLTMV: 4 rows, 4 scored
[OK] ALGIGILTV: 98 rows, 98 scored
[OK] ALLETLSLLL: 4 rows, 4 scored
[OK] ALLQVTLLL: 4 rows, 4 scored
[OK] ALSYTPVEV: 4 rows, 4 scored
[OK] ALVGAIPSI: 4 rows, 4 scored
[OK] ALVPMVATV: 4 rows, 4 scored
[OK] ALWGFFPVL: 6 rows, 6 scored
[OK] ALWGPDPAA: 4 rows, 4 scored
[OK] AMAGSPVFL: 4 rows, 4 scored
[OK] AMAVLYLAL: 4 rows, 4 scored
[OK] APAGPHGGAASGL: 4 rows, 4 scored
[OK] APQPAPENAY: 4 rows, 4 scored
[OK] APRGAHGGAASGL: 4 rows, 4 scored
[OK] APRGPAGGAASGL: 4 rows, 4 scored
[OK] ASFRPELAEFW: 4 rows, 4 scored
[OK] ASFSPELRMAW: 4 rows, 4 scored
[OK] CISSCNPNL: 4 rows, 4 scored
[OK] CLAGLLTMV: 4 rows, 4 scored
[OK] CLGALLTMV: 4 rows, 4 scored
[OK] CLGGLATMV: 4 rows, 4 scored
[OK] CLGGLLAMV: 4 rows, 4 scored
[OK] DLAGIGILTV: 6 rows, 6 scored
[OK] EEAAGIGIL: 6 rows, 6 scored
[OK] EFFWDANDIY: 4 rows, 4 scored
[OK] EFTVSGNIL: 6 rows, 6 scored
[OK] EHEGSGPEL: 4 rows, 4 scored
[OK] EIAGIGILTV: 6 rows, 6 scored
[OK] ELAGIGALTV: 4 rows, 4 scored
[OK] ELAGIGIITV: 6 rows, 6 scored
[OK] ELAGIGILSV: 6 rows, 6 scored
[OK] ELAGIGILTA: 6 rows, 6 scored
[OK] ELAGIGILTI: 6 rows, 6 scored
[OK] ELAGIGLLTV: 6 rows, 6 scored
[OK] ELGGIGILTV: 6 rows, 6 scored
[OK] EMLFSHGLVK: 4 rows, 4 scored
[OK] EMMLFDWKV: 4 rows, 4 scored
[OK] ESITGSLGPLL: 6 rows, 6 scored
[OK] EVLPFFLFF: 4 rows, 4 scored
[OK] FATGIGIITV: 4 rows, 4 scored
[OK] FFAGGIGIRTI: 4 rows, 4 scored
[OK] FGDVGSTLF: 4 rows, 4 scored
[OK] FITGISILL: 4 rows, 4 scored
[OK] FLAGGIGIRTL: 4 rows, 4 scored
[OK] FLEIYTVTV: 4 rows, 4 scored
[OK] FLGIYTVTVV: 4 rows, 4 scored
[OK] FLNVFFPLL: 4 rows, 4 scored
[OK] FLPDLNVNA: 4 rows, 4 scored
[OK] FLPSDFFPSV: 4 rows, 4 scored
[OK] FLRGRFYGL: 4 rows, 4 scored
[OK] FLTGIGIITV: 4 rows, 4 scored
[OK] FLWSVFMLI: 12 rows, 12 scored
[OK] FMGVTYEM: 4 rows, 4 scored
[OK] FMLYLVTLM: 4 rows, 4 scored
[OK] FMSAYSGVL: 4 rows, 4 scored
[OK] FMYSDFHFI: 18 rows, 18 scored
[OK] FQDYIKSYL: 6 rows, 6 scored
[OK] FQLNQSFEI: 4 rows, 4 scored
[OK] FRNEGIHL: 4 rows, 4 scored
[OK] FSFPLDFLV: 4 rows, 4 scored
[OK] FSSEVLNLV: 4 rows, 4 scored
[OK] FVGEFFTDV: 4 rows, 4 scored
[OK] FVVPYMIYLL: 4 rows, 4 scored
[OK] FVYVFTTHL: 4 rows, 4 scored
[OK] FWLLGAWAL: 4 rows, 4 scored
[OK] FWLLPAWAL: 4 rows, 4 scored
[OK] GIWGFVFTL: 4 rows, 4 scored
[OK] GLLHHAPSL: 4 rows, 4 scored
[OK] GLSPNLNRFL: 4 rows, 4 scored
[OK] GMDYHNGHL: 4 rows, 4 scored
[OK] GSLAPEIRMYW: 4 rows, 4 scored
[OK] GSLSPELRPIF: 4 rows, 4 scored
[OK] GTIRPEIPDYF: 4 rows, 4 scored
[OK] GTIRPEIREMW: 4 rows, 4 scored
[OK] HIAKSPFEV: 4 rows, 4 scored
[OK] HIMPDTAEI: 4 rows, 4 scored
[OK] HIVEISTPV: 4 rows, 4 scored
[OK] HPVAEADYFEY: 4 rows, 4 scored
[OK] HQLGGVVEV: 4 rows, 4 scored
[OK] HQNPVTGLLL: 4 rows, 4 scored
[OK] HRRGSRSYV: 6 rows, 6 scored
[OK] HSKKKCDEI: 4 rows, 4 scored
[OK] HSKRKCDEL: 4 rows, 4 scored
[OK] HSRKKCDEL: 4 rows, 4 scored
[OK] IAGLGLLTV: 6 rows, 6 scored
[OK] IAMAVLYLA: 4 rows, 4 scored
[OK] ILAAFLHWL: 4 rows, 4 scored
[OK] ILAKFAHWL: 4 rows, 4 scored
[OK] ILCETCLIV: 4 rows, 4 scored
[OK] ILITQVLGL: 4 rows, 4 scored
[OK] KAANIVLTV: 6 rows, 6 scored
[OK] KIFGSLAFL: 4 rows, 4 scored
[OK] KLAKPLPYT: 4 rows, 4 scored
[OK] KLEFMDWRL: 4 rows, 4 scored
[OK] KLEQLDWTV: 4 rows, 4 scored
[OK] KLLAGDEIV: 4 rows, 4 scored
[OK] KLQCVDLHV: 6 rows, 6 scored
[OK] KLSEGDLLA: 4 rows, 4 scored
[OK] KLSELHAYI: 4 rows, 4 scored
[OK] KLSHQPVLL: 4 rows, 4 scored
[OK] KLTESLHKV: 4 rows, 4 scored
[OK] KLVALGINNV: 8 rows, 8 scored
[OK] KLVALVINAV: 4 rows, 4 scored
[OK] KMGVTYEM: 4 rows, 4 scored
[OK] KQWLVWLFL: 8 rows, 8 scored
[OK] KSCTPEVREYF: 4 rows, 4 scored
[OK] KSFVPELKPAF: 4 rows, 4 scored
[OK] KSLAPEVRDLF: 4 rows, 4 scored
[OK] KSLTPEVRGYW: 4 rows, 4 scored
[OK] KVAELVHFL: 6 rows, 6 scored
[OK] LAITPEIAPYF: 4 rows, 4 scored
[OK] LASYFFWGL: 4 rows, 4 scored
[OK] LGIGVITI: 6 rows, 6 scored
[OK] LLEDLDWDV: 4 rows, 4 scored
[OK] LLFAAFSSA: 4 rows, 4 scored
[OK] LLFGKPVYV: 4 rows, 4 scored
[OK] LLFGLALIEV: 4 rows, 4 scored
[OK] LLFGPVYV: 4 rows, 4 scored
[OK] LLFGYPVFV: 4 rows, 4 scored
[OK] LLHGFSFYL: 72 rows, 72 scored
[OK] LLIDLTSFLL: 4 rows, 4 scored
[OK] LLQCTQQAV: 4 rows, 4 scored
[OK] LLWNTVWNM: 4 rows, 4 scored
[OK] LLYGFVNYI: 4 rows, 4 scored
[OK] LLYGFVNYV: 4 rows, 4 scored
[OK] LMASISSFL: 4 rows, 4 scored
[OK] LMDMHNGQL: 4 rows, 4 scored
[OK] LPEALPQGQLTAY: 4 rows, 4 scored
[OK] LPEPLPQGALTAY: 4 rows, 4 scored
[OK] LPEPLPQGQATAY: 4 rows, 4 scored
[OK] LPLKMLNI: 4 rows, 4 scored
[OK] LSITPEIAPYF: 4 rows, 4 scored
[OK] LSITPEISPYF: 4 rows, 4 scored
[OK] LSLRPEIPLFF: 4 rows, 4 scored
[OK] LTISPEIPPYF: 4 rows, 4 scored
[OK] LTISPEIPSYF: 4 rows, 4 scored
[OK] LTITPEIAPFF: 4 rows, 4 scored
[OK] LTITPEIAPYF: 4 rows, 4 scored
[OK] LTITPEIRPYF: 4 rows, 4 scored
[OK] LTLTPEIAPYF: 4 rows, 4 scored
[OK] LVFPLVMGV: 4 rows, 4 scored
[OK] LVIGMPPPV: 4 rows, 4 scored
[OK] LYPEFIASI: 4 rows, 4 scored
[OK] MEVDPIGHLY: 6 rows, 6 scored
[OK] MLFSHGLVK: 4 rows, 4 scored
[OK] MLGERLFPL: 4 rows, 4 scored
[OK] MLIGIPVYV: 4 rows, 4 scored
[OK] MLMLAVIVA: 4 rows, 4 scored
[OK] MMWDRGLGMM: 4 rows, 4 scored
[OK] MPYGYVLNEF: 4 rows, 4 scored
[OK] MVIGIPVYV: 4 rows, 4 scored
[OK] MVNTVAGAMK: 4 rows, 4 scored
[OK] NLAPMVATV: 4 rows, 4 scored
[OK] NLAQTDLATV: 4 rows, 4 scored
[OK] NLFNRYLAL: 4 rows, 4 scored
[OK] NLNRCSVPV: 4 rows, 4 scored
[OK] NLVGMVATV: 4 rows, 4 scored
[OK] NLVPMVAAV: 4 rows, 4 scored
[OK] NLVPMVASV: 4 rows, 4 scored
[OK] NLVPQVATV: 4 rows, 4 scored
[OK] NLVPTVATV: 4 rows, 4 scored
[OK] NLVPVVATV: 4 rows, 4 scored
[OK] NMEYMTWDV: 4 rows, 4 scored
[OK] NSFRPEVAMKY: 4 rows, 4 scored
[OK] NSLKPEIPDYF: 4 rows, 4 scored
[OK] NSVKPEIRPVW: 4 rows, 4 scored
[OK] NVEYYDIKL: 4 rows, 4 scored
[OK] QLCDVMFYL: 4 rows, 4 scored
[OK] QLIPCMDVV: 4 rows, 4 scored
[OK] QTNPVTLQY: 4 rows, 4 scored
[OK] RIAAWMATY: 6 rows, 6 scored
[OK] RILLVAASY: 4 rows, 4 scored
[OK] RLDAMNGQL: 4 rows, 4 scored
[OK] RLHDLVFPL: 4 rows, 4 scored
[OK] RLHDLVLPL: 4 rows, 4 scored
[OK] RLLCALTSL: 4 rows, 4 scored
[OK] RLLQCTQQAV: 4 rows, 4 scored
[OK] RLSDFSEQL: 24 rows, 24 scored
[OK] RLWEPLRVV: 4 rows, 4 scored
[OK] RMDYNNMQM: 4 rows, 4 scored
[OK] RMEQVDWTV: 4 rows, 4 scored
[OK] RSFVPEIGMGF: 4 rows, 4 scored
[OK] RSGGFSFGK: 4 rows, 4 scored
[OK] RSLAPEVRGYW: 4 rows, 4 scored
[OK] RTYVPEIKHRW: 4 rows, 4 scored
[OK] RVRFFFPSL: 6 rows, 6 scored
[OK] RVSTLRVSL: 4 rows, 4 scored
[OK] RYGSFSVTL: 6 rows, 6 scored
[OK] SALRPEIRLLW: 4 rows, 4 scored
[OK] SLDPTTSPV: 4 rows, 4 scored
[OK] SLLLLPVSV: 4 rows, 4 scored
[OK] SLLLLSVSV: 4 rows, 4 scored
[OK] SLLQGSPHL: 4 rows, 4 scored
[OK] SLLQGSPHV: 4 rows, 4 scored
[OK] SLSKILDTV: 6 rows, 6 scored
[OK] SLVALGINAV: 12 rows, 12 scored
[OK] SLYNTVATLY: 22 rows, 22 scored
[OK] SMGVTYEM: 4 rows, 4 scored
[OK] SMLGIGIVPV: 6 rows, 6 scored
[OK] SSFSPELRMRW: 4 rows, 4 scored
[OK] SSGVPEVRMMF: 4 rows, 4 scored
[OK] SVASTITGV: 4 rows, 4 scored
[OK] SWISDIRAGTAPLCRNHIKSSCSLI: 4 rows, 4 scored
[OK] SYMIMEIE: 4 rows, 4 scored
[OK] TLEELDWCL: 4 rows, 4 scored
[OK] TLEYMDWLV: 4 rows, 4 scored
[OK] TLFTMVGTV: 4 rows, 4 scored
[OK] TLREIRRYQK: 4 rows, 4 scored
[OK] TLYSLTLLY: 4 rows, 4 scored
[OK] TMDFYQGQL: 4 rows, 4 scored
[OK] TMETIDWKV: 4 rows, 4 scored
[OK] TMSSSHLFYL: 4 rows, 4 scored
[OK] TYDTVHRHL: 4 rows, 4 scored
[OK] VLASPSVPL: 4 rows, 4 scored
[OK] VLDLFQGQL: 4 rows, 4 scored
[OK] VLEEVDWLI: 4 rows, 4 scored
[OK] VLFAAFSSA: 4 rows, 4 scored
[OK] VLNGTVHPV: 4 rows, 4 scored
[OK] VMIIVSSLAV: 4 rows, 4 scored
[OK] VPLTEDAEL: 4 rows, 4 scored
[OK] VYAIFIFQL: 4 rows, 4 scored
[OK] VYFFLPDHL: 4 rows, 4 scored
[OK] WLDNFELCL: 4 rows, 4 scored
[OK] WLLPAWGV: 4 rows, 4 scored
[OK] WLLPTWGV: 4 rows, 4 scored
[OK] WLWEPLRVV: 4 rows, 4 scored
[OK] WSYDSTLLAY: 4 rows, 4 scored
[OK] WTYRPEVRGVW: 4 rows, 4 scored
[OK] YIDDVVLGA: 4 rows, 4 scored
[OK] YIFLGNLAL: 4 rows, 4 scored
[OK] YLCLQNNFI: 4 rows, 4 scored
[OK] YLCSGSSYF: 4 rows, 4 scored
[OK] YLCSGSSYFV: 4 rows, 4 scored
[OK] YLDELIKNT: 4 rows, 4 scored
[OK] YLLPAIVHI: 4 rows, 4 scored
[OK] YLNELVVFV: 4 rows, 4 scored
[OK] YLQDSLATT: 4 rows, 4 scored
[OK] YLQQNWWTL: 36 rows, 36 scored
[OK] YLSFYTAEQL: 4 rows, 4 scored
[OK] YLSHLPLTCKF: 4 rows, 4 scored
[OK] YLSNIIPAL: 4 rows, 4 scored
[OK] YLVALGINAV: 12 rows, 12 scored
[OK] YLVALGVNAV: 6 rows, 6 scored
[OK] YLYDRLLRI: 4 rows, 4 scored
[OK] YLYDRLLRV: 4 rows, 4 scored
[OK] YMDDVVLGA: 4 rows, 4 scored
[OK] YMGVSYEM: 4 rows, 4 scored
[OK] YMGVVYEM: 4 rows, 4 scored
[OK] YMLDLQPETT: 4 rows, 4 scored
[OK] YMLTLHTKL: 4 rows, 4 scored
[OK] YMPTTIIAA: 4 rows, 4 scored
[OK] YMVLASPSV: 4 rows, 4 scored
[OK] YSFKPELKEIF: 4 rows, 4 scored
[OK] YTSEILSPI: 4 rows, 4 scored
[OK] YVDDVVLGA: 4 rows, 4 scored
[OK] YVNELVVFV: 4 rows, 4 scored
[OK] YVTAMDIFV: 4 rows, 4 scored
[OK] YVTAMDLFV: 4 rows, 4 scored

Saved to ./result/CASE1_meta_scored.csv
Total rows: 1370, scored: 1370

In [59]:
!{sys.executable} ../../metric_calculation/AUC.py \
                    --root_dir ./result \
                    --output_file ./CASE1_meta_auc.csv

Finding CSV files...
Found 1 CSV files
Processed 1/1 files (100.0%)
Failed: 1

In [60]:
import pandas as pd

df = pd.read_csv("./CASE1_meta_auc.csv")
df

,folder_path,file_name,roc_auc,pr_auc,status
0,./result,CASE1_meta_scored.csv,0.479802,0.524268,success
1,./result,[FOLDER_SUMMARY],0.479802,0.524268,success (averaged over 1 files)

### Other method

If you would like to reproduce other methods, you can use their web servers. For DLpTCR, you can use http://jianglab.org.cn/DLpTCR/ and select pTCRβ. For ERGO-II, you can use http://tcr2.cs.biu.ac.il/home and choose VDJdb mode.

## rank

For demonstration purposes, since running on the full background pool would be too time-consuming, we constructed a subset pool by randomly sampling 0.1% of the background library and used it for reproduction and result presentation. If you would like to reproduce the full original results, you can simply replace the subset background pool with the complete background library and rerun the same pipeline. In other words, the current setup is only for demonstration efficiency, while the full results can be recovered by using the original background pool.

In [ ]:
import sys

SCRIPT_DIR = "./"
TEST_DATA = "../../data/fig2/reshuffling_majority_0.csv"
NEGATIVE_DATA = "../../data/Combined_library_sample_0.1pct.txt"

!{sys.executable} {SCRIPT_DIR}/inference_majority.py \
    --gpu 0 \
    --distillation 3 \
    --batch_size 10000 \
    --test_data "{TEST_DATA}" \
    --negative_data "{NEGATIVE_DATA}" \
    --model_path "{SCRIPT_DIR}/Requirements" \
    --support_dir "../../data/majority_paper" \
    --peptide_encoding "{SCRIPT_DIR}/peptide_b.npz" \
    --tcr_encoding "{SCRIPT_DIR}/tcr_b.npz" \
    --result_dir "{SCRIPT_DIR}/CASE1_majority_rank"

Using 1 GPUs: [0]
Using model configuration: default

Processing peptide: EAAGIGILTV on device: cuda:0
Positive TCRs: 78, Negative TCRs: 57102
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: EAAGIGILTV
Query data size: 57179

Processing batch 1/6 for peptide EAAGIGILTV - 2026-03-16 03:01:19
Finetuning model...
batch processing time: 13.01s, Progress: 16.7%

Processing batch 2/6 for peptide EAAGIGILTV - 2026-03-16 03:01:32
Using finetuned model for inference...
batch processing time: 0.83s, Progress: 33.3%

Processing batch 3/6 for peptide EAAGIGILTV - 2026-03-16 03:01:33
Using finetuned model for inference...
batch processing time: 0.84s, Progress: 50.0%

Processing batch 4/6 for peptide EAAGIGILTV - 2026-03-16 03:01:34
Using finetuned model for inference...
batch processing time: 0.80s, Progress: 66.7%

Processing batch 5/6 for peptide EAAGIGILTV - 2026-03-16 03:01:34
Using finetuned model for inference...
batch processing time: 0.72s, Progress: 83.3%

Processing batch 6/6 for peptide EAAGIGILTV - 2026-03-16 03:01:35
Using finetuned model for inference...
batch processing time: 0.52s, Progress: 100.0%
Successfully wrote 57179 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/EAAGIGILTV.parquet

Peptide EAAGIGILTV processing time: 16.90s

Processing peptide: ELAGIGILTV on device: cuda:0
Positive TCRs: 2204, Negative TCRs: 57100
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: ELAGIGILTV
Query data size: 59303

Processing batch 1/6 for peptide ELAGIGILTV - 2026-03-16 03:01:36
Finetuning model...
batch processing time: 13.08s, Progress: 16.7%

Processing batch 2/6 for peptide ELAGIGILTV - 2026-03-16 03:01:49
Using finetuned model for inference...
batch processing time: 0.81s, Progress: 33.3%

Processing batch 3/6 for peptide ELAGIGILTV - 2026-03-16 03:01:50
Using finetuned model for inference...
batch processing time: 0.77s, Progress: 50.0%

Processing batch 4/6 for peptide ELAGIGILTV - 2026-03-16 03:01:51
Using finetuned model for inference...
batch processing time: 0.83s, Progress: 66.7%

Processing batch 5/6 for peptide ELAGIGILTV - 2026-03-16 03:01:51
Using finetuned model for inference...
batch processing time: 0.85s, Progress: 83.3%

Processing batch 6/6 for peptide ELAGIGILTV - 2026-03-16 03:01:52
Using finetuned model for inference...
batch processing time: 0.76s, Progress: 100.0%
Successfully wrote 59303 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/ELAGIGILTV.parquet

Peptide ELAGIGILTV processing time: 17.26s

Processing peptide: LPRRSGAAGA on device: cuda:0
Positive TCRs: 880, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: LPRRSGAAGA
Query data size: 57979

Processing batch 1/6 for peptide LPRRSGAAGA - 2026-03-16 03:01:53
Finetuning model...
batch processing time: 20.89s, Progress: 16.7%

Processing batch 2/6 for peptide LPRRSGAAGA - 2026-03-16 03:02:14
Using finetuned model for inference...
batch processing time: 0.97s, Progress: 33.3%

Processing batch 3/6 for peptide LPRRSGAAGA - 2026-03-16 03:02:15
Using finetuned model for inference...
batch processing time: 1.00s, Progress: 50.0%

Processing batch 4/6 for peptide LPRRSGAAGA - 2026-03-16 03:02:16
Using finetuned model for inference...
batch processing time: 0.87s, Progress: 66.7%

Processing batch 5/6 for peptide LPRRSGAAGA - 2026-03-16 03:02:17
Using finetuned model for inference...
batch processing time: 0.93s, Progress: 83.3%

Processing batch 6/6 for peptide LPRRSGAAGA - 2026-03-16 03:02:18
Using finetuned model for inference...
batch processing time: 0.78s, Progress: 100.0%
Successfully wrote 57979 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/LPRRSGAAGA.parquet

Peptide LPRRSGAAGA processing time: 25.60s

Processing peptide: TPRVTGGGAM on device: cuda:0
Positive TCRs: 226, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: TPRVTGGGAM
Query data size: 57329

Processing batch 1/6 for peptide TPRVTGGGAM - 2026-03-16 03:02:19
Finetuning model...
batch processing time: 12.50s, Progress: 16.7%

Processing batch 2/6 for peptide TPRVTGGGAM - 2026-03-16 03:02:31
Using finetuned model for inference...
batch processing time: 0.89s, Progress: 33.3%

Processing batch 3/6 for peptide TPRVTGGGAM - 2026-03-16 03:02:32
Using finetuned model for inference...
batch processing time: 0.92s, Progress: 50.0%

Processing batch 4/6 for peptide TPRVTGGGAM - 2026-03-16 03:02:33
Using finetuned model for inference...
batch processing time: 0.83s, Progress: 66.7%

Processing batch 5/6 for peptide TPRVTGGGAM - 2026-03-16 03:02:34
Using finetuned model for inference...
batch processing time: 0.78s, Progress: 83.3%

Processing batch 6/6 for peptide TPRVTGGGAM - 2026-03-16 03:02:35
Using finetuned model for inference...
batch processing time: 0.58s, Progress: 100.0%
Successfully wrote 57329 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/TPRVTGGGAM.parquet

Peptide TPRVTGGGAM processing time: 16.64s

Processing peptide: ATDALMTGY on device: cuda:0
Positive TCRs: 120, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: ATDALMTGY
Query data size: 57223

Processing batch 1/6 for peptide ATDALMTGY - 2026-03-16 03:02:36
Finetuning model...
batch processing time: 11.53s, Progress: 16.7%

Processing batch 2/6 for peptide ATDALMTGY - 2026-03-16 03:02:47
Using finetuned model for inference...
batch processing time: 0.73s, Progress: 33.3%

Processing batch 3/6 for peptide ATDALMTGY - 2026-03-16 03:02:48
Using finetuned model for inference...
batch processing time: 0.69s, Progress: 50.0%

Processing batch 4/6 for peptide ATDALMTGY - 2026-03-16 03:02:49
Using finetuned model for inference...
batch processing time: 0.66s, Progress: 66.7%

Processing batch 5/6 for peptide ATDALMTGY - 2026-03-16 03:02:49
Using finetuned model for inference...
batch processing time: 0.67s, Progress: 83.3%

Processing batch 6/6 for peptide ATDALMTGY - 2026-03-16 03:02:50
Using finetuned model for inference...
batch processing time: 0.53s, Progress: 100.0%
Successfully wrote 57223 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/ATDALMTGY.parquet

Peptide ATDALMTGY processing time: 14.95s

Processing peptide: CINGVCWTV on device: cuda:0
Positive TCRs: 488, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: CINGVCWTV
Query data size: 57591

Processing batch 1/6 for peptide CINGVCWTV - 2026-03-16 03:02:51
Finetuning model...
batch processing time: 10.89s, Progress: 16.7%

Processing batch 2/6 for peptide CINGVCWTV - 2026-03-16 03:03:02
Using finetuned model for inference...
batch processing time: 0.89s, Progress: 33.3%

Processing batch 3/6 for peptide CINGVCWTV - 2026-03-16 03:03:02
Using finetuned model for inference...
batch processing time: 0.82s, Progress: 50.0%

Processing batch 4/6 for peptide CINGVCWTV - 2026-03-16 03:03:03
Using finetuned model for inference...
batch processing time: 0.79s, Progress: 66.7%

Processing batch 5/6 for peptide CINGVCWTV - 2026-03-16 03:03:04
Using finetuned model for inference...
batch processing time: 0.74s, Progress: 83.3%

Processing batch 6/6 for peptide CINGVCWTV - 2026-03-16 03:03:05
Using finetuned model for inference...
batch processing time: 0.55s, Progress: 100.0%
Successfully wrote 57591 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/CINGVCWTV.parquet

Peptide CINGVCWTV processing time: 14.81s

Processing peptide: CRVLCCYVL on device: cuda:0
Positive TCRs: 158, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: CRVLCCYVL
Query data size: 57261

Processing batch 1/6 for peptide CRVLCCYVL - 2026-03-16 03:03:06
Finetuning model...
batch processing time: 13.08s, Progress: 16.7%

Processing batch 2/6 for peptide CRVLCCYVL - 2026-03-16 03:03:19
Using finetuned model for inference...
batch processing time: 0.76s, Progress: 33.3%

Processing batch 3/6 for peptide CRVLCCYVL - 2026-03-16 03:03:19
Using finetuned model for inference...
batch processing time: 0.74s, Progress: 50.0%

Processing batch 4/6 for peptide CRVLCCYVL - 2026-03-16 03:03:20
Using finetuned model for inference...
batch processing time: 0.71s, Progress: 66.7%

Processing batch 5/6 for peptide CRVLCCYVL - 2026-03-16 03:03:21
Using finetuned model for inference...
batch processing time: 0.71s, Progress: 83.3%

Processing batch 6/6 for peptide CRVLCCYVL - 2026-03-16 03:03:22
Using finetuned model for inference...
batch processing time: 0.53s, Progress: 100.0%
Successfully wrote 57261 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/CRVLCCYVL.parquet

Peptide CRVLCCYVL processing time: 16.68s

Processing peptide: FPRPWLHGL on device: cuda:0
Positive TCRs: 80, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: FPRPWLHGL
Query data size: 57183

Processing batch 1/6 for peptide FPRPWLHGL - 2026-03-16 03:03:22
Finetuning model...
batch processing time: 10.37s, Progress: 16.7%

Processing batch 2/6 for peptide FPRPWLHGL - 2026-03-16 03:03:33
Using finetuned model for inference...
batch processing time: 0.75s, Progress: 33.3%

Processing batch 3/6 for peptide FPRPWLHGL - 2026-03-16 03:03:33
Using finetuned model for inference...
batch processing time: 0.76s, Progress: 50.0%

Processing batch 4/6 for peptide FPRPWLHGL - 2026-03-16 03:03:34
Using finetuned model for inference...
batch processing time: 0.73s, Progress: 66.7%

Processing batch 5/6 for peptide FPRPWLHGL - 2026-03-16 03:03:35
Using finetuned model for inference...
batch processing time: 0.72s, Progress: 83.3%

Processing batch 6/6 for peptide FPRPWLHGL - 2026-03-16 03:03:36
Using finetuned model for inference...
batch processing time: 0.48s, Progress: 100.0%
Successfully wrote 57183 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/FPRPWLHGL.parquet

Peptide FPRPWLHGL processing time: 13.96s

Processing peptide: FRCPRRFCF on device: cuda:0
Positive TCRs: 96, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: FRCPRRFCF
Query data size: 57198

Processing batch 1/6 for peptide FRCPRRFCF - 2026-03-16 03:03:36
Finetuning model...
batch processing time: 12.19s, Progress: 16.7%

Processing batch 2/6 for peptide FRCPRRFCF - 2026-03-16 03:03:49
Using finetuned model for inference...
batch processing time: 0.74s, Progress: 33.3%

Processing batch 3/6 for peptide FRCPRRFCF - 2026-03-16 03:03:49
Using finetuned model for inference...
batch processing time: 0.76s, Progress: 50.0%

Processing batch 4/6 for peptide FRCPRRFCF - 2026-03-16 03:03:50
Using finetuned model for inference...
batch processing time: 0.72s, Progress: 66.7%

Processing batch 5/6 for peptide FRCPRRFCF - 2026-03-16 03:03:51
Using finetuned model for inference...
batch processing time: 0.71s, Progress: 83.3%

Processing batch 6/6 for peptide FRCPRRFCF - 2026-03-16 03:03:51
Using finetuned model for inference...
batch processing time: 0.53s, Progress: 100.0%
Successfully wrote 57198 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/FRCPRRFCF.parquet

Peptide FRCPRRFCF processing time: 15.80s

Processing peptide: GILGFVFTL on device: cuda:0
Positive TCRs: 7192, Negative TCRs: 57095
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: GILGFVFTL
Query data size: 64281

Processing batch 1/6 for peptide GILGFVFTL - 2026-03-16 03:03:52
Finetuning model...
batch processing time: 22.27s, Progress: 16.7%

Processing batch 2/6 for peptide GILGFVFTL - 2026-03-16 03:04:15
Using finetuned model for inference...
batch processing time: 1.02s, Progress: 33.3%

Processing batch 3/6 for peptide GILGFVFTL - 2026-03-16 03:04:16
Using finetuned model for inference...
batch processing time: 2.02s, Progress: 50.0%

Processing batch 4/6 for peptide GILGFVFTL - 2026-03-16 03:04:18
Using finetuned model for inference...
batch processing time: 0.98s, Progress: 66.7%

Processing batch 5/6 for peptide GILGFVFTL - 2026-03-16 03:04:19
Using finetuned model for inference...
batch processing time: 0.99s, Progress: 83.3%

Processing batch 6/6 for peptide GILGFVFTL - 2026-03-16 03:04:20
Using finetuned model for inference...
batch processing time: 1.37s, Progress: 100.0%
Successfully wrote 64281 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/GILGFVFTL.parquet

Peptide GILGFVFTL processing time: 28.81s

Processing peptide: GLCTLVAML on device: cuda:0
Positive TCRs: 934, Negative TCRs: 57102
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: GLCTLVAML
Query data size: 58033

Processing batch 1/6 for peptide GLCTLVAML - 2026-03-16 03:04:21
Finetuning model...
batch processing time: 16.32s, Progress: 16.7%

Processing batch 2/6 for peptide GLCTLVAML - 2026-03-16 03:04:37
Using finetuned model for inference...
batch processing time: 0.93s, Progress: 33.3%

Processing batch 3/6 for peptide GLCTLVAML - 2026-03-16 03:04:38
Using finetuned model for inference...
batch processing time: 0.93s, Progress: 50.0%

Processing batch 4/6 for peptide GLCTLVAML - 2026-03-16 03:04:39
Using finetuned model for inference...
batch processing time: 0.89s, Progress: 66.7%

Processing batch 5/6 for peptide GLCTLVAML - 2026-03-16 03:04:40
Using finetuned model for inference...
batch processing time: 0.85s, Progress: 83.3%

Processing batch 6/6 for peptide GLCTLVAML - 2026-03-16 03:04:41
Using finetuned model for inference...
batch processing time: 0.72s, Progress: 100.0%
Successfully wrote 58033 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/GLCTLVAML.parquet

Peptide GLCTLVAML processing time: 20.79s

Processing peptide: LLWNGPMAV on device: cuda:0
Positive TCRs: 90, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: LLWNGPMAV
Query data size: 57193

Processing batch 1/6 for peptide LLWNGPMAV - 2026-03-16 03:04:42
Finetuning model...
batch processing time: 13.01s, Progress: 16.7%

Processing batch 2/6 for peptide LLWNGPMAV - 2026-03-16 03:04:55
Using finetuned model for inference...
batch processing time: 0.78s, Progress: 33.3%

Processing batch 3/6 for peptide LLWNGPMAV - 2026-03-16 03:04:56
Using finetuned model for inference...
batch processing time: 0.78s, Progress: 50.0%

Processing batch 4/6 for peptide LLWNGPMAV - 2026-03-16 03:04:57
Using finetuned model for inference...
batch processing time: 0.77s, Progress: 66.7%

Processing batch 5/6 for peptide LLWNGPMAV - 2026-03-16 03:04:57
Using finetuned model for inference...
batch processing time: 0.82s, Progress: 83.3%

Processing batch 6/6 for peptide LLWNGPMAV - 2026-03-16 03:04:58
Using finetuned model for inference...
batch processing time: 0.59s, Progress: 100.0%
Successfully wrote 57193 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/LLWNGPMAV.parquet

Peptide LLWNGPMAV processing time: 16.90s

Processing peptide: NLVPMVATV on device: cuda:0
Positive TCRs: 7668, Negative TCRs: 57098
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: NLVPMVATV
Query data size: 64762

Processing batch 1/6 for peptide NLVPMVATV - 2026-03-16 03:04:59
Finetuning model...
batch processing time: 15.81s, Progress: 16.7%

Processing batch 2/6 for peptide NLVPMVATV - 2026-03-16 03:05:15
Using finetuned model for inference...
batch processing time: 0.94s, Progress: 33.3%

Processing batch 3/6 for peptide NLVPMVATV - 2026-03-16 03:05:16
Using finetuned model for inference...
batch processing time: 0.96s, Progress: 50.0%

Processing batch 4/6 for peptide NLVPMVATV - 2026-03-16 03:05:17
Using finetuned model for inference...
batch processing time: 0.88s, Progress: 66.7%

Processing batch 5/6 for peptide NLVPMVATV - 2026-03-16 03:05:18
Using finetuned model for inference...
batch processing time: 0.87s, Progress: 83.3%

Processing batch 6/6 for peptide NLVPMVATV - 2026-03-16 03:05:18
Using finetuned model for inference...
batch processing time: 1.29s, Progress: 100.0%
Successfully wrote 64762 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/NLVPMVATV.parquet

Peptide NLVPMVATV processing time: 20.93s

Processing peptide: RLRAEAQVK on device: cuda:0
Positive TCRs: 182, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: RLRAEAQVK
Query data size: 57283

Processing batch 1/6 for peptide RLRAEAQVK - 2026-03-16 03:05:20
Finetuning model...
batch processing time: 12.38s, Progress: 16.7%

Processing batch 2/6 for peptide RLRAEAQVK - 2026-03-16 03:05:32
Using finetuned model for inference...
batch processing time: 0.84s, Progress: 33.3%

Processing batch 3/6 for peptide RLRAEAQVK - 2026-03-16 03:05:33
Using finetuned model for inference...
batch processing time: 0.85s, Progress: 50.0%

Processing batch 4/6 for peptide RLRAEAQVK - 2026-03-16 03:05:34
Using finetuned model for inference...
batch processing time: 0.76s, Progress: 66.7%

Processing batch 5/6 for peptide RLRAEAQVK - 2026-03-16 03:05:35
Using finetuned model for inference...
batch processing time: 0.79s, Progress: 83.3%

Processing batch 6/6 for peptide RLRAEAQVK - 2026-03-16 03:05:36
Using finetuned model for inference...
batch processing time: 0.55s, Progress: 100.0%
Successfully wrote 57283 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/RLRAEAQVK.parquet

Peptide RLRAEAQVK processing time: 16.31s

Processing peptide: SFHSLHLLF on device: cuda:0
Positive TCRs: 74, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: SFHSLHLLF
Query data size: 57177

Processing batch 1/6 for peptide SFHSLHLLF - 2026-03-16 03:05:36
Finetuning model...
batch processing time: 10.46s, Progress: 16.7%

Processing batch 2/6 for peptide SFHSLHLLF - 2026-03-16 03:05:47
Using finetuned model for inference...
batch processing time: 0.80s, Progress: 33.3%

Processing batch 3/6 for peptide SFHSLHLLF - 2026-03-16 03:05:48
Using finetuned model for inference...
batch processing time: 0.85s, Progress: 50.0%

Processing batch 4/6 for peptide SFHSLHLLF - 2026-03-16 03:05:49
Using finetuned model for inference...
batch processing time: 0.83s, Progress: 66.7%

Processing batch 5/6 for peptide SFHSLHLLF - 2026-03-16 03:05:49
Using finetuned model for inference...
batch processing time: 0.72s, Progress: 83.3%

Processing batch 6/6 for peptide SFHSLHLLF - 2026-03-16 03:05:50
Using finetuned model for inference...
batch processing time: 0.52s, Progress: 100.0%
Successfully wrote 57177 records to /mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/.//CASE1_majority_rank/SFHSLHLLF.parquet

Peptide SFHSLHLLF processing time: 14.33s

Processing peptide: TPQDLNTML on device: cuda:0
Positive TCRs: 82, Negative TCRs: 57103
Total batches: 6
Loading support data from: ../../data/majority_paper
Loading support data for peptide: TPQDLNTML
Query data size: 57185

Processing batch 1/6 for peptide TPQDLNTML - 2026-03-16 03:05:51
Finetuning model...
batch processing time: 11.21s, Progress: 16.7%

Processing batch 2/6 for peptide TPQDLNTML - 2026-03-16 03:06:02
Using finetuned model for inference...

In [64]:
!{sys.executable} ../../metric_calculation/sort.py \
                    --input_dir ./CASE1_majority_rank \
                    --output_dir ./CASE1_majority_sort

Found 19 files to process:
  CSV files: 0
  Parquet files: 19

Completed processing 19 files

In [77]:
!{sys.executable} ../../metric_calculation/bedroc.py \
                    -i ./CASE1_majority_sort/CASE1_majority_rank \
                    -o ./CASE1_majority_bedroc

2026-03-16 03:18:22,221 - INFO - Input directory: ./CASE1_majority_sort/CASE1_majority_rank
2026-03-16 03:18:22,222 - INFO - Output directory: ./CASE1_majority_bedroc
2026-03-16 03:18:22,222 - INFO - Number of processes: 8
Total: 19 files, To process: 19 files
Processing files:   0%|                                  | 0/19 [00:00<?, ?it/s]
File: EAAGIGILTV_sorted.parquet

File: FPRPWLHGL_sorted.parquet

File: ELAGIGILTV_sorted.parquet

File: CRVLCCYVL_sorted.parquet

File: CINGVCWTV_sorted.parquet

File: ATDALMTGY_sorted.parquet

File: GILGFVFTL_sorted.parquet

File: FRCPRRFCF_sorted.parquet
Processing files:   5%|█▎                        | 1/19 [00:00<00:03,  5.57it/s]
File: GLCTLVAML_sorted.parquet

File: LLWNGPMAV_sorted.parquet

File: LPRRSGAAGA_sorted.parquet

File: RAKFKQLL_sorted.parquet

File: RLRAEAQVK_sorted.parquet

File: NLVPMVATV_sorted.parquet

File: SFHSLHLLF_sorted.parquet

File: TPQDLNTML_sorted.parquet
Processing files:  63%|███████████████▊         | 12/19 [00:00<00:00, 51.36it/s]
File: VTEHDTLLY_sorted.parquet

File: YVLDHLIVV_sorted.parquet

File: TPRVTGGGAM_sorted.parquet
Processing files: 100%|█████████████████████████| 19/19 [00:00<00:00, 59.09it/s]
2026-03-16 03:18:22,641 - INFO - Successfully processed 19 files.
2026-03-16 03:18:22,641 - INFO - Detailed results stored in: ./CASE1_majority_bedroc/
2026-03-16 03:18:22,641 - INFO - Starting summary calculation...
2026-03-16 03:18:22,648 - INFO - Reading 19 result files...
Reading detailed results: 100%|████████████████| 19/19 [00:00<00:00, 217.67it/s]
2026-03-16 03:18:22,756 - INFO - Summary saved to: ./CASE1_majority_bedroc/summary_by_directory.csv
2026-03-16 03:18:22,756 - INFO - Total files processed: 19
2026-03-16 03:18:22,756 - INFO - Total unique directories: 1
2026-03-16 03:18:22,756 - INFO - Global mean BEDROC score: 0.2005
Top 10 directories by BEDROC score:
                                Directory  BEDROC_Mean  BEDROC_Std  File_Count
./CASE1_majority_sort/CASE1_majority_rank     0.200508    0.077391          19
2026-03-16 03:18:22,759 - INFO - Starting per-directory merge of detailed results...
2026-03-16 03:18:22,777 - WARNING - No directories found for merging.

In [ ]:
import os
import glob
import pandas as pd

detailed_dir = "./CASE1_majority_bedroc"

# Print all CSV files in the detailed results directory
csv_files = sorted(glob.glob(os.path.join(detailed_dir, "*.csv")))

print(f"Found {len(csv_files)} CSV file(s) in: {detailed_dir}\n")

for file_path in csv_files:
    print("=" * 100)
    print(f"File: {file_path}")
    print("=" * 100)
    df = pd.read_csv(file_path)
    print(df)
    print("\n")

Found 20 CSV file(s) in: ./CASE1_majority_bedroc

====================================================================================================
File: ./CASE1_majority_bedroc/summary_by_directory.csv
====================================================================================================
                                   Directory  BEDROC_Mean  BEDROC_Std  \
0  ./CASE1_majority_sort/CASE1_majority_rank     0.200508    0.077391

   File_Count
0          19


====================================================================================================
File: ./CASE1_majority_bedroc/temp_ATDALMTGY_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  ATDALMTGY_sorted.parquet

   BEDROC_Score  Alpha
0      0.151686     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_CINGVCWTV_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  CINGVCWTV_sorted.parquet

   BEDROC_Score  Alpha
0      0.095342     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_CRVLCCYVL_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  CRVLCCYVL_sorted.parquet

   BEDROC_Score  Alpha
0       0.17731     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_EAAGIGILTV_sorted.csv
====================================================================================================
                                   Directory                   Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  EAAGIGILTV_sorted.parquet

   BEDROC_Score  Alpha
0      0.145169     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_ELAGIGILTV_sorted.csv
====================================================================================================
                                   Directory                   Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  ELAGIGILTV_sorted.parquet

   BEDROC_Score  Alpha
0      0.212462     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_FPRPWLHGL_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  FPRPWLHGL_sorted.parquet

   BEDROC_Score  Alpha
0      0.203349     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_FRCPRRFCF_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  FRCPRRFCF_sorted.parquet

   BEDROC_Score  Alpha
0      0.152264     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_GILGFVFTL_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  GILGFVFTL_sorted.parquet

   BEDROC_Score  Alpha
0        0.4388     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_GLCTLVAML_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  GLCTLVAML_sorted.parquet

   BEDROC_Score  Alpha
0      0.223918     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_LLWNGPMAV_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  LLWNGPMAV_sorted.parquet

   BEDROC_Score  Alpha
0      0.199139     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_LPRRSGAAGA_sorted.csv
====================================================================================================
                                   Directory                   Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  LPRRSGAAGA_sorted.parquet

   BEDROC_Score  Alpha
0      0.217962     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_NLVPMVATV_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  NLVPMVATV_sorted.parquet

   BEDROC_Score  Alpha
0      0.324575     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_RAKFKQLL_sorted.csv
====================================================================================================
                                   Directory                 Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  RAKFKQLL_sorted.parquet

   BEDROC_Score  Alpha
0      0.198546     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_RLRAEAQVK_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  RLRAEAQVK_sorted.parquet

   BEDROC_Score  Alpha
0      0.175737     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_SFHSLHLLF_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  SFHSLHLLF_sorted.parquet

   BEDROC_Score  Alpha
0      0.204371     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_TPQDLNTML_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  TPQDLNTML_sorted.parquet

   BEDROC_Score  Alpha
0      0.257008     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_TPRVTGGGAM_sorted.csv
====================================================================================================
                                   Directory                   Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  TPRVTGGGAM_sorted.parquet

   BEDROC_Score  Alpha
0      0.139326     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_VTEHDTLLY_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  VTEHDTLLY_sorted.parquet

   BEDROC_Score  Alpha
0      0.176514     20


====================================================================================================
File: ./CASE1_majority_bedroc/temp_YVLDHLIVV_sorted.csv
====================================================================================================
                                   Directory                  Filename  \
0  ./CASE1_majority_sort/CASE1_majority_rank  YVLDHLIVV_sorted.parquet

   BEDROC_Score  Alpha
0      0.116172     20

In [84]:
!{sys.executable} "../../metric_calculation/success_rate&hit_rate.py" \
    --root_dir "./CASE1_majority_sort/CASE1_majority_rank" \
    --output "CASE1_majority_sort" \
    --output_dir "./CASE1_majority_success"

2026-03-16 03:33:16,918 - INFO - Multiprocessing start method set to 'spawn'.
2026-03-16 03:33:17,022 - INFO - Configuration: ProcessingConfig(root_dir='./CASE1_majority_sort/CASE1_majority_rank', top_k_ratio=1, batch_size=150, num_gpus=1, output_file='CASE1_majority_sort', output_dir='./CASE1_majority_success', gpu_id=None)
2026-03-16 03:33:17,022 - INFO - Detected 1 GPU(s)
Processing directories:   0%|                             | 0/1 [00:00<?, ?it/s]2026-03-16 03:33:18,455 - INFO - Process 532153 using device: cuda:0
Processing directories: 100%|█████████████████████| 1/1 [00:02<00:00,  2.31s/it]
2026-03-16 03:33:19,357 - INFO - Combining 1 DataFrames...
2026-03-16 03:33:19,600 - INFO - Final results saved to CASE1_majority_success/CASE1_majority_sort.csv and CASE1_majority_success/CASE1_majority_sort.parquet

In [85]:
!{sys.executable} "../../metric_calculation/get_success_AUC.py" \
    --input "./CASE1_majority_success/CASE1_majority_sort.parquet" \
    --output "CASE1_majority_success_AUC"

Found 1 directories.
1. 'CASE1_majority_sort/CASE1_majority_rank'
['CASE1_majority_sort/CASE1_majority_rank'] n=64762  Top_K range=(1, 64762)  y range=(0.000232883, 1)
/mnt/d/PanPep_Reusability/inference/PanPep_Weight_Inference/../../metric_calculation/get_success_AUC.py:190: DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.
  area = float(np.trapz(ys, xs_norm))
  AUC@0.0100%: area=9.30964e-08
  AUC@0.1000%: area=6.1079e-06
  AUC@1.0000%: area=0.000316417
  AUC@5.0000%: area=0.00575419
  AUC@10.0000%: area=0.0189795
  AUC@20.0000%: area=0.0590135
  AUC@100.0000%: area=0.711741

Saved results to: CASE1_majority_success_AUC